### ISSUE TITLE
Clay - Proposal

### ISSUE THREAD

**Issue by 2LEPRECHAUN** [SummerFields/SummerFields#125]
For a "new" concept in the texture, i'll propose the change of the texture of the clay.
![clay](https://cloud.githubusercontent.com/assets/7558430/4025555/28e6ec96-2bfc-11e4-808a-f212820f38db.png) ![clay_ball](https://cloud.githubusercontent.com/assets/7558430/4025556/28f541b0-2bfc-11e4-9dae-de973af4fc82.png)

Following the logic -> ![clay](https://cloud.githubusercontent.com/assets/7558430/4025555/28e6ec96-2bfc-11e4-808a-f212820f38db.png) -> ![fire_frame_1](https://cloud.githubusercontent.com/assets/7558430/4025569/9176c48e-2bfc-11e4-8c6a-dfabb55569d5.png) -> ![hardened_clay](https://cloud.githubusercontent.com/assets/7558430/4025590/7524c294-2bfd-11e4-97dc-cd20183d86cd.png)
Fire that evaporates water and consequently reduces the moisture leaving a dull, compressed and dry block.

So?

**Comment by lipki** [comment]
done
