### ISSUE TITLE
License is unclear.

### ISSUE THREAD

**Issue by RobertZenz** [SummerFields/SummerFields#156]
I have a hard time figuring out what license these textures are under, I found a source saying CC-BY-NC-SA 4, is this correct?

Can you please add a LICENSE file to the repository to avoid any confusion about it?

**Comment by lipki** [comment]
oui, you'r right !
it's done.
https://github.com/SummerFields/SummerFields/blob/master/LICENSE.md

**Comment by RobertZenz** [comment]
Thanks for the confirmation.
