### ISSUE TITLE
Sea Block by ImLeeRii

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#176]
proposal to right
![capture du 2015-05-12 16 51 14](https://cloud.githubusercontent.com/assets/401965/7591578/f52f9ee8-f8ce-11e4-877d-9c5a8fa45a5f.png)

**Comment by lipki** [comment]
There are much better than mine ... I do not know.

**Comment by tobyplowy** [comment]
The ones on the right look a lot better.

**Comment by tobyplowy** [comment]
@lipki The ones on the right look a lot better.

**Comment by lipki** [comment]
yes ...

**Comment by tobyplowy** [comment]
Will this get edded to the pack? if Not culd this issue be closed? It's already quite old :)

**Comment by lipki** [comment]
It will remain until we decide.
Even if it remains three years.

**Comment by tobyplowy** [comment]
I do Prefer the lantarn on the lift and the prismarine on the right

**Comment by lipki** [comment]
Yes, I add "ImReeLee textures" to 1.11

**Comment by lipki** [comment]
add in 1.11
