### ISSUE TITLE
Log by ImLeeRii

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#178]
proposal to bottom
![capture du 2015-05-12 16 46 46](https://cloud.githubusercontent.com/assets/401965/7591612/2d382238-f8cf-11e4-9346-7938351cd71b.png)

**Comment by lipki** [comment]
I think the heart of the wood, must match the color of the boards.

**Comment by CuddleWoozle** [comment]
That was my idea when I did those textures originally, that the inner color of the tree should match up to the color of the planks they produce.  Although in real life, wood can lighten or darken with age/exposure to weather.
