### ISSUE TITLE
Cauldron by ImLeeRii

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#186]
proposal to right
![capture du 2015-05-12 16 36 34](https://cloud.githubusercontent.com/assets/401965/7591750/dda1df38-f8cf-11e4-8a04-4c7effc7acd3.png)

**Comment by lipki** [comment]
The craft of the cauldron is made of iron, so for me the cauldron not wood, it is not good.

**Comment by CuddleWoozle** [comment]
That's not to say the textures themselves aren't good.  Those look freaking awesome.  Maybe it can be used for a mod texture or as an alternate for people who want a 'barrel' and not a cauldron.

Although I do agree with Lipki about the wood color...it's a little bit too orange compared to the default textures.  It shouldn't be too hard to tone down though.  :)

**Comment by ImLeeRii** [comment]
The textures become flipped in certain directions, so I actually made a custom model to fix that. The logs are supposed to look like they are stack on top of each other.

**Comment by lipki** [comment]
yep, mi bad.

![capture du 2015-05-13 03 09 16](https://cloud.githubusercontent.com/assets/401965/7601999/a204a18c-f91e-11e4-8e1e-b89799167c94.png)
