### ISSUE TITLE
EnderCrystal by ImLeeRii

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#187]
proposal to right
![capture du 2015-05-10 17 22 01](https://cloud.githubusercontent.com/assets/401965/7591766/ef4cb906-f8cf-11e4-8661-3be0fd139757.png)

**Comment by lipki** [comment]
It is super, I take it.

**Comment by lipki** [comment]
@CuddleWoozle I would switch to that of ImLeeRii.
What do you think?

**Comment by CuddleWoozle** [comment]
It's fine with me.  :)
I think it goes with the rest of the stuff a bit better than my (honestly kind of rushed) version.
