### ISSUE TITLE
I can download SummerFields!

### ISSUE THREAD

**Issue by pangys** [SummerFields/SummerFields#189]
I can download SummerFields!
What's the 'blob:xxxxxxx'?

**Comment by lipki** [comment]
yes you can !

'blob:xxxxxxx' ?

**Comment by pangys** [comment]
Oops.I'm sorry that i had a wrong expression.The truth is, I can't download SummerFields!
When I pressed the download buttom, It gave me a link with 'blob:https%3A//summerfields.github.io/f698564a-2e44-4b9b-842d-1a48e4eb19a4'.
How can i download it?

**Comment by lipki** [comment]
That blob IS the texture pack.
You should be able to save in your computer.
What browser do you use?

Meanwhile, you can find the package to this address:

http://summerfields.info/version/1.8.X/SummerFields-1.8.7.zip

**Comment by pangys** [comment]
Thank you!
I use downloading software but it can't identify the link.And it's work with browser‘s downloading function.
