### ISSUE TITLE
Pack Reconfiguration for 1.9

### ISSUE THREAD

**Issue by CuddleWoozle** [SummerFields/SummerFields#192]
I'm not sure what all has changed but the 1.9 snapshots won't just let you drop the pack in and use it.
If you try to use it the game will not let you because it states that it is for 'A previous version of Minecraft'.

I'm opening this as an issue because as it stands the pack would be unusable in 1.9 because of this.  I'll be looking into how the new packs are put together more as the snapshots progress.  (There has to be a reason for it, right?  It's not just to mess with texture pack authors?)

**Comment by lipki** [comment]
It's nothing serious, just a version number, I will publish a first version 1.9 beta with some textures I made. it takes some time to detail all the changes, but I will.

**Comment by CuddleWoozle** [comment]
This has been solved.  I believe Dinnerbone posted on the forums to change 'pack_format' from 1 to 2 in pack.mcmeta.

**Comment by lipki** [comment]
https://github.com/SummerFields/SummerFields/commit/8a4777d784bf02b69dec45d17c3aaa79ca44d10b

solved
