### ISSUE TITLE
Villagers should look a bit more different from each other

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#214]
All types of villagers pretty much look the same in this texture pack it's really hard to differentiate them.

**Comment by lipki** [comment]
yes yes, in fact I had started work on colors closer to default colors.

![pnj](https://cloud.githubusercontent.com/assets/401965/15635764/f6b128a8-25e7-11e6-9524-524e01cf6a05.png)

What do you think ?

**Comment by tobyplowy** [comment]
@lipki these look beautiful. exactly what I meant! (maybe one little suggestion) I think the butcher should have a little bit more blood on him (more like one big splatter instead of just a couple red pixels)

**Comment by tobyplowy** [comment]
@lipki also the difference between the light and the dark colors/pixels on the ropes/clothes of the brown Villager look a bit too flat maybe a bit more contrast between the colors/pixels on the brown villager

**Comment by lipki** [comment]
yes maybe.

If you want to try a correction, these are the textures.

![butcher](https://cloud.githubusercontent.com/assets/401965/15638667/bc9a9272-2622-11e6-9fef-f3aa00c5876c.png)
![farmer](https://cloud.githubusercontent.com/assets/401965/15638672/bca75f98-2622-11e6-9fa4-948b313fc1c6.png)
![librarian](https://cloud.githubusercontent.com/assets/401965/15638668/bc9decec-2622-11e6-9e7f-613c8b131b99.png)
![priest](https://cloud.githubusercontent.com/assets/401965/15638670/bca2b2cc-2622-11e6-8cf6-f742058f0bc2.png)
![smith](https://cloud.githubusercontent.com/assets/401965/15638669/bc9fd390-2622-11e6-96bd-d25090f514ef.png)
![villager](https://cloud.githubusercontent.com/assets/401965/15638671/bca4bbda-2622-11e6-927f-8169b95bb782.png)

**Comment by tobyplowy** [comment]
@lipki I will work on them later today (one little note they definitely look better than the ones in the pack  know

**Comment by tobyplowy** [comment]
@lipki the butcher texture is done. i hope you like it
![butcher](https://cloud.githubusercontent.com/assets/16853304/15652655/057ce3fe-2688-11e6-8d5a-6077f50991b2.png)

**Comment by lipki** [comment]
ok it's better.

**Comment by tobyplowy** [comment]
@lipki well now you're not alone anymore. I'm here to help if that's okay of course :D (so what will happen with the texture now will it get added to the pack?) (also another little thing I would do is add more facial features like the blacksmith/armorur could have black stains on his face because of the coal.

**Comment by lipki** [comment]
Go ! Make yourself happy !
And yes it will be added to the resource pack, when we will be pleased them both.

**Comment by tobyplowy** [comment]
@lipki are you mad? You sound a bit frustrated did I say anything wrong?

**Comment by lipki** [comment]
Non je suis pas fou, je suis francais :D
j'écris trés mal anglais.

No I'm not crazy, I'm french :)
I write very bad in English.

**Comment by tobyplowy** [comment]
@lipki well you sound like a really fun person :D but are you sure it's okay I help if it's not just say it :D (also I'm really thankful that you update this texture pack it means a lot to me)

**Comment by lipki** [comment]
I'm really happy when someone just participate.
I think the Summerfields is best when it is updated by several people.

I finished the "issues" of the snapshot 16w20 and I put my own textures.
you can go criticize and propose yours.

**Comment by lipki** [comment]
New new new villager
white butcher
green librarian
gray smith
![butcher](https://cloud.githubusercontent.com/assets/401965/15906388/e36fb2d6-2db8-11e6-90b1-b550a2168652.png)![farmer](https://cloud.githubusercontent.com/assets/401965/15906390/e3762562-2db8-11e6-94b2-2de7c40eb346.png)![librarian](https://cloud.githubusercontent.com/assets/401965/15906391/e3791eac-2db8-11e6-9d9d-c72c5336bb29.png)![priest](https://cloud.githubusercontent.com/assets/401965/15906393/e37b7850-2db8-11e6-9b5f-0afb69fb9516.png)![villager](https://cloud.githubusercontent.com/assets/401965/15906392/e37ba460-2db8-11e6-907d-40a254b55d6b.png)

![screenshot at 2016-06-08 20 37 15](https://cloud.githubusercontent.com/assets/401965/15906421/145824c8-2db9-11e6-825f-0b45a7e5fbcc.png)

**Comment by tobyplowy** [comment]
I really like the armourer (like really a lot) nice texturing

**Comment by tobyplowy** [comment]
You're probably going to update the zombie villagers if you do could you also change their clothes they have holes in them but they're all the same size and the same position (could you change that)

**Comment by tobyplowy** [comment]
Also where is the Smith texture? I want to make his skurt a little bit less symmetric

**Comment by lipki** [comment]
smith is armorer

**Comment by lipki** [comment]
a ...

**Comment by lipki** [comment]
![smith](https://cloud.githubusercontent.com/assets/401965/15907736/9b9aa244-2dbe-11e6-9978-5ec42e13b542.png)

**Comment by tobyplowy** [comment]
Im going to make the Smith texture his skurt a little bit less symmetric that's my work :) also it seems like you have not noticed [this](https://github.com/SummerFields/official/issues/6) issue yet

**Comment by tobyplowy** [comment]
your texture
![9b9aa244-2dbe-11e6-9978-5ec42e13b542](https://cloud.githubusercontent.com/assets/16853304/15908733/7560559c-2dc3-11e6-945a-32364a6a06a7.png)


my texture
![smith](https://cloud.githubusercontent.com/assets/16853304/15908726/60cba262-2dc3-11e6-8eab-0c45b4621a2f.png)

**Comment by tobyplowy** [comment]
i also made a dirty alternative
dirty
![smith alt](https://cloud.githubusercontent.com/assets/16853304/15908868/1ff0c028-2dc4-11e6-9d63-5561d4855275.png)
clean
![smith](https://cloud.githubusercontent.com/assets/16853304/15908885/3066bf2a-2dc4-11e6-8995-b304a91bfcff.png)

**Comment by lipki** [comment]
Well I valid this, for release 1.10

**Comment by tobyplowy** [comment]
What is for 1.10 your Smith texture or my edit?

**Comment by lipki** [comment]
surprise !! :D

**Comment by tobyplowy** [comment]
lipki can you pleas creddit me on this page, also it needs to be deied to add 1;9 and 1.10 https://github.com/SummerFields/SummerFields/blob/master/README.md

**Comment by lipki** [comment]
This was done on the 1.10, I just merge to master.
I did not put details, you can add more if you want.

**Comment by tobyplowy** [comment]
i have an new smith texture with a red nose just a test do you like it?
![smith](https://cloud.githubusercontent.com/assets/16853304/15925903/72a9f1ac-2e39-11e6-8b5d-f61b3bacc5b6.png)

**Comment by lipki** [comment]
For me NPCs have no nose. !?

**Comment by tobyplowy** [comment]
Well look between his eyes and above his mouth that's definitely a nose on the villagers ( or is it because of the shading it looks like in nose)

**Comment by tobyplowy** [comment]
Can you check out the textures i made [this](https://github.com/SummerFields/official/issues/6) issue Page

**Comment by lipki** [comment]
I reopens for Villagers Nitwit
