### ISSUE TITLE
Update 16w20 - husk texture

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#215]
hallo @lipki i made a husk texture I don't know how I can help with this project but I've always loved summer fields  its been my favorite texture pack. 

I used to make the New textures for the snapshots/updates
I didn't know this existed (github for summerfields also I thought summerfields was dead/discontinued) so this time im sharing my work with the community hopefully it helps (you're probably not even going to put this in the texture pack but it was fun anyways :D

(NOTE) i did my best and if you're interested I could make more textures for example the polar bear And New blocks :D (I'm definitely interested to help this project) also this is just a recolor but the original texture is also just a recolor so yeah
![husk](https://cloud.githubusercontent.com/assets/16853304/15636103/f7097532-25f4-11e6-8d3f-e842558db8f7.png)

**Comment by lipki** [comment]
I invite you to visit this forum to present new texture is more accessible than github for people.

http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1244128-summerfields-1-9-the-end-is-nigh-dont-look-them-in

For the husk, it seems important to me to be different from other zombie.
And above all, he needs a hat, to explain that he does not burn.

But I take all your proposals with pleasure.
I did not create the tickets for the new textures, but it will be done, one ticket per texture.
You can do that.

**Comment by tobyplowy** [comment]
Hello @lipki can I keep doing my work here? I don't like the forums (also the husk texture had a cap but he didn't look too good) :\

**Comment by lipki** [comment]
Yes of course :)

**Comment by lipki** [comment]
my version : 
![husk](https://cloud.githubusercontent.com/assets/401965/15655711/b673891c-269f-11e6-972c-f59c77f0c912.png)
![307109110mob](https://cloud.githubusercontent.com/assets/401965/15655708/a919a7e2-269f-11e6-8e24-4199ed8dc430.png)

**Comment by tobyplowy** [comment]
@lipki okay you're texture looks a billion times better (only the mouth look's a bit weird but apart from that it's awesome) also the cap on his head is that a Miner's hat (it looks amazing) and now the polar bear :P lol

**Comment by lipki** [comment]
done
