### ISSUE TITLE
Zombie horse texture

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#216]
There still needs to be a zombie horse texture.

**Comment by lipki** [comment]
I have one version: D
But I do not like it, so, go ! propose.

**Comment by lipki** [comment]
![horse_zombie](https://cloud.githubusercontent.com/assets/401965/15655863/71a8780e-26a1-11e6-8c24-5fdc891149cd.png)
![307109110mob](https://cloud.githubusercontent.com/assets/401965/15655932/5983ce6c-26a2-11e6-85a2-3794c9f79c55.png)

**Comment by tobyplowy** [comment]
@lipki yeah I agree it could be better (but it could also been worse) I really like the exposed bone in his neck. also I think you should add more exposed flesh/bones because it's a zombie u know :P  ( and actually if you make the texture less blurry it would actually be looking good) in my opinion

**Comment by lipki** [comment]
done ..... pffff

**Comment by tobyplowy** [comment]
lipki you can improve it later don't worry :)
