### ISSUE TITLE
 Update 16w20 - Nether wart block

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#219]
- ![nether_wart_block](https://cloud.githubusercontent.com/assets/401965/15655135/a4471f74-269a-11e6-876b-83b3bac4e988.png) textures/blocks/nether_wart_block.png

**Comment by lipki** [comment]
![nether_wart_block](https://cloud.githubusercontent.com/assets/401965/15655607/e6690db4-269e-11e6-96d9-392cd227d5ca.png)
![435877110block](https://cloud.githubusercontent.com/assets/401965/15655603/dc8da84a-269e-11e6-8c10-14a1c09f20a4.png)

**Comment by tobyplowy** [comment]
@lipki looks nice

**Comment by lipki** [comment]
done
