### ISSUE TITLE
Update 16w20 - Red nether brick

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#220]
- ![red_nether_brick](https://cloud.githubusercontent.com/assets/401965/15655146/baafa678-269a-11e6-870e-15fd05aa3c49.png) textures/blocks/red_nether_brick.png

ref :
![nether_brick](https://cloud.githubusercontent.com/assets/401965/15655414/44c9c9cc-269d-11e6-8b33-2b9e0e5e2d43.png)

**Comment by lipki** [comment]
![435877110block](https://cloud.githubusercontent.com/assets/401965/15655620/0b7b860e-269f-11e6-9c77-3b351c5acec7.png)
![red_nether_brick](https://cloud.githubusercontent.com/assets/401965/15655622/11acc498-269f-11e6-9a0e-b9a25ff5ae19.png)

**Comment by tobyplowy** [comment]
@lipki it's a bit too much red (the original has some red and purple / black in it) maybe make the shading of this book a bit more purple

**Comment by lipki** [comment]
done
