### ISSUE TITLE
Update 16w20 - Bone block

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#221]
- ![bone_block_side](https://cloud.githubusercontent.com/assets/401965/15655150/c4c2d644-269a-11e6-8639-f4b2fd45471b.png) textures/blocks/bone_block_side.png
- ![bone_block_top](https://cloud.githubusercontent.com/assets/401965/15655151/c4c82978-269a-11e6-9a11-849fd6464a4b.png) textures/blocks/bone_block_top.png

**Comment by lipki** [comment]
![bone_block_side](https://cloud.githubusercontent.com/assets/401965/15655637/2ae1ebd2-269f-11e6-8e38-bc3f5b05b77a.png)
![bone_block_top](https://cloud.githubusercontent.com/assets/401965/15655638/2b0bdc94-269f-11e6-8720-8d58b8a4ef63.png)
![435877110block](https://cloud.githubusercontent.com/assets/401965/15655635/264e902a-269f-11e6-88a6-706465adfe06.png)

**Comment by tobyplowy** [comment]
@lipki this one also looks really good! :Wink:

**Comment by lipki** [comment]
done
