### ISSUE TITLE
Update 16w20 - Structure block

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#222]
- ![structure_block](https://cloud.githubusercontent.com/assets/401965/15655187/1a9dfcec-269b-11e6-8655-c81c90d70ac6.png) textures/blocks/structure_block.png
- ![structure_block_corner](https://cloud.githubusercontent.com/assets/401965/15655188/1aa03926-269b-11e6-8914-fbbf97ffe807.png) textures/blocks/structure_block_corner.png
- ![structure_block_data](https://cloud.githubusercontent.com/assets/401965/15655189/1aa47f04-269b-11e6-8177-5ac97a3b6b4e.png) textures/blocks/structure_block_data.png
- ![structure_block_load](https://cloud.githubusercontent.com/assets/401965/15655190/1aa7620a-269b-11e6-94b9-5295f5132e2f.png) textures/blocks/structure_block_load.png
- ![structure_block_save](https://cloud.githubusercontent.com/assets/401965/15655194/1e4fb5ba-269b-11e6-934a-235b7ea86d1f.png) textures/blocks/structure_block_save.png

- ![structure_void](https://cloud.githubusercontent.com/assets/401965/15655229/68b933f6-269b-11e6-8d10-0f78d61b98e0.png) textures/items/structure_void.png

**Comment by lipki** [comment]
![structure_block](https://cloud.githubusercontent.com/assets/401965/15655656/55ecfeac-269f-11e6-8210-2b4da64bdbf6.png)![structure_block_corner](https://cloud.githubusercontent.com/assets/401965/15655657/560fc234-269f-11e6-8baa-0261a17df8ef.png)![structure_block_data](https://cloud.githubusercontent.com/assets/401965/15655658/56135d40-269f-11e6-94d7-57dc74ea3168.png)![structure_block_load](https://cloud.githubusercontent.com/assets/401965/15655659/561a49ac-269f-11e6-9935-a053e4146516.png)![structure_block_save](https://cloud.githubusercontent.com/assets/401965/15655660/561ccf10-269f-11e6-8b0c-c8238f600c87.png)![structure_void](https://cloud.githubusercontent.com/assets/401965/15655680/61d21a40-269f-11e6-9c24-c3db726f86b7.png)

![446180110structure](https://cloud.githubusercontent.com/assets/401965/15655683/67396fc4-269f-11e6-8a89-879a217a9b3d.png)

**Comment by tobyplowy** [comment]
@lipki these look perfect (there's no way I can do it better than this) good job :D

**Comment by lipki** [comment]
done
