### ISSUE TITLE
Update 16w20 - Stray

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#223]
- ![stray](https://cloud.githubusercontent.com/assets/401965/15655249/a7a5e352-269b-11e6-98ec-3c87dc92e4d0.png) textures/entity/skeleton/stray.png
- ![stray_overlay](https://cloud.githubusercontent.com/assets/401965/15655250/a7a9ed1c-269b-11e6-97d4-900e9a09c1da.png) textures/entity/skeleton/stray_overlay.png

**Comment by lipki** [comment]
![stray](https://cloud.githubusercontent.com/assets/401965/15655727/d8c6ae18-269f-11e6-9b57-4c452f3e0f05.png) ![stray_overlay](https://cloud.githubusercontent.com/assets/401965/15655728/d910e24e-269f-11e6-8037-0184802d38de.png)
![307109110mob](https://cloud.githubusercontent.com/assets/401965/15655724/d25ade0a-269f-11e6-916d-eeaba73e138d.png)

**Comment by lipki** [comment]
I have another idea, a ice skeleton.

**Comment by lipki** [comment]
maybe this one?
![stray](https://cloud.githubusercontent.com/assets/401965/15678699/91548612-274f-11e6-8420-1e68ebffadc2.png)
![stray1](https://cloud.githubusercontent.com/assets/401965/15678691/8afa821c-274f-11e6-9af1-e63378bfe8e2.png)

**Comment by lipki** [comment]
but I prefer this one.
the overlay is lousy.

![stray](https://cloud.githubusercontent.com/assets/401965/15678739/ae50dc02-274f-11e6-902e-a04813430562.png)
![stray2](https://cloud.githubusercontent.com/assets/401965/15678744/b1690540-274f-11e6-94a6-cbea8d1dde37.png)

**Comment by tobyplowy** [comment]
@lipki It Looks Better Without The overlay

**Comment by lipki** [comment]
not overlay

**Comment by tobyplowy** [comment]
Keep the overlay as an option for the customizer
