### ISSUE TITLE
I'm going to update the zombie villagers

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#225]
@lipki I'm going to update the zombie villagers so they match the new textures.

**Comment by lipki** [comment]
not worth it :)

**Comment by lipki** [comment]
![zombie_butcher](https://cloud.githubusercontent.com/assets/401965/15656702/4ab731b4-26aa-11e6-92c9-299301078e19.png)
![Uploading zombie_farmer.png…]()
![Uploading zombie_librarian.png…]()
![Uploading zombie_priest.png…]()
![Uploading zombie_smith.png…]()
![Uploading zombie_villager.png…]()

**Comment by tobyplowy** [comment]
@lipki ah shit im to late :D

**Comment by tobyplowy** [comment]
@lipki hire are the ones i made 
![4ab731b4-26aa-11e6-92c9-299301078e19](https://cloud.githubusercontent.com/assets/16853304/15657578/76b558f6-26b2-11e6-86b5-53232e7b03b7.png)
![56b5a1a8-26aa-11e6-9711-0653498fb29d](https://cloud.githubusercontent.com/assets/16853304/15657580/791b58c0-26b2-11e6-8f12-de6e8b6d6e0b.png)
![56b95564-26aa-11e6-82c4-6eec05fe5ea4](https://cloud.githubusercontent.com/assets/16853304/15657582/7bf028be-26b2-11e6-9ddd-f6da65e11006.png)
![56bc4350-26aa-11e6-93f3-64d9cce96f49](https://cloud.githubusercontent.com/assets/16853304/15657583/7d564a76-26b2-11e6-99b9-f6e29f2190fc.png)
![56bf05e0-26aa-11e6-9481-30b37ffce732](https://cloud.githubusercontent.com/assets/16853304/15657584/7e5863b4-26b2-11e6-8151-fcf44ffea792.png)
![5684b89a-26aa-11e6-9c17-20b28ea4de0f](https://cloud.githubusercontent.com/assets/16853304/15657585/7f9c825a-26b2-11e6-9135-70fb158ae77e.png)

**Comment by lipki** [comment]
yes i can

**Comment by tobyplowy** [comment]
@lipki thanks :D

**Comment by lipki** [comment]
![zombie_butcher](https://cloud.githubusercontent.com/assets/401965/15908685/3748887e-2dc3-11e6-8c78-2d07a377f1f6.png)![zombie_farmer](https://cloud.githubusercontent.com/assets/401965/15908686/374c0666-2dc3-11e6-8291-2574e449d45d.png)![zombie_librarian](https://cloud.githubusercontent.com/assets/401965/15908687/374f5e2e-2dc3-11e6-943b-aac0e792b2a0.png)![zombie_priest](https://cloud.githubusercontent.com/assets/401965/15908688/37551e9a-2dc3-11e6-9764-2ff763978b4e.png)![zombie_smith](https://cloud.githubusercontent.com/assets/401965/15908689/3756774a-2dc3-11e6-9ac5-0f53fb3fee55.png)

**Comment by lipki** [comment]
I reopens for Villagers Nitwit
