### ISSUE TITLE
Hey @lipki I have a question for you

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#226]
@lipki (I have a question for you next time if you make a texture wil you record it for me) because I do pixel art but I'm not so good at this art style it would help me see how you do it so I can learn from it (preferably with a screen recorder software And Not a camera :\ ) it would be really awesome if you can do this for me :D

**Comment by lipki** [comment]
me too :)
What I do take these existing textures, modify and mix.
I know well use Gimp, but this is my only strength.

**Comment by tobyplowy** [comment]
@lipki lol ( well I must compliment you they look like completely original textures)

**Comment by lipki** [comment]
thanks
