### ISSUE TITLE
inused skin (not made by me)

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#227]
![builder](https://cloud.githubusercontent.com/assets/401965/15692578/89d47ec0-278f-11e6-852d-6fa0b583113a.png)![builder](https://cloud.githubusercontent.com/assets/401965/15692618/b658b29a-278f-11e6-8f82-7384235d0864.png)
![food](https://cloud.githubusercontent.com/assets/401965/15692580/89dbcfae-278f-11e6-87bb-05f1edb713b2.png)![food](https://cloud.githubusercontent.com/assets/401965/15692637/dc8f3f06-278f-11e6-8a4b-1942053c4e7b.png)
![forge](https://cloud.githubusercontent.com/assets/401965/15692582/89df08fe-278f-11e6-8549-cf35b0cd49a5.png)![forge](https://cloud.githubusercontent.com/assets/401965/15692738/7c762516-2790-11e6-8349-c1dbdaaf5292.png)
![guardelite](https://cloud.githubusercontent.com/assets/401965/15692581/89debbc4-278f-11e6-9a29-075f02aa027c.png)![gardelite](https://cloud.githubusercontent.com/assets/401965/15692736/769c190c-2790-11e6-9067-d6a4b44f9588.png)
![guild](https://cloud.githubusercontent.com/assets/401965/15692583/89e1fb9a-278f-11e6-9bad-7c86823568a5.png)![guild](https://cloud.githubusercontent.com/assets/401965/15692730/6faf7eae-2790-11e6-96f7-3cfa44d8b336.png)
![head](https://cloud.githubusercontent.com/assets/401965/15692584/89ef4926-278f-11e6-8068-1b5f6a8f3118.png)![head](https://cloud.githubusercontent.com/assets/401965/15692711/478a0a16-2790-11e6-9c1b-5457410431ee.png)
![hunter](https://cloud.githubusercontent.com/assets/401965/15692585/89efc612-278f-11e6-9ddb-c788f414d772.png)![hunter](https://cloud.githubusercontent.com/assets/401965/15692706/425d3a22-2790-11e6-9f47-031852b05920.png)
![inn](https://cloud.githubusercontent.com/assets/401965/15692586/89f5597e-278f-11e6-8123-1396ed6fda25.png)![inn](https://cloud.githubusercontent.com/assets/401965/15692704/3d79285e-2790-11e6-8022-f9e41a8d7ff7.png)
![man6](https://cloud.githubusercontent.com/assets/401965/15692587/89fa91c8-278f-11e6-9eb6-c88f5a222882.png)![man6](https://cloud.githubusercontent.com/assets/401965/15692693/352b1bf8-2790-11e6-96bb-ba80244d9698.png)
![man7](https://cloud.githubusercontent.com/assets/401965/15692588/89faa23a-278f-11e6-8ce2-38ac6ffe081a.png)![man7](https://cloud.githubusercontent.com/assets/401965/15692690/2cf4da78-2790-11e6-9961-514a45875877.png)
![member](https://cloud.githubusercontent.com/assets/401965/15692589/89fd1c4a-278f-11e6-8b56-948721b5569f.png)![member](https://cloud.githubusercontent.com/assets/401965/15692686/27d5838a-2790-11e6-9813-ee8e6fbb9274.png)
![smith](https://cloud.githubusercontent.com/assets/401965/15692590/8a080f2e-278f-11e6-91b9-f244a6ab0e76.png)![smith](https://cloud.githubusercontent.com/assets/401965/15692673/104abe06-2790-11e6-9c23-128dd90396e9.png)

**Comment by tobyplowy** [comment]
who made these textures?

**Comment by lipki** [comment]
I don't no.

**Comment by tobyplowy** [comment]
Can we do Whatever we want with this?

**Comment by RobertZenz** [comment]
It seems like [it has originated from here](http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1230882-32x32-1-3-2-pre12w37a-summerfields-r29-a-is-out?comment=1664). Further down the topic [lithiumsound seems to post progress updates](http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1230882-32x32-1-3-2-pre12w37a-summerfields-r29-a-is-out?comment=1674). So there seems to be a good chance that these are from lithiumsound and maybe under the same license as SumemrFields itself.

 > Can we do Whatever we want with this?

No. Unless you know the original author and license, no, just no.

I mean, you *could*...no plaintiff, no judge. *But* including them in SummerFields and licensing them under the CC which SummerFields is under, would be a copyright violation which might yield its ugly head at some point.

**Comment by lipki** [comment]
I'm assuming that he were created textures for Summerfields.
But I'll do a search.

**Comment by lipki** [comment]
> Can we do Whatever we want with this?

My answer is yes, under Summerfields or modpack.
And I assume the result.

**Comment by lunapanshiel** [comment]
they were made by lithiumsound back when they were doing MCpatcher features, it was for randomobs to replace skins of people using the default "steve" skin with ones fitting summerfields. it got removed from the pack along with the CTM and randomobs textures for a while

**Comment by RobertZenz** [comment]
@lunapanshiel You don't happen to have the link to a relevant forum thread or IRC discussion?

**Comment by lipki** [comment]
Thanks for the info:)

**Comment by lipki** [comment]
add in  database

**Comment by CuddleWoozle** [comment]
Just to assuage any who is fearful that these are 'mystery textures'

These are actually made by Lithium.

http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/1230882-32x32-1-3-2-pre12w37a-summerfields-r29-a-is-out

Scroll down, download "Tale of Kingdoms" support.  There they are.  He used them later on for other things, but he was working on the support for that mod.
