### ISSUE TITLE
We have textures for this mod, but no support.

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#229]
- Minion mod
- aether
- btwmodtex
- buildcraft
- extrabiomes
- Metallurgy 2
- Backpacks
- BetterBreeding
- DoggyTalents
- ElementalCreepers
- FiniteLiquid
- MoCreatures
- PetBat
- Ropes+
- XiesFarmingPartial
- XPBooks
- TyberMod
- UsefulStorage
- Carpenter
- ~~Balkon~~
- ~~WeaponsMod~~
- ~~DecorativesMod~~
- ~~PaintersFlowerPot~~
- ~~MultiPage~~

**Comment by tobyplowy** [comment]
aether yes i love aether 2

**Comment by tobyplowy** [comment]
@lipki  aether yes i love aether 2

**Comment by lipki** [comment]
mod support for balkon's weapon done

**Comment by lipki** [comment]
"Decoratives Mod" not updated.

**Comment by lipki** [comment]
"Painters Flower Pot" included in carpenter

**Comment by lipki** [comment]
mod support for "MultipageChest" done

**Comment by tobyplowy** [comment]
can you give me a download for the aether texures and Minion mod and backpack so i downt do unecesery work :D

**Comment by lipki** [comment]
It's very old textures, but here goes.
The minion texture is not terrible, here is the reference in the dungeon keeper.
http://vignette4.wikia.nocookie.net/dungeonkeeper/images/7/77/Imp0.gif/revision/latest?cb=20120728125543
http://vignette3.wikia.nocookie.net/dungeonkeeper/images/3/33/Imp.jpg/revision/latest?cb=20091105234451
