### ISSUE TITLE
New gravel texture

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#231]
The gravel texture in the pack right now is a 16 by 16 Tile in a 4 by 4 (it's a 16 by 16 tile repeated 4 times)

**Comment by lipki** [comment]
yes, is true :)

**Comment by tobyplowy** [comment]
@lipki lol‚ soooooowww. (will you change it?)

**Comment by lipki** [comment]
after you :)

**Comment by tobyplowy** [comment]
new gravel texture 
![gravel](https://cloud.githubusercontent.com/assets/16853304/15758688/0cff0a04-290c-11e6-9016-dedeca571d03.png)

keep the old Texture for customizer

**Comment by lipki** [comment]
![gravel](https://cloud.githubusercontent.com/assets/401965/15759404/cd7b5bb4-290e-11e6-89fb-aa0c4a4fdf72.png)
mouais

**Comment by tobyplowy** [comment]
What is mouais?

**Comment by lipki** [comment]
not sure this is better.

**Comment by tobyplowy** [comment]
Well it gets rid of the 4 by 4 texture :sweat_smile: it's your choice I guess' will you make your texture (also I will give this another try tomorrow) I will make another gravel texture tomorrow (I didn't have too much time today)
