### ISSUE TITLE
Minecraft 1.10 is going to release very shortly

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#232]
Yes Minecraft 1.10 is going to release very shortly (they are now going to work with shorter updates) I personally think it's really short but yeh (if you don't believe it the evidence is [here](https://mobile.twitter.com/SeargeDP/status/738398048062218244))

**Comment by lipki** [comment]
I follow the Minecraft news very closely.
So yes release made, I will release a beta version of the resource pack.

zombie horse is bad :(

**Comment by tobyplowy** [comment]
(zombie horse is bad) what? Dod they remove It?

**Comment by lipki** [comment]
No.
My texture is poor.
It bothers me to put it in the pack.

**Comment by tobyplowy** [comment]
put it in as a temporary texture :\ (or Make a new one (Bdw ther making leather horse armor for mcpe)

**Comment by lipki** [comment]
Release done https://github.com/SummerFields/SummerFields/releases/tag/mc_1.10-b1
