### ISSUE TITLE
 Make MCPE version of minecraft

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#233]
We need an alpha tester for the #PE version of #Summerfields.
You must have the latest version of Minecraft PE and learn to install a texture pack.

**Comment by tobyplowy** [comment]
Sorry but I can't help with that :/

**Comment by tobyplowy** [comment]
@lipki can you give me a download link maybe I can do something

**Comment by lipki** [comment]
She is beautiful :D
you can do the items ?

**Comment by tobyplowy** [comment]
> She is beautiful :D 
What Who is beautiful?

Also yes I want to do the items if you can give me the bace PNG

**Comment by lipki** [comment]
(My comment was for your elytra.)
https://github.com/SummerFields/MCPE/releases/tag/alpha
