### ISSUE TITLE
Fancy Bush models / tree foliage

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#239]
If you don't know what I'm talking about just look at this [image](http://i.imgur.com/6Nq5wYB.png) the bushes at the top have these panels going through them this makes them more bushy

The picture is of this texture pack also the mobiles are in here http://www.planetminecraft.com/texture_pack/john-smith-legacy-3d-models-addon/

**Comment by lipki** [comment]
I'm not to put new models everywhere, it slowed minecraft.
But there is a repo 3d

https://github.com/SummerFields/Summerfields-newmodel

**Comment by tobyplowy** [comment]
Could you make it an option for the customizer?

**Comment by lipki** [comment]
yes of course.

**Comment by tobyplowy** [comment]
Man your just amazing! :D
