### ISSUE TITLE
add new creeper armor texture

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#241]
this texture is not in the pack jet 
Which is surprising this got added in 1.5 (its old :smile:)

![creeper_armor](https://cloud.githubusercontent.com/assets/16853304/15939067/6ebfe2ee-2e76-11e6-89eb-9c01f174e7ed.png)
new texture 
![creeper_armor](https://cloud.githubusercontent.com/assets/16853304/15940991/a81d73c8-2e7e-11e6-9abe-5fc4b429e6e6.png)
![creeper_armor](https://cloud.githubusercontent.com/assets/16853304/15940996/ade4a7b8-2e7e-11e6-8f42-d44743d88cf1.png)

**Comment by lipki** [comment]
too blur, i think.

**Comment by tobyplowy** [comment]
Maybe it could be an alternative for the customizer?
