### ISSUE TITLE
new sunflower texture 

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#242]
i made a new sunflower texture 

old
![double_plant_sunflower_front](https://cloud.githubusercontent.com/assets/16853304/15994043/001a1c58-30f9-11e6-9d8c-deca9495c985.png)
new
![double_plant_sunflower_front](https://cloud.githubusercontent.com/assets/16853304/15994341/ecdb3b1e-3101-11e6-94b3-80c8ecab349e.png)
new back texture

old
![double_plant_sunflower_back](https://cloud.githubusercontent.com/assets/16853304/15994080/39f8de68-30fa-11e6-8493-da347bfd6bf1.png)
new
![double_plant_sunflower_back](https://cloud.githubusercontent.com/assets/16853304/15994075/0aea3ed2-30fa-11e6-95eb-d45e469473e6.png)

**Comment by tobyplowy** [comment]
@lipki what do you think of my new sunflower texture?

**Comment by lipki** [comment]
add in 1.11
