### ISSUE TITLE
new elytra texture

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#243]
@lipki i made this new elytra texture i hope it's good, i did my best. :P
![elytra](https://cloud.githubusercontent.com/assets/16853304/16170969/30e7e3a0-3564-11e6-95f5-c7e9a25282e2.png)

**Comment by lipki** [comment]
She is beautiful :D
you can do the items ?

**Comment by tobyplowy** [comment]
i know its bad but i cant do any beter :/
![elytra](https://cloud.githubusercontent.com/assets/16853304/16177822/fb4d67ae-3637-11e6-99df-0f340acf320f.png)

**Comment by lipki** [comment]
add a broken Version

**Comment by tobyplowy** [comment]
broken Version done
![broken_elytra](https://cloud.githubusercontent.com/assets/16853304/16177894/981a2f08-3639-11e6-8ef4-1bef58f3febf.png)

**Comment by tobyplowy** [comment]
keep the old one for the customiser on the website
