### ISSUE TITLE
Theme packs

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#244]
I think it would be cool to make Theme packs these are packs dedicated to specific Themes (obviously) like Halloween and Christmas, lipki what do you think about this?

**Comment by tobyplowy** [comment]
@lipki what do you think about this?

**Comment by lipki** [comment]
Patient, I will answer you, but contrary to appearance, I do not sleep on github.

Yes it is a good idea, of course, but it takes work, and I do not know if it will be used a lot.

**Comment by tobyplowy** [comment]
I do not sleep on github?
