### ISSUE TITLE
More random textures

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#245]
The randomized textures look amazing but some blocks don't have random textures so that's what this topic is for

**Comment by tobyplowy** [comment]
random mycelium textures
![mycelium_top1](https://cloud.githubusercontent.com/assets/16853304/16362990/fced7290-3bbc-11e6-9479-1db5f39d2459.png)
![mycelium_top2](https://cloud.githubusercontent.com/assets/16853304/16362991/fcf63100-3bbc-11e6-8bda-c1936b12d605.png)
![mycelium_top3](https://cloud.githubusercontent.com/assets/16853304/16362992/fcfd22b2-3bbc-11e6-884a-0cc49e348382.png)
![mycelium_top4](https://cloud.githubusercontent.com/assets/16853304/16362993/fd0ceb34-3bbc-11e6-991f-c8e110a1434e.png)
![mycelium_top5](https://cloud.githubusercontent.com/assets/16853304/16362994/fd229dc6-3bbc-11e6-8b47-a7a305c1a093.png)
![mycelium_top6](https://cloud.githubusercontent.com/assets/16853304/16362995/fd3fedae-3bbc-11e6-8203-ebfd4fae4f15.png)
![mycelium_top7](https://cloud.githubusercontent.com/assets/16853304/16362996/fd72c472-3bbc-11e6-8f7c-56bb21ba360d.png)
![mycelium_top8](https://cloud.githubusercontent.com/assets/16853304/16362998/fddcbd82-3bbc-11e6-8aed-a72d500332a3.png)
![mycelium_top9](https://cloud.githubusercontent.com/assets/16853304/16362997/fddc3768-3bbc-11e6-88b8-777b0f9d2ea6.png)

**Comment by tobyplowy** [comment]
random reed
![reeds1](https://cloud.githubusercontent.com/assets/16853304/16363082/adc66836-3bbf-11e6-9e1e-d7c8a80fe0d9.png)

**Comment by tobyplowy** [comment]
2 random stone textures
![stone1](https://cloud.githubusercontent.com/assets/16853304/16363264/e31f3796-3bc5-11e6-8dad-6f4e32db2b60.png)
![stone2](https://cloud.githubusercontent.com/assets/16853304/16363265/e3a679ea-3bc5-11e6-9c72-02b51eaeb999.png)

**Comment by lipki** [comment]
cool

For reeds is more complex because it is a 3d model.

**Comment by tobyplowy** [comment]
I did my best I will be doing more stuff, will Stone And mycelium get added to the base pack?

**Comment by lipki** [comment]
Yes, it will done.

**Comment by tobyplowy** [comment]
I will probably do some more Wednesday :D

**Comment by tobyplowy** [comment]
random stone_slab_top textures 
![stone_slab_top png2](https://cloud.githubusercontent.com/assets/16853304/17235858/a48bb6a6-5544-11e6-858e-c5be0d8c4c6b.png)
![stone_slab_top png3](https://cloud.githubusercontent.com/assets/16853304/17235859/a65f14be-5544-11e6-8dec-1f4ab880016a.png)
![stone_slab_top png4](https://cloud.githubusercontent.com/assets/16853304/17235862/a8d723ee-5544-11e6-84da-92125248560f.png)
![stone_slab_top png5](https://cloud.githubusercontent.com/assets/16853304/17235865/ac98be8e-5544-11e6-9c12-30ec1b2ee997.png)

**Comment by tobyplowy** [comment]
@lipki some random prismarine_dark textures
tiled
![pev](https://cloud.githubusercontent.com/assets/16853304/17273884/ec5dd1b6-56c6-11e6-9412-a2cb933ca694.png)
the textures
![prismarine_dark1](https://cloud.githubusercontent.com/assets/16853304/17273886/f39e03a6-56c6-11e6-96f0-69fd81702b3c.png)
![prismarine_dark2](https://cloud.githubusercontent.com/assets/16853304/17273887/f3cfbd6a-56c6-11e6-8def-93354ae13b77.png)
![prismarine_dark3](https://cloud.githubusercontent.com/assets/16853304/17273888/f3d17ccc-56c6-11e6-802a-887ffdb0b759.png)
![prismarine_dark4](https://cloud.githubusercontent.com/assets/16853304/17273889/f3d7848c-56c6-11e6-9768-cb27381926dc.png)

**Comment by tobyplowy** [comment]
flowerpots
![flower_pot1](https://cloud.githubusercontent.com/assets/16853304/17273967/a5dbda54-56ca-11e6-936f-a568538326d0.png)
![flower_pot2](https://cloud.githubusercontent.com/assets/16853304/17273968/a60239ec-56ca-11e6-8dd5-a27ff53d8f87.png)
![flower_pot3](https://cloud.githubusercontent.com/assets/16853304/17273969/a61e5f28-56ca-11e6-8bea-ce9f478c855e.png)
![flower_pot4](https://cloud.githubusercontent.com/assets/16853304/17273970/a6252fc4-56ca-11e6-9530-519367910a55.png)

**Comment by tobyplowy** [comment]
@lipki What do you think about the stuff I've made so far (also is this project still active?)

**Comment by lipki** [comment]
That's fine, I'll include them, but with me it's the holidays :)

**Comment by tobyplowy** [comment]
Its holidays For me as well I was just scared, the project was dead again :)

**Comment by tobyplowy** [comment]
@lipki some random prismarine_dark textures
tiled pev
![pev](https://cloud.githubusercontent.com/assets/16853304/17857365/cb8ddfae-6881-11e6-9d47-3557d3e1800c.png)
the textures
![prismarine_dark1](https://cloud.githubusercontent.com/assets/16853304/17857374/d30a9fce-6881-11e6-84d9-ef01a33c4c9b.png)
![prismarine_dark2](https://cloud.githubusercontent.com/assets/16853304/17857373/d30891ac-6881-11e6-9bb8-0483269c06ab.png)
![prismarine_dark3](https://cloud.githubusercontent.com/assets/16853304/17857376/d31b8c8a-6881-11e6-85fb-d82ceace2065.png)
![prismarine_dark4](https://cloud.githubusercontent.com/assets/16853304/17857375/d30e156e-6881-11e6-804b-a338cb77522f.png)

bdw i inprived the previus one

**Comment by lipki** [comment]
add in 1.11

**Comment by lipki** [comment]
![stonebrick_top_random](https://cloud.githubusercontent.com/assets/401965/18614724/aef8000e-7d94-11e6-94ba-cb572f399376.png)

![stonebrick_top](https://cloud.githubusercontent.com/assets/401965/18614729/b91a0348-7d94-11e6-85c9-f10da2951f72.png)
![stonebrick_top_1](https://cloud.githubusercontent.com/assets/401965/18614730/b9469070-7d94-11e6-9383-60cc320e00b0.png)
![stonebrick_top_2](https://cloud.githubusercontent.com/assets/401965/18614732/b9481db4-7d94-11e6-88ae-c9f79bcaaf35.png)
![stonebrick_top_3](https://cloud.githubusercontent.com/assets/401965/18614731/b947de8a-7d94-11e6-844d-7eb6b14bcaca.png)
![stonebrick_top_4](https://cloud.githubusercontent.com/assets/401965/18614733/b94a701e-7d94-11e6-912b-c794b1118645.png)

**Comment by tobyplowy** [comment]
Looks Nice :D

**Comment by tobyplowy** [comment]
Do you have More?

**Comment by tobyplowy** [comment]
@lipki I'm working on a randomization of the cactus Only Question Is Can you shange The cactus with the Flower model ( instead Of A Long Cube use two Planes Crossing each other Like A Flower) is that Possible?

**Comment by tobyplowy** [comment]
i made this
![cactus_plant](https://cloud.githubusercontent.com/assets/16853304/19417947/d56323be-93b9-11e6-96a7-1d565c8b9f3a.png)
this may not work because is to big in that case i  have this
![cactus_plant_flowerpot](https://cloud.githubusercontent.com/assets/16853304/19417955/f9095400-93b9-11e6-9a2c-c9f8b1008cb4.png)

**Comment by tobyplowy** [comment]
it needs to use this texture
![cactus_pot](https://cloud.githubusercontent.com/assets/16853304/19418115/b6b2d9a6-93bd-11e6-82b9-f04b4c2018d3.png)

**Comment by tobyplowy** [comment]
in game
![nice cactus](https://cloud.githubusercontent.com/assets/16853304/19418139/4fdf7648-93be-11e6-9dd3-975d6f5bb96a.png)

**Comment by tobyplowy** [comment]
This is a random model it shuld be randomized with the original cactus in the Pack right now if thats Possible at least

**Comment by lipki** [comment]
Yes it's possible. Very nice you'r cactus :)
I'm not very available right now, but I'll come back.

**Comment by tobyplowy** [comment]
lipki are you on vacation?

**Comment by tobyplowy** [comment]
mushroom_block_inside random its just one ;D
![mushroom_block_inside random](https://cloud.githubusercontent.com/assets/16853304/19832761/f0ddced2-9e2c-11e6-9ef4-594324379216.png)

**Comment by tobyplowy** [comment]
new pumpkin_face_on texture
![pumpkin_face_on](https://cloud.githubusercontent.com/assets/16853304/20024915/f92ec8e0-a2e9-11e6-9ef1-9de3d4869d5a.png)
and 1 random texture (i will make more)
![pumpkin_face_on1](https://cloud.githubusercontent.com/assets/16853304/20024943/2e3b0c74-a2ea-11e6-8841-fbb2a0b4557f.png)

**Comment by tobyplowy** [comment]
@lipki When will you come back exactly :)

**Comment by tobyplowy** [comment]
@lipki do you have more random textures or Textures i should make More randoazasins for?

**Comment by lipki** [comment]
I added all your textures.
We can do more, for all the blocks, the limit is the weight.

**Comment by lipki** [comment]
I close.
We can reopen it if necessary.

**Comment by tobyplowy** [comment]
@lipki perhaps this could be a separate download to Keep The Size low for the default summerfields texture pack

**Comment by lipki** [comment]
We can consider making a light pack, but I don't feel like it. :)

**Comment by tobyplowy** [comment]
It Doesn't Really Matter It's just an Idea, also I Don't Care about it either maybe later
