### ISSUE TITLE
[1.11] the green villager is back

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#246]
topic for new 1.11 update

**Comment by tobyplowy** [comment]
the green villager is back weoh
![green villager](https://cloud.githubusercontent.com/assets/16853304/17858634/b7678d4a-6886-11e6-8dac-a04907d56db4.png)

**Comment by lipki** [comment]
a new villager ?

**Comment by tobyplowy** [comment]
Yes look at the latest snapshot. the picture is called villager.png it's already in the pack but it's not green

**Comment by lipki** [comment]
Ah ok, I had not seen the last snapshot.

I propose to keep the green for nitwit, what you did.
And using a different color for the Librarian, blue for example.

**Comment by lipki** [comment]
![zombie_villager](https://cloud.githubusercontent.com/assets/401965/17931775/5eb23622-6a0d-11e6-8ba3-3074b18cd50a.png)



![zombie_librarian](https://cloud.githubusercontent.com/assets/401965/17931410/a048166c-6a0b-11e6-9f98-74e292e536b7.png)![librarian](https://cloud.githubusercontent.com/assets/401965/17931176/563091e0-6a0a-11e6-8bfd-da9bf3de1749.png)

**Comment by tobyplowy** [comment]
Look's good

**Comment by tobyplowy** [comment]
I really like the new librarian ( one thing that I must point out about the zombie librarian is there still a little green around the blood that's probably because you copy and pasted the blood from the green one)

**Comment by lipki** [comment]
Yes that's it.
I did not find it annoying :)

**Comment by tobyplowy** [comment]
Yeah it's not that annoying for me but it does take away from the quality of the pack

**Comment by lipki** [comment]
Done better !
:D

**Comment by tobyplowy** [comment]
I don't see a difference ( you probably forgot to update the picture)

**Comment by lipki** [comment]
I wanted to say :
you can do better if you want :p

**Comment by tobyplowy** [comment]
I will probably do it later, (after the vacation I think)

**Comment by tobyplowy** [comment]
![blue guy](https://cloud.githubusercontent.com/assets/16853304/18889338/d7118b22-84fc-11e6-9622-297953780d60.png)
Done ;D

**Comment by lipki** [comment]
ok i take it, thank you.
