### ISSUE TITLE
The leaves can't be transparent with Optifine 

### ISSUE THREAD

**Issue by diouxis** [SummerFields/SummerFields#247]
I've tried changing different configuration in the advanced video setting, but the leaves always looks opacity, like they are in the Fast Quality.
Then, I tried replacing the leaves texture form the old version, and it works.

**Comment by lipki** [comment]
I know this bug. It is normally corrected.
In which version do you find this ?

**Comment by lipki** [comment]
@diouxis ping

**Comment by diouxis** [comment]
sorry about the late reply.
I found this in the latest release version of Optifine and Minecraft 1.10.2.
