### ISSUE TITLE
More mod support

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#248]
In the Future (Next updates) Minecraft wil officially support mods on all platforms (console, mobile, and pc) and i thought we need To support More mods (any suggestions?)

**Comment by tobyplowy** [comment]
I was thinking of

The Twilight Forest mod
Mo Creatures
Biomes o plenty
the aether 2
Mr crayfish's furniture mod
And mutant Creatures mod

**Comment by lipki** [comment]
https://github.com/SummerFields/Mod-Twilight-Forest

**Comment by lipki** [comment]
#229

**Comment by tobyplowy** [comment]
Can you split up the Textures in categories for Twilight Forest (like you did with x-decor mod) so I can begin texting them

**Comment by lipki** [comment]
https://github.com/orgs/SummerFields/teams/summerfields-contributor/discussions/4
