### ISSUE TITLE
mutant Creatures mod support

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#249]
support for mutant Creatures mod

**Comment by tobyplowy** [comment]
![zombie](https://cloud.githubusercontent.com/assets/16853304/18617992/f7b4f5a2-7ddc-11e6-8e44-a871d9c63114.png)

**Comment by tobyplowy** [comment]
I'm going to take my time with this one so I doubt it will be ready till 1.11

**Comment by lipki** [comment]
the mod does not exist in 1.11, so it doesn't matter.

**Comment by tobyplowy** [comment]
This one may take a long time until it's complete because I'm actually working on the twilight forest mod at the moment also I cannot start the mutant creatures mod anymore for some reason :/

**Comment by lipki** [comment]
No need to justify yourself :)

**Comment by tobyplowy** [comment]
Well I'm pulling the plug on this
