### ISSUE TITLE
Update 1.11 - “The Exploration Update”

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#250]
New : 
- The green villager #246 :  
  ![villager](https://cloud.githubusercontent.com/assets/401965/18831692/6bbc7398-83e7-11e6-9db3-460290697abd.png)
- The observer #251  
  ![observer_back](https://cloud.githubusercontent.com/assets/401965/18922822/85bb11a4-85aa-11e6-900c-aedf8a2fcb63.png)
  ![observer_front](https://cloud.githubusercontent.com/assets/401965/18922823/85e211d2-85aa-11e6-939e-9b016429a887.png)
  ![observer_side](https://cloud.githubusercontent.com/assets/401965/18922826/86242054-85aa-11e6-813e-ec4c12b57647.png)
  ![observer_top](https://cloud.githubusercontent.com/assets/401965/18922824/85e74332-85aa-11e6-8630-af96b01344c2.png)
- The Shulker Box #252  
  ![shulker_box](https://cloud.githubusercontent.com/assets/401965/18923530/dc9d1614-85ac-11e6-8d04-6b14f18daee5.png)  
  ![shulker_shell](https://cloud.githubusercontent.com/assets/401965/18923595/2305bee4-85ad-11e6-8bde-67513ed0db1e.png)
  ![shulker_black](https://cloud.githubusercontent.com/assets/401965/18923310/140a2e30-85ac-11e6-89f7-f7012ff5a367.png)![shulker_blue](https://cloud.githubusercontent.com/assets/401965/18923314/1414656c-85ac-11e6-951c-5e3862d06014.png)![shulker_brown](https://cloud.githubusercontent.com/assets/401965/18923312/140eda0c-85ac-11e6-93dd-81e897c5056c.png)![shulker_cyan](https://cloud.githubusercontent.com/assets/401965/18923313/141325e4-85ac-11e6-884e-9f032320a590.png)![shulker_gray](https://cloud.githubusercontent.com/assets/401965/18923311/140ea0a0-85ac-11e6-8477-b7c50ab7f7b1.png)![shulker_green](https://cloud.githubusercontent.com/assets/401965/18923318/14262a9a-85ac-11e6-8e57-9da85a2f1b74.png)![shulker_light_blue](https://cloud.githubusercontent.com/assets/401965/18923317/14253996-85ac-11e6-8399-71d3c5bf2e21.png)![shulker_lime](https://cloud.githubusercontent.com/assets/401965/18923319/142d9f5a-85ac-11e6-970a-7afe9fe8aeb2.png)![shulker_magenta](https://cloud.githubusercontent.com/assets/401965/18923320/142de8d4-85ac-11e6-9483-6a196b07ba49.png)![shulker_orange](https://cloud.githubusercontent.com/assets/401965/18923322/1431346c-85ac-11e6-860f-213c739f9419.png)![shulker_pink](https://cloud.githubusercontent.com/assets/401965/18923321/1430b21c-85ac-11e6-86c9-8165f2eb1e08.png)![shulker_purple](https://cloud.githubusercontent.com/assets/401965/18923323/1444822e-85ac-11e6-84c9-736780787e10.png)![shulker_red](https://cloud.githubusercontent.com/assets/401965/18923324/14452a6c-85ac-11e6-8990-e6d11d4bc412.png)![shulker_silver](https://cloud.githubusercontent.com/assets/401965/18923325/14471ee4-85ac-11e6-9450-fc8b781a0df5.png)![shulker_white](https://cloud.githubusercontent.com/assets/401965/18923326/144ac03a-85ac-11e6-913d-f368b4c3decb.png)![shulker_yellow](https://cloud.githubusercontent.com/assets/401965/18923327/144bd344-85ac-11e6-815b-7874b1bb2ffe.png)  
  ![particle](https://cloud.githubusercontent.com/assets/401965/18923309/14069310-85ac-11e6-830c-b20f26cdb868.png)
- Item treasure map #254  
  ![map_filled](https://cloud.githubusercontent.com/assets/401965/18923583/14846c08-85ad-11e6-8066-fb97bb2b767c.png) ![map_filled_markings](https://cloud.githubusercontent.com/assets/401965/18923967/a89ebf50-85ae-11e6-8422-e4cb3ed13f95.png) ![map_icons](https://cloud.githubusercontent.com/assets/401965/18923613/41fa7128-85ad-11e6-8fd4-600078ed9faf.png)
- The Illagers 
  - The Vindicator #255  
    ![vindicator](https://cloud.githubusercontent.com/assets/401965/18922776/4e81bb7a-85aa-11e6-8d45-d2310f829561.png)
  - The Evoker #256  
    ![evoker](https://cloud.githubusercontent.com/assets/401965/18922746/329358ce-85aa-11e6-8fe4-5f8474ebd56f.png)![fangs](https://cloud.githubusercontent.com/assets/401965/18922799/6a7581d6-85aa-11e6-8256-31c32629d0c0.png)
  - The Vex #257  
    ![vex](https://cloud.githubusercontent.com/assets/401965/18922788/5fb8b4de-85aa-11e6-9f01-2a9e979d3387.png)![vex_charging](https://cloud.githubusercontent.com/assets/401965/18922789/61343306-85aa-11e6-8eb8-3ab1d4b42256.png)
- Item Totem of undying #258  
  ![totem](https://cloud.githubusercontent.com/assets/401965/18923601/2d733fb4-85ad-11e6-888a-8b6ae37a0c53.png)
- The Lamas !! yeah ! #259  
  ![llama](https://cloud.githubusercontent.com/assets/401965/18923100/64dfbd9e-85ab-11e6-916c-efd943d1c416.png)![llama_brown](https://cloud.githubusercontent.com/assets/401965/18923099/64de9ac2-85ab-11e6-8b63-3f30c707009d.png)![llama_creamy](https://cloud.githubusercontent.com/assets/401965/18923101/64e1ef10-85ab-11e6-9889-8e967c2f2665.png)![llama_gray](https://cloud.githubusercontent.com/assets/401965/18923102/64e49b5c-85ab-11e6-94c5-0138b2b628d7.png)![llama_white](https://cloud.githubusercontent.com/assets/401965/18923103/64e845a4-85ab-11e6-8c2c-6895d1c3b9df.png)![spit](https://cloud.githubusercontent.com/assets/401965/18923104/64f58fc0-85ab-11e6-918f-4107632c8f03.png)  
  ![decor_black](https://cloud.githubusercontent.com/assets/401965/18923111/6b59a888-85ab-11e6-9da5-5713a69483d8.png)![decor_blue](https://cloud.githubusercontent.com/assets/401965/18923110/6b407bd8-85ab-11e6-9409-ace9ef1365ea.png)![decor_brown](https://cloud.githubusercontent.com/assets/401965/18923109/6b3deb84-85ab-11e6-851b-1d4c14c5acee.png)![decor_cyan](https://cloud.githubusercontent.com/assets/401965/18923113/6b673f70-85ab-11e6-96f6-1a8b360d0d01.png)![decor_gray](https://cloud.githubusercontent.com/assets/401965/18923116/6b748720-85ab-11e6-8399-06c0f4fd6101.png)![decor_green](https://cloud.githubusercontent.com/assets/401965/18923115/6b6f1dd0-85ab-11e6-8cdd-addd5727ee9b.png)![decor_light_blue](https://cloud.githubusercontent.com/assets/401965/18923114/6b6ef47c-85ab-11e6-9e32-21a9f37803ba.png)![decor_lime](https://cloud.githubusercontent.com/assets/401965/18923112/6b6232fa-85ab-11e6-837d-18c31c07e162.png)![decor_magenta](https://cloud.githubusercontent.com/assets/401965/18923117/6b785a9e-85ab-11e6-93e8-9760610f83b5.png)![decor_orange](https://cloud.githubusercontent.com/assets/401965/18923118/6b80be3c-85ab-11e6-81f5-a5f614e214aa.png)![decor_pink](https://cloud.githubusercontent.com/assets/401965/18923119/6b88359a-85ab-11e6-94f8-1d442cc85e75.png)![decor_purple](https://cloud.githubusercontent.com/assets/401965/18923121/6b975a8e-85ab-11e6-8e51-b39607350434.png)![decor_red](https://cloud.githubusercontent.com/assets/401965/18923120/6b91826c-85ab-11e6-9a22-31deb872dbeb.png)![decor_silver](https://cloud.githubusercontent.com/assets/401965/18923124/6ba31dec-85ab-11e6-90a1-220f565948a3.png)![decor_white](https://cloud.githubusercontent.com/assets/401965/18923122/6b99362e-85ab-11e6-946a-1773a577338a.png)![decor_yellow](https://cloud.githubusercontent.com/assets/401965/18923123/6ba179f6-85ab-11e6-911b-df8ed75bb406.png)

Change : 
- The chicken head #262
  ![chicken](https://cloud.githubusercontent.com/assets/401965/18923554/f481a150-85ac-11e6-9843-5974487f5b94.png)
- Horse inventory  
  ![horse](https://cloud.githubusercontent.com/assets/401965/18923519/cfc18e34-85ac-11e6-9e91-dc401b4abfe1.png)

**Comment by tobyplowy** [comment]
> The Lamas !! yeah !

XD

**Comment by lipki** [comment]
@CuddleWoozle  ping

**Comment by tobyplowy** [comment]
@lipki Why do you need @CuddleWoozle

**Comment by lipki** [comment]
She is the official owner, I want to keep abreast of developments.

**Comment by tobyplowy** [comment]
I knew she was developer but I didn't know she was a girl Until Now :D
