### ISSUE TITLE
[1.11] The observer

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#251]
![screenshot at 2016-09-28 17 16 48](https://cloud.githubusercontent.com/assets/401965/18926056/96e9a1a0-85b6-11e6-9c85-8bc7b80cf6f3.png)

![observer_back](https://cloud.githubusercontent.com/assets/401965/18922037/6a1fce4c-85a7-11e6-9e00-c1fa111ae017.png)![observer_front](https://cloud.githubusercontent.com/assets/401965/18922039/6a2644b6-85a7-11e6-8c56-a05073958649.png)![observer_side](https://cloud.githubusercontent.com/assets/401965/18922036/6a1d19f4-85a7-11e6-9593-0f41493b1237.png)![observer_top](https://cloud.githubusercontent.com/assets/401965/18922038/6a21a33e-85a7-11e6-8a24-99205f0e6dac.png)

ref : 
![dispenser_front_horizontal](https://cloud.githubusercontent.com/assets/401965/18833005/d797504a-83ee-11e6-8093-37aa9c7ba3ea.png)![piston_side](https://cloud.githubusercontent.com/assets/401965/18833042/043b908e-83ef-11e6-84e0-394d3e257ab8.png)![piston_inner](https://cloud.githubusercontent.com/assets/401965/18833044/06b3acde-83ef-11e6-936e-f4c9de16fb18.png)![dispenser_front_vertical](https://cloud.githubusercontent.com/assets/401965/18833007/d8bfffa8-83ee-11e6-94f1-57041e8b9e09.png)![dropper_front_horizontal](https://cloud.githubusercontent.com/assets/401965/18833012/dccaba0c-83ee-11e6-85e3-a350b574e2c7.png)![dropper_front_vertical](https://cloud.githubusercontent.com/assets/401965/18833013/dcf6282c-83ee-11e6-927b-ece4bbc822ab.png)![furnace_side](https://cloud.githubusercontent.com/assets/401965/18833017/e12b08d6-83ee-11e6-9f67-a44227d2ceaa.png)![furnace_top](https://cloud.githubusercontent.com/assets/401965/18833019/e23b71e8-83ee-11e6-82ec-acf968e46688.png)
![comparator_off](https://cloud.githubusercontent.com/assets/401965/18833056/1a7e1f88-83ef-11e6-8c00-511135ca2a7e.png)![comparator_on](https://cloud.githubusercontent.com/assets/401965/18833057/1a873604-83ef-11e6-96ec-af8b2103e679.png)![repeater_off](https://cloud.githubusercontent.com/assets/401965/18833062/237cbb8a-83ef-11e6-9ee4-4d1f443e5a2c.png)![repeater_on](https://cloud.githubusercontent.com/assets/401965/18833063/23833e42-83ef-11e6-8853-378b7977fda8.png)![rail_detector_powered](https://cloud.githubusercontent.com/assets/401965/18833087/3f02e186-83ef-11e6-9548-39622feaac7d.png)

**Comment by tobyplowy** [comment]
side
![side](https://cloud.githubusercontent.com/assets/16853304/18890563/f352cf58-8501-11e6-912e-0f55807ee75c.png)
top Note The Arrow Points To the front
![top](https://cloud.githubusercontent.com/assets/16853304/18890573/ff93d186-8501-11e6-952b-a62a00736b68.png)
back
![back](https://cloud.githubusercontent.com/assets/16853304/18890604/1fae1044-8502-11e6-8e8d-552da1887410.png)
front
![front](https://cloud.githubusercontent.com/assets/16853304/18890600/181c4f3a-8502-11e6-912f-c6258a02a84f.png)

**Comment by lipki** [comment]
great :)

It would be nice to do a test with the wood of repeaters inside.
To give color, and because it's more of the family of repeater.

**Comment by tobyplowy** [comment]
I don't know what you mean by that, but If You Would Be interested In editing the texture Go Ahead :)

**Comment by lipki** [comment]
It is really good ...
![screenshot at 2016-09-28 18 30 09](https://cloud.githubusercontent.com/assets/401965/18922651/d5d40692-85a9-11e6-8d1a-ac9acf115889.png)

**Comment by tobyplowy** [comment]
Thank you :)

**Comment by tobyplowy** [comment]
I'm working on a wood variant (I was also wondering How is the customizer going?)

**Comment by lipki** [comment]
He is on vacation, for now.
But I would pass him hello of you. :D

**Comment by tobyplowy** [comment]
I didn't really Mean that what I asked for the customizer ( You know the thing on the website) but you can Still say hello from me :D

**Comment by tobyplowy** [comment]
@lipki wood variant done 

side
![observer_side - kopie](https://cloud.githubusercontent.com/assets/16853304/18928808/011afb22-85c2-11e6-85f9-a70bf10031a6.png)
top
![observer_top - kopie](https://cloud.githubusercontent.com/assets/16853304/18928810/011f6b08-85c2-11e6-87a7-49a88d4a66cc.png)
back
![observer_back - kopie](https://cloud.githubusercontent.com/assets/16853304/18928809/011dd914-85c2-11e6-9769-f61be91cb0ff.png)
front
![observer_front - kopie](https://cloud.githubusercontent.com/assets/16853304/18928811/011ff2bc-85c2-11e6-84e2-ce41fc462ad4.png)

**Comment by tobyplowy** [comment]
@lipki What do you think of the Wood variant also the one that doesn't get added could be added to the customizer on the website

**Comment by lipki** [comment]
![observer_back](https://cloud.githubusercontent.com/assets/401965/18962218/392bddca-8670-11e6-9582-dafc53a027c7.png)![observer_front](https://cloud.githubusercontent.com/assets/401965/18962219/39310d4a-8670-11e6-9ad9-02711c689593.png)![observer_side](https://cloud.githubusercontent.com/assets/401965/18962220/393240b6-8670-11e6-8538-fc96cc7067c6.png)![observer_top](https://cloud.githubusercontent.com/assets/401965/18962221/39390a72-8670-11e6-9569-0175a4b87a4b.png)

Here is a variant.
I add volume with a new model.
arrow painted in red, as on the repeater.
and a sensor in place of the hole on the front.

![screenshot at 2016-09-29 18 11 04](https://cloud.githubusercontent.com/assets/401965/18962225/3d25b374-8670-11e6-8f26-7794e24d60ea.png)

**Comment by tobyplowy** [comment]
Oh you made a custom model for it that's pretty cool ( but I still prefer the Stone one :/ )
Also When will the customizer be working! (Not the guy on Vacation the thing On The website)

**Comment by lipki** [comment]
It was a joke.
The customizer is on vacation = I have not finished.
And I do not know when I'll be over it.
