### ISSUE TITLE
[1.11] The Shulker Box

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#252]
![screenshot at 2016-09-28 17 16 48](https://cloud.githubusercontent.com/assets/401965/18925781/939b3032-85b5-11e6-9436-a78ed78e977b.png)

![shulker_box](https://cloud.githubusercontent.com/assets/401965/18923530/dc9d1614-85ac-11e6-8d04-6b14f18daee5.png)  
![shulker_shell](https://cloud.githubusercontent.com/assets/401965/18923595/2305bee4-85ad-11e6-8bde-67513ed0db1e.png)
![shulker_black](https://cloud.githubusercontent.com/assets/401965/18923310/140a2e30-85ac-11e6-89f7-f7012ff5a367.png)![shulker_blue](https://cloud.githubusercontent.com/assets/401965/18923314/1414656c-85ac-11e6-951c-5e3862d06014.png)![shulker_brown](https://cloud.githubusercontent.com/assets/401965/18923312/140eda0c-85ac-11e6-93dd-81e897c5056c.png)![shulker_cyan](https://cloud.githubusercontent.com/assets/401965/18923313/141325e4-85ac-11e6-884e-9f032320a590.png)![shulker_gray](https://cloud.githubusercontent.com/assets/401965/18923311/140ea0a0-85ac-11e6-8477-b7c50ab7f7b1.png)![shulker_green](https://cloud.githubusercontent.com/assets/401965/18923318/14262a9a-85ac-11e6-8e57-9da85a2f1b74.png)![shulker_light_blue](https://cloud.githubusercontent.com/assets/401965/18923317/14253996-85ac-11e6-8399-71d3c5bf2e21.png)![shulker_lime](https://cloud.githubusercontent.com/assets/401965/18923319/142d9f5a-85ac-11e6-970a-7afe9fe8aeb2.png)![shulker_magenta](https://cloud.githubusercontent.com/assets/401965/18923320/142de8d4-85ac-11e6-9483-6a196b07ba49.png)![shulker_orange](https://cloud.githubusercontent.com/assets/401965/18923322/1431346c-85ac-11e6-860f-213c739f9419.png)![shulker_pink](https://cloud.githubusercontent.com/assets/401965/18923321/1430b21c-85ac-11e6-86c9-8165f2eb1e08.png)![shulker_purple](https://cloud.githubusercontent.com/assets/401965/18923323/1444822e-85ac-11e6-84c9-736780787e10.png)![shulker_red](https://cloud.githubusercontent.com/assets/401965/18923324/14452a6c-85ac-11e6-8990-e6d11d4bc412.png)![shulker_silver](https://cloud.githubusercontent.com/assets/401965/18923325/14471ee4-85ac-11e6-9450-fc8b781a0df5.png)![shulker_white](https://cloud.githubusercontent.com/assets/401965/18923326/144ac03a-85ac-11e6-913d-f368b4c3decb.png)![shulker_yellow](https://cloud.githubusercontent.com/assets/401965/18923327/144bd344-85ac-11e6-815b-7874b1bb2ffe.png)  
![particle](https://cloud.githubusercontent.com/assets/401965/18923309/14069310-85ac-11e6-830c-b20f26cdb868.png)

ref : 
![endergolem](https://cloud.githubusercontent.com/assets/401965/18833129/79cd105c-83ef-11e6-9c32-bd976c3bf3ba.png)

**Comment by tobyplowy** [comment]
This probably uses the same file as the shulker

**Comment by tobyplowy** [comment]
i mede a shulker shell texture ovrer at #260

**Comment by lipki** [comment]
Put your shulker shell  here please.

**Comment by tobyplowy** [comment]
half shell ![shulker_shell - kopie](https://cloud.githubusercontent.com/assets/16853304/18923920/7a0f807a-85ae-11e6-9eb3-c7d8ced135ae.png)
and this is for the customiser :P
![shulker_shell](https://cloud.githubusercontent.com/assets/16853304/18923935/8660cd52-85ae-11e6-86ee-877b2eeb3d13.png)

**Comment by lipki** [comment]
![shulker_box](https://cloud.githubusercontent.com/assets/401965/18935155/8383de14-85de-11e6-8fc6-b11a8e8cd6ea.png)

![particle](https://cloud.githubusercontent.com/assets/401965/18935174/aed4a922-85de-11e6-82c9-1e88d172fbbf.png)
![shulker_black](https://cloud.githubusercontent.com/assets/401965/18935175/aed7339a-85de-11e6-8b63-75df044a5176.png)![shulker_blue](https://cloud.githubusercontent.com/assets/401965/18935176/aed80f86-85de-11e6-950f-48bb50b2c720.png)![shulker_brown](https://cloud.githubusercontent.com/assets/401965/18935177/aedcd872-85de-11e6-9259-79167e2762ca.png)![shulker_cyan](https://cloud.githubusercontent.com/assets/401965/18935179/aee085b2-85de-11e6-8af3-327753959184.png)![shulker_gray](https://cloud.githubusercontent.com/assets/401965/18935178/aee00b64-85de-11e6-9b70-ac1116a71fcc.png)![shulker_green](https://cloud.githubusercontent.com/assets/401965/18935180/aef4432c-85de-11e6-8621-19af62c21811.png)![shulker_light_blue](https://cloud.githubusercontent.com/assets/401965/18935181/aef47388-85de-11e6-8292-a4f4970a64f9.png)![shulker_lime](https://cloud.githubusercontent.com/assets/401965/18935182/aef6488e-85de-11e6-8692-8aa1a99cde03.png)![shulker_magenta](https://cloud.githubusercontent.com/assets/401965/18935183/aefa4038-85de-11e6-91ef-86e49e6113c9.png)![shulker_orange](https://cloud.githubusercontent.com/assets/401965/18935184/aefe75d6-85de-11e6-94da-892735cf0584.png)![shulker_pink](https://cloud.githubusercontent.com/assets/401965/18935185/aeff096a-85de-11e6-9bcc-a3f86e681e0f.png)![shulker_purple](https://cloud.githubusercontent.com/assets/401965/18935186/af12e1c4-85de-11e6-9451-bce7c5c4fdc4.png)![shulker_red](https://cloud.githubusercontent.com/assets/401965/18935187/af14072a-85de-11e6-90d5-e5581329d1f5.png)![shulker_silver](https://cloud.githubusercontent.com/assets/401965/18935188/af155332-85de-11e6-90e5-b01bcfc197e7.png)![shulker_white](https://cloud.githubusercontent.com/assets/401965/18935189/af19eaa0-85de-11e6-8a2b-b3f3921a23fe.png)![shulker_yellow](https://cloud.githubusercontent.com/assets/401965/18935190/af1fe086-85de-11e6-8ef9-ec1797cad9c0.png)

**Comment by lipki** [comment]
![screenshot at 2016-09-29 00 56 52](https://cloud.githubusercontent.com/assets/401965/18935413/2a6b8c9e-85e0-11e6-9ff8-add77f2804a7.png)

**Comment by tobyplowy** [comment]
Looks Nice I really like the colors ;D

**Comment by tobyplowy** [comment]
lipki can you get ridof the wool textures on the shulker box textures?

**Comment by lipki** [comment]
yes but ... why ?

**Comment by tobyplowy** [comment]
Ocd :/

**Comment by tobyplowy** [comment]
It anoys me
