### ISSUE TITLE
[1.11] Item treasure map

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#254]
![firefox-2016-09-25-20-15-50-80-560x350](https://cloud.githubusercontent.com/assets/401965/18833192/d8b54490-83ef-11e6-83bf-c2abe64dc5eb.jpg)

![map_filled](https://cloud.githubusercontent.com/assets/401965/18923583/14846c08-85ad-11e6-8066-fb97bb2b767c.png) ![map_filled_markings](https://cloud.githubusercontent.com/assets/401965/18923967/a89ebf50-85ae-11e6-8422-e4cb3ed13f95.png)  
![map_icons](https://cloud.githubusercontent.com/assets/401965/18923613/41fa7128-85ad-11e6-8fd4-600078ed9faf.png)

ref : 
![map_filled](https://cloud.githubusercontent.com/assets/401965/18833202/e45fcd4c-83ef-11e6-9c77-c4822d02183b.png)

**Comment by tobyplowy** [comment]
![treshure map](https://cloud.githubusercontent.com/assets/16853304/18889506/88d57d78-84fd-11e6-8edb-9a30a6d140c2.png) i think we shuld use the old one as treasure map and the new one as normal map maby?
![map](https://cloud.githubusercontent.com/assets/16853304/18889522/a3442ae2-84fd-11e6-9d8f-07e007406dcb.png)

**Comment by lipki** [comment]
yes, i make that :

![map_empty](https://cloud.githubusercontent.com/assets/401965/18923931/84825fe6-85ae-11e6-8492-e62ea31a3895.png) empty
![map_filled](https://cloud.githubusercontent.com/assets/401965/18923932/84854134-85ae-11e6-8925-7a922d2fc5fb.png) filled
![map_treasure](https://cloud.githubusercontent.com/assets/401965/18923933/848aff0c-85ae-11e6-9c4d-716935f3f7e7.png) treasure

**Comment by lipki** [comment]
![map_filled](https://cloud.githubusercontent.com/assets/401965/18924696/7cecc368-85b1-11e6-8478-3456bca029f2.png)
![map_filled_markings](https://cloud.githubusercontent.com/assets/401965/18924695/7ce83f5a-85b1-11e6-962d-a3b43dfc564f.png)
![screenshot at 2016-09-28 19 26 33](https://cloud.githubusercontent.com/assets/401965/18924724/96b4200c-85b1-11e6-92e7-641018a40f77.png)

**Comment by tobyplowy** [comment]
Looks good

**Comment by tobyplowy** [comment]
i made this map icones 
![map_icons](https://cloud.githubusercontent.com/assets/16853304/18946795/ca0df70a-8630-11e6-8a4c-028438fe02b3.png)
im happy with the ocean temple icone but i hete the mension icone and i cant make it better :/

**Comment by lipki** [comment]
maybe like this :  
![ca0df70a-8630-11e6-8a4c-028438fe02b3](https://cloud.githubusercontent.com/assets/401965/18954349/ece16506-8652-11e6-9d60-7a203b2067cd.png)

**Comment by tobyplowy** [comment]
Jeh that Looks better but maby change the outline to be not Black

**Comment by tobyplowy** [comment]
Im gonna do that

**Comment by tobyplowy** [comment]
here i fixed the out line
bdw sorry my textures are so bad and you have to fix them sometimes :/
![ece16506-8652-11e6-9d60-7a203b2067cd](https://cloud.githubusercontent.com/assets/16853304/18955331/47044d1a-8657-11e6-833a-72141c15de54.png)

**Comment by lipki** [comment]
No, it's a teamwork.

**Comment by tobyplowy** [comment]
that's actually sort of true I guess
