### ISSUE TITLE
[1.11] The Vindicator

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#255]
![firefox-2016-09-25-20-24-30-52-560x350](https://cloud.githubusercontent.com/assets/401965/18833224/fc997462-83ef-11e6-8edd-e06bced9435a.jpg)

![vindicator](https://cloud.githubusercontent.com/assets/401965/18922883/a2eef8da-85aa-11e6-8433-261b95a11f62.png)

ref : 
![zombie_smith](https://cloud.githubusercontent.com/assets/401965/18844440/89649dea-841d-11e6-921d-5074c1c0a048.png)

**Comment by lipki** [comment]
First draft
I chose a butler outfit.

![vindicator](https://cloud.githubusercontent.com/assets/401965/18844366/48d0eb3a-841d-11e6-9268-953f520e2353.png)
![screenshot at 2016-09-26 19 11 53](https://cloud.githubusercontent.com/assets/401965/18844362/44fd0ea8-841d-11e6-867d-4d8ad7135b73.png)

**Comment by tobyplowy** [comment]
this is my texture
![farmer](https://cloud.githubusercontent.com/assets/16853304/18850339/65ba411e-8437-11e6-94d9-384f00af9b70.png)
i think we need to keep the gray skin

**Comment by tobyplowy** [comment]
this is my texture
![farmer](https://cloud.githubusercontent.com/assets/16853304/18850339/65ba411e-8437-11e6-94d9-384f00af9b70.png)
i think we need to keep the gray skin and bald head

**Comment by tobyplowy** [comment]
@lipki what do you think of my texture? Is the Mad face good?

**Comment by tobyplowy** [comment]
this is my texture
![vindicator](https://cloud.githubusercontent.com/assets/16853304/18921129/eef2f788-85a3-11e6-8ce6-103db75ad932.png)

i think we need to keep the gray skin and bald head
also hes mad :D

**Comment by lipki** [comment]
he look good.

but
the hood is force, it is in the contract. :)

But gray skin is good, the costume is correct, but perhaps too wise, and the face is great.

**Comment by lipki** [comment]
![screenshot at 2016-09-28 19 36 32](https://cloud.githubusercontent.com/assets/401965/18925185/2e2820c2-85b3-11e6-8982-08ee4b5edff0.png)

![screenshot at 2016-09-28 19 37 45](https://cloud.githubusercontent.com/assets/401965/18925184/2e24f0fa-85b3-11e6-81ef-1273c8b7afbe.png)
![vindicator](https://cloud.githubusercontent.com/assets/401965/18925192/398042ce-85b3-11e6-8489-bb5c43421001.png)

**Comment by tobyplowy** [comment]
I don't really feel comfortable with the Hood but the butler costume Looks Nice

**Comment by lipki** [comment]
Me to, the hood does not please me, but it must cover their heads, perhaps another hat.

**Comment by tobyplowy** [comment]
Why exactly do you have to wear something on their head? If you really have to give him a hat I think a ball hat Would Look Good http://thumbnail.image.rakuten.co.jp/@0_mall/platz-ts/cabinet/vwhat/bolhatbrn2.jpg

**Comment by tobyplowy** [comment]
@lipki Why exactly do they have to wear something on their head? If you really have to give him a hat I think a ball hat Would Look Good http://thumbnail.image.rakuten.co.jp/@0_mall/platz-ts/cabinet/vwhat/bolhatbrn2.jpg

**Comment by lipki** [comment]
![screenshot at 2016-10-01 18 30 02](https://cloud.githubusercontent.com/assets/401965/19015464/2251f0da-8805-11e6-9420-a49c349de1bb.png)

**Comment by tobyplowy** [comment]
I really like this, It Looks Like Those guys who wait in the elevators because The people in the elevator have too much money to press the button them self XD
