### ISSUE TITLE
[1.11] The Evoker

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#256]
![firefox-2016-09-25-20-25-08-69-560x350](https://cloud.githubusercontent.com/assets/401965/18833268/26bb22f4-83f0-11e6-977a-68d44a9b406a.jpg)

![evoker](https://cloud.githubusercontent.com/assets/401965/18922931/d41d3f7a-85aa-11e6-9909-1011e04b9a2c.png)![fangs](https://cloud.githubusercontent.com/assets/401965/18922933/d585f032-85aa-11e6-9e59-2a5b22c564c4.png)

ref : 
![witch](https://cloud.githubusercontent.com/assets/401965/18833272/2fbb9f0a-83f0-11e6-91a0-ddaa2127bcb2.png)
Remember: no gender in minecraft.

**Comment by tobyplowy** [comment]
![farmer - kopie](https://cloud.githubusercontent.com/assets/16853304/18850298/38d9ea50-8437-11e6-978c-6c589a96c5f3.png) i made this

**Comment by tobyplowy** [comment]
![evoker](https://cloud.githubusercontent.com/assets/16853304/18921067/b3ce7736-85a3-11e6-81a5-b0e08e0900f6.png)

**Comment by tobyplowy** [comment]
My Evoker texture Doesn't Look great

**Comment by lipki** [comment]
no no it's not bad.

![screenshot at 2016-09-28 19 43 22](https://cloud.githubusercontent.com/assets/401965/18925497/7a443b3e-85b4-11e6-85db-dc0b0d269d10.png)


I had done that (but I took your gray skin)

![screenshot at 2016-09-28 19 46 08](https://cloud.githubusercontent.com/assets/401965/18925501/7d365912-85b4-11e6-8d2b-f26ca4038a78.png)
![evoker](https://cloud.githubusercontent.com/assets/401965/18925507/82140b46-85b4-11e6-9fb6-8c49f2ca945f.png)

**Comment by tobyplowy** [comment]
your Texture is a lot better :/

**Comment by tobyplowy** [comment]
@lipki thers no issue for the fangs (and i cant make a new one becuse you dount like that :P) but this is relateble 
![fangs](https://cloud.githubusercontent.com/assets/16853304/18969535/d9515ec0-868d-11e6-893a-25358671fad8.png)
![naamloos](https://cloud.githubusercontent.com/assets/16853304/18969542/dd27ce6c-868d-11e6-9749-ce9123b852ce.png)
(NOTE) you downt wanna know how hard it was to get this immage i hate the Evoker huh

**Comment by tobyplowy** [comment]
@lipki you forgot the shading on his face
this is a fix for it
![82140b46-85b4-11e6-9fb6-8c49f2ca945f](https://cloud.githubusercontent.com/assets/16853304/19015098/cb2555a6-87fd-11e6-921e-8f8e9caf7576.png)

**Comment by lipki** [comment]
![screenshot at 2016-10-01 17 56 12](https://cloud.githubusercontent.com/assets/401965/19015248/07a8a99e-8801-11e6-848b-e2001d3fc9d2.png)
![screenshot at 2016-10-01 17 59 32](https://cloud.githubusercontent.com/assets/401965/19015250/08fad7fe-8801-11e6-8d99-0a30b97fa044.png)

**Comment by lipki** [comment]
I like the fangs, I thought I had written.

**Comment by tobyplowy** [comment]
I like the one with the red stripes on his face and Red Lines on his clothes It Makes him Look Real Evil :3
