### ISSUE TITLE
[1.11] The Vex

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#257]
![firefox-2016-09-25-20-24-42-86-560x350](https://cloud.githubusercontent.com/assets/401965/18833340/757ba26a-83f0-11e6-8d0a-934b85b8a57f.jpg)

![vex](https://cloud.githubusercontent.com/assets/401965/18922996/065f997e-85ab-11e6-8115-2d8924bdbf7f.png)![vex_charging](https://cloud.githubusercontent.com/assets/401965/18922997/0689c3ca-85ab-11e6-93ab-058297d3a4e0.png)

ref : 
![elytra](https://cloud.githubusercontent.com/assets/401965/18833377/98733b98-83f0-11e6-898d-642b786d3918.png)![elytra_ange](https://cloud.githubusercontent.com/assets/401965/18833376/98717204-83f0-11e6-90ff-c1c64f9c7ce9.png)
![broken_elytra](https://cloud.githubusercontent.com/assets/401965/18833546/7608ce82-83f1-11e6-9012-7a3b1fc5e1d1.png)![broken_elytra_ange](https://cloud.githubusercontent.com/assets/401965/18833547/760b20c4-83f1-11e6-93d5-2953065747cb.png)

**Comment by tobyplowy** [comment]
I think they should reference the Red Wings more but Without The flaps ( you know those things that are connected between the bones the ligt parts)

**Comment by lipki** [comment]
Yes I understand.
I like the idea of mortal angels ...
Or crying angel of dr who.
I do not know yet.

**Comment by tobyplowy** [comment]
I think it should be a dark angel, But The Doctor Who angel is a nice reference :/

**Comment by tobyplowy** [comment]
i made this (note this is not supost to look good i diddent even trie)
![vex](https://cloud.githubusercontent.com/assets/16853304/19015355/4496ad54-8803-11e6-8e22-761486a7e2d5.png)
![vex_charging](https://cloud.githubusercontent.com/assets/16853304/19015354/4495ac24-8803-11e6-8e69-bb22ed8aa7ee.png)

**Comment by tobyplowy** [comment]
Also this uses the creeper texture but you probably already noticed that

**Comment by lipki** [comment]
Not so bad after all.
![screenshot at 2016-10-01 18 42 49](https://cloud.githubusercontent.com/assets/401965/19015546/f204c34c-8806-11e6-9d4f-a2491855e020.png)

**Comment by lipki** [comment]
little test.

Vex
![screenshot at 2016-10-01 19 20 52](https://cloud.githubusercontent.com/assets/401965/19015884/39fc00ce-880d-11e6-885f-d878da239ff1.png)
![screenshot at 2016-10-01 19 20 44](https://cloud.githubusercontent.com/assets/401965/19015885/3b0f2eb4-880d-11e6-946e-6723a2f90205.png)

Vex charging
![screenshot at 2016-10-01 19 20 00](https://cloud.githubusercontent.com/assets/401965/19015881/33f8485e-880d-11e6-9220-deead471547b.png)
![screenshot at 2016-10-01 19 20 13](https://cloud.githubusercontent.com/assets/401965/19015883/375ad282-880d-11e6-87b5-1b91146a2ee1.png)


![screenshot at 2016-10-01 19 36 49](https://cloud.githubusercontent.com/assets/401965/19015952/8e34d066-880e-11e6-9892-c01f6459f8e3.png)

**Comment by tobyplowy** [comment]
@lipki you made it look so awesome I'm so jealous at you because you're so good at This :P 
Also a Little Note about The texture there are no hands to hold the sword (my mistake)
