### ISSUE TITLE
[1.11] Item Totem of undying

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#258]
![firefox-2016-09-25-20-29-48-93-560x350](https://cloud.githubusercontent.com/assets/401965/18833436/dfcb2d48-83f0-11e6-9ffd-d7e05623d1ab.jpg)

![totem](https://cloud.githubusercontent.com/assets/401965/18923601/2d733fb4-85ad-11e6-888a-8b6ae37a0c53.png)

**Comment by tobyplowy** [comment]
Lipki This one is your job I have no Idea What to do with this :/

**Comment by lipki** [comment]
first try : ![totem](https://cloud.githubusercontent.com/assets/401965/19015075/219b4130-87fd-11e6-8234-c42ead7e1bb6.png)

I'm not super happy with the item.
But still, it makes good in games, try it.

![screenshot at 2016-10-01 17 29 18](https://cloud.githubusercontent.com/assets/401965/19015076/262728b8-87fd-11e6-927a-197283b6524c.png)

**Comment by tobyplowy** [comment]
I really like the idea of a voodoo doll This Looks quite Nice
