### ISSUE TITLE
[1.11] The Llama

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#259]
![firefox-2016-09-25-20-31-31-97-560x350](https://cloud.githubusercontent.com/assets/401965/18833464/12cb83e6-83f1-11e6-8572-766645c44147.jpg)

![llama](https://cloud.githubusercontent.com/assets/401965/18923100/64dfbd9e-85ab-11e6-916c-efd943d1c416.png)![llama_brown](https://cloud.githubusercontent.com/assets/401965/18923099/64de9ac2-85ab-11e6-8b63-3f30c707009d.png)![llama_creamy](https://cloud.githubusercontent.com/assets/401965/18923101/64e1ef10-85ab-11e6-9889-8e967c2f2665.png)![llama_gray](https://cloud.githubusercontent.com/assets/401965/18923102/64e49b5c-85ab-11e6-94c5-0138b2b628d7.png)![llama_white](https://cloud.githubusercontent.com/assets/401965/18923103/64e845a4-85ab-11e6-8c2c-6895d1c3b9df.png)![spit](https://cloud.githubusercontent.com/assets/401965/18923104/64f58fc0-85ab-11e6-918f-4107632c8f03.png)  
![decor_black](https://cloud.githubusercontent.com/assets/401965/18923111/6b59a888-85ab-11e6-9da5-5713a69483d8.png)![decor_blue](https://cloud.githubusercontent.com/assets/401965/18923110/6b407bd8-85ab-11e6-9409-ace9ef1365ea.png)![decor_brown](https://cloud.githubusercontent.com/assets/401965/18923109/6b3deb84-85ab-11e6-851b-1d4c14c5acee.png)![decor_cyan](https://cloud.githubusercontent.com/assets/401965/18923113/6b673f70-85ab-11e6-96f6-1a8b360d0d01.png)![decor_gray](https://cloud.githubusercontent.com/assets/401965/18923116/6b748720-85ab-11e6-8399-06c0f4fd6101.png)![decor_green](https://cloud.githubusercontent.com/assets/401965/18923115/6b6f1dd0-85ab-11e6-8cdd-addd5727ee9b.png)![decor_light_blue](https://cloud.githubusercontent.com/assets/401965/18923114/6b6ef47c-85ab-11e6-9e32-21a9f37803ba.png)![decor_lime](https://cloud.githubusercontent.com/assets/401965/18923112/6b6232fa-85ab-11e6-837d-18c31c07e162.png)![decor_magenta](https://cloud.githubusercontent.com/assets/401965/18923117/6b785a9e-85ab-11e6-93e8-9760610f83b5.png)![decor_orange](https://cloud.githubusercontent.com/assets/401965/18923118/6b80be3c-85ab-11e6-81f5-a5f614e214aa.png)![decor_pink](https://cloud.githubusercontent.com/assets/401965/18923119/6b88359a-85ab-11e6-94f8-1d442cc85e75.png)![decor_purple](https://cloud.githubusercontent.com/assets/401965/18923121/6b975a8e-85ab-11e6-8e51-b39607350434.png)![decor_red](https://cloud.githubusercontent.com/assets/401965/18923120/6b91826c-85ab-11e6-9a22-31deb872dbeb.png)![decor_silver](https://cloud.githubusercontent.com/assets/401965/18923124/6ba31dec-85ab-11e6-90a1-220f565948a3.png)![decor_white](https://cloud.githubusercontent.com/assets/401965/18923122/6b99362e-85ab-11e6-946a-1773a577338a.png)![decor_yellow](https://cloud.githubusercontent.com/assets/401965/18923123/6ba179f6-85ab-11e6-911b-df8ed75bb406.png)

ref : 
![sheep_fur](https://cloud.githubusercontent.com/assets/401965/18833487/3149f762-83f1-11e6-9112-fa18bf57b4ea.png)

**Comment by tobyplowy** [comment]
Holy shit you work fast I was just going to post this stuff here Looks Like im Too Late for the party huh :)

**Comment by lipki** [comment]
the summary of snapshot, Rather do it myself.

**Comment by tobyplowy** [comment]
So you don't want me to help?

**Comment by lipki** [comment]
I like to create the "issue", but just the "issue" for the rest of course I want your help.
I am very happy even.

**Comment by tobyplowy** [comment]
oh ok i get it :D 

hey i started work on this lama texture but i downt feal like compleating it today maby is usfull to you
![llama_white](https://cloud.githubusercontent.com/assets/16853304/18924266/d5c9c230-85af-11e6-985d-13933a3db5e5.png)

**Comment by tobyplowy** [comment]
![decor_blue](https://cloud.githubusercontent.com/assets/16853304/18964743/7c2f1128-867a-11e6-86bb-4349d69c03d4.png)

also can you add my name to the Thanks in the README

**Comment by lipki** [comment]
> also can you add my name to the Thanks in the README

It's done.
it will be updated as and measurement.

ok good start for carpets.
do not hesitate to change the patterns.

**Comment by tobyplowy** [comment]
I have an Idea You Can do the lama textures while i do the carpet textures?

**Comment by lipki** [comment]
![screenshot at 2016-09-30 03 06 24](https://cloud.githubusercontent.com/assets/401965/18977542/81ffd182-86bb-11e6-9f92-0afd8e25fc90.png)
I have to redo the muzzle.

![llama](https://cloud.githubusercontent.com/assets/401965/18977551/906220c2-86bb-11e6-9abf-dc0b114984c6.png)![llama_brown](https://cloud.githubusercontent.com/assets/401965/18977552/908a0ce0-86bb-11e6-9683-88c90a6d2363.png)![llama_creamy](https://cloud.githubusercontent.com/assets/401965/18977554/90933b62-86bb-11e6-8eef-e7adc68e2d74.png)![llama_gray](https://cloud.githubusercontent.com/assets/401965/18977553/909066d0-86bb-11e6-8a77-8a64ed3fe3d1.png)![llama_white](https://cloud.githubusercontent.com/assets/401965/18977555/9095017c-86bb-11e6-8d46-8633b1666fd6.png)

**Comment by tobyplowy** [comment]
Yeah the muzzle is a bit strange (now it looks like he's an alien and has 4 eyes)

**Comment by tobyplowy** [comment]
decor_brown done
![decor_brown](https://cloud.githubusercontent.com/assets/16853304/19015003/bc26a9c6-87fb-11e6-9c21-c43eb0c0aad2.png)
 
also i dount like the color of this texture
![llama_creamy](https://cloud.githubusercontent.com/assets/16853304/19015013/dbf31c44-87fb-11e6-8615-a575836ed77f.png)

**Comment by tobyplowy** [comment]
lipki what is spit.png?

**Comment by lipki** [comment]
no idea

**Comment by tobyplowy** [comment]
I don't seem to find what its for, I think It Gets overlayd on ther moth when they spit but im not sure About It :/ 

Also Do You Like my Brown carpet Texture
I also made a fang texture over at #256 what do you think about it

**Comment by lipki** [comment]
I had not seen the carpet, it's great: D
I'll redo the gray texture.

**Comment by tobyplowy** [comment]
I know what Spit.png is for, now, If The lama spits it shoots a 3D particle

**Comment by OwOV** [comment]
The nose holes could be a fainter color so it doesn't look like another pair of eyes.
Also I'm wondering if the llama decor colors are from the carpet colors? The images seem brighter. 
If not then I think the decor should be the same color as the carpets in the texture.
I do love the designs on them though! Also hello!

**Comment by tobyplowy** [comment]
@OwOV look hoe we have here a new person, Welcome to the summerFields project ;)
the decore Use the wool Texture also thank you i really do my best :D

**Comment by tobyplowy** [comment]
lipki can you make the carpets I don't really have time sorry i did my best :/

**Comment by tobyplowy** [comment]
@lipki Can you do the rest of the Carpets and Fix The Gray lama

**Comment by lipki** [comment]
![screenshot at 2016-10-09 23 39 11](https://cloud.githubusercontent.com/assets/401965/19223979/40a0e834-8e7c-11e6-9532-5baed6bbe412.png)

![llama_brown](https://cloud.githubusercontent.com/assets/401965/19223983/5b751d7e-8e7c-11e6-8b6d-1ed8d69d0394.png)![llama_creamy](https://cloud.githubusercontent.com/assets/401965/19223982/5b744084-8e7c-11e6-932e-45b82f239807.png)![llama_gray](https://cloud.githubusercontent.com/assets/401965/19223984/5b7c808c-8e7c-11e6-961b-9ece46ab09e0.png)![llama_white](https://cloud.githubusercontent.com/assets/401965/19223985/5d7d3462-8e7c-11e6-8b1c-9672091ee0e2.png)

![decor_black](https://cloud.githubusercontent.com/assets/401965/19223987/624ca734-8e7c-11e6-9de9-6db7fa69172b.png)![decor_blue](https://cloud.githubusercontent.com/assets/401965/19223990/6278f65e-8e7c-11e6-80ac-a3720384e00a.png)![decor_brown](https://cloud.githubusercontent.com/assets/401965/19223991/62791bfc-8e7c-11e6-9449-356ae25762ba.png)![decor_cyan](https://cloud.githubusercontent.com/assets/401965/19223989/6276c55a-8e7c-11e6-95f0-817877459709.png)![decor_gray](https://cloud.githubusercontent.com/assets/401965/19223992/627d7a6c-8e7c-11e6-8076-73d1a82cbefa.png)![decor_green](https://cloud.githubusercontent.com/assets/401965/19223993/627d7382-8e7c-11e6-9857-baf16372e269.png)![decor_light_blue](https://cloud.githubusercontent.com/assets/401965/19223988/626ab22e-8e7c-11e6-867b-c9ceca02050b.png)![decor_lime](https://cloud.githubusercontent.com/assets/401965/19223994/628588ec-8e7c-11e6-8569-abfdd4ddce5e.png)![decor_magenta](https://cloud.githubusercontent.com/assets/401965/19223995/62925040-8e7c-11e6-8bf3-64399bb9b4ed.png)![decor_orange](https://cloud.githubusercontent.com/assets/401965/19223996/62942e2e-8e7c-11e6-9298-8c730df5cb43.png)![decor_pink](https://cloud.githubusercontent.com/assets/401965/19223997/62a14ad2-8e7c-11e6-975e-dba6f2d97fd6.png)![decor_purple](https://cloud.githubusercontent.com/assets/401965/19223999/62a2c452-8e7c-11e6-8932-2e475665f946.png)![decor_red](https://cloud.githubusercontent.com/assets/401965/19223998/62a27542-8e7c-11e6-9f30-4af3ee0f44c6.png)![decor_silver](https://cloud.githubusercontent.com/assets/401965/19224000/62a639b6-8e7c-11e6-9998-ac71865106d6.png)![decor_white](https://cloud.githubusercontent.com/assets/401965/19224001/62ac2862-8e7c-11e6-8046-31909667f010.png)![decor_yellow](https://cloud.githubusercontent.com/assets/401965/19224002/62aeb1a4-8e7c-11e6-81b3-5b4ae1db9ba8.png)

**Comment by tobyplowy** [comment]
Nice job lipki i like them

**Comment by tobyplowy** [comment]
@lipki Are You Still there?
