### ISSUE TITLE
[1.11] Shulker Shell

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#260]
This is basically the shulker's shell used to craft The shulker box

**Comment by tobyplowy** [comment]
Shulker Shell item texture done
![shulker shell](https://cloud.githubusercontent.com/assets/16853304/18883144/64933f92-84e2-11e6-9bca-bb7fb5ed5073.png)

**Comment by lipki** [comment]
Yeah ok, but keep this up.
We loot only half box.

I close duplicate #252
