### ISSUE TITLE
lucky block mod

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#261]
is rilly popular and its easy :D

**Comment by lipki** [comment]
yep

**Comment by tobyplowy** [comment]
100% Done

lucky_block
![lucky_block](https://cloud.githubusercontent.com/assets/16853304/18927092/ae23b21c-85ba-11e6-8458-cae22aee9fa9.png)

items

lucky_bow_pulling_0
![lucky_bow_pulling_0](https://cloud.githubusercontent.com/assets/16853304/18927100/b60742aa-85ba-11e6-9643-d3417d826960.png)
lucky_bow_pulling_1
![lucky_bow_pulling_1](https://cloud.githubusercontent.com/assets/16853304/18927103/b60e8a10-85ba-11e6-9445-91c6c580e0da.png)
lucky_bow_pulling_2
![lucky_bow_pulling_2](https://cloud.githubusercontent.com/assets/16853304/18927101/b60da078-85ba-11e6-8681-10c06baa92fb.png)
lucky_bow_standby
![lucky_bow_standby](https://cloud.githubusercontent.com/assets/16853304/18927102/b60d9894-85ba-11e6-9067-93c1355284d8.png)
lucky_potion
![lucky_potion](https://cloud.githubusercontent.com/assets/16853304/18927104/b60fb156-85ba-11e6-8321-7b3abe9a67b2.png)
lucky_sword
![lucky_sword](https://cloud.githubusercontent.com/assets/16853304/18927105/b6125cf8-85ba-11e6-998b-d6d859857a15.png)

**Comment by tobyplowy** [comment]
you can put it on the website ;P

**Comment by tobyplowy** [comment]
@lipki you can add this to the website is done :D

**Comment by tobyplowy** [comment]
@lipki is this done?

**Comment by lipki** [comment]
https://github.com/orgs/SummerFields/teams/summerfields-contributor/discussions/5
