### ISSUE TITLE
[1.11] The chicken head  

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#262]
![chicken](https://cloud.githubusercontent.com/assets/401965/18923554/f481a150-85ac-11e6-9843-5974487f5b94.png)

The chickens don't anymore a hole in the head.

**Comment by tobyplowy** [comment]
Im going To Fix this

**Comment by tobyplowy** [comment]
![chicken](https://cloud.githubusercontent.com/assets/16853304/18924567/f2567e7e-85b0-11e6-8c63-f51397829f65.png)
done

**Comment by lipki** [comment]
thank you
