### ISSUE TITLE
[1.11] Horse inventory  

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#263]
![horse](https://cloud.githubusercontent.com/assets/401965/18923519/cfc18e34-85ac-11e6-9e91-dc401b4abfe1.png)

**Comment by tobyplowy** [comment]
this is your job i can't do this :/

**Comment by lipki** [comment]
![horse](https://cloud.githubusercontent.com/assets/401965/18926527/66fc3000-85b8-11e6-98cc-f418cfc356b5.png)

**Comment by tobyplowy** [comment]
How do you make these textures, do you have pre-made things You put Together?

**Comment by lipki** [comment]
I use what already exists.
For that if it was just a small change.
But I am unable to do it from scratch.
