### ISSUE TITLE
Fence texture inprovement?

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#264]
i added a border around the edge of the top 
i like this more but what do you think about it lipki?
![fence_acacia](https://cloud.githubusercontent.com/assets/16853304/18928208/75a3687e-85bf-11e6-8cd4-3e61a9315008.png)
![fence_big_oak](https://cloud.githubusercontent.com/assets/16853304/18928209/75a5df50-85bf-11e6-8f15-c17599d7bae6.png)
![fence_birch](https://cloud.githubusercontent.com/assets/16853304/18928205/75a0bc82-85bf-11e6-8dba-8dc334c549e6.png)
![fence_brick](https://cloud.githubusercontent.com/assets/16853304/18928204/75a0ab5c-85bf-11e6-8f67-f371cb6bd731.png)
![fence_jungle](https://cloud.githubusercontent.com/assets/16853304/18928206/75a0e1b2-85bf-11e6-90a7-057dffdbb676.png)
![fence_oak](https://cloud.githubusercontent.com/assets/16853304/18928207/75a13158-85bf-11e6-9f0b-448f7b8cdd6b.png)
![fence_spruce](https://cloud.githubusercontent.com/assets/16853304/18928210/75c4f87c-85bf-11e6-9b6a-bd276151bb4b.png)
if you dount see the difrence look at the birch and oak ones

**Comment by lipki** [comment]
yes it's better

**Comment by lipki** [comment]
add in master
Thank you.

**Comment by tobyplowy** [comment]
Why did you assign me I did all the textures already ;)
