### ISSUE TITLE
Most mobs Don't have The Bottom of the torso textured

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#265]
Most mobs Don't have The Bottom of the torso textured most noateble the zombie

**Comment by tobyplowy** [comment]
![zombie](https://cloud.githubusercontent.com/assets/16853304/18956179/be409caa-865a-11e6-986b-2e1fae246aed.png)
zombie is fixed

**Comment by tobyplowy** [comment]
![husk](https://cloud.githubusercontent.com/assets/16853304/18956248/0d9aae12-865b-11e6-92f9-47090f143e24.png)
husk is fixed

**Comment by tobyplowy** [comment]
thers probably more

**Comment by tobyplowy** [comment]
@lipki ok im done you can close this

**Comment by lipki** [comment]
add in 1.11
thank you :)
