### ISSUE TITLE
guardian tail fin inprovement?

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#266]
![guardian_elder](https://cloud.githubusercontent.com/assets/16853304/18956778/f7d80550-865c-11e6-8ea0-13379c586bd8.png)
![guardian](https://cloud.githubusercontent.com/assets/16853304/18956779/f7d9c99e-865c-11e6-8986-9998328bfd29.png)

**Comment by lipki** [comment]
yep ok
add in 1.11
