### ISSUE TITLE
minecraft windows 10 edition support

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#267]
we still need to make support for minecraft windows 10 edition

**Comment by lipki** [comment]
yep, we need.

**Comment by tobyplowy** [comment]
I'm testing round with it at the moment ;D

**Comment by lipki** [comment]
He'll have to learn to use git
We will go faster !

**Comment by tobyplowy** [comment]
@lipki Sorry I'm doing my best to be useful :(

**Comment by lipki** [comment]
You may have misunderstood.
git is a software that can manage versions of a project.
Github communicates with git to update the textures.
If you knew to use it, you could manage modpack, alone.

**Comment by tobyplowy** [comment]
it's programming I have no Idea How to do dat :/

**Comment by lipki** [comment]
Not programming.
If you use windows, you can use github desktop.
https://desktop.github.com/
But you have to understand the principle.

**Comment by tobyplowy** [comment]
C:\Users\toby123\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\resource_packs

**Comment by tobyplowy** [comment]
I Made this progress So Far https://1drv.ms/u/s!Ammw1yWbBi3R21F6AcpzICO0vtYe
Now before I continue i used a texture pack as a bace ( I really had to because the game keep crashing with summerfealds and this pack Works It has Something to do with the image format if I export an image and put it in the pack it won't work but if I edit the image it works) so simply put you have to edit the images do not replace them or Minecraft will crash ( also do you have Minecraft Windows 10 Edition?)

And now How to install this
Go To 
C:\Users\yourname\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang
Replace your name with your name 
Also in com.mojang make a new folder and call it resource packs
Going in that folder it Should look like this Now
C:\Users\yourname\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\resource_packs
In the resource pack folder Put the map That's inside the Zip file do not use The Zip file Minecraft Windows 10 Edition doesn't use zip files for resource packs it Should Work Now

**Comment by lipki** [comment]
I can not test for now, I'm going to make you comfiance.
I did the update of this repo https://github.com/SummerFields/MCPE

**Comment by tobyplowy** [comment]
I'm not sure mcpe is the same as Minecraft Windows 10 Edition

**Comment by tobyplowy** [comment]
De texture pack seem To Be Different For Pocket Edition

**Comment by lipki** [comment]
A?

**Comment by tobyplowy** [comment]
What do you mean by a? Also why can't you test The build

**Comment by lipki** [comment]
I do not have "windows".
I use only free software.

**Comment by tobyplowy** [comment]
Well that doesn't matter I tried cloning The repository using the github app doesn't want to work Apparently I don't have permission :/

**Comment by lipki** [comment]
https://github.com/orgs/SummerFields/teams/summerfields-contributor/discussions/6
