### ISSUE TITLE
New Zombie Horse Texture

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#268]
There is no denying The zombie horse Texture doesn't Look really great 
We should make a better One

**Comment by tobyplowy** [comment]
this is what i have made
![horse_zombie](https://cloud.githubusercontent.com/assets/16853304/19016957/bb3e0aa8-8829-11e6-8a7e-de097106943a.png)

**Comment by lipki** [comment]
yeah it's better.

**Comment by tobyplowy** [comment]
I had To redo it alot uh glad that's over :P

**Comment by tobyplowy** [comment]
Hey lipki You Can close This if you want
