### ISSUE TITLE
inproved flower textures

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#273]
on this issue i will try to inprove the fower textures

**Comment by tobyplowy** [comment]
flower_oxeye_daisy
![flower_oxeye_daisy](https://cloud.githubusercontent.com/assets/16853304/19833026/d2d1d792-9e33-11e6-826e-0c402d3b8999.png)

**Comment by tobyplowy** [comment]
flower_houstonia
![flower_houstonia](https://cloud.githubusercontent.com/assets/16853304/19833027/e5376906-9e33-11e6-9a97-b5f63c26d4e1.png)

**Comment by tobyplowy** [comment]
chorus_flower_dead
![chorus_flower_dead](https://cloud.githubusercontent.com/assets/16853304/19833029/f8150844-9e33-11e6-88b8-3e9e3a6deaf8.png)

**Comment by tobyplowy** [comment]
@lipki i will do the other stuff later

**Comment by tobyplowy** [comment]
this one was hard, i did my best :/
![flower_allium](https://cloud.githubusercontent.com/assets/16853304/19839878/a1103d4a-9eea-11e6-9aaa-74d1d80ac3bd.png)

**Comment by tobyplowy** [comment]
@lipki are you interested in doing flower_paeonia and flower_tulip_orange and other colors

**Comment by lipki** [comment]
Ok I take everything: D
But I find the allium too big.

**Comment by tobyplowy** [comment]
@lipki Do you have Any ideas?

**Comment by lipki** [comment]
Maybe less big ? :)
