### ISSUE TITLE
new gravel texture

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#274]
@lipki i did a recolor of the minetest cobblestone (to my suprise this is baced on the 16x16 gravel texture)
![gravel](https://cloud.githubusercontent.com/assets/16853304/19897690/57b6b230-a059-11e6-9fc1-7987e9cd58ce.png)

**Comment by lipki** [comment]
Yes it's @CuddleWoozle that made this change to have smaller gravel.
