### ISSUE TITLE
new jack o lantern

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#275]
new jack o lantern
![pumpkin_face_on](https://cloud.githubusercontent.com/assets/16853304/20023970/a418b722-a2e3-11e6-9c11-17ddcc5b0237.png)
this is for random textures
Also It Makes More Sense because it's a light source but there's no light in the original :)

**Comment by tobyplowy** [comment]
@lipki does it look good?

**Comment by lipki** [comment]
The light was removed some time ago, I know more why.
But I added yours.

**Comment by tobyplowy** [comment]
@lipki why was the light removed?
