### ISSUE TITLE
Stair placement upside down - wrong directions in blockstates

### ISSUE THREAD

**Issue by Ultharine** [SummerFields/SummerFields#277]
posted this on the minecraftforum ... solved it little later:

> Hi all!
> 
> first let me say... your pack is amazing! luv it.
> 
> found something weird tho.
> When Stairs placed upside down, placed from the left (left block first) the corner placement is correct.
> placed from the right tho (right block first) the corner placement is turned 90° or does just look like it is.
> 
> ![0g7wzvr](https://cloud.githubusercontent.com/assets/23386057/20188843/c4ec1e8a-a77a-11e6-9a5d-564405f93dd9.png)
> ![odrc94x](https://cloud.githubusercontent.com/assets/23386057/20188846/cac93dec-a77a-11e6-89d0-ae4c4d68569e.png)
> 
> doesnt occur with other resourcepacks so its not me
> tested with or without optifine
> tested all kinds of stairs, only happens with brick-stairs and stone-brick-stairs.
> 
> dont think it is a feature? ;)
> 
> Greetings.
> 
> Edit:
> solved by deleting the blockstate file stone_brick_stairs.json and brick_stairs.json,
> so something is wrong with those.
> 
> Edit:
> changed directions in rows 35 to 42 solved it:
> 
> 
> "facing=north,half=top,shape=inner_right": { "model": "stone/stone_brick_inner_stairs", "x": 180, "y": 0, "uvlock": true },
> "facing=east,half=top,shape=inner_right": { "model": "stone/stone_brick_inner_stairs", "x": 180, "y": 90, "uvlock": true },
> "facing=south,half=top,shape=inner_right": { "model": "stone/stone_brick_inner_stairs", "x": 180, "y": 180, "uvlock": true },
> "facing=west,half=top,shape=inner_right": { "model": "stone/stone_brick_inner_stairs", "x": 180, "y": 270, "uvlock": true },
> "facing=east,half=top,shape=inner_left": { "model": "stone/stone_brick_inner_stairs", "x": 180, "y": 0, "uvlock": true },
> "facing=south,half=top,shape=inner_left": { "model": "stone/stone_brick_inner_stairs", "x": 180, "y": 90, "uvlock": true },
> "facing=west,half=top,shape=inner_left": { "model": "stone/stone_brick_inner_stairs", "x": 180, "y": 180, "uvlock": true },
> "facing=north,half=top,shape=inner_left": { "model": "stone/stone_brick_inner_stairs", "x": 180, "y": 270, "uvlock": true }

**Comment by tobyplowy** [comment]
@Ultharine Thanks for reporting your Problem This is one for @lipki because I have no Idea what it is It's programming Side i Only do art :/

**Comment by Ultharine** [comment]
:)
He'll know what to do.
It's those eight lines in the end i posted
this is the corrected version.

**Comment by tobyplowy** [comment]
@Ultharine Can you make a pull request?

**Comment by lipki** [comment]
Thank you for your contribution.
We fix this bug here # 278

**Comment by lipki** [comment]
Problem solve, thank again.
