### ISSUE TITLE
chicken fix

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#284]
this will fix the back of the chicken it also fixes the ting on gis shin it was flikkering
![chicken](https://cloud.githubusercontent.com/assets/16853304/20346650/8b49ac4c-abfd-11e6-929c-83f4a4a626ba.png)

also i know its to late for 1.11 but maybe next update

**Comment by lipki** [comment]
I'll get a 1.11.1, so it will be there. #289
