### ISSUE TITLE
forgot to update stats_icons.png

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#286]
![stats_icons](https://cloud.githubusercontent.com/assets/16853304/20352084/469b8b92-ac16-11e6-9af8-79d7c1b74b14.png)
stats_icons.png minecraft

![stats_icons](https://cloud.githubusercontent.com/assets/16853304/20352095/50da09da-ac16-11e6-9dd1-6f9715f38721.png)
stats_icons.png minecraft

**Comment by lipki** [comment]
![stats_icons](https://cloud.githubusercontent.com/assets/401965/20354831/b2592dea-ac1f-11e6-9b70-aee9ae1f2c91.png)
ok thank !

**Comment by tobyplowy** [comment]
@lipki did you really Use the pants as a backpack XD

**Comment by lipki** [comment]
:) yes i do, and assume. :D
