### ISSUE TITLE
terasology support?

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#290]
Personally I have never played it before i Just played for couple minutes and my computer couldn't handle the graphics (i really need a new computer XD) anyways maybe you could also make support for this game, as far as I know it's also open source and free :D
http://terasology.org

**Comment by lipki** [comment]
Really beautiful, I think that only miss the summerfields :)
I can play it, but I do not have the inventory of craft?

**Comment by tobyplowy** [comment]
@lipki Yeah this game together with summerfields would be a masterpiece and that's an understatement!!!!
Sadly I won't be able to run the game just yet before I get my new computer which will be early to Middle next year so I won't be able to do all that much on the game side like testing the textures what I can do is make textures as long as you lipki put them here on github

**Comment by lipki** [comment]
We keep him under the elbow, and we'll deal with it later.
Priority to minetest for now.

**Comment by tobyplowy** [comment]
Minetest Will update December 21, 2016 so we beter wate

**Comment by tobyplowy** [comment]
@lipki so we Don't Skip Anything by accident

**Comment by CuddleWoozle** [comment]
I <3 open source stuff.

I'd take this on, but the game keeps crashing like crazy. :(

**Comment by CuddleWoozle** [comment]
I'm probably gonna have to take a pass on it.  At least until they implement a better way to add textures than ripping into individual modules.

Unless I'm missing something, that's the only way to do it?

**Comment by lipki** [comment]
https://github.com/orgs/SummerFields/teams/summerfields-contributor/discussions/7
