### ISSUE TITLE
remove no glow pumkin from random pumpkin on

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#291]
now pumpkins are random somtimes i get the off pumkin it doesent make sense the block is calld pumpkin on not pumpkin off

**Comment by lipki** [comment]
I will look for the reason for this change on the forum.

**Comment by lipki** [comment]
I think it's a good idea to have some pumpkin switched off and on.
On the other hand, there was a problem with the items.

**Comment by tobyplowy** [comment]
But with that the off pumpkin has no hole for light to go through so where is the light coming from?

**Comment by CuddleWoozle** [comment]
It's a magical Minecraft pumpkin.  It glows on it's own.  XD

**Comment by lipki** [comment]
Anyway in 1.13, the pumpkins change.
The normal, the carved, and the jack'o'lantern.

I have already made the modifications, at home, but I must finish repairing the models of the stones before committing.
