### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by theguywholikesyellow** [SummerFields/SummerFields#294]
no matter what I do I'm unable to download the 1.11 version, i've tried the regular and custom version, neither one works

**Comment by tobyplowy** [comment]
@theguywholikesyellow sorry for the trouble you're having you should be able to use this https://github.com/SummerFields/SummerFields/archive/master.zip

**Comment by tobyplowy** [comment]
Also @lipki can you fix this

**Comment by lipki** [comment]
@theguywholikesyellow This is correct, thank you for warning us.
