### ISSUE TITLE
Summerfields pack

### ISSUE THREAD

**Issue by Jackywaii789** [SummerFields/SummerFields#300]
Minecraft Summerfields 1.11x cannot downloads ?

**Comment by tobyplowy** [comment]
@lipki ping this is the second time this happens :/

**Comment by tobyplowy** [comment]
@Jackywaii789 You should be able to download It using this link https://github.com/SummerFields/SummerFields/archive/master.zip

**Comment by kyzumi** [comment]
I came here for this issue and I am glad to have found an answer :) Thanks
