### ISSUE TITLE
New update soon 1.12

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#302]
- concrete #310
![concrete_black](https://cloud.githubusercontent.com/assets/401965/22757933/04ffbf5e-ee4d-11e6-923e-87a46f467254.png)![concrete_blue](https://cloud.githubusercontent.com/assets/401965/22757932/04fd8626-ee4d-11e6-9915-b03ed4e2fc41.png)![concrete_brown](https://cloud.githubusercontent.com/assets/401965/22757931/04fbd650-ee4d-11e6-9d83-998db954c664.png)![concrete_cyan](https://cloud.githubusercontent.com/assets/401965/22757935/050592c6-ee4d-11e6-84ef-abaf6f221399.png)![concrete_gray](https://cloud.githubusercontent.com/assets/401965/22757934/050315c8-ee4d-11e6-9b3c-161ab0de870e.png)![concrete_green](https://cloud.githubusercontent.com/assets/401965/22757936/050d97fa-ee4d-11e6-87fd-8523546c64f0.png)![concrete_light_blue](https://cloud.githubusercontent.com/assets/401965/22757937/051ef946-ee4d-11e6-9859-bb9410d0b391.png)![concrete_lime](https://cloud.githubusercontent.com/assets/401965/22757938/0521e78c-ee4d-11e6-91c1-f4bebf21b4d7.png)![concrete_magenta](https://cloud.githubusercontent.com/assets/401965/22757939/0525997c-ee4d-11e6-8ea5-fe5d8d18fd92.png)![concrete_orange](https://cloud.githubusercontent.com/assets/401965/22757940/05265d58-ee4d-11e6-9b9e-e3dbc884403d.png)![concrete_pink](https://cloud.githubusercontent.com/assets/401965/22757941/0529892e-ee4d-11e6-91d8-2b9738dc1863.png)![concrete_purple](https://cloud.githubusercontent.com/assets/401965/22757959/058fa416-ee4d-11e6-818d-963d185ae3af.png)![concrete_red](https://cloud.githubusercontent.com/assets/401965/22757960/0593e828-ee4d-11e6-96fe-37bf84973f9c.png)![concrete_silver](https://cloud.githubusercontent.com/assets/401965/22757961/0597d762-ee4d-11e6-8f09-f119233bdfad.png)![concrete_white](https://cloud.githubusercontent.com/assets/401965/22757962/05aa26ba-ee4d-11e6-95c5-466ed03d9ccc.png)![concrete_yellow](https://cloud.githubusercontent.com/assets/401965/22757963/05aeac44-ee4d-11e6-8a59-0f256b1d5303.png)
![concrete_powder_black](https://cloud.githubusercontent.com/assets/401965/22757942/052f3220-ee4d-11e6-869b-1e2b5e1bb507.png)![concrete_powder_blue](https://cloud.githubusercontent.com/assets/401965/22757944/05408570-ee4d-11e6-9931-24e40ba8efc8.png)![concrete_powder_brown](https://cloud.githubusercontent.com/assets/401965/22757949/05542a58-ee4d-11e6-9b57-b13bda0ac738.png)![concrete_powder_cyan](https://cloud.githubusercontent.com/assets/401965/22757945/05482abe-ee4d-11e6-8bb0-d47f7353d0bb.png)![concrete_powder_gray](https://cloud.githubusercontent.com/assets/401965/22757946/054a1c34-ee4d-11e6-95fc-2c14ff9cb7a2.png)![concrete_powder_green](https://cloud.githubusercontent.com/assets/401965/22757947/054deaa8-ee4d-11e6-89cb-37cfff17cd2c.png)![concrete_powder_light_blue](https://cloud.githubusercontent.com/assets/401965/22757948/05511476-ee4d-11e6-95aa-bce52eb19e4a.png)![concrete_powder_lime](https://cloud.githubusercontent.com/assets/401965/22757950/0560db86-ee4d-11e6-96f3-d00d5dff6d95.png)![concrete_powder_magenta](https://cloud.githubusercontent.com/assets/401965/22757951/0568b3ba-ee4d-11e6-8201-9c343d2696e2.png)![concrete_powder_orange](https://cloud.githubusercontent.com/assets/401965/22757952/056c1262-ee4d-11e6-9cd1-9775443532cf.png)![concrete_powder_pink](https://cloud.githubusercontent.com/assets/401965/22757953/056e43a2-ee4d-11e6-876f-fe7fc5abff90.png)![concrete_powder_purple](https://cloud.githubusercontent.com/assets/401965/22757954/05711ece-ee4d-11e6-8246-93b24eb33ae7.png)![concrete_powder_red](https://cloud.githubusercontent.com/assets/401965/22757955/05763710-ee4d-11e6-9f6b-bf0660c17592.png)![concrete_powder_silver](https://cloud.githubusercontent.com/assets/401965/22757958/058ebc54-ee4d-11e6-9cb9-e714b80e6688.png)![concrete_powder_white](https://cloud.githubusercontent.com/assets/401965/22757956/05891b8c-ee4d-11e6-8165-27ab5737f72f.png)![concrete_powder_yellow](https://cloud.githubusercontent.com/assets/401965/22757957/058dd7d0-ee4d-11e6-84e5-6c540f635721.png)
- terracotta #311
![glazed_terracotta_black](https://cloud.githubusercontent.com/assets/401965/22757989/1c6cec3e-ee4d-11e6-82a6-ce12b3fdf84a.png)![glazed_terracotta_blue](https://cloud.githubusercontent.com/assets/401965/22757990/1c6ec34c-ee4d-11e6-9af6-06e3622ec41f.png)![glazed_terracotta_brown](https://cloud.githubusercontent.com/assets/401965/22757991/1c72189e-ee4d-11e6-99c2-1a16a9e3937c.png)![glazed_terracotta_cyan](https://cloud.githubusercontent.com/assets/401965/22757992/1c747c92-ee4d-11e6-940d-056fc8d49779.png)![glazed_terracotta_gray](https://cloud.githubusercontent.com/assets/401965/22757993/1c77336a-ee4d-11e6-8557-d25348231117.png)![glazed_terracotta_green](https://cloud.githubusercontent.com/assets/401965/22757994/1c879f8e-ee4d-11e6-81fd-40c9b25d432a.png)![glazed_terracotta_light_blue](https://cloud.githubusercontent.com/assets/401965/22757995/1c8ddd22-ee4d-11e6-88f0-eec9c9b257f4.png)![glazed_terracotta_lime](https://cloud.githubusercontent.com/assets/401965/22757996/1c918c56-ee4d-11e6-9157-ad62814d06b4.png)![glazed_terracotta_magenta](https://cloud.githubusercontent.com/assets/401965/22757997/1c9546f2-ee4d-11e6-85f0-fe46fe9af661.png)![glazed_terracotta_orange](https://cloud.githubusercontent.com/assets/401965/22757998/1c996fd4-ee4d-11e6-9f53-4efd687da89d.png)![glazed_terracotta_pink](https://cloud.githubusercontent.com/assets/401965/22757999/1ca87150-ee4d-11e6-94e8-6f84d3107eb8.png)![glazed_terracotta_purple](https://cloud.githubusercontent.com/assets/401965/22758000/1caa7298-ee4d-11e6-9449-6f7796f21bb8.png)![glazed_terracotta_red](https://cloud.githubusercontent.com/assets/401965/22758001/1caf298c-ee4d-11e6-9413-c5c3928f899e.png)![glazed_terracotta_silver](https://cloud.githubusercontent.com/assets/401965/22758003/1cb7126e-ee4d-11e6-85a2-8f3ad88d9ac9.png)![glazed_terracotta_white](https://cloud.githubusercontent.com/assets/401965/22758002/1cb69e60-ee4d-11e6-8bf9-e7d2fbe2d438.png)![glazed_terracotta_yellow](https://cloud.githubusercontent.com/assets/401965/22758004/1cba7062-ee4d-11e6-88f1-5ecf9ca63be6.png)

- Correction of cow's udders #312

- new mob, parrot  #313 [couac](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.micky-maus.de%2Ftypo3temp%2Fpics%2Fe6104abeca.jpg&f=1)
![parrot_blue](https://cloud.githubusercontent.com/assets/401965/24581158/6198924e-1716-11e7-8a46-feba4fe1f912.png)![parrot_green](https://cloud.githubusercontent.com/assets/401965/24581159/619befd4-1716-11e7-8d64-3cb25d1859c9.png)![parrot_grey](https://cloud.githubusercontent.com/assets/401965/24581160/619eb98a-1716-11e7-8d1e-50d7b6d400f6.png)![parrot_red_blue](https://cloud.githubusercontent.com/assets/401965/24581161/61a3bb7e-1716-11e7-952b-f3c9e1886bed.png)![parrot_yellow_blue](https://cloud.githubusercontent.com/assets/401965/24581162/61a5079a-1716-11e7-8eb3-9014007d098a.png)

- Achievements become advancements #314

background textures : ![nether](https://cloud.githubusercontent.com/assets/401965/24581206/89813030-1717-11e7-8254-d3dbb1823505.png)![stone](https://cloud.githubusercontent.com/assets/401965/24581207/8983de48-1717-11e7-8304-a69708754fde.png)![adventure](https://cloud.githubusercontent.com/assets/401965/25129073/c2bd3056-243c-11e7-8fc4-489f73e1ecf4.png)
![tabs](https://cloud.githubusercontent.com/assets/401965/24581210/9e6cec5a-1717-11e7-8f1d-fb0f8d7e8649.png)![widgets](https://cloud.githubusercontent.com/assets/401965/25129126/fddfa5a6-243c-11e7-88c8-02223406d73d.png)![window](https://cloud.githubusercontent.com/assets/401965/25129127/fde18a4c-243c-11e7-972e-0bca9817ced7.png)![recipe_book](https://cloud.githubusercontent.com/assets/401965/24581261/65933744-1718-11e7-9f38-cbbda49f3f9b.png)![toasts](https://cloud.githubusercontent.com/assets/401965/25251350/61562ea6-2619-11e7-8e3e-3ea950deff59.png)

- recipes book #315
![crafting_table](https://cloud.githubusercontent.com/assets/401965/25129857/25b0c102-2440-11e7-88c5-eccc5b4edaee.png)![inventory](https://cloud.githubusercontent.com/assets/401965/25129945/8ad3c08e-2440-11e7-90e7-577b8bde561e.png)![recipe_background](https://cloud.githubusercontent.com/assets/401965/24581243/18b75644-1718-11e7-9fa9-ee16f436ebcd.png)![progress_book](https://cloud.githubusercontent.com/assets/401965/24581256/554259e2-1718-11e7-97fc-3fa7a9a13fca.png)

- new items 
![iron_nugget](https://cloud.githubusercontent.com/assets/401965/24581264/8714b05a-1718-11e7-91ef-16968fb02784.png)  #316
![knowledge_book](https://cloud.githubusercontent.com/assets/401965/24581267/88d0a232-1718-11e7-8cd1-e6ff3366facc.png)  #317

- bed  #324
remove :
assets/minecraft/textures/blocks/bed_feet_end.png
assets/minecraft/textures/blocks/bed_feet_side.png
assets/minecraft/textures/blocks/bed_feet_top.png
assets/minecraft/textures/blocks/bed_head_end.png
assets/minecraft/textures/blocks/bed_head_side.png
assets/minecraft/textures/blocks/bed_head_top.png
assets/minecraft/textures/items/bed.png
add : 
![black](https://cloud.githubusercontent.com/assets/401965/25128983/670854de-243c-11e7-9bc6-c337d1ff358f.png)![blue](https://cloud.githubusercontent.com/assets/401965/25128987/67292952-243c-11e7-8764-b7d104399ab1.png)![brown](https://cloud.githubusercontent.com/assets/401965/25128988/6729847e-243c-11e7-907d-f39a5844fe11.png)![cyan](https://cloud.githubusercontent.com/assets/401965/25128989/67299e00-243c-11e7-89d7-329e4c0cffe0.png)![gray](https://cloud.githubusercontent.com/assets/401965/25128990/672ec628-243c-11e7-8fcd-fd9cb4af8e33.png)![green](https://cloud.githubusercontent.com/assets/401965/25128986/67282c5a-243c-11e7-8fb6-3443d7910983.png)![light_blue](https://cloud.githubusercontent.com/assets/401965/25128985/6723c21e-243c-11e7-91f6-a3eb0e741650.png)![lime](https://cloud.githubusercontent.com/assets/401965/25128992/673cab1c-243c-11e7-8768-352e0f7fed4d.png)![magenta](https://cloud.githubusercontent.com/assets/401965/25128991/673affd8-243c-11e7-9e15-c840547050df.png)![orange](https://cloud.githubusercontent.com/assets/401965/25128994/673e41de-243c-11e7-9336-04879ae15c7e.png)![pink](https://cloud.githubusercontent.com/assets/401965/25128993/673e0db8-243c-11e7-8ba5-a33ffaa591dd.png)![purple](https://cloud.githubusercontent.com/assets/401965/25128995/673fffec-243c-11e7-9a8c-c7e221d94612.png)![red](https://cloud.githubusercontent.com/assets/401965/25128996/6746e3e8-243c-11e7-80e0-ab6a713e11f2.png)![silver](https://cloud.githubusercontent.com/assets/401965/25128997/675126e6-243c-11e7-93fc-f86eb3a76114.png)![white](https://cloud.githubusercontent.com/assets/401965/25128998/6751c088-243c-11e7-8bdf-2f48e7167e40.png)![yellow](https://cloud.githubusercontent.com/assets/401965/25128999/6756d12c-243c-11e7-8a17-b044a41c3b17.png)

- illusionist #326 : 
![illusionist](https://cloud.githubusercontent.com/assets/401965/25250278/3cd5db16-2615-11e7-8c87-bc2c8a0dfab8.png)

**Comment by tobyplowy** [comment]
@lipki sources

https://gfycat.com/MenacingSnivelingChimneyswift
https://mobile.twitter.com/jeb_/status/824946351725240320/photo/1

On The First Link you can see a gif of Pink Sand Getting droped into water and turning solid (I think the pink stuff is sand but I'm not sure) and in the second link you can see wool and The New Block (the same block you can see when the sand hits the water in the first link

Also wool got a recolor

**Comment by lipki** [comment]
Je fais rapidement les concretes.

**Comment by lipki** [comment]
![color](https://cloud.githubusercontent.com/assets/401965/22760712/ee8fa45e-ee57-11e6-8857-872079cfedd4.png)

**Comment by tobyplowy** [comment]
brown terracotta
![brown terracotta](https://cloud.githubusercontent.com/assets/16853304/22781546/40404248-eec3-11e6-8b47-85dcb24b30cb.png)

**Comment by tobyplowy** [comment]
lime terracotta
![green](https://cloud.githubusercontent.com/assets/16853304/22782178/269929b0-eec6-11e6-89c5-7834e6cad66e.png)

**Comment by lipki** [comment]
awesome :D

**Comment by tobyplowy** [comment]
@lipki what do you have already?

Also I may redo the brown one

**Comment by lipki** [comment]
![concrete_powder_black](https://cloud.githubusercontent.com/assets/401965/22833752/67d0503c-efb3-11e6-9d35-1b9a60720595.png)![concrete_powder_blue](https://cloud.githubusercontent.com/assets/401965/22833751/67cdc6d2-efb3-11e6-8b5e-a0c71bfd1ad7.png)![concrete_powder_brown](https://cloud.githubusercontent.com/assets/401965/22833754/67d5c0e4-efb3-11e6-8e02-8dc40e27fb92.png)![concrete_powder_cyan](https://cloud.githubusercontent.com/assets/401965/22833753/67d31470-efb3-11e6-85cd-55fe0cf14ca7.png)![concrete_powder_gray](https://cloud.githubusercontent.com/assets/401965/22833755/67dbdbe6-efb3-11e6-8d3d-975bff4b8530.png)![concrete_powder_green](https://cloud.githubusercontent.com/assets/401965/22833757/67df8b1a-efb3-11e6-8a90-2910144f939e.png)![concrete_powder_light_blue](https://cloud.githubusercontent.com/assets/401965/22833759/67ed89c2-efb3-11e6-869c-f6b64d4af59e.png)![concrete_powder_lime](https://cloud.githubusercontent.com/assets/401965/22833760/67f13e28-efb3-11e6-9532-ab4a51301808.png)![concrete_powder_magenta](https://cloud.githubusercontent.com/assets/401965/22833761/67f3799a-efb3-11e6-8a03-c18f2b225d10.png)![concrete_powder_orange](https://cloud.githubusercontent.com/assets/401965/22833762/67f64c42-efb3-11e6-8dc9-379d7c982f1e.png)![concrete_powder_pink](https://cloud.githubusercontent.com/assets/401965/22833763/67fa2baa-efb3-11e6-8992-610001477daf.png)![concrete_powder_purple](https://cloud.githubusercontent.com/assets/401965/22833764/67ff7f60-efb3-11e6-8596-7975447ac5d7.png)![concrete_powder_red](https://cloud.githubusercontent.com/assets/401965/22833765/680ccfc6-efb3-11e6-87bf-122adc258a31.png)![concrete_powder_silver](https://cloud.githubusercontent.com/assets/401965/22833766/68144530-efb3-11e6-9200-50c90426eaad.png)![concrete_powder_white](https://cloud.githubusercontent.com/assets/401965/22833767/68145764-efb3-11e6-8591-dc38d0502d5f.png)![concrete_powder_yellow](https://cloud.githubusercontent.com/assets/401965/22833768/681822a4-efb3-11e6-9a4e-7cb6793ff26e.png)
![concrete_black](https://cloud.githubusercontent.com/assets/401965/22833815/8aa821fc-efb3-11e6-99d2-e74c7c8d4513.png)![concrete_blue](https://cloud.githubusercontent.com/assets/401965/22833816/8aaab610-efb3-11e6-9917-1b4587f2fea6.png)![concrete_brown](https://cloud.githubusercontent.com/assets/401965/22833817/8aadb5ae-efb3-11e6-9448-2be03f2ea8ff.png)![concrete_cyan](https://cloud.githubusercontent.com/assets/401965/22833818/8ab0d590-efb3-11e6-8ddd-116c6027569f.png)![concrete_gray](https://cloud.githubusercontent.com/assets/401965/22833819/8ab29ed4-efb3-11e6-8004-e7e0d397cb21.png)![concrete_green](https://cloud.githubusercontent.com/assets/401965/22833820/8ab56a2e-efb3-11e6-8d2a-a70a6475f17c.png)![concrete_light_blue](https://cloud.githubusercontent.com/assets/401965/22833821/8ac898ba-efb3-11e6-9bff-1b80a862d7b9.png)![concrete_lime](https://cloud.githubusercontent.com/assets/401965/22833822/8aca67b2-efb3-11e6-8d1c-98ecd70017e6.png)![concrete_magenta](https://cloud.githubusercontent.com/assets/401965/22833823/8acd4f90-efb3-11e6-8a83-4d6a83a6d482.png)![concrete_orange](https://cloud.githubusercontent.com/assets/401965/22833824/8ad0eaf6-efb3-11e6-9806-7eef3bb35039.png)![concrete_pink](https://cloud.githubusercontent.com/assets/401965/22833825/8ad6a680-efb3-11e6-8f03-96d06be413fe.png)![concrete_purple](https://cloud.githubusercontent.com/assets/401965/22833826/8ad6ed20-efb3-11e6-9c21-b70d2482a90a.png)![concrete_red](https://cloud.githubusercontent.com/assets/401965/22833827/8aebbdd6-efb3-11e6-8317-0584c30bf4b0.png)![concrete_silver](https://cloud.githubusercontent.com/assets/401965/22833828/8af00ddc-efb3-11e6-9f6c-ddf4f7b00fd6.png)![concrete_white](https://cloud.githubusercontent.com/assets/401965/22833829/8af2b9d8-efb3-11e6-954d-2d278a06f272.png)![concrete_yellow](https://cloud.githubusercontent.com/assets/401965/22833830/8af5d136-efb3-11e6-9407-ede346bcb3c0.png)

![capture du 2017-02-10 17-22-07](https://cloud.githubusercontent.com/assets/401965/22834586/f84242a4-efb5-11e6-9480-6fd8e2c72a86.png)

**Comment by tobyplowy** [comment]
@lipki I ment what terracotta patterns do you have

**Comment by lipki** [comment]
Nothing.
I thought of the tiling.
Like that :
![test1](https://cloud.githubusercontent.com/assets/401965/22836309/285f15b0-efbc-11e6-8edf-05479bfb4d93.png)
![lime](https://cloud.githubusercontent.com/assets/401965/22836315/2d2476f8-efbc-11e6-994f-9e14b0c42ede.png)

**Comment by tobyplowy** [comment]
@lipki yes that is nice can you give me that tile overlay

**Comment by lipki** [comment]
I'm testing this?
![test2](https://cloud.githubusercontent.com/assets/401965/22838858/3c09fbba-efc7-11e6-99f6-e0670c5f148a.png)
![use5603](https://cloud.githubusercontent.com/assets/401965/22838865/3fd6db14-efc7-11e6-86d7-00c503a221e6.png)

**Comment by lipki** [comment]
![test3](https://cloud.githubusercontent.com/assets/401965/22838950/a9bf3760-efc7-11e6-844f-317f134813f4.png)
![use5604](https://cloud.githubusercontent.com/assets/401965/22838957/af6ff2bc-efc7-11e6-82b2-60851951ff56.png)

**Comment by tobyplowy** [comment]
@lipki Yes I like it but the color needs a little bit more work dark is too dark and pink is too pink ( I know this is a bad description XD )

**Comment by lipki** [comment]
I improve the junction between the tiles, it makes it more repetitive.
And I cleared up.
![test3](https://cloud.githubusercontent.com/assets/401965/22839598/5e030326-efca-11e6-8671-023ab7bfc1b8.png)
![use5604](https://cloud.githubusercontent.com/assets/401965/22839603/622895d8-efca-11e6-84b9-41ef8de507a9.png)

**Comment by tobyplowy** [comment]
Yes that is better

**Comment by lipki** [comment]
![eyj1cmwioijodhrwoi8vchv1lnnol3raskz1lznizjjimgzhzjquanbnin0](https://cloud.githubusercontent.com/assets/401965/22863208/24bbee48-f13c-11e6-9e14-6179b2ca5ee1.jpg)
![eyj1cmwioijodhrwoi8vchv1lnnol3raskpolzewmtmzyzg1mdiuanbnin0](https://cloud.githubusercontent.com/assets/401965/22863211/283f3ac0-f13c-11e6-911d-f53efbb8dc54.jpg)
I think we should get to that, anyway.

**Comment by tobyplowy** [comment]
Waw that is impressive

**Comment by tobyplowy** [comment]
@lipki more news!

**Comment by tobyplowy** [comment]
@lipki colord beds are a ting!

**Comment by tobyplowy** [comment]
@lipki horse model will be remade

**Comment by tobyplowy** [comment]
@lipki and parots yes fucking parots 

# I'M SO HYPED

**Comment by tobyplowy** [comment]
@lipki what do you think of this?
![kkkkkkkkkkk](https://cloud.githubusercontent.com/assets/16853304/24322403/f89ee7f0-1163-11e7-8b9c-53656c8efd0c.png)

**Comment by tobyplowy** [comment]
parrot_red_blue
![parrot_red_blue](https://cloud.githubusercontent.com/assets/16853304/24500954/d5bc312e-1547-11e7-9fcf-b4aabfb63353.png)

**Comment by tobyplowy** [comment]
parrot_yellow_blue
![parrot_yellow_blue](https://cloud.githubusercontent.com/assets/16853304/24501605/870e19cc-154a-11e7-931d-c8f616c330f3.png)
parrot_blue
![parrot_blue](https://cloud.githubusercontent.com/assets/16853304/24501606/870ea86a-154a-11e7-9eda-de8ae130e14c.png)
parrot_green
![parrot_green](https://cloud.githubusercontent.com/assets/16853304/24501607/871037d4-154a-11e7-8e83-2ecdcfe0e633.png)

**Comment by tobyplowy** [comment]
@lipki can you do the rest of the tracotta?

**Comment by tobyplowy** [comment]
@lipki crafting_table.png update
![crafting_table](https://cloud.githubusercontent.com/assets/16853304/24514032/2de664ac-1573-11e7-96dd-7d9b449c0ed6.png)

**Comment by tobyplowy** [comment]
new spectral_arrow
![spectral_arrow](https://cloud.githubusercontent.com/assets/16853304/24515577/54a59446-1578-11e7-9b13-e8f3c09cd5cd.png)
this makes it look more magical

**Comment by lipki** [comment]
ok ok :) i'm here.

**Comment by lipki** [comment]
Your parrots are great, my favorite is the yellow blue.
The beaks are perfect.
But blue is a too violet, I find.

**Comment by lipki** [comment]
I updated the first post.
I will make the issues for each change.

**Comment by lipki** [comment]
You transfer your proposal, it's all good.

**Comment by tobyplowy** [comment]
hay recolor #320

**Comment by lipki** [comment]
update 17w15a

**Comment by tobyplowy** [comment]
@lipki the dispenser gui may need some inprovement

**Comment by lipki** [comment]
Which ?

**Comment by tobyplowy** [comment]
@lipki 
![dispenser](https://cloud.githubusercontent.com/assets/16853304/25222745/a7fa518a-25b9-11e7-93fc-00704308e9fc.png)
this one

**Comment by lipki** [comment]
Yes, but what improvement.

**Comment by tobyplowy** [comment]
@lipki the stone tiles need to be randomized a bit

**Comment by lipki** [comment]
Make a issue for that.
But, I don't find it very serious.

**Comment by chengzzi89** [comment]
good boy!

**Comment by chengzzi89** [comment]
![](https://cloud.githubusercontent.com/assets/401965/22838957/af6ff2bc-efc7-11e6-82b2-60851951ff56.png)
I feel this is more like a pebble!

**Comment by chengzzi89** [comment]
This is a preliminary draft, may be a bit ugly!
![timg](https://cloud.githubusercontent.com/assets/28303754/26813062/43dd9044-4aae-11e7-813c-f45e75027177.jpg)
![default](https://cloud.githubusercontent.com/assets/28303754/26813068/4b0bd60a-4aae-11e7-9343-bf897ded2757.png)

**Comment by chengzzi89** [comment]
![tim](https://cloud.githubusercontent.com/assets/28303754/26813990/a5bf9f5e-4ab4-11e7-8964-668ab8371e27.png)
![qqqw](https://cloud.githubusercontent.com/assets/28303754/26813991/a86ddb6c-4ab4-11e7-9431-2553cd14e56f.png)

**Comment by chengzzi89** [comment]
ok？
![timg 4](https://cloud.githubusercontent.com/assets/28303754/26814119/98ae42a6-4ab5-11e7-92cd-9fce63a27200.png)
![uyuu](https://cloud.githubusercontent.com/assets/28303754/26814124/9ae61c38-4ab5-11e7-98b0-32d540f70df2.png)

**Comment by chengzzi89** [comment]
![timg 3](https://cloud.githubusercontent.com/assets/28303754/26814592/4ac508f0-4ab9-11e7-8441-b9e2eba36170.png)
![wwee](https://cloud.githubusercontent.com/assets/28303754/26814599/4ee8c2be-4ab9-11e7-9614-3811a3195557.png)

**Comment by tobyplowy** [comment]
@chengzzi89 those look really nice

**Comment by tobyplowy** [comment]
> This is a preliminary draft, may be a bit ugly!

I like the blue one but it needs more texture :)

**Comment by lipki** [comment]
Yes ok, that's fine.
If you get all the things :) (courage)
It will have to touch up the colors, but for now it's not important.

Good luck.

**Comment by lipki** [comment]
Hello @chengzzi89, could you put your terracotta textures here # 311, please.

**Comment by lipki** [comment]
https://github.com/SummerFields/SummerFields/releases/download/fp3-2b/SummerFields.fp3-2.1.11-1.12.zip

Here is the release 1.12

I test the new release system, so it's version fp3-2 (beta for now)
Compatible with 1.11 and 1.12

It remains to do the readme, and the icon of the pack.
For the icon, I do not know what to put, the concrete is a sad one, and we have not yet glazed terracotta.

**Comment by tobyplowy** [comment]
@lipki why not use a parrot for the icon?

**Comment by tobyplowy** [comment]
@lipki also will you update the website?

**Comment by tobyplowy** [comment]
@lipki if you do update the website can you also add a minetest 0.4.16 update

**Comment by lipki** [comment]
I always use a block except for the shulker, but it is cubic.
But I think about parrots, that's true.
You made the 3d model !?

For the website, I'm waiting for you to test, I do it tomorrow.
And I will add the update of minetest sorry to have forgotten.

**Comment by tobyplowy** [comment]
> I'm waiting for you to test,

I will have a look

> And I will add the update of minetest sorry to have forgotten.

That's ok you're human and humans forget things :)

**Comment by tobyplowy** [comment]
@lipki parrot model remade by @22i
[parrot.zip](https://github.com/SummerFields/SummerFields/files/1066617/parrot.zip)

**Comment by tobyplowy** [comment]
@lipki I found a problem with beds they dount have feet so they float :)

Also the bed feet end is upside-down shading is at the bottom but it should be at the top

**Comment by tobyplowy** [comment]
@lipki and here is the fix for the beds
[bed.zip](https://github.com/SummerFields/SummerFields/files/1066641/bed.zip)

**Comment by tobyplowy** [comment]
update picture for the minetest update on the website
![minetest update](https://user-images.githubusercontent.com/16853304/27013700-76e2fbde-4ee9-11e7-8e9e-d729f2061aa9.png)
