### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by ZombehGoast** [SummerFields/SummerFields#304]
I've been trying to download the newest version of your resource pack for several weeks, but every time I do it sends me to a 404 page not found page. Is there any other way to download your resource pack?

**Comment by tobyplowy** [comment]
@lipki here we go again

**Comment by tobyplowy** [comment]
@ZombehGoast you can use this https://github.com/SummerFields/SummerFields/archive/master.zip

**Comment by lipki** [comment]
I rerererecorrect the link.
