### ISSUE TITLE
A Best Release

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#305]
I always think about the right way to make releases, and I still do not know.
Apart from the customize that allows everyone to make that own version.
But I do not have time to do it.

But I thought.
The resource pack, now, have a version number, 1 2 3.

```
{
  "pack": {
    "pack_format": 3,
    "description": "SummerFields 1.11"
  }
}
```
So we can only do three versions of pack.
- v1 - 1.6.1.... 1.8
- v2 - 1.9 .... 1.10
- v3 - 1.11 .... 1.12

I wanted to update old packs for a long time.

Also, the pack is heavy, especially with McPatcher.
And for small config, it's complicated.
So I think it might be nice to make several different weight versions.

Maybe a heavy version : 
with textures random
animations
and McPatcher

A medium version :
With textures random
Animations
without McPatcher

And a light version :
without textures random
without animations
without McPatcher

And, we can making a lighter version, perhaps a version 16 x 16 ... maybe.

**Comment by tobyplowy** [comment]
@lipki I like the idea of the 16x16 pack

**Comment by tobyplowy** [comment]
@lipki im realy interested in the 16x pack

![default_wood](https://cloud.githubusercontent.com/assets/16853304/23179541/8e7460a2-f86e-11e6-9a9c-9320ef103fc7.png)

**Comment by lipki** [comment]
#306

**Comment by lipki** [comment]
https://github.com/orgs/SummerFields/teams/global-manager/discussions/5

**Comment by lipki** [comment]
Well, I'm looking into this project.
Here is the first package rp1
Which supports 1.6.x versions 1.7.x and 1.8.x
With and without Optifine.
I add the textures changes made after 1.8
I also changed the font, but I'm not sure.
There is still some random texture to add.

I need testers for this pack.
[Summerfields rp1 (1.6|1.7|1.8).tar.gz](https://github.com/SummerFields/SummerFields/files/2001166/Summerfields.rp1.1.6.1.7.1.8.tar.gz)

**Comment by tobyplowy** [comment]
@lipki is this issue still used or needed?
