### ISSUE TITLE
Study of the feasibility of the 16x16 pack

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#306]
...
ref : http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1242675-16x-greatwood-ready-for-1-8-1

**Comment by tobyplowy** [comment]
@lipki shuld I start work on it?

**Comment by tobyplowy** [comment]
@lipki i made this with the mt pack
![16x](https://cloud.githubusercontent.com/assets/16853304/23225914/f627c8cc-f933-11e6-9800-8b694cdee963.png)

**Comment by lipki** [comment]
I'm surprised that it makes it so good.
and yes you can work on it, of course !

**Comment by tobyplowy** [comment]
Can you make repositorys? One for MC and one for mt

**Comment by lipki** [comment]
For now, we are testing.

**Comment by tobyplowy** [comment]
@lipki Ok

**Comment by tobyplowy** [comment]
![16x](https://cloud.githubusercontent.com/assets/16853304/23447221/b68ef526-fe49-11e6-8884-79ac682027d3.png)

**Comment by tobyplowy** [comment]
@lipki @chengzzi89 so do we make this?

**Comment by lipki** [comment]
https://github.com/orgs/SummerFields/teams/summerfields-contributor

**Comment by tobyplowy** [comment]
@lipki @chengzzi89 @CuddleWoozle 
do we do it?

**Comment by lipki** [comment]
It interests me, but like everything else, the job that it represents scares me.

**Comment by tobyplowy** [comment]
@lipki yeah but i will help alot
and most textures shuld not take much longer than 5 minutes to make

**Comment by tobyplowy** [comment]
@chengzzi89 what about you what do you think?

**Comment by CuddleWoozle** [comment]
Just to pop in my thoughts on this:

I've always felt that Jolicraft was the 16x "summerfields".  The packs are
so similar in design/premise that I'm afraid if you start shrinking
SummerFields down you're going to end up with pretty much a Jolicraft clone.

I'm not saying "Don't do it", I'm just saying that's going to be something
you'll have to keep an eye on and make sure that things end up different
enough that people can tell one pack from the other.  This is mostly the
terrain textures and incidentals, the mobs in it are pretty unique.
(Except the wolf.  Totally look similar with the protruding fangs.)

**Comment by tobyplowy** [comment]
@lipki Close?
