### ISSUE TITLE
Update topic on PMC

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#309]
We should post a new topic on pmc (planet Minecraft)

**Comment by tobyplowy** [comment]
@lipki ping

**Comment by lipki** [comment]
I do not have the rights

**Comment by tobyplowy** [comment]
@lipki that suks close?

**Comment by lipki** [comment]
No. I keep it for the record, I have to recover the rights.

**Comment by tobyplowy** [comment]
@lipki ok
