### ISSUE TITLE
[1.12] concrete

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#310]
![concrete_black](https://cloud.githubusercontent.com/assets/401965/22757933/04ffbf5e-ee4d-11e6-923e-87a46f467254.png)![concrete_blue](https://cloud.githubusercontent.com/assets/401965/22757932/04fd8626-ee4d-11e6-9915-b03ed4e2fc41.png)![concrete_brown](https://cloud.githubusercontent.com/assets/401965/22757931/04fbd650-ee4d-11e6-9d83-998db954c664.png)![concrete_cyan](https://cloud.githubusercontent.com/assets/401965/22757935/050592c6-ee4d-11e6-84ef-abaf6f221399.png)![concrete_gray](https://cloud.githubusercontent.com/assets/401965/22757934/050315c8-ee4d-11e6-9b3c-161ab0de870e.png)![concrete_green](https://cloud.githubusercontent.com/assets/401965/22757936/050d97fa-ee4d-11e6-87fd-8523546c64f0.png)![concrete_light_blue](https://cloud.githubusercontent.com/assets/401965/22757937/051ef946-ee4d-11e6-9859-bb9410d0b391.png)![concrete_lime](https://cloud.githubusercontent.com/assets/401965/22757938/0521e78c-ee4d-11e6-91c1-f4bebf21b4d7.png)![concrete_magenta](https://cloud.githubusercontent.com/assets/401965/22757939/0525997c-ee4d-11e6-8ea5-fe5d8d18fd92.png)![concrete_orange](https://cloud.githubusercontent.com/assets/401965/22757940/05265d58-ee4d-11e6-9b9e-e3dbc884403d.png)![concrete_pink](https://cloud.githubusercontent.com/assets/401965/22757941/0529892e-ee4d-11e6-91d8-2b9738dc1863.png)![concrete_purple](https://cloud.githubusercontent.com/assets/401965/22757959/058fa416-ee4d-11e6-818d-963d185ae3af.png)![concrete_red](https://cloud.githubusercontent.com/assets/401965/22757960/0593e828-ee4d-11e6-96fe-37bf84973f9c.png)![concrete_silver](https://cloud.githubusercontent.com/assets/401965/22757961/0597d762-ee4d-11e6-8f09-f119233bdfad.png)![concrete_white](https://cloud.githubusercontent.com/assets/401965/22757962/05aa26ba-ee4d-11e6-95c5-466ed03d9ccc.png)![concrete_yellow](https://cloud.githubusercontent.com/assets/401965/22757963/05aeac44-ee4d-11e6-8a59-0f256b1d5303.png)
![concrete_powder_black](https://cloud.githubusercontent.com/assets/401965/22757942/052f3220-ee4d-11e6-869b-1e2b5e1bb507.png)![concrete_powder_blue](https://cloud.githubusercontent.com/assets/401965/22757944/05408570-ee4d-11e6-9931-24e40ba8efc8.png)![concrete_powder_brown](https://cloud.githubusercontent.com/assets/401965/22757949/05542a58-ee4d-11e6-9b57-b13bda0ac738.png)![concrete_powder_cyan](https://cloud.githubusercontent.com/assets/401965/22757945/05482abe-ee4d-11e6-8bb0-d47f7353d0bb.png)![concrete_powder_gray](https://cloud.githubusercontent.com/assets/401965/22757946/054a1c34-ee4d-11e6-95fc-2c14ff9cb7a2.png)![concrete_powder_green](https://cloud.githubusercontent.com/assets/401965/22757947/054deaa8-ee4d-11e6-89cb-37cfff17cd2c.png)![concrete_powder_light_blue](https://cloud.githubusercontent.com/assets/401965/22757948/05511476-ee4d-11e6-95aa-bce52eb19e4a.png)![concrete_powder_lime](https://cloud.githubusercontent.com/assets/401965/22757950/0560db86-ee4d-11e6-96f3-d00d5dff6d95.png)![concrete_powder_magenta](https://cloud.githubusercontent.com/assets/401965/22757951/0568b3ba-ee4d-11e6-8201-9c343d2696e2.png)![concrete_powder_orange](https://cloud.githubusercontent.com/assets/401965/22757952/056c1262-ee4d-11e6-9cd1-9775443532cf.png)![concrete_powder_pink](https://cloud.githubusercontent.com/assets/401965/22757953/056e43a2-ee4d-11e6-876f-fe7fc5abff90.png)![concrete_powder_purple](https://cloud.githubusercontent.com/assets/401965/22757954/05711ece-ee4d-11e6-8246-93b24eb33ae7.png)![concrete_powder_red](https://cloud.githubusercontent.com/assets/401965/22757955/05763710-ee4d-11e6-9f6b-bf0660c17592.png)![concrete_powder_silver](https://cloud.githubusercontent.com/assets/401965/22757958/058ebc54-ee4d-11e6-9cb9-e714b80e6688.png)![concrete_powder_white](https://cloud.githubusercontent.com/assets/401965/22757956/05891b8c-ee4d-11e6-8165-27ab5737f72f.png)![concrete_powder_yellow](https://cloud.githubusercontent.com/assets/401965/22757957/058dd7d0-ee4d-11e6-84e5-6c540f635721.png)

**Comment by lipki** [comment]
![concrete_black](https://cloud.githubusercontent.com/assets/401965/24581299/3192a190-1719-11e7-9000-6b2ab95f185a.png)![concrete_blue](https://cloud.githubusercontent.com/assets/401965/24581300/3195855e-1719-11e7-8328-a0349d01d4f2.png)![concrete_brown](https://cloud.githubusercontent.com/assets/401965/24581301/31991b88-1719-11e7-98db-d66484b42d22.png)![concrete_cyan](https://cloud.githubusercontent.com/assets/401965/24581302/319c1e8c-1719-11e7-9a0b-873bd9e951d5.png)![concrete_gray](https://cloud.githubusercontent.com/assets/401965/24581303/319dc43a-1719-11e7-9f6b-d5dcf710e979.png)![concrete_green](https://cloud.githubusercontent.com/assets/401965/24581304/31a12724-1719-11e7-941f-22ec81661556.png)![concrete_light_blue](https://cloud.githubusercontent.com/assets/401965/24581306/31b502bc-1719-11e7-93d0-00df1d78f90f.png)![concrete_lime](https://cloud.githubusercontent.com/assets/401965/24581305/31b49a2a-1719-11e7-94dc-89952b79f068.png)![concrete_magenta](https://cloud.githubusercontent.com/assets/401965/24581307/31b71994-1719-11e7-8459-46c0e3711c59.png)![concrete_orange](https://cloud.githubusercontent.com/assets/401965/24581308/31b9f772-1719-11e7-97f8-3cf62769a4ca.png)![concrete_pink](https://cloud.githubusercontent.com/assets/401965/24581309/31bcf12a-1719-11e7-9853-5abfd356d30c.png)![concrete_purple](https://cloud.githubusercontent.com/assets/401965/24581310/31bf604a-1719-11e7-83af-ac9ec78d2766.png)![concrete_red](https://cloud.githubusercontent.com/assets/401965/24581311/31d2e70a-1719-11e7-80b3-e80bdb83f5a7.png)![concrete_silver](https://cloud.githubusercontent.com/assets/401965/24581312/31d61114-1719-11e7-886f-0addebb0d9a9.png)![concrete_white](https://cloud.githubusercontent.com/assets/401965/24581313/31d8edbc-1719-11e7-92fd-a8eaedc6bdbf.png)![concrete_yellow](https://cloud.githubusercontent.com/assets/401965/24581314/31dbead0-1719-11e7-86e3-e5c29ef66e3c.png)
![concrete_powder_black](https://cloud.githubusercontent.com/assets/401965/24581315/3b628eba-1719-11e7-9127-c541d2c90e8c.png)![concrete_powder_blue](https://cloud.githubusercontent.com/assets/401965/24581317/3b9852d4-1719-11e7-8344-0024a11d1bb8.png)![concrete_powder_brown](https://cloud.githubusercontent.com/assets/401965/24581318/3b9b1398-1719-11e7-8877-1e6833747369.png)![concrete_powder_cyan](https://cloud.githubusercontent.com/assets/401965/24581319/3b9bfc68-1719-11e7-9f5c-bdebd4d9d686.png)![concrete_powder_gray](https://cloud.githubusercontent.com/assets/401965/24581320/3ba10eec-1719-11e7-965a-b24f32d5d431.png)![concrete_powder_green](https://cloud.githubusercontent.com/assets/401965/24581321/3ba206d0-1719-11e7-9f53-c176f2cc0630.png)![concrete_powder_light_blue](https://cloud.githubusercontent.com/assets/401965/24581316/3b81ba2e-1719-11e7-8b48-9c746d5d464c.png)![concrete_powder_lime](https://cloud.githubusercontent.com/assets/401965/24581322/3ba490ee-1719-11e7-94e7-813298b71e1f.png)![concrete_powder_magenta](https://cloud.githubusercontent.com/assets/401965/24581323/3bb8c5aa-1719-11e7-90b4-364269a84fc4.png)![concrete_powder_orange](https://cloud.githubusercontent.com/assets/401965/24581324/3bba0a0a-1719-11e7-85ce-5769319cd0bc.png)![concrete_powder_pink](https://cloud.githubusercontent.com/assets/401965/24581325/3bbc88ac-1719-11e7-9100-b62cd87de712.png)![concrete_powder_purple](https://cloud.githubusercontent.com/assets/401965/24581326/3bbfe952-1719-11e7-90bd-bf4f9a4b73ac.png)![concrete_powder_red](https://cloud.githubusercontent.com/assets/401965/24581327/3bc3583a-1719-11e7-8b17-c154185dec21.png)![concrete_powder_silver](https://cloud.githubusercontent.com/assets/401965/24581328/3bc55630-1719-11e7-8830-620d5770ff11.png)![concrete_powder_white](https://cloud.githubusercontent.com/assets/401965/24581329/3bd7d1a2-1719-11e7-98e1-e706fd047a1e.png)![concrete_powder_yellow](https://cloud.githubusercontent.com/assets/401965/24581330/3bda2eb6-1719-11e7-83bf-ab537bfa8cd5.png)

**Comment by tobyplowy** [comment]
@lipki some colors look like a solid colors thats a bit boring

these colors are black, red, dark green, and dark blue,

**Comment by tobyplowy** [comment]
top row

**Comment by lipki** [comment]
I just try to make them very smooth.
For example, black makes it possible to have a real black block, almost a void.
![capture du 2017-04-02 23-23-46](https://cloud.githubusercontent.com/assets/401965/24591197/e554e0ac-17fb-11e7-857b-ca31cb2ffe87.png)

**Comment by tobyplowy** [comment]
@lipki Oh ok I see that's nice
