### ISSUE TITLE
[1.12] terracotta

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#311]
![glazed_terracotta_black](https://cloud.githubusercontent.com/assets/401965/22757989/1c6cec3e-ee4d-11e6-82a6-ce12b3fdf84a.png)![glazed_terracotta_blue](https://cloud.githubusercontent.com/assets/401965/22757990/1c6ec34c-ee4d-11e6-9af6-06e3622ec41f.png)![glazed_terracotta_brown](https://cloud.githubusercontent.com/assets/401965/22757991/1c72189e-ee4d-11e6-99c2-1a16a9e3937c.png)![glazed_terracotta_cyan](https://cloud.githubusercontent.com/assets/401965/22757992/1c747c92-ee4d-11e6-940d-056fc8d49779.png)![glazed_terracotta_gray](https://cloud.githubusercontent.com/assets/401965/22757993/1c77336a-ee4d-11e6-8557-d25348231117.png)![glazed_terracotta_green](https://cloud.githubusercontent.com/assets/401965/22757994/1c879f8e-ee4d-11e6-81fd-40c9b25d432a.png)![glazed_terracotta_light_blue](https://cloud.githubusercontent.com/assets/401965/22757995/1c8ddd22-ee4d-11e6-88f0-eec9c9b257f4.png)![glazed_terracotta_lime](https://cloud.githubusercontent.com/assets/401965/22757996/1c918c56-ee4d-11e6-9157-ad62814d06b4.png)![glazed_terracotta_magenta](https://cloud.githubusercontent.com/assets/401965/22757997/1c9546f2-ee4d-11e6-85f0-fe46fe9af661.png)![glazed_terracotta_orange](https://cloud.githubusercontent.com/assets/401965/22757998/1c996fd4-ee4d-11e6-9f53-4efd687da89d.png)![glazed_terracotta_pink](https://cloud.githubusercontent.com/assets/401965/22757999/1ca87150-ee4d-11e6-94e8-6f84d3107eb8.png)![glazed_terracotta_purple](https://cloud.githubusercontent.com/assets/401965/22758000/1caa7298-ee4d-11e6-9449-6f7796f21bb8.png)![glazed_terracotta_red](https://cloud.githubusercontent.com/assets/401965/22758001/1caf298c-ee4d-11e6-9413-c5c3928f899e.png)![glazed_terracotta_silver](https://cloud.githubusercontent.com/assets/401965/22758003/1cb7126e-ee4d-11e6-85a2-8f3ad88d9ac9.png)![glazed_terracotta_white](https://cloud.githubusercontent.com/assets/401965/22758002/1cb69e60-ee4d-11e6-8bf9-e7d2fbe2d438.png)![glazed_terracotta_yellow](https://cloud.githubusercontent.com/assets/401965/22758004/1cba7062-ee4d-11e6-88f1-5ecf9ca63be6.png)

**Comment by lipki** [comment]
![test3](https://cloud.githubusercontent.com/assets/401965/22839598/5e030326-efca-11e6-8671-023ab7bfc1b8.png)
![use5604](https://cloud.githubusercontent.com/assets/401965/22839603/622895d8-efca-11e6-84b9-41ef8de507a9.png)

**Comment by tobyplowy** [comment]
@lipki I think you should do this one I'm not good at this :/

**Comment by lipki** [comment]
Well, we gotta find something for that.

**Comment by tobyplowy** [comment]
@lipki maybe we should copy the original designs (so we don't brake patterns that poeple have already made)

**Comment by chengzzi89** [comment]
glazed terracotta When can all be done?😃😃😃

**Comment by tobyplowy** [comment]
@chengzzi89 probably never XD no but really it will take alot of effort and time to make new designs (I think we should remake the original 16x16 textures but in 32x32 and recolor them to fit the Summerfields color palette

**Comment by tobyplowy** [comment]
@lipki do you agree with the above comment?

**Comment by chengzzi89** [comment]
Agree, I think so!😋

**Comment by lipki** [comment]
for wait, i add the faithful terracotta.

**Comment by chengzzi89** [comment]
@lipki Really sorry! I have already done my best!😟😔
![1](https://user-images.githubusercontent.com/28303754/27012486-e81f6dd2-4f02-11e7-9879-bb7a317a6bbe.png)![2]https://user-images.githubusercontent.com/28303754/27012489-02f89cdc-4f03-11e7-9164-f056ed556620.png)![3](https://user-images.githubusercontent.com/28303754/27012533-c7254c68-4f03-11e7-9045-ca90cd9b8448.png)![4](https://user-images.githubusercontent.com/28303754/27012617-9c4f540a-4f05-11e7-9f54-469121fe666d.png)![5](https://user-images.githubusercontent.com/28303754/27012622-c7c3a078-4f05-11e7-8095-df62008a7370.png)![6](https://user-images.githubusercontent.com/28303754/27012627-d60afa28-4f05-11e7-961a-4ad3a9ed285c.png)![7](https://user-images.githubusercontent.com/28303754/27012630-e0bdc9d2-4f05-11e7-9696-9ebd8ba4a5db.png)

**Comment by lipki** [comment]
Do not worry @chengzzi89, what you do is very good, it does not matter if it is not finished now, the important thing is that we like it.
We all worked well all three.

**Comment by tobyplowy** [comment]
@chengzzi89 You did a nice job with those

**Comment by chengzzi89** [comment]
@tobyplowy If you are not satisfied, we can also rework!😃

**Comment by tobyplowy** [comment]
@chengzzi89 the textures are nice but the colors need some fixing 
apart from that it's pretty much perfect

**Comment by chengzzi89** [comment]
@tobyplowy Color on my fixed is not very accurate, I hope you can help!

**Comment by tobyplowy** [comment]
@chengzzi89 I will take a look at it later I already have insane amounts of work to do on other projects I help 

Maybe @lipki can help?

**Comment by chengzzi89** [comment]
@tobyplowy 😟😞Suddenly on their own design is not satisfied!😞Just to see the Conquest texture of the glazed tiles, looking back at their own design, feeling ugly!

**Comment by chengzzi89** [comment]
@tobyplowy The color fixes! I wonder if I can use it?😮？
![1498265162361](https://user-images.githubusercontent.com/28303754/27544966-36e54954-5ac1-11e7-90ae-9a2d1182787a.png)
![1498265162578](https://user-images.githubusercontent.com/28303754/27544964-36dbfbb0-5ac1-11e7-8076-eaa653314dc7.png)
![1498265162984](https://user-images.githubusercontent.com/28303754/27544963-36d604a8-5ac1-11e7-92f8-0d4fa305f573.png)
![1498265163225](https://user-images.githubusercontent.com/28303754/27544965-36e12ef0-5ac1-11e7-9250-8b3bd906b569.png)
![1498265164091](https://user-images.githubusercontent.com/28303754/27544968-36ed6c9c-5ac1-11e7-989a-a6571249e7a7.png)
![1498265164307](https://user-images.githubusercontent.com/28303754/27544967-36ea6c40-5ac1-11e7-838a-e23b3280da9f.png)
![1498265164513](https://user-images.githubusercontent.com/28303754/27544969-37073ed8-5ac1-11e7-929a-81c86036249b.png)
![1498265164712](https://user-images.githubusercontent.com/28303754/27544970-3709b7a8-5ac1-11e7-88d3-52a001f294f4.png)
![1498265164945](https://user-images.githubusercontent.com/28303754/27544971-3713b0f0-5ac1-11e7-8a3e-546c85dc9514.png)
![1498403654169](https://user-images.githubusercontent.com/28303754/27544972-3715cfca-5ac1-11e7-82fd-c74891cc691b.png)
![1498410865925](https://user-images.githubusercontent.com/28303754/27544973-371d5d80-5ac1-11e7-814a-85dfb7a1165e.png)
![1498411692921](https://user-images.githubusercontent.com/28303754/27544974-3725f38c-5ac1-11e7-983b-75800084c81c.png)
![1](https://user-images.githubusercontent.com/28303754/27544975-373677f2-5ac1-11e7-994c-cf1295a8345f.png)
![2](https://user-images.githubusercontent.com/28303754/27544978-377a635e-5ac1-11e7-9011-e58122d23f69.png)
![default](https://user-images.githubusercontent.com/28303754/27544977-37785e56-5ac1-11e7-8feb-bf56cff49749.png)
![default](https://user-images.githubusercontent.com/28303754/27544976-37780a46-5ac1-11e7-9189-3c3ac75c23c5.png)

**Comment by tobyplowy** [comment]
@chengzzi89 yeh that's good @lipki what do you think?

**Comment by chengzzi89** [comment]
Hi! Do you have Sina Weibo?😃

**Comment by tobyplowy** [comment]
@chengzzi89 i dunno what Sina Weibo is :/

**Comment by lipki** [comment]
I think that is very good. It's a good job. We have to test them, a little, to see if they fit right. I'll see if I can find a map for that.

**Comment by tobyplowy** [comment]
@lipki so do we add @chengzzi89 s textures?

**Comment by lipki** [comment]
@CuddleWoozle Since you are in the corner.
What do you think of that?

**Comment by lipki** [comment]
I took a little, the colors, to be in the sheme summerfields.
That's what it gives in image.

![color](https://user-images.githubusercontent.com/401965/41443075-072097b0-703b-11e8-8120-5745676bc2d9.png)
![capture du 2018-06-15 01-26-29](https://user-images.githubusercontent.com/401965/41443097-3432e23a-703b-11e8-8808-799d1cc3c3ee.png)
![capture du 2018-06-15 01-38-37](https://user-images.githubusercontent.com/401965/41443399-e678c940-703c-11e8-9d4a-9aa40973b451.png)

The patterns are good, but I'm still not satisfied with the result.
What do you think.

**Comment by chengzzi89** [comment]
Yellow and orange may be exchanged!🤔

**Comment by chengzzi89** [comment]
Yellow and orange may be exchanged!🤔

**Comment by lipki** [comment]
![red_glazed_terracotta](https://user-images.githubusercontent.com/401965/41609496-2897697e-73eb-11e8-8fc0-42983a415942.png)
![capture du 2018-06-19 17-54-11](https://user-images.githubusercontent.com/401965/41609483-22063a86-73eb-11e8-9dd5-7c0620aa2452.png)
Inspired by a dragon texture quest
![39201](https://user-images.githubusercontent.com/401965/41609601-7ceff9a0-73eb-11e8-8bab-2deff648c47f.png)

**Comment by tobyplowy** [comment]
I think these textures are perfect, I feel like they are ready to be added :D

**Comment by tobyplowy** [comment]
@lipki Close?

**Comment by chengzzi89** [comment]
Determined by the re-drawn glazed_terracotta texture,Hope this time's be satisfied!
![glazed_terracotta_black](https://user-images.githubusercontent.com/28303754/76326098-1c6afc00-6323-11ea-8e7a-dd4a60029e8a.png)
![Screenshot_20200310_224823](https://user-images.githubusercontent.com/28303754/76326427-956a5380-6323-11ea-8546-8a026809ab1a.jpg)
![Screenshot_20200310_224835](https://user-images.githubusercontent.com/28303754/76326492-ab781400-6323-11ea-8b5c-cdf8ca338296.jpg)
![Screenshot_20200310_224846](https://user-images.githubusercontent.com/28303754/76326505-b0d55e80-6323-11ea-8c5d-b09db2d3c924.jpg)

**Comment by tobyplowy** [comment]
@chengzzi89 That's a really nice terracotta texture!!!
