### ISSUE TITLE
[1.12] Correction of cow's udders

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#312]
![cow](https://cloud.githubusercontent.com/assets/401965/24581341/9d4e1b4e-1719-11e7-8959-d14f3221ee6f.png)
![mooshroom](https://cloud.githubusercontent.com/assets/401965/24581342/9d517d20-1719-11e7-815b-0770a76d4162.png)

**Comment by tobyplowy** [comment]
yes this was a problem i forgot to report it or did i i forgot ;/

**Comment by lipki** [comment]
No worries, mojang also made a mistake :)

**Comment by tobyplowy** [comment]
@lipki I consider this done :)
