### ISSUE TITLE
[1.12] parrot

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#313]
- new mob, parrot
![parrot_blue](https://cloud.githubusercontent.com/assets/401965/24581158/6198924e-1716-11e7-8a46-feba4fe1f912.png)![parrot_green](https://cloud.githubusercontent.com/assets/401965/24581159/619befd4-1716-11e7-8d64-3cb25d1859c9.png)![parrot_grey](https://cloud.githubusercontent.com/assets/401965/24581160/619eb98a-1716-11e7-8d1e-50d7b6d400f6.png)![parrot_red_blue](https://cloud.githubusercontent.com/assets/401965/24581161/61a3bb7e-1716-11e7-952b-f3c9e1886bed.png)![parrot_yellow_blue](https://cloud.githubusercontent.com/assets/401965/24581162/61a5079a-1716-11e7-8eb3-9014007d098a.png)

**Comment by tobyplowy** [comment]
![parrot_blue](https://cloud.githubusercontent.com/assets/16853304/24582223/407919b6-172b-11e7-9475-65a7a1378e51.png)
![parrot_green](https://cloud.githubusercontent.com/assets/16853304/24582224/4241a92a-172b-11e7-9555-6de8fb290493.png)
![parrot_red_blue](https://cloud.githubusercontent.com/assets/16853304/24582226/43a9213a-172b-11e7-8ad4-14824a7e8fe4.png)
![parrot_yellow_blue](https://cloud.githubusercontent.com/assets/16853304/24582229/4be45284-172b-11e7-9612-a6165f05bdce.png)

**Comment by lipki** [comment]
for the last : https://duckduckgo.com/?q=cacaotes&t=lm&iax=1&ia=images

**Comment by tobyplowy** [comment]
@lipki [what the fuck is this XD](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.parrot-parrots.com%2Fphotos%2Ftextes%2Fespeces%2Fcacatoes%2Fcacatoes7.jpg&f=1)

**Comment by tobyplowy** [comment]
parrot_grey.png
![parrot_grey](https://cloud.githubusercontent.com/assets/16853304/24586523/ad1882dc-17a3-11e7-86b3-ea24fce2c726.png)

**Comment by tobyplowy** [comment]
kaketoe

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by lipki** [comment]
To participate, I made some changes.
![parrot_grey](https://cloud.githubusercontent.com/assets/401965/24591209/28c41600-17fc-11e7-8c5c-d804915eac2e.png)

**Comment by tobyplowy** [comment]
@lipki nice

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by lipki** [comment]
Yes but we wait for 1.12 to close
