### ISSUE TITLE
[1.12] Advancements

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#314]
- Achievements become advancements

background textures : ![nether](https://cloud.githubusercontent.com/assets/401965/24581206/89813030-1717-11e7-8254-d3dbb1823505.png)![stone](https://cloud.githubusercontent.com/assets/401965/24581207/8983de48-1717-11e7-8304-a69708754fde.png)![adventure](https://cloud.githubusercontent.com/assets/401965/25129073/c2bd3056-243c-11e7-8fc4-489f73e1ecf4.png)

![tabs](https://cloud.githubusercontent.com/assets/401965/24581210/9e6cec5a-1717-11e7-8f1d-fb0f8d7e8649.png)![widgets](https://cloud.githubusercontent.com/assets/401965/25129126/fddfa5a6-243c-11e7-88c8-02223406d73d.png)![window](https://cloud.githubusercontent.com/assets/401965/25129127/fde18a4c-243c-11e7-972e-0bca9817ced7.png)![recipe_book](https://cloud.githubusercontent.com/assets/401965/24581261/65933744-1718-11e7-9f38-cbbda49f3f9b.png)
![toasts](https://cloud.githubusercontent.com/assets/401965/25254094/116d4a4a-2624-11e7-9f5a-2e38e4e27f62.png)

**Comment by tobyplowy** [comment]
@lipki can you do window.png

![window](https://cloud.githubusercontent.com/assets/16853304/24582209/f1207814-172a-11e7-8f49-fd70f262337b.png)

**Comment by lipki** [comment]
![tabs](https://cloud.githubusercontent.com/assets/401965/24582928/9e9abe54-173b-11e7-823a-df20ea8d186e.png)
![widgets](https://cloud.githubusercontent.com/assets/401965/24582927/9e989ec6-173b-11e7-8aa0-5176bd6ea36d.png)
![window](https://cloud.githubusercontent.com/assets/401965/24582929/9e9cdba8-173b-11e7-85cc-4e4133bef659.png)
![recipe_book](https://cloud.githubusercontent.com/assets/401965/24583540/e6fd64d2-174d-11e7-9e3d-73df1c047440.png)

**Comment by tobyplowy** [comment]
@lipki edit of your texture for recipe_book
![recipe_book](https://cloud.githubusercontent.com/assets/16853304/24587631/5866e3de-17ba-11e7-9186-613fa9f5c350.png)

**Comment by lipki** [comment]
- the back of the window darker and desaturated.
- the blue buttons :) _ ( when we will agree on a color )
- the back of the boxes, to distinguish the impossible crafts.
- the smaller boxes.
![recipe_book](https://cloud.githubusercontent.com/assets/401965/24590195/59f7acb8-17e9-11e7-982b-95fa9f723460.png)

**Comment by tobyplowy** [comment]
@lipki maybe a dark desaturated blue looks good (I have to test that thow)

**Comment by lipki** [comment]
background
![nether](https://cloud.githubusercontent.com/assets/401965/25179227/3b0544be-2509-11e7-896e-f5d4283c18ae.png)![stone](https://cloud.githubusercontent.com/assets/401965/25179228/3b0a4f54-2509-11e7-9a8d-d4dff165528f.png)![adventure](https://cloud.githubusercontent.com/assets/401965/25179226/3ad53b5c-2509-11e7-9b42-13b73afc73ac.png)

**Comment by lipki** [comment]
![widgets](https://cloud.githubusercontent.com/assets/401965/25184170/f50f50e2-2519-11e7-9aff-1a8a4c748412.png)
![recipe_book](https://cloud.githubusercontent.com/assets/401965/25184181/01e86920-251a-11e7-92ba-81336346ce55.png)
![toasts](https://cloud.githubusercontent.com/assets/401965/25184190/07162b30-251a-11e7-8f31-9b5aecb44a63.png)

**Comment by tobyplowy** [comment]
@lipki you may wanna add a search area the recipe book gui

So you know that you can type to search do I do it or you?

**Comment by lipki** [comment]
![toasts](https://cloud.githubusercontent.com/assets/401965/25253281/8b61ee40-2620-11e7-8fcb-9d04a4fe5ec2.png)![recipe_book](https://cloud.githubusercontent.com/assets/401965/25253603/ddfe893c-2621-11e7-8d8b-0cd020e4a2bd.png)
