### ISSUE TITLE
[1.12] Recipes book

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#315]
- recipes book #315
![crafting_table](https://cloud.githubusercontent.com/assets/401965/25129857/25b0c102-2440-11e7-88c5-eccc5b4edaee.png)![inventory](https://cloud.githubusercontent.com/assets/401965/25129945/8ad3c08e-2440-11e7-90e7-577b8bde561e.png)![recipe_background](https://cloud.githubusercontent.com/assets/401965/24581243/18b75644-1718-11e7-9fa9-ee16f436ebcd.png)![progress_book](https://cloud.githubusercontent.com/assets/401965/24581256/554259e2-1718-11e7-97fc-3fa7a9a13fca.png)

**Comment by tobyplowy** [comment]
crafting_table.png
![crafting_table](https://cloud.githubusercontent.com/assets/16853304/24582090/90fed162-1728-11e7-9d10-e1c9b21244f0.png)

**Comment by tobyplowy** [comment]
inventory.png
![inventory](https://cloud.githubusercontent.com/assets/16853304/24582289/93e4f254-172c-11e7-9ca3-5ba603e3961f.png)

**Comment by lipki** [comment]
I find it better without support, just the book.
![inventory](https://cloud.githubusercontent.com/assets/401965/24582378/3a986976-172f-11e7-88ab-730db19d8db6.png)
![crafting_table](https://cloud.githubusercontent.com/assets/401965/24582399/7ac0ea78-172f-11e7-9aca-e83125604ed9.png)

**Comment by tobyplowy** [comment]
progress_book 
![progress_book](https://cloud.githubusercontent.com/assets/16853304/24582575/24a1ec10-1733-11e7-818d-bcfd96558359.png)

**Comment by tobyplowy** [comment]
@lipki this one took long XD

**Comment by tobyplowy** [comment]
@lipki also i dount know what those 3 icones are i think the first is a cube 
i will add them as soon as i know what it is

**Comment by tobyplowy** [comment]
recipe_background
![recipe_background](https://cloud.githubusercontent.com/assets/16853304/24582863/a8217884-1739-11e7-8c23-51d570efb492.png)

**Comment by lipki** [comment]
You put two covers :)

**Comment by tobyplowy** [comment]
@lipki oh i didn't notice that XD

Thank you for bringing this to my attention :) I will fix it later

**Comment by tobyplowy** [comment]
progress_book with one cover :D
![progress_book](https://cloud.githubusercontent.com/assets/16853304/24586416/799a7904-17a0-11e7-9a7e-56058086e7ae.png)

**Comment by lipki** [comment]
We're waiting to see how it works.
It's a good start.

**Comment by tobyplowy** [comment]
@lipki I hope I got rid Of The symmetry on the book so you can't see that it is copy pasted and mirrored :)

**Comment by lipki** [comment]
I didn't realize at all, absolutely not, impossible, really, I do not see what you're talking about.

**Comment by tobyplowy** [comment]
@lipki now I'm confused sorry :/

**Comment by lipki** [comment]
It was ironyIt was irony

**Comment by lipki** [comment]
- add bookbinding
- color
- shadow
- And shifting the middle to the left to match the initial texture.
![progress_book](https://cloud.githubusercontent.com/assets/401965/24590882/97c34c58-17f5-11e7-9be6-14c39275c33b.png)

**Comment by lipki** [comment]
![crafting_table](https://cloud.githubusercontent.com/assets/401965/25184273/4068c910-251a-11e7-8614-47cddba1e8c6.png)
![inventory](https://cloud.githubusercontent.com/assets/401965/25184286/4ae96624-251a-11e7-85ca-4b9016cb4092.png)
