### ISSUE TITLE
[1.12] Iron nugget

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#316]
![iron_nugget](https://cloud.githubusercontent.com/assets/401965/24581264/8714b05a-1718-11e7-91ef-16968fb02784.png)

**Comment by lipki** [comment]
![iron_nugget](https://cloud.githubusercontent.com/assets/401965/24581355/ef9ee5c2-1719-11e7-8482-c830c8636102.png)

**Comment by tobyplowy** [comment]
@lipki can you make it 1 big peace instead of 3

**Comment by lipki** [comment]
You have arguments ?

**Comment by tobyplowy** [comment]
Yes this \/

> @lipki can you make it 1 big peace instead of 3

**Comment by lipki** [comment]
Yeah! Bah! I have no idea, so for now I keep that one.
And I leave the ticket open.

**Comment by tobyplowy** [comment]
@lipki on second thought I think the texture you have made is good
