### ISSUE TITLE
[1.12] Knowledge book

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#317]
![knowledge_book](https://cloud.githubusercontent.com/assets/401965/24581267/88d0a232-1718-11e7-8cd1-e6ff3366facc.png)

**Comment by lipki** [comment]
![knowledge_book](https://cloud.githubusercontent.com/assets/401965/24581445/d5cfcdd0-171b-11e7-9013-3607585ef6c9.png)
i try this.

**Comment by tobyplowy** [comment]
@lipki looks good

**Comment by lipki** [comment]
A little more blue
![knowledge_book](https://cloud.githubusercontent.com/assets/401965/24583591/2fcfd634-1750-11e7-9221-f29351e9abfe.png)

**Comment by tobyplowy** [comment]
@lipki yes it looks better like that

**Comment by lipki** [comment]
done
