### ISSUE TITLE
A new pack

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#318]
@lipki Would You be interested in making a new texture pack With Me?
This Would Be a completely New pack Made from Scratch
This is just a question we can talk about More details later

**Comment by tobyplowy** [comment]
@lipki ping

**Comment by lipki** [comment]
Honestly i dont know if i have the time :)

**Comment by tobyplowy** [comment]
@lipki well we can work on it slowly

It's just an idea anyway it would be interesting what we can do together :)

**Comment by lipki** [comment]
Always proposes, opens a repo.

**Comment by tobyplowy** [comment]
@lipki I don't really understand what you are saying

Are you asking me to make a repo?

**Comment by lipki** [comment]
You can create a repository on github, start suggesting textures, and explain what you want to do.
And if it inspires me, I would help you.

**Comment by tobyplowy** [comment]
@lipki 
https://github.com/tobyplowy/temp-name
for now the project called temp-name and its a minetest pack but it can also be made for minecraft

please have a look at what i have so far

**Comment by tobyplowy** [comment]
and give feedback :D

**Comment by tobyplowy** [comment]
@lipki have you tryed it yet :D

**Comment by tobyplowy** [comment]
@lipki close?
