### ISSUE TITLE
New interface button

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#319]
I'm testing, what do you think?

![widgets](https://cloud.githubusercontent.com/assets/401965/24582343/fa718de2-172d-11e7-9a91-33801e85e99b.png)

**Comment by tobyplowy** [comment]
@lipki im not shure about the blue :/ but the new textures are nice

**Comment by tobyplowy** [comment]
@lipki how is this?
![widgets](https://cloud.githubusercontent.com/assets/16853304/24582856/18c6a47a-1739-11e7-8482-87bfd50e0029.png)

**Comment by lipki** [comment]
I'm not sure about the blue either, but, I think it takes a color.

**Comment by lipki** [comment]
Here the colors tests.

**Comment by tobyplowy** [comment]
@lipki can you make the little letter icone for Minecraft realms?

Next to the 12345!

**Comment by lipki** [comment]
I do not use realms and anyway it does not work anymore on the old launcher under linux.
Tell me what size does it.

**Comment by tobyplowy** [comment]
@lipki can you do the thing thats in the red secle (or oval)
![18c6a47a-1739-11e7-8482-87bfd50e0029](https://cloud.githubusercontent.com/assets/16853304/24591170/387eb268-17fb-11e7-8827-fb46849771fa.png)

**Comment by lipki** [comment]
Yes, but can you tell me what size max.

**Comment by tobyplowy** [comment]
@lipki nevermind​ you can't edit it :/

**Comment by lipki** [comment]
![widgets](https://cloud.githubusercontent.com/assets/401965/25184366/82be61ee-251a-11e7-8ce0-b39ae3d44bfe.png)

**Comment by tobyplowy** [comment]
@lipki yes that color is good

but the lock difficulty button is not working corectly

**Comment by tobyplowy** [comment]
fix
![widgets](https://cloud.githubusercontent.com/assets/16853304/25194784/cb796de0-253b-11e7-8e29-e3db470c5065.png)
