### ISSUE TITLE
hay recolor

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#320]
in my opinion this looks better and less blinding XD

hay_block_top.png
![hay_block_top](https://cloud.githubusercontent.com/assets/16853304/24582890/9bfb3fee-173a-11e7-8ebf-b77a4875385b.png)
hay_block_side.png
![hay_block_side](https://cloud.githubusercontent.com/assets/16853304/24582892/9c1011ee-173a-11e7-8968-1cdda0cabe18.png)

**Comment by lipki** [comment]
yep

**Comment by tobyplowy** [comment]
@lipki can you add it to the 1.12 Milestone?

**Comment by lipki** [comment]
je l'ai ajouter chez moi.
je vais faire le commit.
