### ISSUE TITLE
new selection arrows

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#321]
world_selection
![world_selection](https://cloud.githubusercontent.com/assets/16853304/24586899/95a83f22-17ab-11e7-882d-37b66f34c764.png)
resource_packs
![resource_packs](https://cloud.githubusercontent.com/assets/16853304/24586900/95bb63fe-17ab-11e7-9dfd-67e6c7c99880.png)
server_selection
![server_selection](https://cloud.githubusercontent.com/assets/16853304/24586901/95cad474-17ab-11e7-9036-fbdda78bab3b.png)

**Comment by tobyplowy** [comment]
spectator_widgets
![spectator_widgets](https://cloud.githubusercontent.com/assets/16853304/24587368/8913c902-17b5-11e7-80fd-329379260e2e.png)
stats_icons
![stats_icons](https://cloud.githubusercontent.com/assets/16853304/24587369/8914c1e0-17b5-11e7-98a9-87b68be0cadb.png)

**Comment by lipki** [comment]
yes ok

**Comment by tobyplowy** [comment]
@lipki can you do the ! simbol in the first picture

**Comment by lipki** [comment]
Yes, it remains that one.

**Comment by lipki** [comment]
![world_selection](https://cloud.githubusercontent.com/assets/401965/25240041/1c5c4ad2-25f2-11e7-9f81-b64e28a0262e.png)

**Comment by lipki** [comment]
![stats_icons](https://cloud.githubusercontent.com/assets/401965/25240496/42b9f5de-25f3-11e7-9b4a-c75c9dd502e9.png)

**Comment by tobyplowy** [comment]
@lipki looks good

**Comment by tobyplowy** [comment]
@lipki done?
