### ISSUE TITLE
new gravel texture

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#322]
![gravel](https://cloud.githubusercontent.com/assets/16853304/24587299/2221329e-17b4-11e7-944c-ef0d22ab18c5.png)

**Comment by lipki** [comment]
XD

**Comment by tobyplowy** [comment]
@lipki no idea why this is funny but ok :)

**Comment by tobyplowy** [comment]
@lipki can you add it to the 1.12 Milestone?

**Comment by tobyplowy** [comment]
@lipki will this be added?

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by lipki** [comment]
yep
