### ISSUE TITLE
[1.12] colored bed

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#324]
remove :
assets/minecraft/textures/blocks/bed_feet_end.png
assets/minecraft/textures/blocks/bed_feet_side.png
assets/minecraft/textures/blocks/bed_feet_top.png
assets/minecraft/textures/blocks/bed_head_end.png
assets/minecraft/textures/blocks/bed_head_side.png
assets/minecraft/textures/blocks/bed_head_top.png
assets/minecraft/textures/items/bed.png
add : 
![black](https://cloud.githubusercontent.com/assets/401965/25128983/670854de-243c-11e7-9bc6-c337d1ff358f.png)![blue](https://cloud.githubusercontent.com/assets/401965/25128987/67292952-243c-11e7-8764-b7d104399ab1.png)![brown](https://cloud.githubusercontent.com/assets/401965/25128988/6729847e-243c-11e7-907d-f39a5844fe11.png)![cyan](https://cloud.githubusercontent.com/assets/401965/25128989/67299e00-243c-11e7-89d7-329e4c0cffe0.png)![gray](https://cloud.githubusercontent.com/assets/401965/25128990/672ec628-243c-11e7-8fcd-fd9cb4af8e33.png)![green](https://cloud.githubusercontent.com/assets/401965/25128986/67282c5a-243c-11e7-8fb6-3443d7910983.png)![light_blue](https://cloud.githubusercontent.com/assets/401965/25128985/6723c21e-243c-11e7-91f6-a3eb0e741650.png)![lime](https://cloud.githubusercontent.com/assets/401965/25128992/673cab1c-243c-11e7-8768-352e0f7fed4d.png)![magenta](https://cloud.githubusercontent.com/assets/401965/25128991/673affd8-243c-11e7-9e15-c840547050df.png)![orange](https://cloud.githubusercontent.com/assets/401965/25128994/673e41de-243c-11e7-9336-04879ae15c7e.png)![pink](https://cloud.githubusercontent.com/assets/401965/25128993/673e0db8-243c-11e7-8ba5-a33ffaa591dd.png)![purple](https://cloud.githubusercontent.com/assets/401965/25128995/673fffec-243c-11e7-9a8c-c7e221d94612.png)![red](https://cloud.githubusercontent.com/assets/401965/25128996/6746e3e8-243c-11e7-80e0-ab6a713e11f2.png)![silver](https://cloud.githubusercontent.com/assets/401965/25128997/675126e6-243c-11e7-93fc-f86eb3a76114.png)![white](https://cloud.githubusercontent.com/assets/401965/25128998/6751c088-243c-11e7-8bdf-2f48e7167e40.png)![yellow](https://cloud.githubusercontent.com/assets/401965/25128999/6756d12c-243c-11e7-8a17-b044a41c3b17.png)

**Comment by lipki** [comment]
![white](https://cloud.githubusercontent.com/assets/401965/25133413/eb858546-244c-11e7-8ca6-42005feba81e.png)

colored --- decorated
![black_2](https://cloud.githubusercontent.com/assets/401965/25133736/d89ee26e-244d-11e7-97e4-f515293a8abe.png)![black](https://cloud.githubusercontent.com/assets/401965/25133422/f000cc98-244c-11e7-8c44-57bd6738aada.png)

**Comment by tobyplowy** [comment]
@lipki wait this update has dubble beds

**Comment by lipki** [comment]
No it's just a proposition, with or without decor.

**Comment by tobyplowy** [comment]
@lipki oh I see I think with decore is better

**Comment by lipki** [comment]
![silver](https://cloud.githubusercontent.com/assets/401965/25177302/aa99442c-2501-11e7-94fb-0ad11d9d06f4.png)
![capture du 2017-04-19 13-09-18](https://cloud.githubusercontent.com/assets/401965/25177292/9cccac08-2501-11e7-8c7d-394e577e0263.png)

**Comment by tobyplowy** [comment]
I rather have a wooden bed than metal

**Comment by lipki** [comment]
Yes, I have fun :)

**Comment by tobyplowy** [comment]
@lipki I have a idea maybe it's a bad one maybe a good one

But wuld it look good if the white bed was a mattress without bed sheets?

**Comment by tobyplowy** [comment]
@lipki how is this?
![e1ea2780-2456-11e7-8f41-a754232c6c6e](https://cloud.githubusercontent.com/assets/16853304/25190088/7afb6630-252b-11e7-81b3-3b49595d028d.png)

**Comment by lipki** [comment]
Yeah it is very good, and I like the idea.

**Comment by tobyplowy** [comment]
@lipki thanks :)

**Comment by chengzzi89** [comment]
![tim](https://cloud.githubusercontent.com/assets/28303754/26813956/7a5705be-4ab4-11e7-8838-98feb937749c.png)
![qqqw](https://cloud.githubusercontent.com/assets/28303754/26813960/7d576c22-4ab4-11e7-9152-c64b66e30210.png)

**Comment by lipki** [comment]
done
