### ISSUE TITLE
[1.12] Illusionist

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#326]
![illusionist](https://cloud.githubusercontent.com/assets/401965/25250310/59ed6354-2615-11e7-8aa5-329d9d299bb6.png)

**Comment by lipki** [comment]
Noted

**Comment by tobyplowy** [comment]
@lipki i have no idea what to do with it :/
![illusionist](https://cloud.githubusercontent.com/assets/16853304/25304847/e21719fe-276f-11e7-8249-604890e30e62.png)

**Comment by lipki** [comment]
I like the face and the eyes in the shadow.
But the clothes are too black.
Evoker and witch is already very black.

**Comment by tobyplowy** [comment]
@lipki what wuld you do with the clothes?

**Comment by lipki** [comment]
You said you wanted to.
I make you trust.

**Comment by tobyplowy** [comment]
@lipki I Donno what to do with the clothes

**Comment by lipki** [comment]
Maybe watch the disney magician.
Or figures of magicians in pop culture, video games.

**Comment by tobyplowy** [comment]
![illusionist](https://cloud.githubusercontent.com/assets/16853304/25356277/e7f424fe-2939-11e7-9982-28504df8a594.png)

**Comment by lipki** [comment]
ihihih :D 
![capture du 2017-04-25 23-59-05](https://cloud.githubusercontent.com/assets/401965/25409774/adf4a0fa-2a13-11e7-8d77-695ece61edaf.png)
![illusionist](https://cloud.githubusercontent.com/assets/401965/25409789/bbe68570-2a13-11e7-8f27-516b63771735.png)
![latest](https://cloud.githubusercontent.com/assets/401965/25409835/e91432cc-2a13-11e7-8812-7ac50fc08b14.png)

**Comment by tobyplowy** [comment]
@lipki I like the mummygician :)

I wish I was so good at this like you :/

**Comment by tobyplowy** [comment]
@lipki also the one based on the picture looks super evil :)

**Comment by tobyplowy** [comment]
@lipki how do you make your textures?

Do you just make the texture and see how it looks in game
Or Do you have Some Kind of program that shows you the model in 3d? (Like Nova skin or blender)
Or do you just have a really good sense of visualising the models in your head?

**Comment by lipki** [comment]
Since time, I visualize models very well in my head.
But I regularly watch in the games.
I enclose the mob in a prison of block barrier, and then I refresh with F3 + T.

For ideas, I do a search on the internet, in the images.
And I reuse a lot of the existing textures.

The momy is a body of pigmen, gray, with pieces of gold armor.
The cape is the texture of the banner, with the crown of the gold armor as decoration (you recognized it?).
The bands are just strokes, with shadows cast.

For the first, to place the red lines correctly, I used this:
Https://minecraft.novaskin.me/resourcepacks#default/assets/minecraft/textures/entity/villager/librarian.png
It's a first time, it does not finalize, but to put up the shape, it's not bad.

**Comment by lipki** [comment]
[william kaplan](http://marvel.wikia.com/wiki/William_Kaplan_(Earth-616)) is not a bad guy though.

**Comment by tobyplowy** [comment]
> with the crown of the gold armor as decoration (you recognized it?).

No I didn't so that's a good job :)

**Comment by tobyplowy** [comment]
@lipki also thank you for explaining :)

**Comment by lipki** [comment]
done ... magiptien ?

**Comment by tobyplowy** [comment]
@lipki Yes Also please check before you post a comment :)

It's kind of hard to read sometimes

**Comment by lipki** [comment]
magicien - egyptien -> magiptien
Magician - egyptian -> magiptian
;D
