### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by chengzzi89** [SummerFields/SummerFields#327]
Hello I'm coming.

**Comment by tobyplowy** [comment]
@chengzzi89 coming for what?
To help?

**Comment by lipki** [comment]
yes, see twitter.
[MCPE#1](https://github.com/SummerFields/MCPE/issues/1)

**Comment by lipki** [comment]
@chengzzi89 I like your idea of discord, but I can not join you, the invitation expired.

**Comment by tobyplowy** [comment]
@lipki I don't think discord is a good idea I think we should stay with GitHub

**Comment by lipki** [comment]
No, the "issues" are good to discuss of one change, but not to telling our lives.
As is the case here.
It will be necessary to make an "issue" for each decision taken on discord.

Finally discord or other things, you know a free tool?

**Comment by lipki** [comment]
I opened this, when you arrived.
https://framateam.org/summerfields/channels/town-square

**Comment by tobyplowy** [comment]
@lipki Gitter is interesting the minetest good morning craft project uses it
https://gitter.im/good-morning-craft/Lobby

Maybe we can open one for Summerfields?

**Comment by lipki** [comment]
https://gitter.im/Summerfields/Lobby
If we have to choose a tool, I prefer it free (open source).

**Comment by lipki** [comment]
https://framateam.org/signup_user_complete/?id=zdkutw38dbndpdqqznftpxra7r
for test
