### ISSUE TITLE
new sounds

### ISSUE THREAD

**Issue by chengzzi89** [SummerFields/SummerFields#328]
I have a question! Why doesn't SummerFields have sounds? I think we should have this project!

**Comment by tobyplowy** [comment]
@chengzzi89 i think it's because it takes alot of time (more than me and lipki heve)

And in my opinion the time it takes is not worth it

**Comment by chengzzi89** [comment]
@  OK! Oh, I see！ You've been working hard！

**Comment by tobyplowy** [comment]
@chengzzi89 there's no need to close yet lipki may like it (also I didn't say no I sayd it may take too much time)

@lipki Can you give me the rights to close and reopen alredy closed issues also to edit milestones

**Comment by lipki** [comment]
I can't, I'm bad in souds :)

**Comment by lipki** [comment]
@tobyplowy I can not. I do not find the settings.
You can comment the closed "issues", I would see.

**Comment by tobyplowy** [comment]
@lipki ok :/

**Comment by tobyplowy** [comment]
@lipki so do we consider this something we should try or do we leave it? 

(Because I'm not good with making sounds but I can try you say yes or no it's your call to make is this important enough)

**Comment by RobertZenz** [comment]
@lipki Collaborators do have the right to do that (and more, obviously). There is no "fine-grained" permissions as far as I know.

**Comment by lipki** [comment]
I only found this:

- Owner
    Has full administrative access to the entire organization.

- Member
    Can see every team and member in the organization, and can create new repositories.
