### ISSUE TITLE
leaf fix

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#329]
birch and oak have the same leaf texture (thats not suposto be)

birch leaf
![image](https://user-images.githubusercontent.com/16853304/27013311-dd8da670-4ee1-11e7-9d87-8a91a6e2055b.png)
oak leaf
![image](https://user-images.githubusercontent.com/16853304/27013315-e86eabd4-4ee1-11e7-9c08-71201b8da155.png)

oak is good but birch needs a new texture

also theres no difrence between oak and dark oak texture

**Comment by tobyplowy** [comment]
@lipki ping

**Comment by lipki** [comment]
Yes, it's true.
When it was necessary to add sheets, I did that quickly. At the time, I created very few new textures, just simple transformations.
But yeah, we have to change that.

**Comment by tobyplowy** [comment]
@lipki add to 1.13?

**Comment by tobyplowy** [comment]
@lipki ping
can this finnaly be fixed please?

**Comment by lipki** [comment]
I agree for the change.
But we should propose new texture.

**Comment by lipki** [comment]
acacia leaf ![acacia_leaves](https://user-images.githubusercontent.com/401965/41512517-d7828af8-7289-11e8-9d58-54b1d0ee6825.png)
birch leaf ![birch_leaves](https://user-images.githubusercontent.com/401965/41512762-4b6fb09e-728f-11e8-976f-6d65209de21f.png)
ping @tobyplowy

**Comment by lipki** [comment]
![capture du 2018-06-18 00-41-54](https://user-images.githubusercontent.com/401965/41512834-4ea8947c-7291-11e8-9044-51f608a4289f.png)
![capture du 2018-06-18 00-53-26](https://user-images.githubusercontent.com/401965/41512867-1b019898-7292-11e8-8ba4-557856c51c7b.png)

**Comment by tobyplowy** [comment]
@lipki good job
I like it!
