### ISSUE TITLE
Andesite???

### ISSUE THREAD

**Issue by glxy14colourse** [SummerFields/SummerFields#330]
Uhm... so.... Andesite is a great block. Builders often use it in castles and other builds with Stone bricks to bring in their builds more texture. So i have a bunch of screenshots of andesite and stone bricks.
Vanilla:
![2017-06-14_13 12 08](https://user-images.githubusercontent.com/29414200/27127581-412ca644-5104-11e7-9d76-6993e652aabd.png)
Summerfields:
![2017-06-14_13 11 35](https://user-images.githubusercontent.com/29414200/27127621-69efde34-5104-11e7-8c0c-d6b92aaf30af.png)
Vanilla:
![2017-06-14_13 12 26](https://user-images.githubusercontent.com/29414200/27127658-9097eb1c-5104-11e7-8159-307f825ff5a4.png)
Summerfiels:
![2017-06-14_13 12 42](https://user-images.githubusercontent.com/29414200/27127692-ab744840-5104-11e7-8f77-30a4f8a0c7bf.png)
Vanilla:
![2017-06-14_13 13 17](https://user-images.githubusercontent.com/29414200/27127723-c56ff762-5104-11e7-84c1-00818a790c37.png)
Summerfields:
![2017-06-14_13 13 02](https://user-images.githubusercontent.com/29414200/27127824-2130cec8-5105-11e7-8099-48ea30f2ab62.png)
As you can see, in summerfields resource pack andesite is very blue. And most of Stone brick builds look ugly when i play with SummerFields resource pack. Can you please make a new texture? Or make it optional?

(Sorry for bad English)

**Comment by tobyplowy** [comment]
@lipki yeh this looks like a problem

**Comment by chengzzi89** [comment]
@tobyplowy Cover a little warm tone？😮
![1497899388228](https://user-images.githubusercontent.com/28303754/27301501-fe97aebc-5565-11e7-81ba-356a0654f21a.png)
![1497899388419](https://user-images.githubusercontent.com/28303754/27301502-fe98dd28-5565-11e7-98f7-1b54ffef4d37.png)
![1497899388551](https://user-images.githubusercontent.com/28303754/27301504-fea03988-5565-11e7-9d5d-462aa6906f2d.png)
![1497899388721](https://user-images.githubusercontent.com/28303754/27301503-fea00c06-5565-11e7-827b-96ae2dcf30b9.png)
![1497899388854](https://user-images.githubusercontent.com/28303754/27301505-fea37a58-5565-11e7-9474-f90c2478e9fb.png)
![1497899388990](https://user-images.githubusercontent.com/28303754/27301506-feb3e988-5565-11e7-9e35-e94bf019aa2d.png)

**Comment by tobyplowy** [comment]
@chengzzi89 yeh that seems good to me

**Comment by lipki** [comment]
I like this blue, but I know it's weird.
I will think about it.
Made proposals with screens mixing the stones.

**Comment by lipki** [comment]
I reopen and I make my proposal.

![andesite](https://user-images.githubusercontent.com/401965/97174905-02d3d300-1793-11eb-818e-094e74004837.png) ![polished_andesite_1](https://user-images.githubusercontent.com/401965/97174948-12ebb280-1793-11eb-85e1-337b6da43ec7.png)![polished_andesite_2](https://user-images.githubusercontent.com/401965/97174951-13844900-1793-11eb-9d53-d48f0d65aef3.png)![polished_andesite_3](https://user-images.githubusercontent.com/401965/97174955-141cdf80-1793-11eb-98d6-a2c1f80b3d88.png)![polished_andesite_4](https://user-images.githubusercontent.com/401965/97174956-141cdf80-1793-11eb-8a33-bd794ad0c207.png)

**Comment by lipki** [comment]
#692
