### ISSUE TITLE
HD 64X-SummerFields ??

### ISSUE THREAD

**Issue by chengzzi89** [SummerFields/SummerFields#334]
![img_20170707_235453](https://user-images.githubusercontent.com/28303754/27966626-7a197f92-6372-11e7-9661-7312e5c27c4a.jpg)
![img_20170707_235457](https://user-images.githubusercontent.com/28303754/27966627-7a1a6330-6372-11e7-99ad-888dd136b933.jpg)
![img_20170707_235500](https://user-images.githubusercontent.com/28303754/27966628-7a1da176-6372-11e7-9dfa-21fad126c5ba.jpg)
![img_20170707_235504](https://user-images.githubusercontent.com/28303754/27966629-7a26e98e-6372-11e7-92f4-6e91a25bd680.jpg)

**Comment by tobyplowy** [comment]
@chengzzi89 This is what the website says and I agree

> Q: "Why not 64x . 128x .. 256x .... 2048x .............. aaah !"
> A: The purpose of Summerfields is not to deny the pixel, on the contrary.

**Comment by chengzzi89** [comment]
@tobyplowy Do you have time to do it?😶

**Comment by tobyplowy** [comment]
@chengzzi89 if lipki wantes to help yes

**Comment by lipki** [comment]
Without me,

**Comment by tobyplowy** [comment]
@chengzzi89 well I guess that's a no than

**Comment by tobyplowy** [comment]
@chengzzi89 but you can do it if you want I may join to help later If support for minetest is added 
chengzzi89 you probably don't know minetest so here have look http://www.minetest.net

**Comment by chengzzi89** [comment]
@tobyplowy Maybe I just want to be a mere HD64X😄
