### ISSUE TITLE
1.12 new bed

### ISSUE THREAD

**Issue by chengzzi89** [SummerFields/SummerFields#335]
1.12 official version of the bed, it's the latest texture you do not know?
![black](https://user-images.githubusercontent.com/28303754/27992643-222b4940-64cc-11e7-96e5-f8726ba55bb1.png)![blue](https://user-images.githubusercontent.com/28303754/27992641-2228731e-64cc-11e7-8dc0-d8de1cd57131.png)![brown](https://user-images.githubusercontent.com/28303754/27992640-2227fa6a-64cc-11e7-94ff-9f4824230156.png)![cyan](https://user-images.githubusercontent.com/28303754/27992639-2217f976-64cc-11e7-8797-fc22a831c263.png)![gray](https://user-images.githubusercontent.com/28303754/27992644-222caba0-64cc-11e7-9c0f-50395257d6c6.png)![green](https://user-images.githubusercontent.com/28303754/27992642-222a888e-64cc-11e7-8b7f-c6163b9fdbb5.png)![light_blue](https://user-images.githubusercontent.com/28303754/27992645-2252d78a-64cc-11e7-82ef-4ae1d23b32e1.png)![lime](https://user-images.githubusercontent.com/28303754/27992647-22678a36-64cc-11e7-91b1-c43157da45a1.png)![magenta](https://user-images.githubusercontent.com/28303754/27992646-2267212c-64cc-11e7-8271-5d8ec8c78d86.png)![orange](https://user-images.githubusercontent.com/28303754/27992649-2268b4c4-64cc-11e7-8777-e725a56a43bd.png)![pink](https://user-images.githubusercontent.com/28303754/27992648-22687d06-64cc-11e7-9e31-21a470a38369.png)![purple](https://user-images.githubusercontent.com/28303754/27992650-22705aa8-64cc-11e7-91d9-104b0309cdfe.png)![red](https://user-images.githubusercontent.com/28303754/27992651-22911c70-64cc-11e7-8657-69c1aac1217d.png)![silver](https://user-images.githubusercontent.com/28303754/27992652-22a42b62-64cc-11e7-8761-c2598ab4b909.png)![white](https://user-images.githubusercontent.com/28303754/27992654-22a79c8e-64cc-11e7-9d1e-129c9fed4aa5.png)![yellow](https://user-images.githubusercontent.com/28303754/27992653-22a54574-64cc-11e7-9a0f-cfdc66b0e6fa.png)

**Comment by chengzzi89** [comment]
![black](https://user-images.githubusercontent.com/28303754/27992682-c366084a-64cc-11e7-83e1-89e14b2f99c7.png)![blue](https://user-images.githubusercontent.com/28303754/27992683-c3685384-64cc-11e7-9a5c-2ccef4039fa1.png)![brown](https://user-images.githubusercontent.com/28303754/27992684-c39e081c-64cc-11e7-9245-8e972a13fd76.png)![cyan](https://user-images.githubusercontent.com/28303754/27992685-c3a181b8-64cc-11e7-8277-168eb0568bdd.png)![gray](https://user-images.githubusercontent.com/28303754/27992686-c3d61612-64cc-11e7-9501-f64333b319e7.png)![green](https://user-images.githubusercontent.com/28303754/27992687-c3d89568-64cc-11e7-8439-ff609e0c237b.png)![light_blue](https://user-images.githubusercontent.com/28303754/27992703-e8043334-64cc-11e7-8660-52252a097a03.png)![lime](https://user-images.githubusercontent.com/28303754/27992704-e8082bba-64cc-11e7-8806-e63029218112.png)![magenta](https://user-images.githubusercontent.com/28303754/27992705-e844315a-64cc-11e7-9170-980617328972.png)![orange](https://user-images.githubusercontent.com/28303754/27992706-e8560c36-64cc-11e7-83d6-40c0a3cca5d6.png)![pink](https://user-images.githubusercontent.com/28303754/27992692-c40b233e-64cc-11e7-8669-be394bd1e928.png)![purple](https://user-images.githubusercontent.com/28303754/27992693-c41401e8-64cc-11e7-8eeb-37be234cf8c0.png)![red](https://user-images.githubusercontent.com/28303754/27992694-c4492a30-64cc-11e7-9eb4-7878f7fccb62.png)![silver](https://user-images.githubusercontent.com/28303754/27992695-c44a0536-64cc-11e7-8204-701186efb481.png)![white](https://user-images.githubusercontent.com/28303754/27992697-c53728fc-64cc-11e7-89ff-9b1fffd89ecf.png)![yellow](https://user-images.githubusercontent.com/28303754/27992699-c5e7d60c-64cc-11e7-8f1c-0c36ce4f949f.png)

**Comment by chengzzi89** [comment]
new bed
![black](https://user-images.githubusercontent.com/28303754/27992944-501a0750-64d2-11e7-9541-6bdb9e5cabbf.png)![blue](https://user-images.githubusercontent.com/28303754/27992942-5019b3ea-64d2-11e7-9fcf-3c42845e8160.png)![brown](https://user-images.githubusercontent.com/28303754/27992945-501a56e2-64d2-11e7-86af-8460b023c2e0.png)![cyan](https://user-images.githubusercontent.com/28303754/27992943-5019db68-64d2-11e7-9a36-be96756f6785.png)
![gray](https://user-images.githubusercontent.com/28303754/27992947-502df620-64d2-11e7-9baa-d98c627ac3b0.png)![green](https://user-images.githubusercontent.com/28303754/27992946-501e0b20-64d2-11e7-9d8b-c3e0d0c2546c.png)![light_blue](https://user-images.githubusercontent.com/28303754/27992948-50525dd0-64d2-11e7-85b0-61b23299e444.png)![lime](https://user-images.githubusercontent.com/28303754/27992949-50534aba-64d2-11e7-9df3-b6765320e927.png)
![magenta](https://user-images.githubusercontent.com/28303754/27992950-50537c6a-64d2-11e7-8c17-9c2c17321301.png)![orange](https://user-images.githubusercontent.com/28303754/27992951-5053e966-64d2-11e7-8e1e-e8409a474da3.png)![pink](https://user-images.githubusercontent.com/28303754/27992952-505668c6-64d2-11e7-950a-a00cb9b75f17.png)![purple](https://user-images.githubusercontent.com/28303754/27992953-5064d424-64d2-11e7-93b8-6f40eff8f76d.png)
![red](https://user-images.githubusercontent.com/28303754/27992954-508964d8-64d2-11e7-82d7-866670186117.png)![silver](https://user-images.githubusercontent.com/28303754/27992955-508b1864-64d2-11e7-8652-402109fbb7ac.png)![white](https://user-images.githubusercontent.com/28303754/27992956-508ccf06-64d2-11e7-9ea1-dbff49045a92.png)![yellow](https://user-images.githubusercontent.com/28303754/27992957-508cf72e-64d2-11e7-9d42-833ce36a8790.png)

**Comment by tobyplowy** [comment]
@chengzzi89 yup looks good
