### ISSUE TITLE
Red ≠ Yellow

### ISSUE THREAD

**Issue by garlicy** [SummerFields/SummerFields#336]
Why are the Red Bricks Yellow in SummerFields resource packs?
![2017-07-23_09 07 51](https://user-images.githubusercontent.com/29414200/28497110-1fdc4296-6f87-11e7-8254-624cf75fb776.png)
![2017-07-23_09 08 07](https://user-images.githubusercontent.com/29414200/28497111-1fe2cec2-6f87-11e7-8504-20a5b3c1cb26.png)

Doesn't it kill all the Bricks buildings?

**Comment by FlorianDoyen95** [comment]
I change the texture of brick if you want : 

![Uploading brick.png…]()

Bricks building look like this now : 

![2017-08-13_14 05 29](https://user-images.githubusercontent.com/23485756/29249502-e5002c4a-8030-11e7-8cf9-b947ba2abab2.png)
