### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#337]
@lipki are you still here why are you so inpresent?

**Comment by lipki** [comment]
Yes, I am here...
Tell me what is most urgent.

**Comment by tobyplowy** [comment]
@lipki can you help with this?
https://github.com/SummerFields/Summerfields-Minetest/issues/99

**Comment by tobyplowy** [comment]
@lipki also i think you should allow me to merge pull requests and make me collaborator
it will give you less work and i can make sure the minecraft version of summerfields stays updated
(i have already asked this and i got a no but that was in the beginning i have been helping summerfields for over 3 years i think you can trust me)

**Comment by lipki** [comment]
You asked, and I did not say no, I said "I can not find a way" :)
But I'm back in the settings, and I think I have succeeded.
You should be able to do a lot of things now.
Tell me.

3 years ... waw! time passes so quickly :)
I am very happy that you are here, do not doubt it.

**Comment by tobyplowy** [comment]
> But I'm back in the settings, and I think I have succeeded.

I will have to test it whin the next Minecraft version is released :)

> You should be able to do a lot of things now.
> Tell me.

I hope so XD
And I will tell you when I do something :)

> 3 years ... waw! time passes so quickly :)

Yeh it's scary how fast time gos 

> I am very happy that you are here, do not doubt it.

Thanks also I don't :)

**Comment by tobyplowy** [comment]
@lipki they are adding corral to mc

can you make a kelp texure?

**Comment by tobyplowy** [comment]
@lipki I'm having the feeling that you try to leave is that correct?
If so that would be sad but I will keep this pack updated as good as I can!

Also can we get the licence for Summerfields so we can make it open source?
And another question wuld i be allowed to use the textures in a personal project 
(comesial use I don't whant to do that but I just wanted to know)

**Comment by lipki** [comment]
I'm not playing Minecraft, Minetest, or anything at the moment.
And snapshots are rare.

But no, I have no intention of leaving Summerfield.

It's just that it's hard to stay motivated.

But the ads 1.13 and 1.14 make me very happy, and I intend to adapt the Summerfield for its new update.

**Comment by tobyplowy** [comment]
@lipki Ok that's a relief
I was getting scared

**Comment by tobyplowy** [comment]
> It's just that it's hard to stay motivated.

Do you whant motivation well 
know that Everytime there's an update for Minecraft or minetest there's 1000s (more than that) of people waiting for Summerfields to update becouse they love it just like you and me,

that's why we make updates for Summerfields becouse we want to take care of It,
Make sure It Stays Alive 

Look at all the love time and care we have put into Summerfields we do it because we love Summerfields :)

Also thank you for the amazing 3 or 4 years of working together I wouldn't be able to do it without you
To be honest the fact that you are working on Summerfields with me really motivates me :)

Your digital friend tobyplowy :)

**Comment by RobertZenz** [comment]
> It's just that it's hard to stay motivated.

Also keep in mind that Summerfields is a quite awesome texture pack which can also be used for all kind of projects, not just Minecraft/Minetest.

**Comment by tobyplowy** [comment]
@RobertZenz yeh exactly!

**Comment by lipki** [comment]
It's nice,
Well, I contacted lithium sound, I'm sure this time if he will receive the message.
So if he answers me, I will be able to definitively settle this question of license.
If he does not answer, he does not care, which will also settle the problem of license.

**Comment by tobyplowy** [comment]
> If he does not answer, he does not care, which will also settle the problem of license.

Well it's true but we can not just steal Summerfields it's not nice :/

**Comment by tobyplowy** [comment]
I'm making the trapdoor textures

**Comment by tobyplowy** [comment]
slabs are added

**Comment by lipki** [comment]
make a issue for trapdoor

**Comment by tobyplowy** [comment]
Can I do https://github.com/SummerFields/SummerFields/issues/343 

And can you already begin making the new horse textures

**Comment by lipki** [comment]
Do you think they'll keep the new models?
