### ISSUE TITLE
[1.13] renaming all textures

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#338]
They suck, really ...

**Comment by tobyplowy** [comment]
@lipki hahahah yeh

**Comment by lipki** [comment]
I did the renaming.
I have to modify all the models, but minecraft do not want to work anymore, so we'll see tomorrow.

**Comment by lipki** [comment]
I progress in the update of models, it's long.

**Comment by tobyplowy** [comment]
@lipki +1 :)
