### ISSUE TITLE
[1.13] Horses are broken

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#339]
The horse got a new model and with that comes a new texture :/
(The new horse model just looks so bad)

**Comment by tobyplowy** [comment]
It seems People are really Negative about the new model (It Looks terrible I'm my opinion)
The devs are not sure if this will stay so I'm going to wait until I'm sure

**Comment by kingoscargames** [comment]
I hope it wont stay like that. xD

**Comment by tobyplowy** [comment]
@kingoscargames dude what are you doing here 
You are everywhere :/

**Comment by lipki** [comment]
Ok i take that...
yeaah .... :(

**Comment by tobyplowy** [comment]
@lipki yeh I guess the new horse models are here to stay :(
Well to bad, I loved the original model more!

**Comment by lipki** [comment]
And the model is horrible technically.
Certain texture are superimposed.
The legs are all identical, and without symmetry.
The reins are cut off !!

**Comment by lipki** [comment]
![donkey](https://user-images.githubusercontent.com/401965/35398278-c841de26-01f1-11e8-81e3-a25c02fc5b39.png)

![capture du 2018-01-25 16-59-01](https://user-images.githubusercontent.com/401965/35398282-cbb2069e-01f1-11e8-8a59-97274fd81711.png)

**Comment by tobyplowy** [comment]
@lipki Well you did a good job on the texture
But that model tho :/

Wasn't it possible to change mob models with resource packs
I know it's possible to do on the windows 10 edition
Maybe we can add the old model back?

**Comment by lipki** [comment]
Well, I'll do them, but the model is buggy, really!
There is no halter and the bit to the texture of the chest.

**Comment by tobyplowy** [comment]
@lipki thank you, I wouldn't want to be in your situation at this point :)

Best of luck with those horses :)

**Comment by lipki** [comment]
![mule](https://user-images.githubusercontent.com/401965/35401257-48c021e6-01f9-11e8-9ec5-122df2cbc697.png)
![capture du 2018-01-25 17-57-13](https://user-images.githubusercontent.com/401965/35401263-4bcf25c6-01f9-11e8-85ec-d6ccb3252706.png)

**Comment by lipki** [comment]
![horse_zombie](https://user-images.githubusercontent.com/401965/35402848-0a8e60d6-01fe-11e8-807b-0f9d6fed8cfb.png)
![capture du 2018-01-25 18-30-09](https://user-images.githubusercontent.com/401965/35402853-0ecdf4e0-01fe-11e8-932a-96f7b69b9336.png)

**Comment by lipki** [comment]
![horse_skeleton](https://user-images.githubusercontent.com/401965/35404835-8bb76440-0204-11e8-9842-ba1cc7b71b53.png)
![capture du 2018-01-25 19-17-53](https://user-images.githubusercontent.com/401965/35404839-8ed1f938-0204-11e8-942f-c74bda8329be.png)

**Comment by lipki** [comment]
![horse_white](https://user-images.githubusercontent.com/401965/35407972-d8532a92-020d-11e8-8efc-4dccdc0c71a1.png)

![capture du 2018-01-25 20-21-50](https://user-images.githubusercontent.com/401965/35407983-e1585b3a-020d-11e8-8ee2-715a2420d396.png)

**Comment by lipki** [comment]
![horse_gray](https://user-images.githubusercontent.com/401965/35409554-d789f1f4-0212-11e8-9d50-acdc8af98b41.png)
![capture du 2018-01-25 20-59-19](https://user-images.githubusercontent.com/401965/35409558-d9c2685c-0212-11e8-854a-9e6e9fbcdfc9.png)

**Comment by lipki** [comment]
![horse_brown](https://user-images.githubusercontent.com/401965/35410223-fe62ea54-0214-11e8-8f16-c6f49e44946e.png)
![capture du 2018-01-25 21-14-58](https://user-images.githubusercontent.com/401965/35410229-02d85420-0215-11e8-82e3-22ad8a644ab8.png)

**Comment by tobyplowy** [comment]
@lipki be sure to keep a backup of the old model
Maybe put it in the database

**Comment by lipki** [comment]
With git everything is backed up, we can not lose anything.
example : first gravel 2014
https://github.com/SummerFields/SummerFields/blob/c2db217313263dbc6466fa2036ea8acab46dc1a2/textures/blocks/gravel.png

**Comment by lipki** [comment]
![horse_black](https://user-images.githubusercontent.com/401965/35412355-3c73fab6-021c-11e8-9188-bcd812c8ffdc.png)
![capture du 2018-01-25 21-47-59](https://user-images.githubusercontent.com/401965/35412358-3f278ce6-021c-11e8-8bdb-c2633d1362fb.png)

**Comment by lipki** [comment]
![horse_creamy](https://user-images.githubusercontent.com/401965/35412370-48218f68-021c-11e8-8df3-6014c1ae9637.png)
![capture du 2018-01-25 21-58-54](https://user-images.githubusercontent.com/401965/35412373-4a575d9e-021c-11e8-8f67-78b7c6487922.png)

**Comment by lipki** [comment]
![horse_chestnut](https://user-images.githubusercontent.com/401965/35413106-b1e0fdc4-021e-11e8-885a-2425afe91fb9.png)
![capture du 2018-01-25 22-25-13](https://user-images.githubusercontent.com/401965/35413107-b49c1940-021e-11e8-8c19-d20f01fc9e97.png)

**Comment by lipki** [comment]
![horse_darkbrown](https://user-images.githubusercontent.com/401965/35414085-bc151bc4-0221-11e8-966e-a4ea63c69678.png)
![capture du 2018-01-25 22-46-41](https://user-images.githubusercontent.com/401965/35414088-bed781ee-0221-11e8-8e7f-755b68a45c7b.png)

**Comment by lipki** [comment]
three saddle color.
![capture du 2018-01-25 23-58-59](https://user-images.githubusercontent.com/401965/35417351-4ab3fa2a-022d-11e8-94b4-993c9ffe9301.png)

**Comment by tobyplowy** [comment]
@lipki do I need to chose? 
Or are they all in the game?

I like the one on the most left the most bdw

**Comment by lipki** [comment]
I put the three, depending on the horse.

**Comment by tobyplowy** [comment]
@lipki ooooh ok :)

**Comment by lipki** [comment]
i wait one check in games before merge.

**Comment by lipki** [comment]
Repair in 1.13
So I could finish the armor.

![capture du 2018-06-16 19-38-27](https://user-images.githubusercontent.com/401965/41501049-32e07006-719d-11e8-98f1-5193edfa6abd.png)


![horse_armor_diamond](https://user-images.githubusercontent.com/401965/41501052-3d8e5c5c-719d-11e8-9930-db8cd85f8290.png)![horse_armor_gold](https://user-images.githubusercontent.com/401965/41501053-3db1f202-719d-11e8-92d1-50e06c32134f.png)![horse_armor_iron](https://user-images.githubusercontent.com/401965/41501054-3dd9bc7e-719d-11e8-81d8-b3a7e377974b.png)
