### ISSUE TITLE
[1.13] new trapdoor

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#341]
![acacia_trapdoor](https://user-images.githubusercontent.com/401965/33218432-300c8762-d13d-11e7-85a8-df222d83da25.png)![birch_trapdoor](https://user-images.githubusercontent.com/401965/33218433-302d4088-d13d-11e7-8d72-4ed3a266fca3.png)![dark_oak_trapdoor](https://user-images.githubusercontent.com/401965/33218434-3052d352-d13d-11e7-8df4-c437e030d194.png)![iron_trapdoor](https://user-images.githubusercontent.com/401965/33218435-307265d2-d13d-11e7-90e0-3672c5a52926.png)![jungle_trapdoor](https://user-images.githubusercontent.com/401965/33218436-3094b1d2-d13d-11e7-8241-79c0ac68d0a0.png)![oak_trapdoor](https://user-images.githubusercontent.com/401965/33218437-30dc4588-d13d-11e7-99c3-f13bd3fe6428.png)![spruce_trapdoor](https://user-images.githubusercontent.com/401965/33218438-30fbc4ee-d13d-11e7-8f7c-64ae31cbc606.png)

référence : 
![iron_trapdoor](https://user-images.githubusercontent.com/401965/33218495-74a8ac34-d13d-11e7-8d99-d2e6f38b5be0.png)![iron_trapdoor_side](https://user-images.githubusercontent.com/401965/33218485-6c16251a-d13d-11e7-805a-162fdd76041c.png)
![oak_trapdoor_side](https://user-images.githubusercontent.com/401965/33218486-6c345daa-d13d-11e7-9592-fa54f522184b.png)![oak_trapdoor](https://user-images.githubusercontent.com/401965/33218496-74cef6aa-d13d-11e7-8451-f9500ff78808.png)

**Comment by tobyplowy** [comment]
I have already added them

**Comment by tobyplowy** [comment]
oak_trapdoor
![oak_trapdoor](https://user-images.githubusercontent.com/16853304/33219048-8eb51ee8-d140-11e7-9515-b3c789396812.png)
iron_trapdoor
![iron_trapdoor](https://user-images.githubusercontent.com/16853304/33219049-8ecd5346-d140-11e7-8350-36415ad82b38.png)
jungle_trapdoor
![jungle_trapdoor](https://user-images.githubusercontent.com/16853304/33219050-8ee64a68-d140-11e7-96d2-f0a7c76594af.png)
birch_trapdoor
![birch_trapdoor](https://user-images.githubusercontent.com/16853304/33219051-8efd2abc-d140-11e7-9543-0f35bbe47bc0.png)
spruce_trapdoor
![spruce_trapdoor](https://user-images.githubusercontent.com/16853304/33219052-8f163106-d140-11e7-935b-0edb10b6eab8.png)
dark_oak_trapdoor
![dark_oak_trapdoor](https://user-images.githubusercontent.com/16853304/33219053-8f2d8694-d140-11e7-88af-50a570d0afa6.png)
acacia_trapdoor
![acacia_trapdoor](https://user-images.githubusercontent.com/16853304/33219055-8f514462-d140-11e7-98c3-43bf0ac4aaec.png)

theres no side textures anymore
they removed that

**Comment by lipki** [comment]
Not, the "side textures" are mine, I remake the 3d model.
We must do them.

She are very good these trapdoor.

**Comment by tobyplowy** [comment]
> Not, the "side textures" are mine,

ooooh ok i will make them

**Comment by tobyplowy** [comment]
@lipki done

**Comment by chengzzi89** [comment]
😃

**Comment by chengzzi89** [comment]
So painful! I actually can not upload images!😖😣

**Comment by tobyplowy** [comment]
@chengzzi89 Yes You can Just drag and Drop The png files in the text box 

Also you can click the blue text above comment to chose a file

**Comment by chengzzi89** [comment]
![spruce_trapdoor](https://user-images.githubusercontent.com/28303754/33232370-4baf960e-d240-11e7-9477-f371d4e14b3d.png)![spruce_trapdoor_side](https://user-images.githubusercontent.com/28303754/33232375-54d2b8f6-d240-11e7-99f7-f9f9884bcfc6.png)
@tobyplowy  This is my design, my other trapdoor texture and your idea is the same!

**Comment by tobyplowy** [comment]
@chengzzi89 i like my own texture more but yours is fine

@lipki what do you think?
