### ISSUE TITLE
[1.12] java edition logo

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#342]
edition logo
![edition](https://user-images.githubusercontent.com/16853304/33219320-e8fa3496-d141-11e7-9c59-3d35df828447.png)

i whant to try to make this first if thats ok

**Comment by lipki** [comment]
yep

**Comment by tobyplowy** [comment]
how is this
![edition](https://user-images.githubusercontent.com/16853304/33220623-0aefa16e-d14a-11e7-9ffb-b82c576adc77.png)

**Comment by kingoscargames** [comment]
" [1.13] java edition logo"  its actually used in 1.12.2 :p

**Comment by lipki** [comment]
And if we put the name of the game in big.
And "summerfields" instead of "java edition"

MINECRAFT
[Summerfields]

**Comment by lipki** [comment]
I will give an example.

**Comment by tobyplowy** [comment]
Good Idea

**Comment by lipki** [comment]
nop, it deserves to be made cleaner, and a better contrast between minecraft and Summerfields.
It is difficult to distinguish it.

It can still wait for 1.13.2.
