### ISSUE TITLE
Update 1.14 Update Aquatic 

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#345]
It's not released yet but I already have made this issue so we can work on it

First is dolphins I can remake the model and we can already make a texture :)
![update_aquatic_teaser](https://user-images.githubusercontent.com/16853304/33231580-ac4f411a-d1f7-11e7-8d30-ab6f7ddd95c0.jpeg)

> Coral[3], new decorative block, clusters of which generate in warm ocean biomes as coral reefs. At least four color variations were shown: white, dark purple, magenta and yellow. Stairs and slabs are also presented.

Coral will be added this will get 4 variants (maybe we can use the minetest texture for this?)

Normal stone stairs will also be added so we may make a new texture for that (just like the stone slab)

> Kelp[4], new underwater plant. It seems like there are many types of it: some are small, reddish and yellowish bushes, some are green and can stretch up for dozens of blocks, even reaching surface level - this variation even has an animation of "leaves moving with current".

Kelp will be added (I made a texture for kelp in minetest maybe we can use that?)

Also small sea plants 

Also they will add fish that you can pick up in a bukket (so those items will probably also have a texture)
![screenshot_20171125-155229](https://user-images.githubusercontent.com/16853304/33231649-5a80b1f0-d1f9-11e7-9748-7063a924a8b9.png)

And a terrible image of the trident :)
![screenshot_20171125-155012](https://user-images.githubusercontent.com/16853304/33231653-60be0d1a-d1f9-11e7-9a08-be46f4543182.png)

**Comment by chengzzi89** [comment]
@tobyplowy Underwater world blocks and dolphins need to work?

**Comment by tobyplowy** [comment]
@chengzzi89 I don't really understand what you are saying in the above comment :/

Are you asking if you can work on this?
Or are you saying that they have to work?

**Comment by chengzzi89** [comment]
@tobyplowy  My point is to start designing the texture of 1.14?😶

**Comment by tobyplowy** [comment]
@chengzzi89 ok yes that's good let's split the work

**Comment by tobyplowy** [comment]
my kelp texture (NOTE i mostly made it as placeholder)
![default_kelp](https://user-images.githubusercontent.com/16853304/33239755-03f461d2-d2a9-11e7-955b-b9e5f4bc7f31.png)

**Comment by lipki** [comment]
This update merges with 1.13, and is scheduled for spring.

**Comment by tobyplowy** [comment]
@lipki closed because update aquatic aka 1.14 will merge with 1.13
