### ISSUE TITLE
[1.13] pressure plate

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#346]

**Comment by lipki** [comment]
![acacia_pressure_plate](https://user-images.githubusercontent.com/401965/33245362-3bb00e24-d307-11e7-888c-c415b5502623.png)![birch_pressure_plate](https://user-images.githubusercontent.com/401965/33245363-3bd5e522-d307-11e7-8f28-1de305c2be8d.png)![dark_oak_pressure_plate](https://user-images.githubusercontent.com/401965/33245364-3bf4b9c0-d307-11e7-8625-585a0a507719.png)![gold_pressure_plate](https://user-images.githubusercontent.com/401965/33245365-3c16c286-d307-11e7-9b6a-2e7a19344a87.png)![iron_pressure_plate](https://user-images.githubusercontent.com/401965/33245366-3c35fb74-d307-11e7-86a8-590658d65fbd.png)![jungle_pressure_plate](https://user-images.githubusercontent.com/401965/33245367-3c53f962-d307-11e7-895c-3ce52cc724e4.png)![oak_planks](https://user-images.githubusercontent.com/401965/33245368-3c892858-d307-11e7-9df3-cea6599e3a95.png)![oak_pressure_plate](https://user-images.githubusercontent.com/401965/33245369-3ca8ae08-d307-11e7-9c37-cd38c34e1238.png)![spruce_pressure_plate](https://user-images.githubusercontent.com/401965/33245370-3cc60584-d307-11e7-9bc0-75a90bd0cd51.png)![stone_pressure_plate](https://user-images.githubusercontent.com/401965/33245371-3ce29c94-d307-11e7-93ef-f02f698a9da9.png)

![capture du 2017-11-27 00-09-58](https://user-images.githubusercontent.com/401965/33245390-7708cdd0-d307-11e7-81fb-9eb219f4ed1e.png)

**Comment by lipki** [comment]
![acacia_pressure_plate](https://user-images.githubusercontent.com/401965/33245362-3bb00e24-d307-11e7-888c-c415b5502623.png)![birch_pressure_plate](https://user-images.githubusercontent.com/401965/33245363-3bd5e522-d307-11e7-8f28-1de305c2be8d.png)![dark_oak_pressure_plate](https://user-images.githubusercontent.com/401965/33245364-3bf4b9c0-d307-11e7-8625-585a0a507719.png)![gold_pressure_plate](https://user-images.githubusercontent.com/401965/33245365-3c16c286-d307-11e7-9b6a-2e7a19344a87.png)![iron_pressure_plate](https://user-images.githubusercontent.com/401965/33245366-3c35fb74-d307-11e7-86a8-590658d65fbd.png)![jungle_pressure_plate](https://user-images.githubusercontent.com/401965/33245367-3c53f962-d307-11e7-895c-3ce52cc724e4.png)![oak_planks](https://user-images.githubusercontent.com/401965/33245368-3c892858-d307-11e7-9df3-cea6599e3a95.png)![oak_pressure_plate](https://user-images.githubusercontent.com/401965/33245369-3ca8ae08-d307-11e7-9c37-cd38c34e1238.png)![spruce_pressure_plate](https://user-images.githubusercontent.com/401965/33245370-3cc60584-d307-11e7-9bc0-75a90bd0cd51.png)![stone_pressure_plate](https://user-images.githubusercontent.com/401965/33245371-3ce29c94-d307-11e7-93ef-f02f698a9da9.png)

![capture du 2017-11-27 00-09-58](https://user-images.githubusercontent.com/401965/33245390-7708cdd0-d307-11e7-81fb-9eb219f4ed1e.png)

**Comment by lipki** [comment]
![acacia_pressure_plate](https://user-images.githubusercontent.com/401965/33245883-2a57a0c2-d30e-11e7-8fbc-27d6ea03ac19.png)![birch_pressure_plate](https://user-images.githubusercontent.com/401965/33245884-2a7c35e0-d30e-11e7-95b4-45f83c7b6782.png)![dark_oak_pressure_plate](https://user-images.githubusercontent.com/401965/33245885-2aa0f3da-d30e-11e7-8752-227da6ea8a78.png)![gold_pressure_plate](https://user-images.githubusercontent.com/401965/33245886-2ac60bb6-d30e-11e7-9764-5cef227e7865.png)![iron_pressure_plate](https://user-images.githubusercontent.com/401965/33245887-2aeaa390-d30e-11e7-8b8b-46d1ee5d5a45.png)![stone_pressure_plate](https://user-images.githubusercontent.com/401965/33245888-2b0b3d08-d30e-11e7-947e-6b497b34f0e0.png)

![capture du 2017-11-27 00-55-59](https://user-images.githubusercontent.com/401965/33245881-13e977e8-d30e-11e7-9ab5-ad4a537e5377.png)

**Comment by tobyplowy** [comment]
@lipki I like the second picture more

But the stone pressure plate on the first picture is better

**Comment by lipki** [comment]
I hesitate in fact, between pressure plate well visible, and pressure plate well hiding in the ground.

**Comment by tobyplowy** [comment]
@lipki well jeh makeing them hard to see is a good idea but on the other hand you still have to know they are there I like the second image more :)

**Comment by CuddleWoozle** [comment]
I like the second group as well.

They're both really nice, though.  (Maybe add the others to the database as alts for those who want them?)

**Comment by chengzzi89** [comment]
@lipki  Excuse me, do we want to record a SummerFields texture documentary?😀

**Comment by tobyplowy** [comment]
@chengzzi89 I think that's a good idea

**Comment by lipki** [comment]
What do you mean by that?
