### ISSUE TITLE
Making a texture database on GitHub

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#347]
What if we made a texture database on GitHub that wuld be here https://github.com/SummerFields
This would be a place to store all our textures for Minecraft and minetest and mods and future projects 
(if we make any)

It wuld provide a easy way to access all our textures

**Comment by lipki** [comment]
?
It's already done ...

**Comment by lipki** [comment]
I think I did not understand, maybe you can make an example.

**Comment by tobyplowy** [comment]
Basically put all Summerfields textures in one repo on GitHub the current texture database is not very grate how good does the current database work?

I think we need a better texture database

**Comment by RobertZenz** [comment]
@lipki I think what @tobyplowy is suggesting is to gather *all* textures made (and being made) under one repository, as one single, big source which can be used for various projects easily. The Minecraft texture pack would then result from this single repository by using certain textures (hand picked).

**Comment by tobyplowy** [comment]
@RobertZenz yes correct

**Comment by lipki** [comment]
I tried to do that:
  http://ref.summerfields.info/
But I was not satisfied with the tool used.

**Comment by tobyplowy** [comment]
@lipki We just need a better texture database

**Comment by tobyplowy** [comment]
@lipki can one be added on the website

**Comment by lipki** [comment]
Ok we will try.
How do you see the file tree.

**Comment by lipki** [comment]
https://github.com/SummerFields/DataBase

**Comment by tobyplowy** [comment]
@lipki ok good

**Comment by tobyplowy** [comment]
@lipki this my also be considerd 
https://github.com/SummerFields/official/issues/16

**Comment by tobyplowy** [comment]
also the databace may need nameing guidelines 

for example steel_trapdoor shuld be steel trapdoor
and default_dirt shuld just be dirt is that ok like that?

**Comment by lipki** [comment]
proposition 1 : by texture

```
textures
├ blocks
│├ oak_planks
││├ oak_plank_v1.png
││└ oak_plank_v2.png
│├ end_stone.png (juste one texture)
││...
├ items
││...
├ entity
││...
|...
```

proposition 2 : by theme

```
textures
├ wood
│├ oak
││├ oak_planks
│││├ oak_plank_v1.png
│││└ oak_plank_v2.png
││...
├ end
│├ stone
││├ end_stone.png (juste one texture)
││...
|...
```

**Comment by RobertZenz** [comment]
By theme, I'd say, much easier to navigate.

**Comment by tobyplowy** [comment]
@lipki Yes I also like by theme more

**Comment by tobyplowy** [comment]
So it's settled can we begin

**Comment by lipki** [comment]
yep makes a pull request if you already have something.

**Comment by lipki** [comment]
https://github.com/orgs/SummerFields/teams/global-manager/discussions/2
