### ISSUE TITLE
new background

### ISSUE THREAD

**Issue by chengzzi89** [SummerFields/SummerFields#351]
I re-made a background
![panorama_0](https://user-images.githubusercontent.com/28303754/34908315-611cbb4e-f8c8-11e7-9ca9-ed4fba6ab40c.png)![panorama_1](https://user-images.githubusercontent.com/28303754/34908317-746700ec-f8c8-11e7-9f04-79dde14037c3.png)![panorama_2](https://user-images.githubusercontent.com/28303754/34908324-86a3d280-f8c8-11e7-8cae-65c379134fd0.png)![panorama_3](https://user-images.githubusercontent.com/28303754/34908329-99c9943a-f8c8-11e7-89bb-29ed6cf96107.png)
![panorama_4](https://user-images.githubusercontent.com/28303754/34908335-b36f0c08-f8c8-11e7-8f69-ef7be2ccc679.png)![panorama_5](https://user-images.githubusercontent.com/28303754/34908339-b997d7a4-f8c8-11e7-9e3f-d46922726b0f.png)
![1515805013015](https://user-images.githubusercontent.com/28303754/34908343-cdeb53b6-f8c8-11e7-84aa-c7c239314888.png)

**Comment by tobyplowy** [comment]
@chengzzi89 No shaders?

**Comment by chengzzi89** [comment]
@tobyplowy Yesterday morning, temporarily done, if not satisfied I can re-create!😃

**Comment by tobyplowy** [comment]
@chengzzi89 Can you re do it with shaders on?

I recommend Sonic Ether's Unbelievable Shaders

**Comment by chengzzi89** [comment]
@tobyplowy OK😊

**Comment by chengzzi89** [comment]
@tobyplowy Shader and Render360 can not have both! Would like to open the shader will lose Render function, open the Render360 lost shader function! I feel helpless!😞

**Comment by chengzzi89** [comment]
![2018-01-15_12 26 23_2](https://user-images.githubusercontent.com/28303754/34927902-ba2f56d8-f9f4-11e7-98c9-da38c93bebff.png)
![2018-01-15_12 15 00_2](https://user-images.githubusercontent.com/28303754/34927918-cfe7c9b0-f9f4-11e7-8242-9568fd71de4f.png)
![2018-01-15_12 30 23_2](https://user-images.githubusercontent.com/28303754/34928108-51a50480-f9f6-11e7-936a-572d06ebb981.png)

**Comment by tobyplowy** [comment]
@chengzzi89 I like the pumpkin guy alot :)

Can you make more pictures maybe one of the desert and somewhere where you can see the ocean and land?

But I think that the pumpkin in day one looks amazing

**Comment by lipki** [comment]
Me too I love the scarecrow :)
It's very much in the Summerfield spirit

**Comment by lipki** [comment]
@chengzzi89 
Can you make a underwater background ?

**Comment by chengzzi89** [comment]
@lipki Ok, no problem!😄

**Comment by chengzzi89** [comment]
@lipki Ok, no problem!😄

**Comment by tobyplowy** [comment]
@chengzzi89 Here's a little reminder :D

**Comment by tobyplowy** [comment]
@lipki Just the scarecrow makes me sad... it reminds me of a friend that left me.

**Comment by tobyplowy** [comment]
@lipki done?
