### ISSUE TITLE
[1.13] Kelp

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#356]
![dried_kelp](https://user-images.githubusercontent.com/401965/36286182-d6440f58-12ae-11e8-9aac-76890bf80b2e.png)![kelp](https://user-images.githubusercontent.com/401965/36286183-d66febfa-12ae-11e8-9d85-cc4aa36dab7e.png)

![dried_kelp_bottom](https://user-images.githubusercontent.com/401965/36285798-534f8d94-12ad-11e8-85c3-7b034352113c.png)![dried_kelp_side](https://user-images.githubusercontent.com/401965/36285799-537a0d76-12ad-11e8-8a0c-950d58933d7d.png)![dried_kelp_side_mirror](https://user-images.githubusercontent.com/401965/36285800-539f8510-12ad-11e8-938e-32d7b521df41.png)![dried_kelp_top](https://user-images.githubusercontent.com/401965/36285801-53cca9be-12ad-11e8-8f42-5c39e22e191a.png)

![kelp_plant](https://user-images.githubusercontent.com/401965/37063803-ed877be6-219a-11e8-8e76-4f64a4cf640f.png)![kelp_top](https://user-images.githubusercontent.com/401965/37063804-eda2d288-219a-11e8-8d17-5bf35863e11b.png)

**Comment by lipki** [comment]
![capture du 2018-02-17 03-23-01](https://user-images.githubusercontent.com/401965/36337229-186bb474-1392-11e8-95da-b5c6e32d67d6.png)
![kelp_plant](https://user-images.githubusercontent.com/401965/36337226-144c0c5e-1392-11e8-87e6-f8fa710776db.png)![kelp_top](https://user-images.githubusercontent.com/401965/36337227-14753f34-1392-11e8-98e1-4d64bc4495b8.png)

**Comment by chengzzi89** [comment]
![dried_kelp](https://user-images.githubusercontent.com/28303754/37561311-699c3476-2a86-11e8-9361-2d36ec10f995.png)![kelp](https://user-images.githubusercontent.com/28303754/37561313-765bb1e6-2a86-11e8-9b0d-7e4bf63c990e.png)

**Comment by tobyplowy** [comment]
@lipki @chengzzi89 kelp block still needs to be done

**Comment by lipki** [comment]
done

**Comment by chengzzi89** [comment]
![dried_kelp_side_mirror](https://user-images.githubusercontent.com/28303754/41435980-00fe6958-7053-11e8-8a92-bf52b404202e.png)![dried_kelp_top](https://user-images.githubusercontent.com/28303754/41435983-0243fca6-7053-11e8-9e26-c0dee38a74a1.png)

**Comment by chengzzi89** [comment]
@lipki Your kelp is cool ;)

**Comment by lipki** [comment]
Your as well.
@tobyplowy  you choose !?

**Comment by tobyplowy** [comment]
@lipki I like your top more but I don't like the side bucouse it's a Junglewood recolor XD

**Comment by tobyplowy** [comment]
The strings look like strings so I guess that's fine :)

**Comment by tobyplowy** [comment]
@lipki I like it

**Comment by chengzzi89** [comment]
@lipki perfect!
