### ISSUE TITLE
[1.13] Turtle

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#359]
![scute](https://user-images.githubusercontent.com/401965/36286206-f21a01e2-12ae-11e8-8f4f-95ca67410659.png)![turtle_helmet](https://user-images.githubusercontent.com/401965/36286211-031488be-12af-11e8-92b4-f8bb20bde201.png)

![turtle_layer_1](https://user-images.githubusercontent.com/401965/36286254-2f96c258-12af-11e8-85c2-b40e45046d6a.png)

![turtle_egg_not_cracked](https://user-images.githubusercontent.com/401965/36285988-f88f5230-12ad-11e8-9b05-5093051fb746.png)![turtle_egg_slightly_cracked](https://user-images.githubusercontent.com/401965/36285989-f8b87c1e-12ad-11e8-9f73-bf1fe2ecaf10.png)![turtle_egg_very_cracked](https://user-images.githubusercontent.com/401965/36285990-f8e14b12-12ad-11e8-8c75-9862aa219511.png)
![turtle_egg](https://user-images.githubusercontent.com/401965/39815602-d0b8afd2-5398-11e8-8959-2bcc2334e76d.png)

![big_sea_turtle](https://user-images.githubusercontent.com/401965/36286001-0e1ec266-12ae-11e8-8267-361110147e4e.png)

**Comment by tobyplowy** [comment]
turtle_egg_not_cracked.png

![turtle_egg_not_cracked](https://user-images.githubusercontent.com/16853304/36287501-9f8f66d6-12b5-11e8-8f73-495ea801491d.png)

**Comment by tobyplowy** [comment]
@lipki you do the turtle and i do the turtle hat and eggs

**Comment by tobyplowy** [comment]
yes

**Comment by lipki** [comment]
if you want to do it, go there.

**Comment by lipki** [comment]
For the turtle helmet, I imagined doing a mask to dive or something like that.
What do you think ?
Something like that.
http://www.fanrek.com/media/catalog/product/cache/1/image/29b82db22504fb0479cf1248d4fc542c/m/o/mortal_kombat_x_cosplay_sub_zero_mask2.jpg

**Comment by tobyplowy** [comment]
Yeh that's cool

But the item is called turtle hat can we change that name with texturepacks in vanilla?

**Comment by lipki** [comment]
It must look like a turtle shell.

**Comment by tobyplowy** [comment]
Ok I see

**Comment by lipki** [comment]
![capture du 2018-02-19 00-39-31](https://user-images.githubusercontent.com/401965/36368762-0ea20ea2-1559-11e8-8473-b2d3e2fc9222.png)
![big_sea_turtle](https://user-images.githubusercontent.com/401965/36368776-22411e9e-1559-11e8-8f5d-7208f36d3bd8.png)

**Comment by lipki** [comment]
![turtle_egg_slightly_cracked](https://user-images.githubusercontent.com/401965/36369283-075b9242-155b-11e8-8831-89ca5bd6ff1c.png)![turtle_egg_very_cracked](https://user-images.githubusercontent.com/401965/36369284-079dfc72-155b-11e8-9e71-c6c5e67b2555.png)

**Comment by tobyplowy** [comment]
turtle_shell_piece.png
![turtle_shell_piece](https://user-images.githubusercontent.com/16853304/36383016-23e65c00-158b-11e8-91e2-1b64ed401474.png)

(its not super good but its reasonable)

**Comment by tobyplowy** [comment]
turtle_layer_1.png
![turtle_layer_1](https://user-images.githubusercontent.com/16853304/36385510-0b3e77fc-1593-11e8-8172-608ce7e10ece.png)

**Comment by tobyplowy** [comment]
@lipki you will have to do the item 
im not good at 3d like that

**Comment by lipki** [comment]
I think I have an inkscape file to do the 3d armor items.

**Comment by lipki** [comment]
update 18w19a

**Comment by lipki** [comment]
![turtle_egg](https://user-images.githubusercontent.com/401965/41439716-1e1b83e4-702c-11e8-9177-5ba881b60e49.png)

**Comment by lipki** [comment]
I tried to make a new turtle helmet, what do you think?
![capture du 2018-06-14 23-37-45](https://user-images.githubusercontent.com/401965/41439719-245de382-702c-11e8-82b8-6894b65a95fc.png)
![turtle_layer_1](https://user-images.githubusercontent.com/401965/41439736-377557b6-702c-11e8-9090-122e40b1c1e7.png)

**Comment by lipki** [comment]
![turtle_helmet](https://user-images.githubusercontent.com/401965/41441148-a6067d7c-7031-11e8-8180-4e988c67c7e1.png)
