### ISSUE TITLE
[1.13] Phantom (mob B)

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#360]
![phantom](https://user-images.githubusercontent.com/401965/37063828-07dcff48-219b-11e8-91ae-e99d74471b67.png)![phantom_eyes](https://user-images.githubusercontent.com/401965/37063833-0a7c7f1c-219b-11e8-9974-4258551c96d8.png)
![phantom_membrane](https://user-images.githubusercontent.com/401965/38338184-b9b7d38a-3868-11e8-9909-3bc1875f2909.png)

**Comment by lipki** [comment]
First try.
![capture du 2018-02-16 20-41-27](https://user-images.githubusercontent.com/401965/36326089-3201a00c-135a-11e8-988b-c81bf679def4.png)
![phantom](https://user-images.githubusercontent.com/401965/36326099-389fd5e6-135a-11e8-8a08-c1fec8fd9b3f.png)

**Comment by tobyplowy** [comment]
@lipki nice i like the mantaray consept

**Comment by lipki** [comment]
![capture du 2018-02-16 21-07-33](https://user-images.githubusercontent.com/401965/36327109-d5272cc2-135d-11e8-9b2d-42d5c42cc912.png)

**Comment by tobyplowy** [comment]
@lipki i added more texture to the top of the wings

![image](https://user-images.githubusercontent.com/16853304/36328060-0b3ffeee-1361-11e8-8dcd-908656c88422.png)
un compresed
![phantom](https://user-images.githubusercontent.com/16853304/36328091-24b23c3e-1361-11e8-84e7-1f93985d2ff5.png)

compressed
![phantom](https://user-images.githubusercontent.com/16853304/36328069-0f314cf6-1361-11e8-91f6-705ae5c03e89.png)

**Comment by lipki** [comment]
It's nice to add details, but I think it's too much bat wing.

**Comment by tobyplowy** [comment]
@lipki yeh true :/

**Comment by lipki** [comment]
![phantom](https://user-images.githubusercontent.com/401965/37284103-9ca97f6c-25fa-11e8-9719-e042fe8a8c2b.png)![phantom_eyes](https://user-images.githubusercontent.com/401965/37284104-9d1dfe14-25fa-11e8-9102-a4426eee57cf.png)

I stay on the same model while waiting better.
I just place the skeleton shape on the bright layer of the eyes.

![capture du 2018-03-12 13-36-46](https://user-images.githubusercontent.com/401965/37284162-cac4a3f4-25fa-11e8-9461-eeab57a309e7.png)

**Comment by lipki** [comment]
Quickly done, Poorly done, Membrane.
![phantom_membrane](https://user-images.githubusercontent.com/401965/41039842-f667dc9a-699a-11e8-8c7f-612957e6a1bb.png)
![phantom_membrane](https://user-images.githubusercontent.com/401965/41040243-1e7e731e-699c-11e8-91d5-11da95cd5ecb.png)
