### ISSUE TITLE
new magma cube

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#374]
the texture of the magma cube is buggy since a lot of version.

![capture du 2018-02-21 20-43-12](https://user-images.githubusercontent.com/401965/36501726-2676cef0-1748-11e8-9aa8-2d7fdb73e960.png)

Here is 4 proposal.

![magmacube](https://user-images.githubusercontent.com/401965/36501625-e9372350-1747-11e8-979b-a071da850516.png)
![magmacube2](https://user-images.githubusercontent.com/401965/36501626-e95d6a06-1747-11e8-8026-1762f0f32f1f.png)
![magmacube3](https://user-images.githubusercontent.com/401965/36501627-e97fe144-1747-11e8-9b1e-fa3d975a1478.png)
![magmacube4](https://user-images.githubusercontent.com/401965/36501628-e9a55546-1747-11e8-9b9d-f0dd6ef70641.png)

![capture du 2018-02-21 20-21-28](https://user-images.githubusercontent.com/401965/36501747-39a6a75c-1748-11e8-9c89-bf996d943075.png)

**Comment by tobyplowy** [comment]
https://user-images.githubusercontent.com/401965/36501625-e9372350-1747-11e8-979b-a071da850516.png
I like this one the most
