### ISSUE TITLE
[1.13] Real Fish

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#376]
![cod_mob](https://user-images.githubusercontent.com/401965/36556265-e47b9e14-1804-11e8-9b1c-8e087ff3103d.png)![pufferfish](https://user-images.githubusercontent.com/401965/36556266-e4a3a4ae-1804-11e8-9c49-ba2b345e95dc.png)![salmon_mob](https://user-images.githubusercontent.com/401965/36556267-e4c56df0-1804-11e8-882b-2f83ba1e3784.png)

![clownfish_bucket](https://user-images.githubusercontent.com/401965/36556410-62229f0c-1805-11e8-9115-a5b7d8677e4f.png)![cod_bucket](https://user-images.githubusercontent.com/401965/36556411-628059b2-1805-11e8-8f43-0ad7683023ff.png)![pufferfish_bucket](https://user-images.githubusercontent.com/401965/36556412-62eeaae8-1805-11e8-9a0b-99e8442ad1a7.png)![salmon_bucket](https://user-images.githubusercontent.com/401965/36556413-632e6052-1805-11e8-9c2b-6392e6c7747b.png)

![fish_pufferfish_raw](https://user-images.githubusercontent.com/401965/36556813-bcffc688-1806-11e8-9ae4-791d23cffbbc.png)

tropical a
![tropical_a](https://user-images.githubusercontent.com/401965/37064013-b8a2a148-219b-11e8-8976-30a98d3c97ca.png)-![tropical_a_pattern_1](https://user-images.githubusercontent.com/401965/37064014-b8bcaa20-219b-11e8-8826-6cbaa5bd0590.png)-![tropical_a_pattern_2](https://user-images.githubusercontent.com/401965/37064015-b8db97d2-219b-11e8-8b5d-76b6c2fb55e9.png)-![tropical_a_pattern_3](https://user-images.githubusercontent.com/401965/37064017-b8f6da56-219b-11e8-952c-42c332bf20e0.png)-![tropical_a_pattern_4](https://user-images.githubusercontent.com/401965/37064018-b910231c-219b-11e8-8c2f-7efe0cdc2a9b.png)-![tropical_a_pattern_5](https://user-images.githubusercontent.com/401965/37064019-b939558e-219b-11e8-9f48-e5c8c5870023.png)-![tropical_a_pattern_6](https://user-images.githubusercontent.com/401965/37064020-b95271b8-219b-11e8-815c-a9dc689be8c5.png)-

tropical b
![tropical_b](https://user-images.githubusercontent.com/401965/37064073-de759470-219b-11e8-8f62-faee5aa53085.png)-![tropical_b_pattern_1](https://user-images.githubusercontent.com/401965/37064074-dec17110-219b-11e8-93d5-a6c942e7b74b.png)-![tropical_b_pattern_2](https://user-images.githubusercontent.com/401965/37064076-dedc73de-219b-11e8-9bcc-d7a9d3a45dfd.png)-![tropical_b_pattern_3](https://user-images.githubusercontent.com/401965/37064077-def65ef2-219b-11e8-8656-a182e6850133.png)-![tropical_b_pattern_4](https://user-images.githubusercontent.com/401965/37064078-df297468-219b-11e8-95ca-da1b877c9021.png)-![tropical_b_pattern_6](https://user-images.githubusercontent.com/401965/37064079-df45fd0e-219b-11e8-94db-d301c9901575.png)-

ref :   
![salmon](https://user-images.githubusercontent.com/401965/36556885-f74dbdcc-1806-11e8-997a-6ef87cb0e854.png)![cod](https://user-images.githubusercontent.com/401965/36556896-fe01546c-1806-11e8-8db5-1cefae0ff2a5.png)![clownfish](https://user-images.githubusercontent.com/401965/36556921-1172eec0-1807-11e8-8b1b-aa54096d45cb.png)![pufferfish](https://user-images.githubusercontent.com/401965/36556904-07eb43c0-1807-11e8-806e-106b9f3da4cd.png)
![bucket](https://user-images.githubusercontent.com/401965/36556942-1ed23b52-1807-11e8-92fa-d444bc27c7b6.png)![water_bucket](https://user-images.githubusercontent.com/401965/36556943-1ef490e4-1807-11e8-951c-bcb1b9ce29c6.png)

**Comment by lipki** [comment]
I leave them to you.

**Comment by lipki** [comment]
You can change the original fish if needed.

**Comment by tobyplowy** [comment]
@lipki yep ok I will do them

**Comment by tobyplowy** [comment]
pufferfish done now doing the other 2
![pufferfish](https://user-images.githubusercontent.com/16853304/36595620-236b144e-18a3-11e8-99d5-c6f7902b7b11.png)

**Comment by tobyplowy** [comment]
@kingoscargames dude

**Comment by kingoscargames** [comment]
what?

**Comment by tobyplowy** [comment]
@kingoscargames lol your just waiting non stop for updates are you XD

**Comment by lipki** [comment]
It's great, that's exactly it ...
Bravo !

**Comment by chengzzi89** [comment]
![https://github.com/SummerFields/SummerFields/issues/3763](https://user-images.githubusercontent.com/28303754/36639680-2eecea76-1a4d-11e8-9ca5-ac8933b1130b.png)
![2](https://user-images.githubusercontent.com/28303754/36639712-b2bf8962-1a4d-11e8-8589-fbfabb83dd9a.png)
![1](https://user-images.githubusercontent.com/28303754/36639718-c14a7410-1a4d-11e8-91ce-4d3bb5377f5f.png)
![4](https://user-images.githubusercontent.com/28303754/36639698-66e550e4-1a4d-11e8-9ade-bdeb56cba4a7.png)

**Comment by chengzzi89** [comment]
@tobyplowy I do the barrel of fish do not know can not!😅😅

**Comment by tobyplowy** [comment]
salmon
![image](https://user-images.githubusercontent.com/16853304/36786995-c4a46f02-1c88-11e8-90bb-77bbe2288e43.png)
![salmon_mob](https://user-images.githubusercontent.com/16853304/36787002-cb069320-1c88-11e8-84b5-8329984283a1.png)

**Comment by tobyplowy** [comment]
cod
![image](https://user-images.githubusercontent.com/16853304/36788381-0326c9fa-1c8e-11e8-8f03-fdc9061922b4.png)
![cod_mob](https://user-images.githubusercontent.com/16853304/36788372-fd02121e-1c8d-11e8-87ff-649d825fdf2a.png)

**Comment by tobyplowy** [comment]
@lipki done ;D

**Comment by chengzzi89** [comment]
@lipki  @tobyplowy Java Edition 18w09a is officially out and includes Underwater Ruins and Coral Blocks which come in 5 different colours! Read more here: https://t.co/H9073eqeMg :D https://t.co/PsZfQU1uAe
![img_20180302_000437](https://user-images.githubusercontent.com/28303754/36855775-5db21b46-1daf-11e8-927f-30f33f415aaf.jpg)

**Comment by lipki** [comment]
you'r cod is wonderful !
salmon to.

**Comment by tobyplowy** [comment]
@lipki thanks :)

**Comment by lipki** [comment]
update tropical fish

**Comment by lipki** [comment]
basique

![tropical_a](https://user-images.githubusercontent.com/401965/37117746-6869e044-2252-11e8-9243-9b73d990d073.png)![tropical_a_pattern_1](https://user-images.githubusercontent.com/401965/37117748-688ab814-2252-11e8-9548-a3cc2a298214.png)![tropical_a_pattern_2](https://user-images.githubusercontent.com/401965/37117749-68a4a18e-2252-11e8-9191-f88834f26812.png)![tropical_a_pattern_3](https://user-images.githubusercontent.com/401965/37117750-68c28d70-2252-11e8-9774-20d015ee1dfa.png)![tropical_a_pattern_4](https://user-images.githubusercontent.com/401965/37117751-68e41170-2252-11e8-8126-714fc932bee9.png)![tropical_a_pattern_5](https://user-images.githubusercontent.com/401965/37117752-68ffaa0c-2252-11e8-9d92-90e1ecb2357b.png)![tropical_a_pattern_6](https://user-images.githubusercontent.com/401965/37117753-691db934-2252-11e8-8e9d-abf7641ff44b.png)

![tropical_b](https://user-images.githubusercontent.com/401965/37117754-6939fef0-2252-11e8-9e3f-93a1877f950c.png)![tropical_b_pattern_1](https://user-images.githubusercontent.com/401965/37117755-69597ea6-2252-11e8-9657-8c6b648321c4.png)![tropical_b_pattern_2](https://user-images.githubusercontent.com/401965/37117756-6978fd3a-2252-11e8-8e81-4ab4e9faf9e9.png)![tropical_b_pattern_3](https://user-images.githubusercontent.com/401965/37117757-69940e72-2252-11e8-8f2c-77dac53ed301.png)![tropical_b_pattern_4](https://user-images.githubusercontent.com/401965/37117759-69b0b482-2252-11e8-913c-d333ec54369f.png)![tropical_b_pattern_5](https://user-images.githubusercontent.com/401965/37117760-69cef276-2252-11e8-9f43-74a23bc8cc9f.png)![tropical_b_pattern_6](https://user-images.githubusercontent.com/401965/37117762-69f1d520-2252-11e8-860c-8987f5da5398.png)

![capture du 2018-03-07 19-01-42](https://user-images.githubusercontent.com/401965/37117789-80da3750-2252-11e8-8710-ddbca541d5cb.png)

**Comment by tobyplowy** [comment]
@lipki nice

**Comment by chengzzi89** [comment]
mcpe1.2.14.2 Fish eggs[1.3]  ![egg_clownfish](https://user-images.githubusercontent.com/28303754/38091802-20b72524-3399-11e8-8317-ff1e00412c8a.png)
![egg_fish](https://user-images.githubusercontent.com/28303754/38091806-21cb8e78-3399-11e8-8ea4-18942c4c01b5.png)
![egg_pufferfish](https://user-images.githubusercontent.com/28303754/38091808-22732732-3399-11e8-8a10-712e4c9389a5.png)
![egg_salmon](https://user-images.githubusercontent.com/28303754/38091809-22bc3404-3399-11e8-8232-6dd86aad254a.png)
![1522332625632](https://user-images.githubusercontent.com/28303754/38094064-57840e22-339f-11e8-8f09-9db4c32165b5.png)
![1522332626090](https://user-images.githubusercontent.com/28303754/38094067-57ef4804-339f-11e8-9653-504007972caa.png)
![1522332625165](https://user-images.githubusercontent.com/28303754/38094068-587d6ecc-339f-11e8-89c4-d7d4f828d946.png)
![1522332625462](https://user-images.githubusercontent.com/28303754/38094071-59162a5e-339f-11e8-9ba0-e2e6b595a691.png)

**Comment by lipki** [comment]
It's not bad, but ... :)

We can do more SummerField, the eggs could be cubic. or other things.

**Comment by chengzzi89** [comment]
@lipki But I still think that the traditional egg is more uniform!😃

**Comment by tobyplowy** [comment]
@lipki 
![38094071-59162a5e-339f-11e8-9ba0-e2e6b595a691](https://user-images.githubusercontent.com/16853304/38428510-391a1bf2-39bc-11e8-827e-09b6dca8c94b.png)

**Comment by chengzzi89** [comment]
@tobyplowy so cool! Brighten up!😃🐚🐚

**Comment by chengzzi89** [comment]
@tobyplowy MOJANG is really a joke! Fish egg are now in the mcpe 1.2.20.1 version, change into the traditional kind of egg!😅

**Comment by lipki** [comment]
I guess teams have agreed to leave the old eggs.
