### ISSUE TITLE
[1.13] Coral

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#377]
![blue_coral](https://user-images.githubusercontent.com/401965/37121026-548349da-225c-11e8-948f-8fb20ceca0c3.png)![pink_coral](https://user-images.githubusercontent.com/401965/37121027-54a4966c-225c-11e8-9ab8-c973a564ec27.png)![purple_coral](https://user-images.githubusercontent.com/401965/37121028-54c4432c-225c-11e8-8d5a-c5045460a6f4.png)![red_coral](https://user-images.githubusercontent.com/401965/37121029-54eef34c-225c-11e8-98a8-5d59952dbcd0.png)![yellow_coral](https://user-images.githubusercontent.com/401965/37121030-5513a14c-225c-11e8-84a1-88cfd27a555a.png)
![blue_dead_coral](https://user-images.githubusercontent.com/401965/37121036-5eeaba16-225c-11e8-9848-6cc4d58a47f5.png)![pink_dead_coral](https://user-images.githubusercontent.com/401965/37121037-5f08f24c-225c-11e8-8152-71462da2c054.png)![purple_dead_coral](https://user-images.githubusercontent.com/401965/37121038-5f29ad52-225c-11e8-9e5a-e2d77c52cc19.png)![red_dead_coral](https://user-images.githubusercontent.com/401965/37121039-5f4c2d96-225c-11e8-9744-f6e5134592b2.png)![yellow_dead_coral](https://user-images.githubusercontent.com/401965/37121040-5f6afc08-225c-11e8-9942-bdcb59ecfee7.png)

![blue_coral_plant](https://user-images.githubusercontent.com/401965/37064129-04d6bc52-219c-11e8-9ac6-cfa27e5b51e1.png)![pink_coral_plant](https://user-images.githubusercontent.com/401965/37064131-04f57b7e-219c-11e8-9c57-414f019c8910.png)![purple_coral_plant](https://user-images.githubusercontent.com/401965/37064132-05113fda-219c-11e8-94c8-4a1beb75fa95.png)![red_coral_plant](https://user-images.githubusercontent.com/401965/37064133-052bcf9e-219c-11e8-80f0-d9b7161182b6.png)![yellow_coral_plant](https://user-images.githubusercontent.com/401965/37064135-0546d172-219c-11e8-823d-cb009f5e1930.png)

![blue_coral_fan](https://user-images.githubusercontent.com/401965/37372262-6d44123c-2712-11e8-8e1c-0691871a4856.png)![pink_coral_fan](https://user-images.githubusercontent.com/401965/37372263-6d7313b6-2712-11e8-9735-27b8318da9f5.png)![purple_coral_fan](https://user-images.githubusercontent.com/401965/37372265-6db938c8-2712-11e8-8dbe-1f4b486e2792.png)![red_coral_fan](https://user-images.githubusercontent.com/401965/37372266-6ddebd82-2712-11e8-95c5-ea5b196df66d.png)![yellow_coral_fan](https://user-images.githubusercontent.com/401965/37372267-6e2a87d0-2712-11e8-988e-89ae58ad8e9c.png)

![capture du 2018-03-09 18-12-53](https://user-images.githubusercontent.com/401965/37220919-69040d0a-23c8-11e8-9f1e-29f60f28239b.png)

**Comment by lipki** [comment]
![dead_coral](https://user-images.githubusercontent.com/401965/36871464-a0655834-1da2-11e8-9beb-eeb26c63e294.png)
![blue_coral](https://user-images.githubusercontent.com/401965/36871479-aad56534-1da2-11e8-8ce9-a562e4a7db79.png)![blue_coral_2](https://user-images.githubusercontent.com/401965/36871481-aaf39824-1da2-11e8-9676-21c997b3445f.png)
![pink_coral](https://user-images.githubusercontent.com/401965/36871482-ab116de0-1da2-11e8-8d9c-9e7c79a41fb7.png)![pink_coral_2](https://user-images.githubusercontent.com/401965/36871483-ab5a9d8a-1da2-11e8-991b-4fedc62d06cd.png)
![purple_coral](https://user-images.githubusercontent.com/401965/36871484-ab78d778-1da2-11e8-9bd7-e8d40c9fa974.png)![purple_coral_2](https://user-images.githubusercontent.com/401965/36871486-ab96f546-1da2-11e8-9b11-6a711be42dfc.png)
![red_coral](https://user-images.githubusercontent.com/401965/36871487-abb31a3c-1da2-11e8-8682-56c5e55cf648.png)![red_coral_2](https://user-images.githubusercontent.com/401965/36871488-abe564f6-1da2-11e8-98ac-881ce0f53144.png)
![yellow_coral](https://user-images.githubusercontent.com/401965/36871489-ac070412-1da2-11e8-9833-00282bf66a90.png)![yellow_coral_2](https://user-images.githubusercontent.com/401965/36871490-ac290e68-1da2-11e8-972a-db113ca9f633.png)

I just took the minetest textures, adjusting the colors.
If you can do better, I commit you to it.

**Comment by tobyplowy** [comment]
@lipki yeh the minetest coral textures are good but there's no hue shifting in the recolors

**Comment by tobyplowy** [comment]
@chengzzi89 you interested?

**Comment by lipki** [comment]
![capture du 2018-03-01 23-08-11](https://user-images.githubusercontent.com/401965/36872430-87c69b8c-1da5-11e8-8743-4478a9280fb4.png)

**Comment by lipki** [comment]
![capture du 2018-03-01 23-12-11](https://user-images.githubusercontent.com/401965/36872608-17f26894-1da6-11e8-8c2e-facc60627e05.png)

**Comment by tobyplowy** [comment]
yellow inprovement
![image](https://user-images.githubusercontent.com/16853304/36872712-768fde9a-1da6-11e8-80ba-bc77c0e23bdb.png)
![image](https://user-images.githubusercontent.com/16853304/36872715-788a6a3a-1da6-11e8-9637-b953f37055fa.png)

**Comment by tobyplowy** [comment]
red
![image](https://user-images.githubusercontent.com/16853304/36873060-a4ba0772-1da7-11e8-8e40-c8ba932df2ee.png)
![image](https://user-images.githubusercontent.com/16853304/36873065-a71043c4-1da7-11e8-9896-74133650f571.png)

**Comment by chengzzi89** [comment]
@tobyplowy You draw well!👏

**Comment by lipki** [comment]
update

**Comment by kingoscargames** [comment]
There is more than one "dead coral" version now.

**Comment by tobyplowy** [comment]
@kingoscargames we know this is still not added so its still WIP

if you have any textures please show them

**Comment by lipki** [comment]
@kingoscargames yes we know, but thank you ;)
update 18w10b

**Comment by lipki** [comment]
![blue_coral](https://user-images.githubusercontent.com/401965/37287294-cb7f5280-2604-11e8-8ad5-e3df85d24a67.png) ![purple_coral](https://user-images.githubusercontent.com/401965/37287296-cbc77b8c-2604-11e8-8e2e-d15793a82a34.png) ![red_coral](https://user-images.githubusercontent.com/401965/37287297-cc0a9cbe-2604-11e8-85a8-6e22942dd895.png)

new batch, what do you think of this style ?

![purple_coral_plant](https://user-images.githubusercontent.com/401965/37287522-4677f76c-2605-11e8-8a73-1d2bffa7d924.png)![yellow_coral_plant](https://user-images.githubusercontent.com/401965/37287502-3c58a268-2605-11e8-8e06-223e369ad6e2.png)

**Comment by lipki** [comment]
update 18w11a

**Comment by chengzzi89** [comment]
No content of coral found in the bag🤔

**Comment by lipki** [comment]
![dead_brain_coral_block](https://user-images.githubusercontent.com/401965/41434707-f74769ea-701c-11e8-82e2-e0f42e2c88d7.png)![dead_bubble_coral_block](https://user-images.githubusercontent.com/401965/41434708-f77eed98-701c-11e8-9d7a-d965c13a24fb.png)![dead_fire_coral_block](https://user-images.githubusercontent.com/401965/41434709-f7ab884e-701c-11e8-8561-bfa630b2d11b.png)![dead_horn_coral_block](https://user-images.githubusercontent.com/401965/41434711-f7d3db96-701c-11e8-9d60-b99d3dd54ab8.png)![dead_tube_coral_block](https://user-images.githubusercontent.com/401965/41434712-f7fef45c-701c-11e8-9ddb-92c5f94b23df.png)

![brain_coral_block](https://user-images.githubusercontent.com/401965/41434736-0b0d7820-701d-11e8-9439-11a1150deb8e.png)![bubble_coral_block](https://user-images.githubusercontent.com/401965/41434737-0b3d2e8a-701d-11e8-91a5-c06aa5248603.png)![fire_coral_block](https://user-images.githubusercontent.com/401965/41434738-0b6af6d0-701d-11e8-92e3-a6f315e50c29.png)![horn_coral_block](https://user-images.githubusercontent.com/401965/41434739-0b8e8c94-701d-11e8-82b6-eac393903c25.png)![tube_coral_block](https://user-images.githubusercontent.com/401965/41434740-0bb3be88-701d-11e8-9c2e-923b45eacf87.png)

![brain_coral](https://user-images.githubusercontent.com/401965/41434756-1a71cd84-701d-11e8-9f65-6d07def2602e.png)![bubble_coral](https://user-images.githubusercontent.com/401965/41434757-1a98f7ba-701d-11e8-8717-10a07d96ffa3.png)![fire_coral](https://user-images.githubusercontent.com/401965/41434758-1abe0230-701d-11e8-82ea-d5a63e4ecf80.png)![horn_coral](https://user-images.githubusercontent.com/401965/41434759-1ae4d252-701d-11e8-9700-e6f4377f4413.png)![tube_coral](https://user-images.githubusercontent.com/401965/41434760-1b0fc520-701d-11e8-878e-10f74d7e4131.png)

![brain_coral_fan](https://user-images.githubusercontent.com/401965/41434778-27f4a4c2-701d-11e8-989b-e589cc3063aa.png)![bubble_coral_fan](https://user-images.githubusercontent.com/401965/41434780-281fecf4-701d-11e8-913e-de8539b4158a.png)![fire_coral_fan](https://user-images.githubusercontent.com/401965/41434781-28491af2-701d-11e8-847a-7789f08da766.png)![horn_coral_fan](https://user-images.githubusercontent.com/401965/41434782-286bb490-701d-11e8-89b8-128aa6cffa52.png)![tube_coral_fan](https://user-images.githubusercontent.com/401965/41434784-2894a68e-701d-11e8-8a13-86acad0ec29f.png)
