### ISSUE TITLE
[1.13] Map icons

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#378]
![map_icons](https://user-images.githubusercontent.com/401965/37063898-53acae28-219b-11e8-8624-f4163e258e25.png)

ref :  
![map_icons](https://user-images.githubusercontent.com/401965/37063954-83e191b2-219b-11e8-8ff0-e1a8a2fe8720.png)

**Comment by chengzzi89** [comment]
![map_icons](https://user-images.githubusercontent.com/28303754/37106461-dd03c900-226c-11e8-8759-0dd7fb3306c5.png)

**Comment by lipki** [comment]
I make that also.
I choose points rather than banners, I find it more precise.
Your red cross is better.
![map_icons](https://user-images.githubusercontent.com/401965/37117829-a31c6e6e-2252-11e8-9139-99bceaa4c141.png)

**Comment by chengzzi89** [comment]
@lipki Because it feels like a banner, so it looks like that!😃

**Comment by chengzzi89** [comment]
@lipki Because it feels like a banner, so I painted it like that!😃

**Comment by lipki** [comment]
done
