### ISSUE TITLE
[1.13] Drowned

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#379]
![drowned](https://user-images.githubusercontent.com/401965/37372019-a4fe231c-2711-11e8-8056-334f13427021.png)![drowned_outer_layer](https://user-images.githubusercontent.com/401965/37372020-a522dc70-2711-11e8-9e9a-f3d78b68fec0.png)

**Comment by lipki** [comment]
First proposal.
It is not because I make a proposal, that you should not do it too.
Mmmm ...

![drowned](https://user-images.githubusercontent.com/401965/37372387-da2a7058-2712-11e8-9aba-29c0b9a9a142.png)![drowned_outer_layer](https://user-images.githubusercontent.com/401965/37372388-da4e9992-2712-11e8-9775-1dec6d4a264f.png)

![capture du 2018-03-13 22-45-45](https://user-images.githubusercontent.com/401965/37372395-e080f31e-2712-11e8-9206-35e18c5a16fa.png)

**Comment by tobyplowy** [comment]
more sea thing
![37372387-da2a7058-2712-11e8-9aba-29c0b9a9a142](https://user-images.githubusercontent.com/16853304/37374907-9d246fdc-271d-11e8-91b7-723d0fad42a4.png)
![37372388-da4e9992-2712-11e8-9775-1dec6d4a264f](https://user-images.githubusercontent.com/16853304/37374908-9d3b70e2-271d-11e8-9e69-a3772a3f8928.png)

**Comment by chengzzi89** [comment]
It will be more perfect if you add some water plants properly!🤔

**Comment by lipki** [comment]
yes it's better.

**Comment by lipki** [comment]
I still have doubts about that one.

**Comment by lipki** [comment]
ok it's done
