### ISSUE TITLE
[1.13] sea pickle

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#380]
![sea_pickle](https://user-images.githubusercontent.com/401965/38614519-c265f078-3d8d-11e8-9c69-317181317bb2.png)
![sea_pickle](https://user-images.githubusercontent.com/401965/38614562-da493cf4-3d8d-11e8-81df-90f105888052.png)

**Comment by lipki** [comment]
![sea_pickle](https://user-images.githubusercontent.com/401965/38708958-ef987dc8-3eb8-11e8-9463-bcfe760cab22.png)

![capture du 2018-04-13 01-22-19](https://user-images.githubusercontent.com/401965/38709030-372b6178-3eb9-11e8-8641-4ef5a00f8abe.png)

**Comment by lipki** [comment]
done ?

**Comment by tobyplowy** [comment]
@lipki yes
