### ISSUE TITLE
[1.13] dolphin

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#381]
![dolphin](https://user-images.githubusercontent.com/401965/38646914-2b6e3b0a-3dea-11e8-9c47-c702a086e531.png)

**Comment by lipki** [comment]
go toby, he is for you this one :)

**Comment by tobyplowy** [comment]
@lipki whats the texture file of the dolphin called?

**Comment by lipki** [comment]
yeah :)
I'm going to swim with the dolphins now.

**Comment by lipki** [comment]
done ?

**Comment by tobyplowy** [comment]
@lipki jup

**Comment by chengzzi89** [comment]
[mcpe]  ![dolphin](https://user-images.githubusercontent.com/28303754/41479133-c0d26a8c-70fc-11e8-97c4-c306d0512886.png)
