### ISSUE TITLE
[1.13] inventory

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#389]
![inventory](https://user-images.githubusercontent.com/401965/39830058-92155848-53c0-11e8-875c-e5717c21ca7c.png)

**Comment by chengzzi89** [comment]
Has this UI been completed?😃

**Comment by tobyplowy** [comment]
![inventory](https://user-images.githubusercontent.com/16853304/40080747-3e2bd6fa-588c-11e8-9c82-885a771c825e.png)

**Comment by tobyplowy** [comment]
@chengzzi89 now it is completed :)

**Comment by lipki** [comment]
Ok that's done, I make the commit.
