### ISSUE TITLE
Some suggestions on color scheme

### ISSUE THREAD

**Issue by Jaychiung** [SummerFields/SummerFields#393]
Hi, em......
This is my first time write to you, my friend. I have been using your product for almost 7 years. I sometimes recall the history of my game experience and ask myself how did I chose your resource pack. I guess it's because, the skin, the color is always close to the original version and the pattern is always better. I love the way you design the pattern but now I realized that somethings goes different on the colors. The color of concrete and clay is quite different with the original version and that made my building looks not that good in others' eyes. 
May I suggest the adjust the color scheme back to the original version and do more on the pattern improvements? I think that, players make buildings to show to others not only to watch them alone. What do you think?

**Comment by lipki** [comment]
I think you are right :)

There have been changes of texture, and new textures not necessarily very well chosen (in terms of color).

The fact is, there are not many contributors, and most importantly, no builder in the team.

If you have proposals for change, one or more, do not hesitate to say it here.
If in addition you can propose textures it is even better.
And even several textures with variations.
You can also show, with screen shot, the defects you have found.

**Comment by Jaychiung** [comment]
Well, yes, I understand you.
I wanna say THANKS to the team, I really wish the texture pack can stand
for as long as possible.
Do you have any suggestions of how to start learn how to make textures? I
wish oneday I could join you~~

Jay

2018-05-22 16:19 GMT+08:00 Lepeltier kévin <notifications@github.com>:

**Comment by tobyplowy** [comment]
@Jaychiung hahahah thanks I'm happy that you like the pack :)

I have some tips try to replace some textures that are already in the pack 
And make them fit as well as you can

Also color index mode on 32 colors is a nice thing as it makes your textures feel more retro

Also watch these videos as they are very useful!
https://youtu.be/xw65wUfEKIc
https://youtu.be/946Qt7jEzbE
https://youtu.be/iga8qwm9S00

**Comment by Jaychiung** [comment]
Well, it seems I joined a group chat.....
Hey everyone~~~
About clay, well emm.....textures of clay in summerfields are always super
cool, I love them all!!
But one thing here bother me is that the color is quite different from the
orginal resource pack....the color scheme in the oringal one is
nasty....but, you know, when I build somethings using summerfields and I
feel that the building is awesome, it is not always that case in others'
eyes. So I mean, maybe we can make a less change in the texture?? So maybe
our texture can better fits all the other textures?

2018-05-27 23:25 GMT+08:00 Lepeltier kévin <notifications@github.com>:

**Comment by tobyplowy** [comment]
@lipki do we finish this?
