### ISSUE TITLE
glass ctm

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#397]
![image](https://user-images.githubusercontent.com/16853304/41038673-4d9dc064-6997-11e8-8b7b-6ee2892defe7.png)
[ctm.zip](https://github.com/SummerFields/SummerFields/files/2076199/ctm.zip)
put the mcpatcher folder from the ctm.zip summerfealds\assets\minecraft

**Comment by tobyplowy** [comment]
i will do the colored versions later

**Comment by lipki** [comment]
The ctm files already exist:
https://github.com/SummerFields/SummerFields/tree/rp1/assets/minecraft/mcpatcher
https://github.com/SummerFields/SummerFields/blob/rp1/SummerFields_rp1.zip?raw=true
If you want to check and complete them.

**Comment by lipki** [comment]
it's for which version ?

**Comment by tobyplowy** [comment]
1.12.2

**Comment by lipki** [comment]
ah,great, I still have not checked mcpatcher on 1.12.
Look here : https://twitter.com/Zombiellaa/status/1002313683391746048

**Comment by tobyplowy** [comment]
Uuuuh not sure why that happens
Bdw I very new to ctm so I probably won't be able to fix it

**Comment by lipki** [comment]
It was just for info, I'll finish by taking care of it.
