### ISSUE TITLE
[1.13] conduit winds

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#399]
![wind](https://user-images.githubusercontent.com/401965/38647018-80a354b6-3dea-11e8-9c6c-6eab7d159755.png)![wind_vertical](https://user-images.githubusercontent.com/401965/38647019-80c57d5c-3dea-11e8-9bb7-c9623a527000.png)

**Comment by tobyplowy** [comment]
i like these
done?

**Comment by lipki** [comment]
it's the originals.
I did not manage to do a good thing.

**Comment by tobyplowy** [comment]
Hummm... I can't seem to do it ether.
This is a hard one.

**Comment by tobyplowy** [comment]
@chengzzi89 Can you give it an attempt?

**Comment by tobyplowy** [comment]
I have given it another try.
![outputimage](https://user-images.githubusercontent.com/16853304/53769190-70a2fb00-3edb-11e9-8d7d-45b72cbec9b8.png)
![outputimage 1](https://user-images.githubusercontent.com/16853304/53769191-713b9180-3edb-11e9-9df0-d34076bb2719.png)
