### ISSUE TITLE
[1.13] panorama

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#400]
![panorama_overlay](https://user-images.githubusercontent.com/401965/41290506-606636d0-6e4d-11e8-8427-9f4d1ca5caa8.png)

**Comment by chengzzi89** [comment]
Sorry, my Render-360mod is 1.12 and I can't run it in the 1.13 snapshot!😟

**Comment by chengzzi89** [comment]
1.13-pre1
![recipe_book](https://user-images.githubusercontent.com/28303754/41416078-ae53807a-701c-11e8-911a-1450957467de.png)

**Comment by lipki** [comment]
It's not the right issue, but thanks :)
Too bad for the render 360, you will wait for the update.
