### ISSUE TITLE
bubble_column

### ISSUE THREAD

**Issue by chengzzi89** [SummerFields/SummerFields#419]
Request help
![bubble_column_down_top_a](https://user-images.githubusercontent.com/28303754/41482516-6ba4005a-7108-11e8-9f54-3b4a4cf61509.png)       ![bubble_column_inner_a](https://user-images.githubusercontent.com/28303754/41482517-6bf678d0-7108-11e8-9d6d-78cef197b1d1.png)       ![bubble_column_outer_a](https://user-images.githubusercontent.com/28303754/41482519-6cb74100-7108-11e8-9945-a23ff3caafae.png)       ![bubble_column_up_top_a](https://user-images.githubusercontent.com/28303754/41482521-6d7fb41e-7108-11e8-9385-5a42f713c69a.png)

**Comment by lipki** [comment]
Which version is it for?

**Comment by chengzzi89** [comment]
@lipki mcpe ocean bubble column！😅😅

**Comment by lipki** [comment]
I can help, but can you put this here : https://github.com/SummerFields/MCPE/issues/new

**Comment by chengzzi89** [comment]
I am sorry, I am anxious, so I made a mistake!

**Comment by lipki** [comment]
No need to apologize, there is no problem.

**Comment by lipki** [comment]
view -> #12
