### ISSUE TITLE
[1.14.2] Minecraft update

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#438]
This issue is to gather information and prep textures for the upcoming minecraft update 1.14.

**Comment by tobyplowy** [comment]
There will now be 8 cat textures in minecraft instead of just 4.
![image](https://user-images.githubusercontent.com/16853304/46260233-9ae32d80-c4e3-11e8-8000-f00a2a844311.png)
every village will be unique depending on the biome it will be in.
villagers will also get a Unique texture and it seems like they will get special models depending on there profession,

**Comment by tobyplowy** [comment]
@lipki We can use the hat layer now :D 
![image](https://user-images.githubusercontent.com/16853304/46260589-3d051480-c4e8-11e8-89a3-654e4946decf.png)

**Comment by lipki** [comment]
nop, he misses the brim for hats.

**Comment by lipki** [comment]
nop, he misses the brim for hats.

**Comment by tobyplowy** [comment]
The brim is new but I'm sure it uses that hat layer.

**Comment by lipki** [comment]
New series of block variation.
![](https://pbs.twimg.com/media/Do_3_6fXUAAF0F6.jpg)

**Comment by lipki** [comment]
New sign for all types of wood.
![](https://pbs.twimg.com/media/DpjgmvRW4AAl9g1.jpg)

**Comment by lipki** [comment]
Lectern #461
![](https://pbs.twimg.com/media/Dpy2vICX4AAMBzs.jpg)
