### ISSUE TITLE
[1.14] Nine cats (la la lala lalalala la ....)

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#439]
![capture du 2018-11-02 12-32-50](https://user-images.githubusercontent.com/401965/47913203-87890080-de9b-11e8-9a55-f1a35412fc3e.png)

+ jellie
![jellie](https://user-images.githubusercontent.com/401965/49890278-00d52500-fe44-11e8-8914-2bba61109a28.png)

**Comment by lipki** [comment]
There is in the currently bedrock version, 8 different cats + the ocelot.
Most are tame, even the ocelots.
Some cat have variations.

![allblackcat](https://user-images.githubusercontent.com/401965/46862182-a05e4300-ce14-11e8-9bf8-bab3fc2ea8d5.png) ![tuxedo](https://user-images.githubusercontent.com/401965/46862213-ac4a0500-ce14-11e8-9999-82f1ee552e16.png)
![britishshorthair](https://user-images.githubusercontent.com/401965/46862222-b23fe600-ce14-11e8-8856-763005fc1d18.png)
![calico](https://user-images.githubusercontent.com/401965/46862225-b66c0380-ce14-11e8-898a-988ac8f30f83.png)
![persian](https://user-images.githubusercontent.com/401965/46862250-c1bf2f00-ce14-11e8-93a8-28e54c2e507d.png)
![ragdoll](https://user-images.githubusercontent.com/401965/46862264-c84da680-ce14-11e8-8d78-16e691387981.png)
![siamesecat](https://user-images.githubusercontent.com/401965/46862296-d69bc280-ce14-11e8-9076-6d208aeb5145.png) ![z___siamese](https://user-images.githubusercontent.com/401965/46862301-da2f4980-ce14-11e8-825f-b165025eba2d.png)
![tabby](https://user-images.githubusercontent.com/401965/46862313-e1565780-ce14-11e8-8301-1c44f1d4dc15.png)
![white](https://user-images.githubusercontent.com/401965/46862328-e7e4cf00-ce14-11e8-8850-8608ba658ade.png)

![ocelot](https://user-images.githubusercontent.com/401965/46862236-bbc94e00-ce14-11e8-9d32-b47fa0d240ba.png)

![capture du 2018-10-12 12-40-45](https://user-images.githubusercontent.com/401965/46865587-59754b00-ce1e-11e8-8c61-a38f74b91823.png)

**Comment by lipki** [comment]
![all_black](https://user-images.githubusercontent.com/401965/47918479-033f7900-dead-11e8-848b-c389a7c17908.png)all_black
![black](https://user-images.githubusercontent.com/401965/47918481-033f7900-dead-11e8-86a7-5db579130bd3.png)black
![british_shorthair](https://user-images.githubusercontent.com/401965/47918482-033f7900-dead-11e8-984d-e460c6bf62cc.png)british_shorthair
![calico](https://user-images.githubusercontent.com/401965/47918483-03d80f80-dead-11e8-9eca-bb4f14c16ed8.png)calico
![ocelot](https://user-images.githubusercontent.com/401965/47918484-03d80f80-dead-11e8-8644-0f931e3baaba.png)ocelot
![persian](https://user-images.githubusercontent.com/401965/47918486-03d80f80-dead-11e8-8623-0f659eab979c.png)persian
![ragdoll](https://user-images.githubusercontent.com/401965/47918487-03d80f80-dead-11e8-97bc-49cf10e5d420.png)ragdoll
![red](https://user-images.githubusercontent.com/401965/47918488-0470a600-dead-11e8-95e6-07fa5ad79b86.png)red
![siamese](https://user-images.githubusercontent.com/401965/47918489-0470a600-dead-11e8-9cde-690620f16d4f.png)siamese
![tabby](https://user-images.githubusercontent.com/401965/47918490-0470a600-dead-11e8-9cc4-eccd85f921f1.png)tabby
![white](https://user-images.githubusercontent.com/401965/47918491-0470a600-dead-11e8-8f3a-9655104944cb.png)white

**Comment by lipki** [comment]
![capture du 2018-11-02 17-36-10](https://user-images.githubusercontent.com/401965/47928543-f039a280-dec6-11e8-9460-119ec6efb1a0.png)
![capture du 2018-11-02 17-42-09](https://user-images.githubusercontent.com/401965/47928550-f3cd2980-dec6-11e8-956e-f2ad845cef5a.png)
![all_black](https://user-images.githubusercontent.com/401965/47928608-0a738080-dec7-11e8-8160-3f1aa7b647fb.png)![black](https://user-images.githubusercontent.com/401965/47928609-0a738080-dec7-11e8-95ff-4a54394d5a94.png)![british_shorthair](https://user-images.githubusercontent.com/401965/47928610-0a738080-dec7-11e8-9313-04444ceab487.png)![calico](https://user-images.githubusercontent.com/401965/47928613-0b0c1700-dec7-11e8-93fe-47a0dee69a00.png)![ocelot](https://user-images.githubusercontent.com/401965/47928615-0b0c1700-dec7-11e8-8c90-ff900cf10665.png)![persian](https://user-images.githubusercontent.com/401965/47928616-0b0c1700-dec7-11e8-8a6d-186f1c43a16b.png)![ragdoll](https://user-images.githubusercontent.com/401965/47928618-0ba4ad80-dec7-11e8-9b71-f68cb6a5745d.png)![red](https://user-images.githubusercontent.com/401965/47928620-0c3d4400-dec7-11e8-8516-95f829ec1f34.png)![siamese](https://user-images.githubusercontent.com/401965/47928621-0c3d4400-dec7-11e8-907e-d71dec8cb1d6.png)![tabby](https://user-images.githubusercontent.com/401965/47928623-0c3d4400-dec7-11e8-9516-3388ce4ee873.png)![white](https://user-images.githubusercontent.com/401965/47928625-0c3d4400-dec7-11e8-8950-43c2ceb712cc.png)

**Comment by tobyplowy** [comment]
I like it :D

**Comment by tobyplowy** [comment]
@lipki Done?

**Comment by lipki** [comment]
It's missing jellie.

**Comment by tobyplowy** [comment]
@lipki Here is my attempt at jellie.
![47918488-0470a600-dead-11e8-95e6-07fa5ad79b86](https://user-images.githubusercontent.com/16853304/53357464-41feb080-392e-11e9-8451-d061c7e85f8d.png)

**Comment by lipki** [comment]
ok done!

**Comment by chengzzi89** [comment]
@lipki 
Is there a cat collar?🤔

**Comment by chengzzi89** [comment]
😁![screenshot_20190303_070013](https://user-images.githubusercontent.com/28303754/53688663-3d992400-3d82-11e9-9261-ce15bc84a00a.jpg)
