### ISSUE TITLE
[1.14] Really more villagers

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#441]
![](https://community-content-assets.minecraft.net/upload/styles/large/s3/ecc42eac7a61534efdb13c2d23d049b0-Header.jpg)
![](https://community-content-assets.minecraft.net/upload/styles/small/s3/261bb692505f27684b7d1a04e248773b-HereWeGo.jpg)

- Maybe 5 origins / biomes
- 12 different professions
- Mainly differentiate by their hats in the original version.

Maybe the textures will be assembled.
A basic texture,
covered with a biome texture,
covered with a job texture.
This is the impression given by the screenshots.

It is, in any case, like that that we will work while waiting for more information.

**Comment by chengzzi89** [comment]
☹️Too much?

**Comment by chengzzi89** [comment]
☹️Too much?

**Comment by tobyplowy** [comment]
@chengzzi89 yup it is too much, but we MUST do it.
It's going to be fun (sarcasm) :/

**Comment by chengzzi89** [comment]
![screenshot_20181213_011949](https://user-images.githubusercontent.com/28303754/49886684-38a89080-fe75-11e8-9986-d9e929a58777.jpg)
