### ISSUE TITLE
[1.14] Bamboo

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#442]
Bamboo will be added to minecraft.
![image](https://user-images.githubusercontent.com/16853304/46260329-cca8c400-c4e4-11e8-81f1-f32bfd01b987.png)
Bamboo seems to be 3 pixels wide.
And there seems to be 2 variants, one with leaves and one without, and there seems to be a bottom bamboo leaves version.
![image](https://user-images.githubusercontent.com/16853304/46260956-3f1da200-c4ed-11e8-995b-391983a61af6.png)

Also I may be wrong but the light lines on the bamboo seem to be irregular, I think they are using random textures, but I may be wrong.
![image](https://user-images.githubusercontent.com/16853304/46260744-2e1f6180-c4ea-11e8-9204-deb27861a75d.png)

There also seems to be bamboo sprouts.
![image](https://user-images.githubusercontent.com/16853304/46260353-0d084200-c4e5-11e8-91da-c1345f622617.png)

And a bamboo item.
![image](https://user-images.githubusercontent.com/16853304/46260381-5fe1f980-c4e5-11e8-9a75-573c79128339.png)

![bamboo_stage0](https://user-images.githubusercontent.com/401965/47446318-46b62b00-d7bb-11e8-93d0-a0c8cc4032bb.png)
![bamboo_large_leaves](https://user-images.githubusercontent.com/401965/47446331-4d44a280-d7bb-11e8-952c-be493d035d05.png)![bamboo_small_leaves](https://user-images.githubusercontent.com/401965/47446336-4fa6fc80-d7bb-11e8-9c25-05d805c6b6ea.png)![bamboo_singleleaf](https://user-images.githubusercontent.com/401965/47446338-52095680-d7bb-11e8-91f3-47424b80169e.png)
![bamboo_stalk](https://user-images.githubusercontent.com/401965/47446354-57ff3780-d7bb-11e8-9b69-666932cd31fa.png)
![bamboo](https://user-images.githubusercontent.com/401965/47446357-5afa2800-d7bb-11e8-8ae8-75112af75a47.png)

**Comment by lipki** [comment]
I think it will be necessary to change the sugar cane, too.

**Comment by tobyplowy** [comment]
@lipki What do you think about this?
![sugar_cane](https://user-images.githubusercontent.com/16853304/46262697-1e614680-c505-11e8-929b-3623123dc1e4.png)

**Comment by lipki** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/8/8e/Canne_en_fleur.jpeg)

**Comment by tobyplowy** [comment]
@lipki I made it look like this.
https://www.google.be/search?q=sugarcane&safe=active&client=tablet-android-google&prmd=inmv&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi-gcKT5uXdAhVQKewKHX0yBaoQ_AUIESgB&biw=960&bih=600#imgrc=EbblvTEMvhl6HM:

But I will try the other image.

**Comment by lipki** [comment]
It's just to differentiate them.
maybe just make them redder.

**Comment by tobyplowy** [comment]
@lipki What about this?
![sugar_cane](https://user-images.githubusercontent.com/16853304/46315562-14574a80-c5ce-11e8-9609-457d5bc4e616.png)

**Comment by lipki** [comment]
up
![bamboo_sapling](https://user-images.githubusercontent.com/401965/46865765-fc2dc980-ce1e-11e8-9ada-c87a27912b32.png)
![bamboo_leaf](https://user-images.githubusercontent.com/401965/46865787-0a7be580-ce1f-11e8-9489-d5fb337f612f.png) ![bamboo_small_leaf](https://user-images.githubusercontent.com/401965/46865788-0cde3f80-ce1f-11e8-881e-291631ba39e1.png) ![bamboo_singleleaf](https://user-images.githubusercontent.com/401965/46865789-0f409980-ce1f-11e8-8956-de49ce61732c.png)
![bamboo_stem](https://user-images.githubusercontent.com/401965/46865800-1bc4f200-ce1f-11e8-906e-4087c506e334.png)

**Comment by tobyplowy** [comment]
bamboo_stem
![bamboo_stem](https://user-images.githubusercontent.com/16853304/46886445-459c0a00-ce5b-11e8-9e6b-ddfa3b06f041.png)

**Comment by chengzzi89** [comment]
![8aa782f4705adc8cb44fbfd06844135d](https://user-images.githubusercontent.com/28303754/46901588-3b285180-cee9-11e8-8a95-c86dc72d1273.jpg)
![4df667efb6a8b17247e3d570e5c0d432](https://user-images.githubusercontent.com/28303754/46901590-424f5f80-cee9-11e8-9542-f9f16c255e17.jpg)

![u 107508993 618390947 fm 26 gp 0](https://user-images.githubusercontent.com/28303754/46901596-4da28b00-cee9-11e8-9b4c-4484eb32d3bd.jpg)

**Comment by lipki** [comment]
![capture du 2018-10-25 00-44-20](https://user-images.githubusercontent.com/401965/47465977-767f2600-d7ef-11e8-8a36-8ae38a8ad39c.png)
I'm not sure about the leaves.

**Comment by chengzzi89** [comment]
@lipki Bamboo joints are not reasonable! Bamboo leaves you can follow the photos I provided!😃

**Comment by tobyplowy** [comment]
@chengzzi89 are you interested in giving it a try?

**Comment by tobyplowy** [comment]
@chengzzi89 Maybe you can make a nice model for it :)

**Comment by chengzzi89** [comment]
🤔🤔🤔![bamboo](https://user-images.githubusercontent.com/28303754/53520472-af6a3700-3b10-11e9-8ce7-c6cf0954b4bb.png)

**Comment by tobyplowy** [comment]
That actually looks really nice =D

**Comment by chengzzi89** [comment]
![texture](https://user-images.githubusercontent.com/28303754/53523154-0410b080-3b17-11e9-9f15-3a0f78a58b4f.png)
![texture](https://user-images.githubusercontent.com/28303754/53523159-08d56480-3b17-11e9-823e-0967e4448f5f.png)

**Comment by chengzzi89** [comment]
@tobyplowy Bamboo leaves I painted some small!

**Comment by chengzzi89** [comment]
Bamboo small leaves
![-2dc568373f06d5a8](https://user-images.githubusercontent.com/28303754/53532569-51e6e200-3b32-11e9-830b-ab006d525195.png)

**Comment by tobyplowy** [comment]
@lipki What do you think?
I think these are amazing.

**Comment by lipki** [comment]
perfect :D

**Comment by chengzzi89** [comment]
![bamboo_stem](https://user-images.githubusercontent.com/28303754/53669932-c72df080-3cb3-11e9-879c-8669ccd491a9.png)

**Comment by chengzzi89** [comment]
@lipki 
bamboo_large_leaveshttps://www.dropbox.com/s/9kquyxuqpue1ejb/bamboo_large_leaves.zip?dl=0

**Comment by lipki** [comment]
![capture du 2019-03-02 00-34-58](https://user-images.githubusercontent.com/401965/53672545-51119580-3c83-11e9-89c0-b40f71b438a2.png)

**Comment by tobyplowy** [comment]
I'm a little bothered by the floating leaves at the top of the bamboo.
@chengzzi89 Can you please fix this?

**Comment by lipki** [comment]
better ?
![capture du 2019-03-02 02-27-19](https://user-images.githubusercontent.com/401965/53675045-04ce5180-3c93-11e9-8479-78a663172e20.png)

**Comment by lipki** [comment]
It does not float! But the stems are thin, is hard to see if you are not in the right angle.

**Comment by tobyplowy** [comment]
Alright yeah.
Nevermind :)
