### ISSUE TITLE
[1.14] Panda

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#444]
![](https://community-content-assets.minecraft.net/upload/styles/small/s3/e2d0abe34518a1e27ec6ed1067d41e1b-Pandas.JPEG)

**Comment by lipki** [comment]
On the bedrock, there are currently 7 pandas.

classic
![panda](https://user-images.githubusercontent.com/401965/46868340-48c9d280-ce28-11e8-998a-3a7d0e55b529.png)
aggressive
![panda_aggressive](https://user-images.githubusercontent.com/401965/46868341-48c9d280-ce28-11e8-9253-bfdcbf664c47.png) 
brown
![panda_brown](https://user-images.githubusercontent.com/401965/46868342-48c9d280-ce28-11e8-95cc-57e4a7f5a03f.png) 
lazy
![panda_lazy](https://user-images.githubusercontent.com/401965/46868343-48c9d280-ce28-11e8-9be1-a15e635d9c7f.png)
playful
![panda_playful](https://user-images.githubusercontent.com/401965/46868344-49626900-ce28-11e8-8129-f64debb0b9dd.png) 
sneezy
![panda_sneezy](https://user-images.githubusercontent.com/401965/46868345-49626900-ce28-11e8-85d4-718d821f4103.png)
worried
![panda_worried](https://user-images.githubusercontent.com/401965/46868347-49faff80-ce28-11e8-8ec5-26e6ecae9f67.png) 

![capture du 2018-10-12 14-41-11](https://user-images.githubusercontent.com/401965/46869709-f50db800-ce2c-11e8-8afa-de8988aa9ec6.png)

**Comment by chengzzi89** [comment]
![e83b8ef194ca5c1af19a90b5ef6b71f4](https://user-images.githubusercontent.com/28303754/46901678-83943f00-ceea-11e8-8fd8-6ca08cc27d52.jpg)
![u 107508993 618390947 fm 26 gp 0](https://user-images.githubusercontent.com/28303754/46901679-84c56c00-ceea-11e8-98f4-d318b4411f0f.jpg)

**Comment by lipki** [comment]
not yet.

**Comment by tobyplowy** [comment]
I will see if I can start working on this soon.

**Comment by tobyplowy** [comment]
@lipki Here are the 2 panda colors.
![black classic](https://user-images.githubusercontent.com/16853304/53359840-5e9de700-3934-11e9-945d-17742d60a8e6.png)
![brown](https://user-images.githubusercontent.com/16853304/53359841-5e9de700-3934-11e9-8ee1-33706a9d9dd3.png)
I didn't do the emotions.
And I don't plan on doing them soon.
@lipki @chengzzi89 You guys interested in doing the emotions?

**Comment by lipki** [comment]
![capture du 2019-02-25 22-38-42](https://user-images.githubusercontent.com/401965/53373213-1e029580-3955-11e9-95b8-58c152b7ca1f.png)

**Comment by lipki** [comment]
![aggressive_panda](https://user-images.githubusercontent.com/401965/53373297-573b0580-3955-11e9-8083-ca893080972c.png) ![brown_panda](https://user-images.githubusercontent.com/401965/53373682-77b78f80-3956-11e9-9567-25436a7c4263.png) ![lazy_panda](https://user-images.githubusercontent.com/401965/53373299-573b0580-3955-11e9-8af1-604f12394ee8.png) ![panda](https://user-images.githubusercontent.com/401965/53373300-57d39c00-3955-11e9-9cec-2a3124ba2cac.png) ![playful_panda](https://user-images.githubusercontent.com/401965/53373301-57d39c00-3955-11e9-8db2-69adfa6fd563.png) ![weak_panda](https://user-images.githubusercontent.com/401965/53373695-82722480-3956-11e9-98f6-ecaaaecf7ec4.png) ![worried_panda](https://user-images.githubusercontent.com/401965/53373304-5904c900-3955-11e9-9610-6f9208b2e17d.png)

**Comment by chengzzi89** [comment]
Wow! Nice!😘

**Comment by chengzzi89** [comment]
Please mark the name of the emoticon!😀

**Comment by tobyplowy** [comment]
@lipki Is this done?
