### ISSUE TITLE
[1.14 Villager] Identify professions with things other than colors

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#448]
As a reminder, we have textures that are not used.
And that can be used for trades.

![builder](https://user-images.githubusercontent.com/401965/46281855-31f5c700-c570-11e8-9d2f-0d179f5d324e.png) Builder
![forge](https://user-images.githubusercontent.com/401965/46281858-328e5d80-c570-11e8-9057-3734a0546939.png) Forge
![guard elite](https://user-images.githubusercontent.com/401965/46281859-328e5d80-c570-11e8-9fca-6b980eae1653.png) Soldat
![guild](https://user-images.githubusercontent.com/401965/46281860-328e5d80-c570-11e8-8096-3b7c4f376103.png)  Soldat
![head](https://user-images.githubusercontent.com/401965/46281861-328e5d80-c570-11e8-8626-499b781cdd69.png) Soldat
![hunter](https://user-images.githubusercontent.com/401965/46281862-3326f400-c570-11e8-9629-f9f941d9dd28.png) Hunter
![member](https://user-images.githubusercontent.com/401965/46281865-3326f400-c570-11e8-9a71-a69015787497.png)  Soldat
![smith](https://user-images.githubusercontent.com/401965/46281967-9153d700-c570-11e8-863d-c83f6f586e82.png) Smith (already use)

**Comment by lipki** [comment]
Jobs (currently) :
Librarian : blue bearded
Cartographer : blue bearded
Butcher : white - apron in blood
Leatherworker : white - apron in blood
Cleric : pink bearded
Fletcher : brown
Shepherd : brown
Farmer : brown
Fisher : brown
Armorer : gris - leather apron
Toolsmith : gris - leather apron
Weaponsmith : gris - leather apron
idiot : green

**Comment by lipki** [comment]
New Job : 

armorer
butcher
cartographer
cleric
farmer
fisherman
fletcher
leatherworker
librarian
mason
nitwit
shepherd
toolsmith
weaponsmith

Can you propose keywords for each profession, to start accumulating ideas.

**Comment by tobyplowy** [comment]
Nitwit
![nitwit](https://user-images.githubusercontent.com/16853304/52066502-f77d5480-2578-11e9-9a78-4c6e9eee868d.png)
Farmer
![farmer](https://user-images.githubusercontent.com/16853304/52066491-f5b39100-2578-11e9-91a1-edabff688adf.png)

**Comment by tobyplowy** [comment]
I really like the farmer hat :D

**Comment by lipki** [comment]
The texture for the nitwit totally ruins the clothes of the pnj.
I propose to put nothing for the nitwit, an empty texture.
![capture du 2019-02-01 12-20-45](https://user-images.githubusercontent.com/401965/52120285-1b45a680-261c-11e9-961d-49bc2ce3f839.png)
![capture du 2019-02-01 12-23-31](https://user-images.githubusercontent.com/401965/52120332-4203dd00-261c-11e9-97fe-800829f2f18a.png)

The farmers are good.
The overlay of hats is sometimes weird, but ...
we could put a tool at the waist of every profession.

![capture du 2019-02-01 12-20-34](https://user-images.githubusercontent.com/401965/52120660-4ed50080-261d-11e9-837d-630c42276620.png)

**Comment by tobyplowy** [comment]
@lipki My attempt at the armorer.
![armorer](https://user-images.githubusercontent.com/16853304/52170822-83e26f80-2751-11e9-8ba7-08359295edf3.png)

**Comment by tobyplowy** [comment]
@lipki also an empty texture for the nitwit is good.

**Comment by lipki** [comment]
![capture du 2019-02-25 17-28-37](https://user-images.githubusercontent.com/401965/53352454-14f8d080-3923-11e9-92da-1a23286030b9.png)

**Comment by lipki** [comment]
![Capture du 2019-04-15 18-54-57](https://user-images.githubusercontent.com/401965/56150958-65e68600-5fb0-11e9-9531-e6d0f9bb3e72.png)
![Capture du 2019-04-15 18-54-48](https://user-images.githubusercontent.com/401965/56150973-70a11b00-5fb0-11e9-8988-afac84fb8afc.png)
![Capture du 2019-04-15 18-54-41](https://user-images.githubusercontent.com/401965/56150978-73037500-5fb0-11e9-980b-d89e8ced4ff6.png)
![Capture du 2019-04-15 18-54-31](https://user-images.githubusercontent.com/401965/56150982-74cd3880-5fb0-11e9-9f6e-2e0eb5c97a17.png)

**Comment by lipki** [comment]
![armorer](https://user-images.githubusercontent.com/401965/56196462-2adb6580-6037-11e9-801b-08f2a51af62e.png)![leatherworker](https://user-images.githubusercontent.com/401965/56196463-2b73fc00-6037-11e9-82c2-628552d9fabd.png)![toolsmith](https://user-images.githubusercontent.com/401965/56196464-2b73fc00-6037-11e9-9e99-08cfc8478d7d.png)![weaponsmith](https://user-images.githubusercontent.com/401965/56196466-2ca52900-6037-11e9-9f54-b06137d0c98a.png)

**Comment by lipki** [comment]
![Capture du 2019-04-15 22-27-02](https://user-images.githubusercontent.com/401965/56196576-62e2a880-6037-11e9-95f4-414ff5bb5dd3.png)
![shepherd](https://user-images.githubusercontent.com/401965/56196587-69712000-6037-11e9-8e08-d5860609701b.png)

**Comment by lipki** [comment]
![Capture du 2019-04-15 22-27-14](https://user-images.githubusercontent.com/401965/56196606-71c95b00-6037-11e9-917b-7d10b4ae9413.png)
![butcher](https://user-images.githubusercontent.com/401965/56196620-7726a580-6037-11e9-9140-9e813a21d635.png)

**Comment by tobyplowy** [comment]
@lipki nice stuff you got here :)

**Comment by lipki** [comment]
nitwit - ok
armorer - ok
butcher - ok
leatherworker - ok
shepherd - ok
toolsmith - ok
weaponsmith - ok
librarian
mason
cartographer
cleric
farmer
fisherman
fletcher

**Comment by lipki** [comment]
librarian ... sober
![Capture du 2019-12-19 14-59-15](https://user-images.githubusercontent.com/401965/71179394-625a7b80-2270-11ea-9354-0146c547807b.png)

**Comment by lipki** [comment]
Mason, yellow glove and tool belt.
![Capture du 2019-12-19 15-21-14](https://user-images.githubusercontent.com/401965/71180829-473d3b00-2273-11ea-985f-4b297a542d45.png)

**Comment by lipki** [comment]
![librarian](https://user-images.githubusercontent.com/401965/71181134-cfbbdb80-2273-11ea-9b92-f33daa5324f1.png)
![mason](https://user-images.githubusercontent.com/401965/71181153-d5b1bc80-2273-11ea-9807-7534f53f0044.png)

**Comment by lipki** [comment]
cartographer
complicated glasses and card bag.
![Capture du 2019-12-19 16-24-10](https://user-images.githubusercontent.com/401965/71185788-668c9600-227c-11ea-89a0-a6c3df95db6e.png)
![cartographer](https://user-images.githubusercontent.com/401965/71185802-6d1b0d80-227c-11ea-9f7b-e4fb9128904c.png)

**Comment by lipki** [comment]
cleric
toga and jewelry
![Capture du 2019-12-19 18-30-13](https://user-images.githubusercontent.com/401965/71195193-b9bb1480-228d-11ea-9a72-300129dd08b8.png)
![cleric](https://user-images.githubusercontent.com/401965/71195247-d8b9a680-228d-11ea-9bdd-2a8e4c9a51b4.png)

**Comment by lipki** [comment]
fiherman
pocket vest and rubber boot
![Capture du 2019-12-19 19-03-25](https://user-images.githubusercontent.com/401965/71197706-829b3200-2292-11ea-85bd-bc82402b4e81.png)
![fisherman](https://user-images.githubusercontent.com/401965/71197784-a6f70e80-2292-11ea-8327-7998947e4051.png)

**Comment by lipki** [comment]
fletcher
Arrow, feather and a flint in hand, to recognize it more easily.
![Capture du 2019-12-19 19-39-23](https://user-images.githubusercontent.com/401965/71200046-91d0ae80-2297-11ea-8cb9-61a9332c051c.png)
![fletcher](https://user-images.githubusercontent.com/401965/71200115-bdec2f80-2297-11ea-9d00-725611ff4233.png)

**Comment by lipki** [comment]
done
![Capture du 2019-12-19 19-46-35](https://user-images.githubusercontent.com/401965/71200454-5c789080-2298-11ea-8d47-82553decf7a7.png)
BOOOOUUUUUMMM !!!!! :1st_place_medal:

**Comment by lipki** [comment]
There is a problem with the sheperd, he is not wearing a working outfit, can you test?

**Comment by tobyplowy** [comment]
@lipki Ow... You are already done?
Nice. I was going to do some later today but I guess you beat me to it again XD
Leave some stuff for me ;)

**Comment by lipki** [comment]
I've been away for months ...
