### ISSUE TITLE
[1.14 Villager] Identify type with clothes

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#449]
As a reminder, we have textures that are not used.
And this can be used for biomes.

![builder](https://user-images.githubusercontent.com/401965/46282265-51412400-c571-11e8-9278-249d2f64b41b.png)![lambda](https://user-images.githubusercontent.com/401965/46282286-6027d680-c571-11e8-8fed-ed0993650906.png)![smithgoonmkii](https://user-images.githubusercontent.com/401965/46282344-88afd080-c571-11e8-88c4-52979dcb5320.png)

But we also have the proposal of different face of villager date since the very beginning.

![smith](https://user-images.githubusercontent.com/401965/46282501-f1974880-c571-11e8-8fe3-972e3a33c3a5.png) Goon
![librariancow2](https://user-images.githubusercontent.com/401965/46282527-fd830a80-c571-11e8-9bf3-25b5b5c863a6.png) Cow
![priestcreeper](https://user-images.githubusercontent.com/401965/46282537-0673dc00-c572-11e8-93b4-47c470112e8b.png) Creeper
![smithhumanm](https://user-images.githubusercontent.com/401965/46282561-20152380-c572-11e8-9fc8-1fcb9d5c244f.png) Human
![librariansummerpig1beard](https://user-images.githubusercontent.com/401965/46282602-38853e00-c572-11e8-8347-0417b973041f.png) pigman

**Comment by lipki** [comment]
Biomes :
Plains
Deserts
Taiga
Savannas
Jungle
Snowy taiga
... ?

**Comment by chengzzi89** [comment]
I can't help anything!☹️

**Comment by chengzzi89** [comment]
I can't help anything!☹️

**Comment by lipki** [comment]
New type :

Plain
Desert
Taiga
Savanna
Jungle
Snow
Swamp

Can you propose keywords for each profession, to start accumulating ideas.

**Comment by tobyplowy** [comment]
@lipki what do you mean by keywords?

**Comment by lipki** [comment]
Snow : warm clothing, covering, bear, fur, hood, boot, glove

**Comment by lipki** [comment]
Proposition ...

Desert :
Reference country : Sahara
Hat : Cheche
Color clothes : Indigo/blue

Jungle :
RC : Cambodia
H : Conical straw hat
CC : a lot

Plains :
RC : Europe
H : Cowboy hat
CC : brown/beige

Savanna :
RC : Tanzania
H : Kofia
CC : Red/orange

Snow :
RC : Russia
H : ouchanka
CC : white/black/red

Swamp :
RC : Ireland
H : Irish Hat
CC : Green

Taiga :
RC : Greenland
H : fur hood
CC : white/grey

![7617dc428be15e6601998864de5316a6](https://user-images.githubusercontent.com/401965/49911594-48c96b80-fe87-11e8-969c-71abeb85a8ab.jpg)

**Comment by tobyplowy** [comment]
@lipki yup sounds good.

**Comment by lipki** [comment]
Skin color :
![desert](https://user-images.githubusercontent.com/401965/50044639-c1e2e180-0086-11e9-9586-6d0a63170a23.png) Desert
![jungle](https://user-images.githubusercontent.com/401965/50044640-c1e2e180-0086-11e9-9f22-c6dc33d2f143.png) Jungle
![plains](https://user-images.githubusercontent.com/401965/50044641-c1e2e180-0086-11e9-8c3f-1dfcc6bfff54.png) Plains
![savanna](https://user-images.githubusercontent.com/401965/50044642-c1e2e180-0086-11e9-93bf-c07c71313a23.png) Savanna
![snow](https://user-images.githubusercontent.com/401965/50044643-c27b7800-0086-11e9-8b23-f9ab98f4dd7c.png) Snow
![swamp](https://user-images.githubusercontent.com/401965/50044644-c27b7800-0086-11e9-96df-86a8ede6958f.png) Swamp
![taiga](https://user-images.githubusercontent.com/401965/50044645-c27b7800-0086-11e9-8ee3-16c077aae4b8.png) Taiga

All this is only proposition, you can propose other things without problem.
And even criticize the bottom.
Does changing the skin color is really a good idea? I'm not sure about myself.

**Comment by lipki** [comment]
First attempt.
The swamp people, the Irish appreciate :)
The result is a cliché, but it's the goal.
![swamp](https://user-images.githubusercontent.com/401965/50044630-9f50c880-0086-11e9-919a-71674e0c9bd6.png)
![capture du 2018-12-15 16-11-22](https://user-images.githubusercontent.com/401965/50044602-4b45e400-0086-11e9-939f-e369a6176232.png)
It may be necessary to add details, asymmetry, imperfection ect ...

**Comment by tobyplowy** [comment]
@lipki hahahah I like that :)
Also I like the idea of the skin colors.
Nice work.

**Comment by tobyplowy** [comment]
Maybe for the snow base we can make them have a red nose because it's cold? 
![50044643-c27b7800-0086-11e9-8b23-f9ab98f4dd7c](https://user-images.githubusercontent.com/16853304/51286920-714c0480-19f5-11e9-91ae-d12f20803c5b.png)

**Comment by lipki** [comment]
yeah ! :D

**Comment by tobyplowy** [comment]
![snow](https://user-images.githubusercontent.com/16853304/52094232-a728e580-25be-11e9-9883-cb252af8849b.png)
Here's my attempt for the snow villager. 
This took me 3 hours to make XD

**Comment by lipki** [comment]
It's a super job !!
![capture du 2019-02-01 11-53-04](https://user-images.githubusercontent.com/401965/52119122-68c01480-2618-11e9-987f-06d12fac386c.png)

**Comment by lipki** [comment]
The citizen of the plain.
![plains](https://user-images.githubusercontent.com/401965/52122721-2bfa1a80-2624-11e9-9543-e0c9f51df94a.png)
![capture du 2019-02-01 13-18-37](https://user-images.githubusercontent.com/401965/52122747-3ddbbd80-2624-11e9-8b05-d1caaeadda3d.png)

**Comment by lipki** [comment]
The desert people.
![desert](https://user-images.githubusercontent.com/401965/52125412-af1f6e80-262c-11e9-9322-3dca6da3dabe.png)
![capture du 2019-02-01 14-20-06](https://user-images.githubusercontent.com/401965/52125402-a9298d80-262c-11e9-8058-e80835dc8a7f.png)

**Comment by tobyplowy** [comment]
@lipki OH WOW YOUR TEXTURES ARE SO GOOD DUDE!!!
For the swamp can we keep the leaves on the characters?

**Comment by lipki** [comment]
Make a proposal.

**Comment by lipki** [comment]
![capture du 2019-02-25 18-45-03](https://user-images.githubusercontent.com/401965/53362659-f999bf80-393a-11e9-8d41-644875b80deb.png)

**Comment by tobyplowy** [comment]
Hey @lipki  can you finish the villagers?

**Comment by lipki** [comment]
twoo last

jungle
![Capture du 2019-12-18 16-23-30](https://user-images.githubusercontent.com/401965/71099056-f49c4a00-21b2-11ea-8b8a-58c04a0242f7.png)

taiga
![Capture du 2019-12-18 17-23-43](https://user-images.githubusercontent.com/401965/71103924-41841e80-21bb-11ea-9aff-83f1702565f4.png)

**Comment by tobyplowy** [comment]
@lipki Very nice!
I like the Eskimo look. Is that Christmas decoration on his solders?

**Comment by lipki** [comment]
No it's supposed to be the thing on the shoulders.
https://www.ecosia.org/images?q=greenland+people#id=B80A9199E18A7E179979F7B6B8B187867E261549

**Comment by lipki** [comment]
It's better, if I share the textures ...
![desert](https://user-images.githubusercontent.com/401965/71180904-705dcb80-2273-11ea-9dde-9bbfa073245c.png)
![jungle](https://user-images.githubusercontent.com/401965/71180905-705dcb80-2273-11ea-8cda-ebdee5175193.png)
![plains](https://user-images.githubusercontent.com/401965/71180908-70f66200-2273-11ea-87f1-42b4b3272dcc.png)
![savanna](https://user-images.githubusercontent.com/401965/71180910-70f66200-2273-11ea-82cc-11d0e96b1ee6.png)
![snow](https://user-images.githubusercontent.com/401965/71180911-718ef880-2273-11ea-82bb-4e3b59c1c432.png)
![swamp](https://user-images.githubusercontent.com/401965/71180914-72278f00-2273-11ea-81d6-2ccfcd81e938.png)
![taiga](https://user-images.githubusercontent.com/401965/71180915-72278f00-2273-11ea-8550-4fe768244f51.png)

**Comment by tobyplowy** [comment]
@lipki Very nice!

**Comment by lipki** [comment]
I consider that all the PNJ are good.
We can improve them later, and make an update, but for now, it will be fine.
OK ?

**Comment by tobyplowy** [comment]
@lipki Yup.
