### ISSUE TITLE
[1.14] Pillager

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#450]
![capture du 2018-10-01 16-21-14](https://user-images.githubusercontent.com/401965/46294464-21f0de00-c596-11e8-8c91-3c8ddbadcce0.png)

![pillager](https://user-images.githubusercontent.com/401965/47445168-9b0bdb80-d7b8-11e8-9b93-01165ea4dee3.png)

**Comment by tobyplowy** [comment]
@lipki done?
