### ISSUE TITLE
New 3d rail

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#452]
I wanted to do that for so long.

![capture du 2018-10-03 17-41-02](https://user-images.githubusercontent.com/401965/46423281-834fb300-c736-11e8-9e97-c71fe1e4237b.png)
![capture du 2018-10-03 17-41-57](https://user-images.githubusercontent.com/401965/46423305-8ba7ee00-c736-11e8-960d-4699625782f8.png)
![capture du 2018-10-03 17-41-36](https://user-images.githubusercontent.com/401965/46423291-86e33a00-c736-11e8-9ae5-be71d9d5228f.png)
![capture du 2018-10-03 17-42-17](https://user-images.githubusercontent.com/401965/46423296-88acfd80-c736-11e8-8988-c437c4a77465.png)

**Comment by tobyplowy** [comment]
@lipki this is amazing man!
One thing that anoyes me is the light pixels on the metal rail.
They seme to mirror a lot.
![screenshot_20181003-194638](https://user-images.githubusercontent.com/16853304/46428753-168fe500-c745-11e8-8ff9-f79dcd92900a.png)
Maybe have the highlight on the rail always on the outside of the rail.
That way there wount be any flipping of the light line.

**Comment by lipki** [comment]
like this :
![capture du 2018-10-03 20-34-22](https://user-images.githubusercontent.com/401965/46431354-e1d35c00-c74b-11e8-9616-5ff8db116b46.png)

**Comment by lipki** [comment]
it's better, thank you.

**Comment by tobyplowy** [comment]
@lipki Yes exactly like that :D
