### ISSUE TITLE
New ladder 3d

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#453]
![capture du 2018-10-03 19-13-27](https://user-images.githubusercontent.com/401965/46427038-88196480-c740-11e8-9138-32b3529c44ef.png)

[ladder.json.zip](https://github.com/SummerFields/SummerFields/files/2443010/ladder.json.zip)

**Comment by tobyplowy** [comment]
@lipki The 3D looks a bit odd.
Why not make the planks look a bit like this?
![image](https://user-images.githubusercontent.com/16853304/46510548-f1d16580-c849-11e8-9c76-2c65ef551ca1.png)

**Comment by lipki** [comment]
You can not make free angles, only 0 / 22.5 / 90 and on one axis at a time.
But yes it might be better.

**Comment by lipki** [comment]
![capture du 2018-10-05 09-54-26](https://user-images.githubusercontent.com/401965/46523039-cd46af00-c884-11e8-9808-aaf7528c9c8a.png)
not great ...
