### ISSUE TITLE
New note block

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#454]
Displays the note and the instrument.

![capture du 2018-10-03 23-23-33](https://user-images.githubusercontent.com/401965/46472672-36271c00-c7de-11e8-9b9b-7d865180e6c9.png)

![capture du 2018-10-04 13-56-39](https://user-images.githubusercontent.com/401965/46472679-3aebd000-c7de-11e8-8038-283784374e43.png)

**Comment by tobyplowy** [comment]
Looks nice but I feel that it's a bit odd to have the texture on all sides.

**Comment by lipki** [comment]
We can not always see all the faces.
![capture du 2018-10-05 10-14-04](https://user-images.githubusercontent.com/401965/46524001-c40b1180-c887-11e8-8fa8-6cd97009ec8f.png)
But if you have a better idea, I take it.
