### ISSUE TITLE
[1.14.1] scaffolding

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#458]
![scaffolding_bottom](https://user-images.githubusercontent.com/401965/48195772-d083fd80-e350-11e8-93a4-a727e558455c.png)![scaffolding_side](https://user-images.githubusercontent.com/401965/48195773-d083fd80-e350-11e8-8571-5df26e0660ee.png)![scaffolding_top](https://user-images.githubusercontent.com/401965/48195775-d11c9400-e350-11e8-9fce-e749fb6ad32f.png)

![800px-scaffolding_be_beta](https://user-images.githubusercontent.com/401965/46866713-cab6fd00-ce22-11e8-8aa5-7ceca5d525b1.jpeg)
![capture du 2018-10-12 14-01-02](https://user-images.githubusercontent.com/401965/46868050-5a5eaa80-ce27-11e8-8df6-4f691ba4bce3.png)

**Comment by tobyplowy** [comment]
This model looks like trash :/
This will need a custom model to look good.

**Comment by lipki** [comment]
I think the same.

**Comment by lipki** [comment]
![scaffolding_bottom](https://user-images.githubusercontent.com/401965/48209750-2cad4880-e376-11e8-8bea-c0dfbcafaad1.png) ![scaffolding_side](https://user-images.githubusercontent.com/401965/48209752-2cad4880-e376-11e8-8f69-50e2d8a03825.png) ![scaffolding_top](https://user-images.githubusercontent.com/401965/48209754-2cad4880-e376-11e8-8a67-d23b893eeb9f.png)

![capture du 2018-11-08 16-46-59](https://user-images.githubusercontent.com/401965/48209698-13a49780-e376-11e8-82a1-b67b297b649a.png)
![capture du 2018-11-08 16-45-59](https://user-images.githubusercontent.com/401965/48209712-17d0b500-e376-11e8-9b16-0d4204617c43.png)
![capture du 2018-11-08 16-46-44](https://user-images.githubusercontent.com/401965/48209723-1bfcd280-e376-11e8-962e-4899da1cb262.png)

**Comment by lipki** [comment]
![capture du 2018-11-08 16-52-03](https://user-images.githubusercontent.com/401965/48210048-e1e00080-e376-11e8-9a48-df44952bf771.png)
![capture du 2018-11-08 16-52-37](https://user-images.githubusercontent.com/401965/48210050-e1e00080-e376-11e8-8ffa-8d49520ed057.png)

**Comment by tobyplowy** [comment]
Looking good :)

**Comment by lipki** [comment]
![capture du 2019-01-25 12-51-18](https://user-images.githubusercontent.com/401965/51744672-d613f880-20a0-11e9-8c23-c4dcad6da435.png)

**Comment by tobyplowy** [comment]
@lipki what changed?
Also nice bridge :)

**Comment by lipki** [comment]
Before there were 4 stages, now there are 6.
