### ISSUE TITLE
[1.14] New series of block variation.

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#459]
![](https://pbs.twimg.com/media/Do_3_6fXUAAF0F6.jpg)
![](https://pbs.twimg.com/media/DpDM0EpWsAAVIYC.jpg)
![](https://pbs.twimg.com/media/DpJ3-zsX4AA9DrI.jpg)
![](https://pbs.twimg.com/media/DpJ8PhIXoAYPSRN.jpg)

**Comment by lipki** [comment]
slab
![capture du 2018-10-24 16-30-10](https://user-images.githubusercontent.com/401965/47440656-e620f100-d7ae-11e8-8ff9-48e9591b8503.png)

qwartz: the normal and smooth are too similar.
stone and smooth stone: you have to invert the textures and make the slab of stone.
petrified wood (2): make a different texture.

double slab
![capture du 2018-10-24 16-36-59](https://user-images.githubusercontent.com/401965/47440897-6182a280-d7af-11e8-96ee-8c0da9dd6319.png)

sandstone : maybe add dark ligne
brick : maybe add séparation

**Comment by lipki** [comment]
![capture du 2018-10-24 16-44-52](https://user-images.githubusercontent.com/401965/47441382-54b27e80-d7b0-11e8-8c45-752b4b5bacc0.png)

qwartz: the normal and smooth are too similar.
sandstone : maybe add dark line

**Comment by lipki** [comment]
![capture du 2018-10-24 16-53-55](https://user-images.githubusercontent.com/401965/47441447-74e23d80-d7b0-11e8-8766-48ffb87a4ea0.png)
cobble: I'm doing tests.

**Comment by lipki** [comment]
![oak_petrified](https://user-images.githubusercontent.com/401965/47467900-c0203e80-d7f8-11e8-93a0-d3518e1881bd.png) petrified oak

**Comment by lipki** [comment]
quartz modification  :
Normal / Smooth
![capture du 2018-10-25 10-48-36](https://user-images.githubusercontent.com/401965/47488479-c0462b80-d844-11e8-8eff-c99dc0cbfc2c.png)

**Comment by lipki** [comment]
Petrified wood :
![capture du 2018-10-25 11-11-12](https://user-images.githubusercontent.com/401965/47489375-c89f6600-d846-11e8-8b25-bd4326c20436.png)

**Comment by lipki** [comment]
Sandstone : 
![capture du 2018-10-25 13-46-38](https://user-images.githubusercontent.com/401965/47498113-8bde6980-d85c-11e8-9636-a6f5f11d9221.png)

**Comment by lipki** [comment]
Stone and smooth stone :
![capture du 2018-10-25 11-53-19](https://user-images.githubusercontent.com/401965/47498145-a1ec2a00-d85c-11e8-8202-6e9b2b25e213.png)
![capture du 2018-10-25 11-53-35](https://user-images.githubusercontent.com/401965/47498149-a6b0de00-d85c-11e8-9630-22bdad0b4128.png)

**Comment by lipki** [comment]
Wall :
![capture du 2018-10-25 15-13-12](https://user-images.githubusercontent.com/401965/47502662-af0f1600-d868-11e8-9243-5a07ea62e7d4.png)

**Comment by tobyplowy** [comment]
@lipki Is this merged yet?

**Comment by tobyplowy** [comment]
@lipki I see, ok :)
