### ISSUE TITLE
[1.14] Lectern

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#461]
![lectern_base](https://user-images.githubusercontent.com/401965/48195668-91ee4300-e350-11e8-8744-924f8d9c506a.png)![lectern_front](https://user-images.githubusercontent.com/401965/48195669-9286d980-e350-11e8-91ac-e0147adac270.png)![lectern_sides](https://user-images.githubusercontent.com/401965/48195670-9286d980-e350-11e8-9900-572cd31d0689.png)![lectern_top](https://user-images.githubusercontent.com/401965/48195672-9286d980-e350-11e8-89c0-ed7dcaa94909.png)

![capture du 2018-11-01 10-08-51](https://user-images.githubusercontent.com/401965/47842887-3c4cf000-ddbe-11e8-8ab2-3a0a0e78f292.png)

**Comment by tobyplowy** [comment]
@lipki Can I do this one?

**Comment by lipki** [comment]
yep

**Comment by lipki** [comment]
up

**Comment by lipki** [comment]
18w45a up

**Comment by tobyplowy** [comment]
bace
![48195668-91ee4300-e350-11e8-8744-924f8d9c506a](https://user-images.githubusercontent.com/16853304/51157815-dd0d6080-1881-11e9-8392-19c3e19b1295.png)
front
![48195669-9286d980-e350-11e8-91ac-e0147adac270](https://user-images.githubusercontent.com/16853304/51157822-e0a0e780-1881-11e9-9101-1d31369caf71.png)
sides
![48195670-9286d980-e350-11e8-9900-572cd31d0689](https://user-images.githubusercontent.com/16853304/51157824-e3034180-1881-11e9-9d5d-6f5c5f7a1e87.png)
top
![48195672-9286d980-e350-11e8-89c0-ed7dcaa94909](https://user-images.githubusercontent.com/16853304/51157825-e4cd0500-1881-11e9-961d-0c6bed9114c3.png)

**Comment by tobyplowy** [comment]
@lipki

**Comment by lipki** [comment]
Yes it's pretty cool.
![capture du 2019-01-15 16-47-24](https://user-images.githubusercontent.com/401965/51191950-c4cf2d00-18e5-11e9-81db-515d2755a3ab.png)
![capture du 2019-01-15 16-47-43](https://user-images.githubusercontent.com/401965/51191951-c567c380-18e5-11e9-986b-54ba3b84e7d3.png)
