### ISSUE TITLE
[1.14] The crossbow

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#462]
![crossbow_standby](https://user-images.githubusercontent.com/401965/47186645-88655280-d331-11e8-86fa-b40af2f5db30.png) ![crossbow_pulling_0](https://user-images.githubusercontent.com/401965/47186649-8c917000-d331-11e8-9254-15118b7a04fc.png) ![crossbow_pulling_1](https://user-images.githubusercontent.com/401965/47186650-8dc29d00-d331-11e8-86c0-5f708af4558b.png) ![crossbow_pulling_2](https://user-images.githubusercontent.com/401965/47186652-8ef3ca00-d331-11e8-9521-8c5aa447bf6d.png) ![crossbow_arrow](https://user-images.githubusercontent.com/401965/47186659-94511480-d331-11e8-9b94-bb886370420f.png) ![crossbow_firework](https://user-images.githubusercontent.com/401965/47186664-961ad800-d331-11e8-83ce-6db93f8147ae.png)

**Comment by tobyplowy** [comment]
Maybe this can be used as a bace?
https://github.com/SummerFields/Mod-balkon/blob/master/assets/weaponmod/textures/items/crossbow-loaded.png

**Comment by lipki** [comment]
![](https://raw.githubusercontent.com/SummerFields/Mod-balkon/master/assets/weaponmod/textures/items/crossbow-loaded.png) ![](https://raw.githubusercontent.com/SummerFields/Mod-balkon/master/assets/weaponmod/textures/items/crossbow.png)
Yes I did not remember it anymore.

Must make some changes anyway.

**Comment by tobyplowy** [comment]
@lipki Do you make the crossbow item?
If it's ok I would like to do the rocket one.

**Comment by lipki** [comment]
as you wish

**Comment by lipki** [comment]
![crossbow_standby](https://user-images.githubusercontent.com/401965/48215309-45236000-e382-11e8-87b6-ed3c2ac04391.png)![crossbow_pulling_0](https://user-images.githubusercontent.com/401965/48215318-49e81400-e382-11e8-86ff-39f6cf078c3f.png)![crossbow_pulling_1](https://user-images.githubusercontent.com/401965/48215319-49e81400-e382-11e8-9376-be80db03aeb1.png)![crossbow_pulling_2](https://user-images.githubusercontent.com/401965/48215321-49e81400-e382-11e8-9497-432f262bb215.png)![crossbow_arrow](https://user-images.githubusercontent.com/401965/48215323-4bb1d780-e382-11e8-8563-5b7305d3c59c.png)

**Comment by tobyplowy** [comment]
@lipki Firework arrow.
![48215323-4bb1d780-e382-11e8-8563-5b7305d3c59c](https://user-images.githubusercontent.com/16853304/48305301-6de55a00-e528-11e8-9493-f818cec68e30.png)
TNT arrows in case they are added.
![48215323-4bb1d780-e382-11e8-8563-5b7305d3c59c](https://user-images.githubusercontent.com/16853304/48305220-198daa80-e527-11e8-860a-86df34664709.png)

**Comment by tobyplowy** [comment]
@lipki Done?
