### ISSUE TITLE
[1.14] Loom

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#463]
![loom_bottom](https://user-images.githubusercontent.com/401965/47445588-9267d500-d7b9-11e8-94bc-daafa6da24af.png)![loom_front](https://user-images.githubusercontent.com/401965/47445589-9267d500-d7b9-11e8-9676-60909d653485.png)![loom_side](https://user-images.githubusercontent.com/401965/47445590-93006b80-d7b9-11e8-9992-c064845a9a52.png)![loom_top](https://user-images.githubusercontent.com/401965/47445591-93006b80-d7b9-11e8-8465-cecb072973e2.png)

![loom](https://user-images.githubusercontent.com/401965/47445594-9693f280-d7b9-11e8-8ccb-84912dc476ab.png)

![creeper_banner_pattern](https://user-images.githubusercontent.com/401965/48196489-fca07e00-e352-11e8-846d-eaf3a1220fae.png)![flower_banner_pattern](https://user-images.githubusercontent.com/401965/48196497-03c78c00-e353-11e8-8b41-ce6e5234a9df.png)![mojang_banner_pattern](https://user-images.githubusercontent.com/401965/48196498-03c78c00-e353-11e8-8450-74effeb22bf7.png)![skull_banner_pattern](https://user-images.githubusercontent.com/401965/48196499-04602280-e353-11e8-8d07-e3b0894de3ff.png)

**Comment by lipki** [comment]
It's a loom.
But I do not think it makes sense, we do not weave the pattern, we print it.
So I propose instead to do some kind of lithography press.

**Comment by lipki** [comment]
Or Sérigraphie

**Comment by tobyplowy** [comment]
Maybe the block model with an animated texture would be nice?

**Comment by lipki** [comment]
something like that
![capture du 2018-10-25 23-51-30](https://user-images.githubusercontent.com/401965/47532615-1bae0300-d8b1-11e8-8372-2d1300293845.png)
The problem with animation is that it will always play.
Not just when we use it.

**Comment by tobyplowy** [comment]
@lipki Nice.

**Comment by lipki** [comment]
![capture du 2018-11-08 14-53-50](https://user-images.githubusercontent.com/401965/48202801-2911c580-e366-11e8-9f59-48641505aeac.png)

**Comment by tobyplowy** [comment]
@lipki Done?

**Comment by lipki** [comment]
I am not sure.

The block of loom allows to make the nice decoration.
Mine does not allow that.
I like it, but I have doubts.

**Comment by tobyplowy** [comment]
@lipki hmm yeah but I mean poeple will find a nice decorative use for your model too I'm sure.

**Comment by tobyplowy** [comment]
@lipki I feel like this is good to be honest :)

**Comment by AzurLighting** [comment]
> @lipki hmm yeah but I mean poeple will find a nice decorative use for your model too I'm sure.

i think the problem is that other people not always use summerfields or use other pack so sticking to the original concept is actually better



> I am not sure.
> 
> The block of loom allows to make the nice decoration.
> Mine does not allow that.
> I like it, but I have doubts.

its possible to make a alternate textures of this one but with the summerfield tone? i mean the loom itself

**Comment by lipki** [comment]
Everything is possible when we have time.

**Comment by lipki** [comment]
![loom](https://user-images.githubusercontent.com/401965/71219789-96f92200-22c6-11ea-9b80-172ea8d42a49.png)

**Comment by tobyplowy** [comment]
@lipki Looks good.
I already put a version in the master branch but it did not have the item prints.

**Comment by lipki** [comment]
Yes, I saw :)
That's why I put it there, I have forgot.

**Comment by lipki** [comment]
Well, today it "pull requests" day.
