### ISSUE TITLE
[1.14] Pattern for banner

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#464]
![creeper_banner_pattern](https://user-images.githubusercontent.com/401965/47445790-1621c180-d7ba-11e8-8eac-b83706f21019.png)![flower_banner_pattern](https://user-images.githubusercontent.com/401965/47445792-16ba5800-d7ba-11e8-867d-2f38458d3f62.png)![mojang_banner_pattern](https://user-images.githubusercontent.com/401965/47445793-16ba5800-d7ba-11e8-8228-c6e770d1e486.png)![skull_banner_pattern](https://user-images.githubusercontent.com/401965/47445794-16ba5800-d7ba-11e8-942c-baffd0a4bcf0.png)
19w11
new pattern globe
![globe](https://user-images.githubusercontent.com/401965/54376494-7d65e280-4683-11e9-911f-f30fd491feb6.png)
and the shield
![globe](https://user-images.githubusercontent.com/401965/55281341-3a6a6700-5333-11e9-82ce-692e88dc77ea.png)
![globe_banner_pattern](https://user-images.githubusercontent.com/401965/54376532-8f478580-4683-11e9-8b7e-ae9113f3f5d5.png)

**Comment by lipki** [comment]
![creeper_banner_pattern](https://user-images.githubusercontent.com/401965/51777311-d510b480-20fc-11e9-9e16-6aa508ca8de8.png)![flower_banner_pattern](https://user-images.githubusercontent.com/401965/51777317-d9d56880-20fc-11e9-94f7-9a52d2199677.png)![mojang_banner_pattern](https://user-images.githubusercontent.com/401965/51777320-dfcb4980-20fc-11e9-919d-d899f483639c.png)![skull_banner_pattern](https://user-images.githubusercontent.com/401965/51777328-e659c100-20fc-11e9-9030-b40e46d95930.png)

**Comment by chengzzi89** [comment]
banner_pattern_illager
![banner_pattern_illager](https://user-images.githubusercontent.com/28303754/53689935-a771f780-3d9b-11e9-812c-7a6ab40445e4.png)

**Comment by lipki** [comment]
In the game it looks like that.
![53689935-a771f780-3d9b-11e9-812c-7a6ab40445e4](https://user-images.githubusercontent.com/401965/53697421-23d2fd80-3dd1-11e9-9096-fcc1c9dc112d.png)

**Comment by lipki** [comment]
I would like something like that, I did it fast.
![53689935-a771f780-3d9b-11e9-812c-7a6ab40445e4](https://user-images.githubusercontent.com/401965/53697793-4404bb80-3dd5-11e9-9557-b0bccd6b9a26.png)

**Comment by chengzzi89** [comment]
> I would like something like that, I did it fast.
> ![53689935-a771f780-3d9b-11e9-812c-7a6ab40445e4](https://user-images.githubusercontent.com/401965/53697793-4404bb80-3dd5-11e9-9557-b0bccd6b9a26.png)

Wow, this is great! I like!👍👍😍

**Comment by lipki** [comment]
19w11
new pattern globe
![globe](https://user-images.githubusercontent.com/401965/54376494-7d65e280-4683-11e9-911f-f30fd491feb6.png)
![globe_banner_pattern](https://user-images.githubusercontent.com/401965/54376532-8f478580-4683-11e9-8b7e-ae9113f3f5d5.png)

**Comment by tobyplowy** [comment]
A bit of battle damage :D
![53697793-4404bb80-3dd5-11e9-9557-b0bccd6b9a26](https://user-images.githubusercontent.com/16853304/54479474-5d6a2680-481d-11e9-8a90-49202a821004.png)
Also globe banner.
![54376494-7d65e280-4683-11e9-911f-f30fd491feb6](https://user-images.githubusercontent.com/16853304/54479661-4c221980-481f-11e9-83b2-504e46265137.png)

**Comment by lipki** [comment]
whistles ... :D  
![boule](https://user-images.githubusercontent.com/401965/54492440-fb65fb80-48c6-11e9-87cf-2eba2720f151.png)

**Comment by tobyplowy** [comment]
![54376494-7d65e280-4683-11e9-911f-f30fd491feb6](https://user-images.githubusercontent.com/16853304/54496275-c28d4d00-48ed-11e9-8b90-48c69ab94bd4.png)

**Comment by lipki** [comment]
![globe_banner_pattern](https://user-images.githubusercontent.com/401965/54498147-6df4cc80-4903-11e9-89d2-e1b3461aeb77.png)

**Comment by lipki** [comment]
and the shield

**Comment by lipki** [comment]
![globe](https://user-images.githubusercontent.com/401965/55281526-03498500-5336-11e9-99a5-6ca700070b9a.png)

**Comment by tobyplowy** [comment]
@lipki Can you make a PR?

**Comment by tobyplowy** [comment]
@lipki What else needs to be done for this to be finished?

**Comment by lipki** [comment]
I think he's missing a PR ...

**Comment by tobyplowy** [comment]
@lipki I will make the PR for this =D
