### ISSUE TITLE
[1.14]  suspicious stew

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#466]
![suspicious_stew](https://user-images.githubusercontent.com/401965/47446195-05258000-d7bb-11e8-838b-e8679f69d17e.png)

**Comment by lipki** [comment]
![suspicious_stew](https://user-images.githubusercontent.com/401965/47464666-38cbce80-d7ea-11e8-8443-4ccaa4f252c7.png)
Inspire by "Dubious Food" of "Breath of the Wild"
![suspicious_stew](https://vignette.wikia.nocookie.net/zelda/images/4/43/Breath_of_the_Wild_Failed_Food_Dish_Dubious_Food_%28Icon%29.png/revision/latest?cb=20170409233042)
http://zelda.wikia.com/wiki/Dubious_Food

**Comment by tobyplowy** [comment]
@lipki Can you make the stuff that's dripping out of the bowl green instead of yellow?

**Comment by tobyplowy** [comment]
Otherwise I like it.
Nice reference!

**Comment by tobyplowy** [comment]
![47506052-a4a44a80-d86f-11e8-8af6-cb8b9552f2c8](https://user-images.githubusercontent.com/16853304/47506373-3318cc00-d870-11e8-80b9-570bef57f76c.png)
@lipki I did some small adjustments.

**Comment by tobyplowy** [comment]
@lipki Done?
