### ISSUE TITLE
[1.14] New Flowers

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#467]
![cornflower](https://user-images.githubusercontent.com/401965/47446444-8c72f380-d7bb-11e8-980a-912d1936edf1.png)![lily_of_the_valley](https://user-images.githubusercontent.com/401965/47446467-97c61f00-d7bb-11e8-8712-ba5de1db8703.png)![wither_rose](https://user-images.githubusercontent.com/401965/47446487-a3194a80-d7bb-11e8-9731-f5a734b05b7b.png)

**Comment by tobyplowy** [comment]
I would like to attempt this.

**Comment by tobyplowy** [comment]
Wither rose.
![47446487-a3194a80-d7bb-11e8-9731-f5a734b05b7b](https://user-images.githubusercontent.com/16853304/48305555-2b724c00-e52d-11e8-9e4a-661cbae9cf4b.png)

**Comment by lipki** [comment]
Blah I don't find it very poison.

**Comment by OwOV** [comment]
Maybe give it spikes like roses have somehow? I do like the dead look though.

**Comment by tobyplowy** [comment]
Is this better?
![47446487-a3194a80-d7bb-11e8-9731-f5a734b05b7b](https://user-images.githubusercontent.com/16853304/48436949-60c2a800-e780-11e8-904e-3b7b35ef7784.png)

**Comment by lipki** [comment]
yes better.

**Comment by tobyplowy** [comment]
Bell flower
![47446467-97c61f00-d7bb-11e8-8712-ba5de1db8703](https://user-images.githubusercontent.com/16853304/52894294-6bd60b80-31a7-11e9-842d-134ca682279a.png)

**Comment by lipki** [comment]
@tobyplowy  you make the blue ?

**Comment by tobyplowy** [comment]
@lipki Can you do that?
Currently having trouble to do it.
Also I know it's not part of the issue but Ididen't like the allium so I changed it a bit.
![allium](https://user-images.githubusercontent.com/16853304/56131657-5ce1be80-5f88-11e9-95b4-3c3b2ed7b96f.png)
Hope you like it.

**Comment by lipki** [comment]
One more allium, one allium of less ...
It must be the fifth version :)

**Comment by tobyplowy** [comment]
XD

**Comment by chengzzi89** [comment]
Flower_cornflower has not drawn

**Comment by lipki** [comment]
for later
![Capture du 2019-12-20 20-19-40](https://user-images.githubusercontent.com/401965/71285708-2a356480-2366-11ea-8c2b-ee3da6cc53e4.png)
