### ISSUE TITLE
Easily recognize infested blocks.

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#468]
I suggest this look for infested blocks.
Only in the inventory.
To never confuse them again.

![capture du 2018-10-25 21-22-09](https://user-images.githubusercontent.com/401965/47525268-1777ea80-d89d-11e8-8781-bd9e5b70230f.png)
![capture du 2018-10-25 21-27-27](https://user-images.githubusercontent.com/401965/47525275-19da4480-d89d-11e8-92ca-4cfdd50195e2.png)

**Comment by tobyplowy** [comment]
@lipki AMAZING!
Look at how cute he is :3
I approve!
