### ISSUE TITLE
[1.14] Barrel

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#481]
![barrel_bottom](https://user-images.githubusercontent.com/401965/47843721-cb5b0780-ddc0-11e8-9661-55d054155739.png)![barrel_side](https://user-images.githubusercontent.com/401965/47843722-cb5b0780-ddc0-11e8-8330-606e6fe268a6.png)![barrel_top](https://user-images.githubusercontent.com/401965/47843723-cb5b0780-ddc0-11e8-9cda-6c424bcf65d8.png)
![capture du 2018-11-01 09-49-03](https://user-images.githubusercontent.com/401965/47842759-ef691980-ddbd-11e8-8889-cf7b7adcf7ad.png)

**Comment by lipki** [comment]
texture from mods:
Factorization : ![barrel_bottom](https://user-images.githubusercontent.com/401965/47845733-0dd31300-ddc6-11e8-9df0-71a95f71163f.png)![barrel_face](https://user-images.githubusercontent.com/401965/47845734-0e6ba980-ddc6-11e8-8d34-66d6597d08d8.png)![barrel_top](https://user-images.githubusercontent.com/401965/47845788-3a872a80-ddc6-11e8-9ac3-6dd9c09d8e89.png)![barrel_side](https://user-images.githubusercontent.com/401965/47845781-33f8b300-ddc6-11e8-9450-62e714c04fe6.png)

Tarrafirmacraft : ![barrelhoop](https://user-images.githubusercontent.com/401965/47845767-28a58780-ddc6-11e8-8bfc-269c877df822.png)

**Comment by tobyplowy** [comment]
Here is my attempt :D
Side
![mid](https://user-images.githubusercontent.com/16853304/47871487-83fa6880-de0c-11e8-9f2a-abfa02a45277.png)
Top
![top](https://user-images.githubusercontent.com/16853304/47871496-8957b300-de0c-11e8-8b85-99a203c62b81.png)
Bottom
![bottom](https://user-images.githubusercontent.com/16853304/47871499-8a88e000-de0c-11e8-87f9-0bade66eb728.png)

**Comment by lipki** [comment]
All right.
![capture du 2018-11-01 21-59-47](https://user-images.githubusercontent.com/401965/47879695-8915e280-de21-11e8-8b62-1f2d9d4500ea.png)

**Comment by tobyplowy** [comment]
@lipki Done?

**Comment by chengzzi89** [comment]
Added a new barrel_top_open

**Comment by lipki** [comment]
![barrel_top_open](https://user-images.githubusercontent.com/401965/53672692-ead94280-3c83-11e9-9ebd-725b663c4e1e.png)

**Comment by lipki** [comment]
![capture du 2019-03-02 01-57-57](https://user-images.githubusercontent.com/401965/53674530-e9f9de00-3c8e-11e9-966e-0f8f86dd45b7.png)
