### ISSUE TITLE
[1.14] Stonecutter

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#482]
![stonecutter_bottom](https://user-images.githubusercontent.com/401965/47843695-b8483780-ddc0-11e8-9894-5804fd31e67b.png)![stonecutter_saw](https://user-images.githubusercontent.com/401965/47843696-b8483780-ddc0-11e8-9a1e-b7756b7970bf.png)![stonecutter_side](https://user-images.githubusercontent.com/401965/47843697-b8e0ce00-ddc0-11e8-9137-adf0b870bbae.png)![stonecutter_top](https://user-images.githubusercontent.com/401965/47843698-b8e0ce00-ddc0-11e8-9796-54acfcd4b414.png)
![stonecutter](https://user-images.githubusercontent.com/401965/53354154-825a3080-3926-11e9-8487-46839793be36.png)
![capture du 2018-11-01 09-33-57](https://user-images.githubusercontent.com/401965/47842896-4373fe00-ddbe-11e8-9f66-d8726e8f7612.png)

**Comment by tobyplowy** [comment]
Can I do this one?

**Comment by lipki** [comment]
yep, You think retouch the model?
We must give the thickness to the blade.

**Comment by tobyplowy** [comment]
@lipki Yeah can you please improve the blade with a model?
:)

**Comment by lipki** [comment]
Make your 3D model, I will adapt it then.
Enjoy yourself :)

**Comment by tobyplowy** [comment]
@lipki Can't make 3 models tho.

**Comment by lipki** [comment]
You know blender !?

**Comment by tobyplowy** [comment]
@lipki Yeah...
But you can't use those models in Minecraft.

**Comment by tobyplowy** [comment]
@lipki Easy and nice looking 3d blade :D
![image](https://user-images.githubusercontent.com/16853304/51155530-1640d300-1878-11e9-9862-5ec9db8226ba.png)
End result with bace.
![image](https://user-images.githubusercontent.com/16853304/51155669-8fd8c100-1878-11e9-8121-961b29bff6cb.png)

**Comment by tobyplowy** [comment]
Blade texture not animated yet ![stonecutter](https://user-images.githubusercontent.com/16853304/51155711-b39c0700-1878-11e9-9ce0-4ff2cb01a9be.png)

**Comment by tobyplowy** [comment]
@lipki that looks pretty good :)
Now I will try and do the stone bace of the cutter.

**Comment by tobyplowy** [comment]
@lipki Here it is.
Bottom.
![47843695-b8483780-ddc0-11e8-9894-5804fd31e67b](https://user-images.githubusercontent.com/16853304/51286336-deaa6600-19f2-11e9-855c-352c30179208.png)
Side.
![47843697-b8e0ce00-ddc0-11e8-9137-adf0b870bbae](https://user-images.githubusercontent.com/16853304/51286350-ea962800-19f2-11e9-8974-22254c217674.png)
Top.
![47843698-b8e0ce00-ddc0-11e8-9796-54acfcd4b414](https://user-images.githubusercontent.com/16853304/51286356-ef5adc00-19f2-11e9-8a8b-037f55bf18a0.png)

**Comment by lipki** [comment]
![capture du 2019-01-17 17-08-10](https://user-images.githubusercontent.com/401965/51331691-8e76e680-1a7a-11e9-8a65-0aa4fb58b4f5.png)

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by tobyplowy** [comment]
I wish that they would just add the GUIs for these.

**Comment by lipki** [comment]
yep

**Comment by tobyplowy** [comment]
![53354154-825a3080-3926-11e9-8487-46839793be36](https://user-images.githubusercontent.com/16853304/56838524-98309700-687e-11e9-9649-dc74c4734da4.png)
Hmmmm, I have given it a try but I can't seem to be able to do this right now.

**Comment by lipki** [comment]
![Capture du 2019-12-20 01-08-16](https://user-images.githubusercontent.com/401965/71219416-4e8d3480-22c5-11ea-89b4-b6485da8436d.png)

![stonecutter](https://user-images.githubusercontent.com/401965/71219453-606ed780-22c5-11ea-9180-43b649393c39.png)

Like this ?

**Comment by tobyplowy** [comment]
Yes. NICE.
