### ISSUE TITLE
[1.14] Bell

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#483]
![bell_bottom](https://user-images.githubusercontent.com/401965/47843664-9f3f8680-ddc0-11e8-8de0-5301fab900ce.png)![bell_side](https://user-images.githubusercontent.com/401965/47843665-9fd81d00-ddc0-11e8-8c55-ce6b64ce7458.png)![bell_top](https://user-images.githubusercontent.com/401965/47843666-9fd81d00-ddc0-11e8-95e4-1f236a633c3e.png)

![bell_body](https://user-images.githubusercontent.com/401965/49890084-7a204800-fe43-11e8-9350-c0ee830664b9.png)

![capture du 2018-11-01 09-33-15](https://user-images.githubusercontent.com/401965/47842900-45d65800-ddbe-11e8-8cf0-7fb19a65508e.png)

**Comment by lipki** [comment]
texture from mods :
thaumcraft : ![arcaneearbellside](https://user-images.githubusercontent.com/401965/47846293-a5853100-ddc7-11e8-858e-240660bfdcfe.png)![arcaneearbelltop](https://user-images.githubusercontent.com/401965/47846298-a7e78b00-ddc7-11e8-8f11-69fda80d2c88.png)

**Comment by lipki** [comment]
![bell_bottom](https://user-images.githubusercontent.com/401965/47855025-ac21a180-dde3-11e8-8a89-63e41f54ce7e.png)![bell_side](https://user-images.githubusercontent.com/401965/47855026-ac21a180-dde3-11e8-9623-3ad293cc60e7.png)![bell_top](https://user-images.githubusercontent.com/401965/47855027-ac21a180-dde3-11e8-875e-e0a2af5bddb2.png)

![capture du 2018-11-01 14-35-46](https://user-images.githubusercontent.com/401965/47855010-a1670c80-dde3-11e8-85e9-11fe1d00dd75.png)

**Comment by tobyplowy** [comment]
I have adjusted your texture a little. here is what I have made.
![47855027-ac21a180-dde3-11e8-875e-e0a2af5bddb2](https://user-images.githubusercontent.com/16853304/47872068-f6b81380-de0d-11e8-96d5-092656ed8b00.png)
![47855026-ac21a180-dde3-11e8-9623-3ad293cc60e7](https://user-images.githubusercontent.com/16853304/47872071-f6b81380-de0d-11e8-825f-de476e09244f.png)
![47855025-ac21a180-dde3-11e8-8a89-63e41f54ce7e](https://user-images.githubusercontent.com/16853304/47872069-f6b81380-de0d-11e8-8138-ce8e730e3675.png)

**Comment by lipki** [comment]
the bell becomes an entity, I take care of modifying the model.

![bell_body](https://user-images.githubusercontent.com/401965/49890084-7a204800-fe43-11e8-9350-c0ee830664b9.png)

**Comment by tobyplowy** [comment]
@lipki Have you made the texture yet?

**Comment by lipki** [comment]
I took yours, but I have to remodel the model again.

**Comment by lipki** [comment]
![bell_body](https://user-images.githubusercontent.com/401965/51753080-39aa2000-20b9-11e9-95f5-5a8e25922ab9.png)
![capture du 2019-01-25 15-50-25](https://user-images.githubusercontent.com/401965/51753022-1b442480-20b9-11e9-9d31-2e2e1db8cb62.png)
