### ISSUE TITLE
[1.14] Smoker

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#485]
![smoker_bottom](https://user-images.githubusercontent.com/401965/47843608-76b78c80-ddc0-11e8-8083-1e3c251003b9.png)![smoker_front](https://user-images.githubusercontent.com/401965/47843609-77502300-ddc0-11e8-9ed4-435edcfc7ae9.png)![smoker_front_on](https://user-images.githubusercontent.com/401965/47843610-77502300-ddc0-11e8-8712-c20ef2b62eaa.png)![smoker_side](https://user-images.githubusercontent.com/401965/47843611-77502300-ddc0-11e8-812d-3c2ac3c54a94.png)![smoker_top](https://user-images.githubusercontent.com/401965/47843613-77502300-ddc0-11e8-8bff-fccf45c2f76e.png)
![smoker](https://user-images.githubusercontent.com/401965/49901415-6be12480-fe61-11e8-835a-3f538c0dc14b.png)
![capture du 2018-11-01 09-35-44](https://user-images.githubusercontent.com/401965/47842771-f3953700-ddbd-11e8-8699-4bbe820bfb15.png)
![capture du 2018-11-01 10-23-55](https://user-images.githubusercontent.com/401965/47843590-68697080-ddc0-11e8-8bfa-ac4a29599984.png)
![capture du 2018-12-12 23-00-35](https://user-images.githubusercontent.com/401965/49901872-aa2b1380-fe62-11e8-8b84-ddd014164b7c.png)

**Comment by lipki** [comment]
tinker : ![smeltery_furnace_off](https://user-images.githubusercontent.com/401965/47846128-37406e80-ddc7-11e8-9cde-ea9c36d56956.png)![smeltery_furnace_on](https://user-images.githubusercontent.com/401965/47846136-3ad3f580-ddc7-11e8-8bfa-fc851f3d3d94.png)

**Comment by lipki** [comment]
![capture du 2019-01-25 22-53-07](https://user-images.githubusercontent.com/401965/51774877-1bade100-20f4-11e9-9d45-d36eb3b3bb98.png)
![smoker_bottom](https://user-images.githubusercontent.com/401965/51774931-413aea80-20f4-11e9-9027-96b3637d2933.png)![smoker_front](https://user-images.githubusercontent.com/401965/51774932-41d38100-20f4-11e9-8c3a-71dc38ba0551.png)![smoker_side](https://user-images.githubusercontent.com/401965/51774934-426c1780-20f4-11e9-89bb-01eeec27ed84.png)![smoker_top](https://user-images.githubusercontent.com/401965/51774935-4304ae00-20f4-11e9-82db-c86661dec56c.png)
![smoker_front_on](https://user-images.githubusercontent.com/401965/51774938-4435db00-20f4-11e9-9186-69e8209ed621.png)

**Comment by tobyplowy** [comment]
@lipki Not sure on the front texture, it looks a little odd.

**Comment by lipki** [comment]
I agree.

**Comment by tobyplowy** [comment]
@lipki I will try to improve it :)

**Comment by lipki** [comment]
![capture du 2019-01-26 13-48-37](https://user-images.githubusercontent.com/401965/51787376-530ea300-2171-11e9-8742-f7e86a0de1ef.png)
![smoker_front](https://user-images.githubusercontent.com/401965/51787378-5ace4780-2171-11e9-949f-698224338b82.png)
![smoker_front_on](https://user-images.githubusercontent.com/401965/51787379-5d30a180-2171-11e9-9da2-ba1d17fcf561.png)

**Comment by tobyplowy** [comment]
@lipki That's a lot better yeah.
Maybe improve the fire a bit, but other than that it's really good.
I think the fire should fill the furnace more, there is not enough fire :)

**Comment by tobyplowy** [comment]
@lipki Nice :D
Done?
We can probably use the furnace GUI for the ui.
![furnace](https://user-images.githubusercontent.com/16853304/52060965-9c923000-256d-11e9-909f-312102c09541.png)

**Comment by tobyplowy** [comment]
This add 2 little things that connect the door when it's cosed so it looks less like it's floating =D
![image](https://user-images.githubusercontent.com/16853304/61673235-e8d55600-acee-11e9-9c72-c34f9f4e8702.png)

**Comment by jaygradon** [comment]
Would this be acceptable for a GUI?

![smoker](https://user-images.githubusercontent.com/16079512/63647225-1a1fc680-c772-11e9-986b-0ca7125b4ec6.png)

**Comment by tobyplowy** [comment]
@jaygradon Very nice!

**Comment by tobyplowy** [comment]
Done.
