### ISSUE TITLE
[1.14] Blast Furnace

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#486]
![blast_furnace_front](https://user-images.githubusercontent.com/401965/47843251-50452180-ddbf-11e8-9c75-700693f8313d.png)![blast_furnace_front_on](https://user-images.githubusercontent.com/401965/47843252-50452180-ddbf-11e8-878d-1bd03e83abec.png)![blast_furnace_side](https://user-images.githubusercontent.com/401965/47843253-50452180-ddbf-11e8-8585-535972cea90d.png)![blast_furnace_top](https://user-images.githubusercontent.com/401965/47843254-50452180-ddbf-11e8-8053-ca39df4bae03.png)
![blast_furnace](https://user-images.githubusercontent.com/401965/49901350-4227fd80-fe61-11e8-9160-cb27c53f679b.png)
![capture du 2018-11-01 09-35-14](https://user-images.githubusercontent.com/401965/47842772-f5f79100-ddbd-11e8-9123-813dcdec0c23.png)
![qqqqqq](https://user-images.githubusercontent.com/401965/47843585-60113580-ddc0-11e8-825f-499317752031.png)
![capture du 2018-12-12 23-05-25](https://user-images.githubusercontent.com/401965/49901837-8c5dae80-fe62-11e8-90ed-080a4596dce8.png)

**Comment by lipki** [comment]
texture from mods :
Railcraft : ![blast furnace](https://user-images.githubusercontent.com/401965/47845952-baad9000-ddc6-11e8-8a23-5f61ff55372f.png)

Terrafirmacraft : ![blast furnace bottom off](https://user-images.githubusercontent.com/401965/47845967-cac56f80-ddc6-11e8-8265-1b5f3650ce24.png)![blast furnace bottom on](https://user-images.githubusercontent.com/401965/47845968-cac56f80-ddc6-11e8-8506-5687024f2c39.png)![blast furnace off](https://user-images.githubusercontent.com/401965/47845978-d1ec7d80-ddc6-11e8-8652-ab57f75c5af0.png)![blast furnace on](https://user-images.githubusercontent.com/401965/47846002-da44b880-ddc6-11e8-8da9-30532bba9c83.png)

**Comment by tobyplowy** [comment]
I like the one from tinkers construct.

**Comment by lipki** [comment]
I think rather keep this design for the smoker, i do not know too much.
We will wait the craft anyway.

**Comment by lipki** [comment]
![capture du 2019-01-25 21-41-55](https://user-images.githubusercontent.com/401965/51771739-4a26be80-20ea-11e9-8527-c6e6e4dae6f0.png)
![blast_furnace_front](https://user-images.githubusercontent.com/401965/51771753-5874da80-20ea-11e9-83fb-9bf657018cba.png)![blast_furnace_side](https://user-images.githubusercontent.com/401965/51771756-5b6fcb00-20ea-11e9-9a29-c396489258c1.png)![blast_furnace_top](https://user-images.githubusercontent.com/401965/51771758-5c086180-20ea-11e9-8cb9-6f86acf6ae07.png)
![blast_furnace_front_on](https://user-images.githubusercontent.com/401965/51771764-5f035200-20ea-11e9-8a11-2d3d3bf7b40b.png)

**Comment by tobyplowy** [comment]
@lipki I like the color on the furnace a lot :D
Done?

**Comment by lipki** [comment]
not yet ui

**Comment by lipki** [comment]
I would like to make a difference.
Maybe change the furnace ...
The furnace is stone, the blast furnace is metal.

**Comment by tobyplowy** [comment]
But the furnace GUI looks like metal.

**Comment by lipki** [comment]
yep

**Comment by tobyplowy** [comment]
@lipki are you interested in doing something special with the GUI?
I think that the furnace GUI can be used.
And then we can add a special GUI for the smoker.
What do you think?

**Comment by lipki** [comment]
Ideally I would like three different interface.
but if the interface of the furnace becomes that of the blast furnace, it is good.
But it would take a new interface for the furnace.

Maybe stone for the furnace.
the furnace interface for the blast furnace
and stone + wood for the smoker.

**Comment by tobyplowy** [comment]
@lipki Can you do the GUIs?

**Comment by lipki** [comment]
For Furnace ?
![furnace](https://user-images.githubusercontent.com/401965/54499338-e3b36500-4910-11e9-916a-141bf5fd072d.png)

**Comment by tobyplowy** [comment]
Yeah that would be a nice one.
