### ISSUE TITLE
[1.14] Cartography Table

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#487]
![cartography_table_front](https://user-images.githubusercontent.com/401965/47843233-3dcae800-ddbf-11e8-97be-02054bbaaaf0.png)![cartography_table_side](https://user-images.githubusercontent.com/401965/47843234-3e637e80-ddbf-11e8-8e7d-c7600e7ef285.png)![cartography_table_top](https://user-images.githubusercontent.com/401965/47843235-3e637e80-ddbf-11e8-9d90-8b725ee06e16.png)
![cartography_table](https://user-images.githubusercontent.com/401965/50936737-33893200-1471-11e9-82f2-9b926b3dd56c.png)
![capture du 2018-11-01 09-35-06](https://user-images.githubusercontent.com/401965/47842778-f8f28180-ddbd-11e8-88ce-2114b66461c8.png)

**Comment by lipki** [comment]
No it's great!
here is the table.
![capture du 2019-01-25 21-50-17](https://user-images.githubusercontent.com/401965/51772094-6bd47580-20eb-11e9-9e53-e019dc2fc787.png)

**Comment by lipki** [comment]
![cartography_table_side1](https://user-images.githubusercontent.com/401965/51772350-151b6b80-20ec-11e9-9158-3b501b9af7e1.png)![cartography_table_side2](https://user-images.githubusercontent.com/401965/51772352-15b40200-20ec-11e9-8c23-010b07fb5143.png)![cartography_table_side3](https://user-images.githubusercontent.com/401965/51772353-15b40200-20ec-11e9-9949-082490f092fe.png)![cartography_table_top](https://user-images.githubusercontent.com/401965/51772354-15b40200-20ec-11e9-8087-5c5653496e34.png)

**Comment by tobyplowy** [comment]
@lipki Nice.
