### ISSUE TITLE
[1.14] Fletching Table

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#488]
![fletching_table_front](https://user-images.githubusercontent.com/401965/47843212-30156280-ddbf-11e8-8eb8-ba7e910d1fac.png)![fletching_table_side](https://user-images.githubusercontent.com/401965/47843213-30156280-ddbf-11e8-880d-e36d9bba983e.png)![fletching_table_top](https://user-images.githubusercontent.com/401965/47843214-30156280-ddbf-11e8-8add-736ff0ccb675.png)
![capture du 2018-11-01 09-34-56](https://user-images.githubusercontent.com/401965/47842787-fee86280-ddbd-11e8-8f7f-13c3f7480a21.png)

**Comment by lipki** [comment]
![fletching_table_front](https://user-images.githubusercontent.com/401965/51772716-fc5f8580-20ec-11e9-8d1d-c9092b400263.png)![fletching_table_side](https://user-images.githubusercontent.com/401965/51772717-fcf81c00-20ec-11e9-83d3-268839e8a8d7.png)![fletching_table_top](https://user-images.githubusercontent.com/401965/51772718-fcf81c00-20ec-11e9-8375-d1255e79bed3.png)
![capture du 2019-01-25 22-02-03](https://user-images.githubusercontent.com/401965/51772690-f10c5a00-20ec-11e9-96ba-63ef64be39d3.png)

**Comment by tobyplowy** [comment]
@lipki Looking good :D
