### ISSUE TITLE
Paintings.

### ISSUE THREAD

**Issue by GloomyAnthony** [SummerFields/SummerFields#491]
I love all the 1.13 textures but I really liked the old paintings.

**Comment by lipki** [comment]
All the tables are available in the pack, just rename.

assets/minecraft/textures/painting/

![](https://raw.githubusercontent.com/SummerFields/SummerFields/master/assets/minecraft/textures/painting/paintings_kristoffer_zetterstrand.png)
![](https://raw.githubusercontent.com/SummerFields/SummerFields/master/assets/minecraft/textures/painting/paintings_kristoffer_zetterstrand_2.png)
