### ISSUE TITLE
[1.14]  Lantern

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#492]
![lantern](https://user-images.githubusercontent.com/401965/48591383-f65a6500-e943-11e8-951e-770cdf17795a.png)
![](https://community-content-assets.minecraft.net/upload/6c4423190a87d93d41923203a52c900a-LanternHeader.jpeg)

**Comment by chengzzi89** [comment]
excuse me I can try making this Lantern it?😅

**Comment by chengzzi89** [comment]
Should this be ok?😅
![lantern](https://user-images.githubusercontent.com/28303754/48668385-e353ba80-eb26-11e8-871f-a333c9d7ddda.png)

**Comment by chengzzi89** [comment]
Should this be ok?😅
![lantern](https://user-images.githubusercontent.com/28303754/48668385-e353ba80-eb26-11e8-871f-a333c9d7ddda.png)

**Comment by lipki** [comment]
That's great :)
![capture du 2018-11-18 15-55-32](https://user-images.githubusercontent.com/401965/48674320-1c9e2180-eb4b-11e8-811b-79cb65096381.png)

**Comment by tobyplowy** [comment]
@lipki Do we use my edit or the original from chengzzi?

**Comment by tobyplowy** [comment]
I also propose a darker shain.
![48668385-e353ba80-eb26-11e8-871f-a333c9d7ddda](https://user-images.githubusercontent.com/16853304/51157991-9f5d0780-1882-11e9-9b8a-4c9d4be7eb58.png)

**Comment by lipki** [comment]
I do not know !?
![capture du 2019-01-15 16-56-21](https://user-images.githubusercontent.com/401965/51192425-c77e5200-18e6-11e9-9b0b-7fbc527895c4.png)

**Comment by tobyplowy** [comment]
@chengzzi89 what do you think?

**Comment by chengzzi89** [comment]
@tobyplowy Obviously, you are more comfortable!👍

**Comment by chengzzi89** [comment]
@tobyplowy Obviously, you are more comfortable!👍

**Comment by chengzzi89** [comment]
@tobyplowy Obviously, you are more comfortable!👍
