### ISSUE TITLE
[1.14] Berry

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#493]
![sweet_berry_bush_stage0](https://user-images.githubusercontent.com/401965/49527144-922b2100-f8b1-11e8-9245-c9c889f2e086.png)![sweet_berry_bush_stage1](https://user-images.githubusercontent.com/401965/49527145-92c3b780-f8b1-11e8-8985-003a365e12d5.png)![sweet_berry_bush_stage2](https://user-images.githubusercontent.com/401965/49527147-935c4e00-f8b1-11e8-981c-8f54925919ff.png)![sweet_berry_bush_stage3](https://user-images.githubusercontent.com/401965/49527148-935c4e00-f8b1-11e8-9f51-041755494cb7.png)
![sweet_berries](https://user-images.githubusercontent.com/401965/49527331-f948d580-f8b1-11e8-9831-1aa276457fd4.png)

**Comment by lipki** [comment]
For the item?
It may be too big a branch for the item, but for the bush it's not bad.
I will do a test.

**Comment by tobyplowy** [comment]
Yeah I made it for the item :D

**Comment by lipki** [comment]
Proposal for berry bush.
![sweet_berry_bush_stage0](https://user-images.githubusercontent.com/401965/51755751-b8a25700-20bf-11e9-8c30-0f5ad7e4b6f7.png)![sweet_berry_bush_stage3](https://user-images.githubusercontent.com/401965/51755753-b93aed80-20bf-11e9-80a4-b287f0f274a0.png)
![capture du 2019-01-25 16-38-13](https://user-images.githubusercontent.com/401965/51755739-b213df80-20bf-11e9-94e4-79242695a79a.png)

**Comment by lipki** [comment]
![capture du 2019-01-25 16-44-00](https://user-images.githubusercontent.com/401965/51756187-bbea1280-20c0-11e9-8fc9-adb6bb722006.png)

**Comment by tobyplowy** [comment]
@lipki That is really nice looking.
Also is that my item texture as a bace XD

**Comment by lipki** [comment]
She is "in it". Literally.

**Comment by tobyplowy** [comment]
@lipki hahaha yeah :)

**Comment by tobyplowy** [comment]
@lipki is the item texture that I made good as the item?
If so this is done right?

**Comment by tobyplowy** [comment]
@lipki is the item texture that I made good as the item?
If so this is done right?

**Comment by tobyplowy** [comment]
@lipki Ping?

**Comment by lipki** [comment]
![sweet_berries](https://user-images.githubusercontent.com/401965/54541475-4c92ef80-499a-11e9-8fca-fdb1908a2376.png)
And like this ?

**Comment by tobyplowy** [comment]
Yeah that is better, I like it :)
