### ISSUE TITLE
[1.14] Jigsaw technical block

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#494]
![jigsaw_bottom](https://user-images.githubusercontent.com/401965/51190961-b1bb5d80-18e3-11e9-9164-2e3ad2c2dd96.png)
![jigsaw_side](https://user-images.githubusercontent.com/401965/51190962-b1bb5d80-18e3-11e9-8be4-3c53c1479e03.png)
![jigsaw_top](https://user-images.githubusercontent.com/401965/51190964-b253f400-18e3-11e9-835a-8ba181311313.png)

**Comment by chengzzi89** [comment]
![jigsaw_bottom](https://user-images.githubusercontent.com/28303754/50040749-8515eb00-0084-11e9-9b72-2c195aeb9eee.png)
![jigsaw_side](https://user-images.githubusercontent.com/28303754/50040753-8b0bcc00-0084-11e9-85ee-a4be0435bb49.png)
![jigsaw_top](https://user-images.githubusercontent.com/28303754/50040754-8f37e980-0084-11e9-9d70-d914b691d66b.png)

**Comment by tobyplowy** [comment]
@lipki Done?

**Comment by lipki** [comment]
yep
