### ISSUE TITLE
[1.14 Villager] zombie Villager

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#495]

**Comment by tobyplowy** [comment]
@lipki Can you do this one?

**Comment by lipki** [comment]
It is necessary to zombify this textures : #449

**Comment by lipki** [comment]
![zombie_villager](https://user-images.githubusercontent.com/401965/52130887-ba2dcb00-263b-11e9-9ac9-14e7399967c9.png)

**Comment by lipki** [comment]
![swamp](https://user-images.githubusercontent.com/401965/52131003-01b45700-263c-11e9-9155-9db35ec74ccf.png)
![capture du 2019-02-01 16-06-52](https://user-images.githubusercontent.com/401965/52130911-cca80480-263b-11e9-9418-ba06a4b53ada.png)

**Comment by tobyplowy** [comment]
I like that a lot, he looks really scary now XD

**Comment by lipki** [comment]
![Capture du 2019-12-19 13-45-33](https://user-images.githubusercontent.com/401965/71175089-f293c300-2266-11ea-81c6-1a3d1bc10610.png)
![Capture du 2019-12-19 13-45-56](https://user-images.githubusercontent.com/401965/71175091-f293c300-2266-11ea-916e-c27e7192d0d2.png)
![Capture du 2019-12-19 13-46-18](https://user-images.githubusercontent.com/401965/71175092-f293c300-2266-11ea-84a6-dd98c3aebe0e.png)
![Capture du 2019-12-19 13-46-41](https://user-images.githubusercontent.com/401965/71175093-f32c5980-2266-11ea-801c-fcd9d44340fd.png)
![Capture du 2019-12-19 13-47-00](https://user-images.githubusercontent.com/401965/71175094-f32c5980-2266-11ea-96d7-1076fee5eb54.png)
![Capture du 2019-12-19 13-47-21](https://user-images.githubusercontent.com/401965/71175095-f3c4f000-2266-11ea-98fa-f55037309d04.png)







![Capture du 2019-12-19 13-38-51](https://user-images.githubusercontent.com/401965/71174508-a6944e80-2265-11ea-9ad6-9dfb70c15e51.png)

**Comment by tobyplowy** [comment]
@lipki hahaH I love how the little creature on the head of the first one came back to life.
Also I was planning to do these textures. Guess you beat me to it XD

**Comment by lipki** [comment]
It's always better when you go over it, and add your ideas, so don't hesitate.
I knew you would like the little creature :)

**Comment by lipki** [comment]
![Capture du 2019-12-19 20-58-37](https://user-images.githubusercontent.com/401965/71205451-bd0ccb00-22a2-11ea-98bd-c010bd7939db.png)

**Comment by lipki** [comment]
![desert](https://user-images.githubusercontent.com/401965/71205527-e299d480-22a2-11ea-9445-c22be354c1f2.png)![jungle](https://user-images.githubusercontent.com/401965/71205528-e3326b00-22a2-11ea-924c-c82bec34532e.png)![plains](https://user-images.githubusercontent.com/401965/71205529-e3326b00-22a2-11ea-821c-c774d3dd0f80.png)![savanna](https://user-images.githubusercontent.com/401965/71205530-e3cb0180-22a2-11ea-8fb3-3eeaf21592aa.png)![snow](https://user-images.githubusercontent.com/401965/71205531-e3cb0180-22a2-11ea-813b-c9e4c8472600.png)![swamp](https://user-images.githubusercontent.com/401965/71205534-e3cb0180-22a2-11ea-82c2-d785f83a05ad.png)![taiga](https://user-images.githubusercontent.com/401965/71205535-e4639800-22a2-11ea-9076-17bc6823598a.png)

![armorer](https://user-images.githubusercontent.com/401965/71205572-f80efe80-22a2-11ea-9ad1-f1699cd36a57.png)![butcher](https://user-images.githubusercontent.com/401965/71205574-f80efe80-22a2-11ea-9148-336e73ff16f4.png)![cartographer](https://user-images.githubusercontent.com/401965/71205575-f8a79500-22a2-11ea-9ba4-dcd5b21f4749.png)![cleric](https://user-images.githubusercontent.com/401965/71205577-f8a79500-22a2-11ea-8895-1f312e261f06.png)![farmer](https://user-images.githubusercontent.com/401965/71205578-f8a79500-22a2-11ea-80c1-e42a2e184733.png)![fisherman](https://user-images.githubusercontent.com/401965/71205579-f9402b80-22a2-11ea-837f-1c8fcfc67742.png)![fletcher](https://user-images.githubusercontent.com/401965/71205580-f9402b80-22a2-11ea-9858-9630414550c7.png)![leatherworker](https://user-images.githubusercontent.com/401965/71205581-f9402b80-22a2-11ea-908b-f46797f439d3.png)![librarian](https://user-images.githubusercontent.com/401965/71205583-f9d8c200-22a2-11ea-9891-ca93ec8b467f.png)![mason](https://user-images.githubusercontent.com/401965/71205585-f9d8c200-22a2-11ea-824c-ea0a5944acda.png)![nitwit](https://user-images.githubusercontent.com/401965/71205586-f9d8c200-22a2-11ea-804e-90bbdb9cb37b.png)![shepherd](https://user-images.githubusercontent.com/401965/71205588-f9d8c200-22a2-11ea-8ef2-7b9251f4af5d.png)![toolsmith](https://user-images.githubusercontent.com/401965/71205591-fa715880-22a2-11ea-9842-4873395b201c.png)![weaponsmith](https://user-images.githubusercontent.com/401965/71205593-fa715880-22a2-11ea-83d6-cb9aba976974.png)

![diamond](https://user-images.githubusercontent.com/401965/71205632-0eb55580-22a3-11ea-91f6-3d9b238b11db.png)![emerald](https://user-images.githubusercontent.com/401965/71205633-0eb55580-22a3-11ea-8be8-d7e66d61e186.png)![gold](https://user-images.githubusercontent.com/401965/71205634-0eb55580-22a3-11ea-858b-8f834498db9e.png)![iron](https://user-images.githubusercontent.com/401965/71205635-0eb55580-22a3-11ea-8527-057f97820126.png)![stone](https://user-images.githubusercontent.com/401965/71205638-0f4dec00-22a3-11ea-9e3d-a48e2ff481b1.png)

**Comment by tobyplowy** [comment]
@lipki the rust on the blacksmith helmet is a nice detail!

**Comment by lipki** [comment]
well, i forgot a lot of it actually.

**Comment by tobyplowy** [comment]
What do you mean?

**Comment by lipki** [comment]
I forgot these two.
![cartographer](https://user-images.githubusercontent.com/401965/71213792-cbfc7900-22b4-11ea-804f-e666e0e78fdc.png)
![cleric](https://user-images.githubusercontent.com/401965/71213793-cbfc7900-22b4-11ea-8cd7-2a3cc81ae1dc.png)

**Comment by tobyplowy** [comment]
I see. Also is it just me or is the bag a zombie face?

**Comment by lipki** [comment]
hmmmm

**Comment by tobyplowy** [comment]
Wait theirs a zombie head in the bag?
I like that bdw.
