### ISSUE TITLE
[1.14 Villager] level

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#496]
Villagers will apparently have level display on their skin.
Like medals.

Diamonds
emerald
gold
iron
stone

![diamond](https://user-images.githubusercontent.com/401965/49902670-dba4de80-fe64-11e8-9a56-26a8267d91bb.png)![emerald](https://user-images.githubusercontent.com/401965/49902671-dba4de80-fe64-11e8-8abb-35c3062f7a32.png)![gold](https://user-images.githubusercontent.com/401965/49902672-dba4de80-fe64-11e8-99bd-1f8c34d0c888.png)![iron](https://user-images.githubusercontent.com/401965/49902673-dc3d7500-fe64-11e8-8a60-e3ec81616682.png)![stone](https://user-images.githubusercontent.com/401965/49902674-dc3d7500-fe64-11e8-895c-aee843faac56.png)

**Comment by lipki** [comment]
Difficult with a dozen pixels.
But why not.

**Comment by lipki** [comment]
![diamond](https://user-images.githubusercontent.com/401965/52131299-b9e1ff80-263c-11e9-8d49-570309b42042.png)
![emerald](https://user-images.githubusercontent.com/401965/52131300-b9e1ff80-263c-11e9-9cda-e812d730f4c6.png)
![gold](https://user-images.githubusercontent.com/401965/52131301-b9e1ff80-263c-11e9-9ad4-e90276db1699.png)
![iron](https://user-images.githubusercontent.com/401965/52131303-ba7a9600-263c-11e9-9eaf-92ded7c789fc.png)
![stone](https://user-images.githubusercontent.com/401965/52131305-ba7a9600-263c-11e9-831e-193b88bd657f.png)

**Comment by lipki** [comment]
version zombie
![diamond](https://user-images.githubusercontent.com/401965/52131341-d2eab080-263c-11e9-88f4-7641c5db1499.png)![emerald](https://user-images.githubusercontent.com/401965/52131342-d3834700-263c-11e9-85ed-7d301b0a5981.png)![gold](https://user-images.githubusercontent.com/401965/52131344-d3834700-263c-11e9-9cda-b90924f21077.png)![iron](https://user-images.githubusercontent.com/401965/52131345-d41bdd80-263c-11e9-8e3a-49dce1e83db7.png)![stone](https://user-images.githubusercontent.com/401965/52131346-d41bdd80-263c-11e9-9563-110f86ac6044.png)

**Comment by tobyplowy** [comment]
@lipki Done?

**Comment by tobyplowy** [comment]
@lipki Done?

**Comment by tobyplowy** [comment]
@lipki Is this done?

**Comment by lipki** [comment]
we are waiting to finish all the villagers to be safe.

**Comment by tobyplowy** [comment]
Ok.

**Comment by lipki** [comment]
What level?
we do not see it !!
![Capture du 2019-03-17 15-27-53](https://user-images.githubusercontent.com/401965/54492740-6e707180-48c9-11e9-9079-19fd6e488c84.png)

**Comment by tobyplowy** [comment]
hmmm.. not sure what you mean.
It's on their shoulder right?

**Comment by lipki** [comment]
yes, but we do not see it when we do the exchanges, it's not good.
I have another proposal.

**Comment by lipki** [comment]
![Capture du 2019-03-17 21-37-18](https://user-images.githubusercontent.com/401965/54497628-47339780-48fd-11e9-87d3-f354c187e6d1.png)
![diamond](https://user-images.githubusercontent.com/401965/54497634-56b2e080-48fd-11e9-9045-21406c5e4018.png)![emerald](https://user-images.githubusercontent.com/401965/54497635-56b2e080-48fd-11e9-9228-e729af529d82.png)![gold](https://user-images.githubusercontent.com/401965/54497636-56b2e080-48fd-11e9-88c4-8e0e5bff33ee.png)![iron](https://user-images.githubusercontent.com/401965/54497638-574b7700-48fd-11e9-9715-8d72d8be5fb1.png)![stone](https://user-images.githubusercontent.com/401965/54497639-574b7700-48fd-11e9-9d7c-764cdbcf7c24.png)

**Comment by tobyplowy** [comment]
Yeah that looks nice :)
Looks like epaulettes.
Maybe add some strands to it so it's a bit nicer (more texture/shape)

**Comment by lipki** [comment]
Enjoy yourself.

**Comment by tobyplowy** [comment]
@lipki Seems like this can be merged.

**Comment by tobyplowy** [comment]
Added by https://github.com/SummerFields/SummerFields/pull/550
