### ISSUE TITLE
[1.14] CampFire

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#497]
![capture du 2019-01-10 00-36-30](https://user-images.githubusercontent.com/401965/50936627-b9f14400-1470-11e9-9a45-a2b7816ed3f9.png)
![campfire_fire](https://user-images.githubusercontent.com/401965/50936706-16546380-1471-11e9-8aab-7e73750cbb89.png)
![campfire_side](https://user-images.githubusercontent.com/401965/50936712-19e7ea80-1471-11e9-8843-9f541f7831c3.png)
![campfire_top](https://user-images.githubusercontent.com/401965/50936713-19e7ea80-1471-11e9-8009-cdf16e349e8e.png)
![campfire_top_on](https://user-images.githubusercontent.com/401965/50936715-19e7ea80-1471-11e9-9d56-d78617773c01.png)

**Comment by chengzzi89** [comment]
3D campfire
![qq 20190111013738](https://user-images.githubusercontent.com/28303754/50986404-b7aaea80-1541-11e9-8821-03fb94673b5f.png)

**Comment by lipki** [comment]
Yeah great, way better than the original.
Can you put the file here ?

**Comment by chengzzi89** [comment]
@lipki https://www.dropbox.com/sh/fi8wg8ld0j29q6j/AABympw3gpFAR52dFc_57nF4a?dl=0

**Comment by tobyplowy** [comment]
I think making the campfire look like this may be nice, no?
![image](https://user-images.githubusercontent.com/16853304/51153333-07562280-1870-11e9-895d-25a55257c4cf.png)

**Comment by tobyplowy** [comment]
@chengzzi89 Nice model :D

**Comment by tobyplowy** [comment]
@chengzzi89 still like your model more.

**Comment by lipki** [comment]
![campfire_fire](https://user-images.githubusercontent.com/401965/51748994-6b69b980-20ae-11e9-935c-aa75ff65ac90.png)![campfire_log](https://user-images.githubusercontent.com/401965/51748995-6c025000-20ae-11e9-8147-749a5d5fdc65.png)![campfire_log_lit](https://user-images.githubusercontent.com/401965/51748996-6c025000-20ae-11e9-8013-1ee050da8156.png)
![particles](https://user-images.githubusercontent.com/401965/51749027-7f152000-20ae-11e9-9fe6-c04f1504512d.png)
![capture du 2019-01-25 14-32-43](https://user-images.githubusercontent.com/401965/51748963-512fdb80-20ae-11e9-9a06-2c685f0fec88.png)

**Comment by tobyplowy** [comment]
@lipki I'm not sure about the smoke texture.
It looks a bit odd.

Maybe make it have a swirl, a bit like this animation https://www.spriters-resource.com/game_boy_advance/thelegendofzeldatheminishcap/sheet/37862/

**Comment by lipki** [comment]
Yes why not.
Particles are not animated, they move up.

**Comment by lipki** [comment]
Look for yourself, you will understand.

**Comment by lipki** [comment]
![ezgif com-apng-to-gif](https://user-images.githubusercontent.com/401965/51788099-79850c00-217a-11e9-83fd-ebb3595b4e46.gif)

**Comment by tobyplowy** [comment]
@lipki Done?

**Comment by lipki** [comment]
ok, I understand.

**Comment by lipki** [comment]
![53683619-e1acac00-3d3d-11e9-8130-bb618339c890](https://user-images.githubusercontent.com/401965/56118243-24cb8300-5f6a-11e9-8432-38d2a75df906.png)
![campfire_log_lit](https://user-images.githubusercontent.com/401965/56118225-18472a80-5f6a-11e9-9485-7d472fa002bd.png)

**Comment by chengzzi89** [comment]
> @ chengzzi89
> ![53683619-e1acac00-3d3d-11e9-8130-bb618339c890](https://user-images.githubusercontent.com/401965/56118243-24cb8300-5f6a-11e9-8432-38d2a75df906.png)
> ![campfire_log_lit](https://user-images.githubusercontent.com/401965/56118225-18472a80-5f6a-11e9-9485-7d472fa002bd.png)

@lipki 
Thank you!
