### ISSUE TITLE
[1.14] Composter

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#498]
composter_top
![composter_top](https://user-images.githubusercontent.com/16853304/51291048-1a9af680-1a06-11e9-8639-ab40282e4439.png)
composter_bottom
![composter_bottom](https://user-images.githubusercontent.com/16853304/51291049-1a9af680-1a06-11e9-981e-d6d39eaa70a8.png)
composter_compost
![composter_compost](https://user-images.githubusercontent.com/16853304/51291050-1b338d00-1a06-11e9-8527-7b6e36a20de2.png)
composter_ready
![composter_ready](https://user-images.githubusercontent.com/16853304/51291051-1b338d00-1a06-11e9-8783-62591d165eb9.png)
composter_side
![composter_side](https://user-images.githubusercontent.com/16853304/51291052-1b338d00-1a06-11e9-9479-d69397e53956.png)

**Comment by lipki** [comment]
![composter_bottom](https://user-images.githubusercontent.com/401965/51710558-d8873b80-2029-11e9-911d-8f16dbc3e72b.png)![composter_compost](https://user-images.githubusercontent.com/401965/51710569-dcb35900-2029-11e9-883f-b4703c8dd727.png)![composter_ready](https://user-images.githubusercontent.com/401965/51710570-dcb35900-2029-11e9-8190-8c99c5c5576a.png)![composter_side](https://user-images.githubusercontent.com/401965/51710571-dd4bef80-2029-11e9-8d08-716544f5644c.png)![composter_top](https://user-images.githubusercontent.com/401965/51710573-dde48600-2029-11e9-82a4-69d30fb669a0.png)
![capture du 2019-01-24 22-41-54](https://user-images.githubusercontent.com/401965/51710500-b2619b80-2029-11e9-87b7-ebe87e2213c3.png)

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by tobyplowy** [comment]
Also looking nice :)
I really like the compost texture, good job!

**Comment by lipki** [comment]
![composter_bottom](https://user-images.githubusercontent.com/401965/51710558-d8873b80-2029-11e9-911d-8f16dbc3e72b.png)![composter_compost](https://user-images.githubusercontent.com/401965/51710569-dcb35900-2029-11e9-883f-b4703c8dd727.png)![composter_ready](https://user-images.githubusercontent.com/401965/51710570-dcb35900-2029-11e9-8190-8c99c5c5576a.png)![composter_side](https://user-images.githubusercontent.com/401965/51710571-dd4bef80-2029-11e9-8d08-716544f5644c.png)![composter_top](https://user-images.githubusercontent.com/401965/51710573-dde48600-2029-11e9-82a4-69d30fb669a0.png)
![capture du 2019-01-24 22-41-54](https://user-images.githubusercontent.com/401965/51710500-b2619b80-2029-11e9-87b7-ebe87e2213c3.png)
