### ISSUE TITLE
[1.14 Villager] Wandering trader

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#499]
There was not enough! Here is a new villager.
![wandering_trader](https://user-images.githubusercontent.com/401965/52119587-d1f45780-2619-11e9-8e2e-65ec7c832122.png)![trader_llama](https://user-images.githubusercontent.com/401965/52119591-d3be1b00-2619-11e9-84f2-f77ea53deddd.png)
![capture du 2019-02-01 12-04-37](https://user-images.githubusercontent.com/401965/52119581-cc970d00-2619-11e9-9d39-724645a67ae7.png)

**Comment by tobyplowy** [comment]
I will give this a try if that's alright.

**Comment by lipki** [comment]
:D

**Comment by tobyplowy** [comment]
@lipki Done or do I make him more colorful?

**Comment by lipki** [comment]
We have time to decide.

**Comment by tobyplowy** [comment]
@lipki maybe it would be nice to just completely desaturate the wandering trader and make him feel even less colorful, so he is a real boring business man :,D
Same for the lama.

**Comment by tobyplowy** [comment]
![52150385-1d395500-2670-11e9-8b3e-ff34707e0496](https://user-images.githubusercontent.com/16853304/53349728-05c35400-391e-11e9-8ca9-0286941fca4f.png)
