### ISSUE TITLE
[1.14] splash screen

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#500]
![mojang](https://user-images.githubusercontent.com/401965/52526843-5ea8b080-2cbf-11e9-8792-ff93cc25f5ff.png)

**Comment by lipki** [comment]
Proposal
![mojang](https://user-images.githubusercontent.com/401965/52526847-6a947280-2cbf-11e9-9d0a-8c961eec05e6.png)

**Comment by tobyplowy** [comment]
@lipki looks good to me.
I like the notch apple a lot :)

**Comment by tobyplowy** [comment]
@lipki Done?

**Comment by lipki** [comment]
It does not work anymore: /
