### ISSUE TITLE
Light gray glass and gray glass are opposite

### ISSUE THREAD

**Issue by BaronJPN** [SummerFields/SummerFields#501]
Hello. Thank you for the wonderful texture.

Light gray glass and gray glass seem to be opposite.
Compare the following images.

https://github.com/SummerFields/SummerFields/blob/master/assets/minecraft/textures/block/gray_stained_glass.png
https://github.com/SummerFields/SummerFields/blob/master/assets/minecraft/textures/block/light_gray_stained_glass.png

I would be grateful if you could fix.

**Comment by lipki** [comment]
Thank you.
Do not hesitate to come back here to criticize our work.

**Comment by tobyplowy** [comment]
@lipki Can you resolve this?

**Comment by lipki** [comment]
It is done it will merge with the next update.
