### ISSUE TITLE
[1.14] Separated painting

### ISSUE THREAD

**Issue by chengzzi89** [SummerFields/SummerFields#502]
I really want to know why mojang wants to do this?😂

![alban](https://user-images.githubusercontent.com/28303754/52816597-98712100-30dc-11e9-82ec-8b1fccaedcc9.png)
![aztec](https://user-images.githubusercontent.com/28303754/52816632-a8890080-30dc-11e9-96bb-b8548bd32ea6.png)
![aztec2](https://user-images.githubusercontent.com/28303754/52816726-d66e4500-30dc-11e9-9468-6a919164fe8a.png)
![bomb](https://user-images.githubusercontent.com/28303754/52816745-e38b3400-30dc-11e9-9f84-76b1f742bc6b.png)
![burning_skull](https://user-images.githubusercontent.com/28303754/52816756-eab24200-30dc-11e9-9904-9a4973ca5eb8.png)
![bust](https://user-images.githubusercontent.com/28303754/52816770-f271e680-30dc-11e9-8c4a-9b470fc229b7.png)
![courbet](https://user-images.githubusercontent.com/28303754/52816779-f9005e00-30dc-11e9-9fee-df9d91625f7d.png)
![creebet](https://user-images.githubusercontent.com/28303754/52816792-ff8ed580-30dc-11e9-8b92-b743b3af4c8c.png)
![donkey_kong](https://user-images.githubusercontent.com/28303754/52816799-06b5e380-30dd-11e9-9692-e640882dfc00.png)
![fighters](https://user-images.githubusercontent.com/28303754/52816809-0ae20100-30dd-11e9-91f8-e656ff9d8d59.png)
![graham](https://user-images.githubusercontent.com/28303754/52816819-12090f00-30dd-11e9-9a14-6a6d2209e9a0.png)
![kebab](https://user-images.githubusercontent.com/28303754/52816834-18978680-30dd-11e9-90ac-ffff01395c7c.png)
![match](https://user-images.githubusercontent.com/28303754/52816849-1df4d100-30dd-11e9-832a-316d3eba5bd1.png)
![pigscene](https://user-images.githubusercontent.com/28303754/52816861-26e5a280-30dd-11e9-96fb-526b63203acd.png)
![plant](https://user-images.githubusercontent.com/28303754/52816869-2d741a00-30dd-11e9-8680-fe95d5c696b4.png)
![pointer](https://user-images.githubusercontent.com/28303754/52816883-34029180-30dd-11e9-9c0d-28bbc209d571.png)
![pool](https://user-images.githubusercontent.com/28303754/52816897-3d8bf980-30dd-11e9-9c00-171a8357db9e.png)
![sea](https://user-images.githubusercontent.com/28303754/52816916-45e43480-30dd-11e9-9753-157fd3af72cb.png)
![skeleton](https://user-images.githubusercontent.com/28303754/52816935-509ec980-30dd-11e9-80bf-fa11e2f3136f.png)
![skull_and_roses](https://user-images.githubusercontent.com/28303754/52816951-58f70480-30dd-11e9-9109-696b88a1b68d.png)
![stage](https://user-images.githubusercontent.com/28303754/52816957-61e7d600-30dd-11e9-8b3e-feab703466ce.png)
![sunset](https://user-images.githubusercontent.com/28303754/52816969-6ca26b00-30dd-11e9-8b0d-6be4e8da85c4.png)
![void](https://user-images.githubusercontent.com/28303754/52816976-74620f80-30dd-11e9-9449-8d18d917f42f.png)
![wanderer](https://user-images.githubusercontent.com/28303754/52816994-82179500-30dd-11e9-9f5c-a39c669588ce.png)
![wasteland](https://user-images.githubusercontent.com/28303754/52817009-89d73980-30dd-11e9-8352-e72bd7358e69.png)
![wither](https://user-images.githubusercontent.com/28303754/52817017-8fcd1a80-30dd-11e9-8ed5-645ebe920829.png)

**Comment by lipki** [comment]
It's much easier to add new ones.
This is the next step after what they start in beta 1.6.

And we can make animated painting.

**Comment by tobyplowy** [comment]
@chengzzi89 Thanks for doing this.
@lipki Done?
Maybe we also need to split up the alternative painting?

**Comment by chengzzi89** [comment]
@lipki Another painting is also necessary to open! Please give it to me!

**Comment by tobyplowy** [comment]
Actually making new paintings would be interesting.

**Comment by chengzzi89** [comment]
I tried to do one!😅
![1550247775682](https://user-images.githubusercontent.com/28303754/52872643-fdce1c00-3187-11e9-8ca4-5ec515495c6e.gif)
![1550250699913](https://user-images.githubusercontent.com/28303754/52872659-06beed80-3188-11e9-9f0c-005887987131.png)

**Comment by lipki** [comment]
done :)
I was looking for pictures at "Fool" who already provided some painting.

![alban](https://user-images.githubusercontent.com/401965/52878055-11fc2400-315c-11e9-8dea-4c3759270417.png)![aztec](https://user-images.githubusercontent.com/401965/52878056-11fc2400-315c-11e9-8c56-da6832489e88.png)![aztec2](https://user-images.githubusercontent.com/401965/52878057-11fc2400-315c-11e9-8951-e46fe552667d.png)![bomb](https://user-images.githubusercontent.com/401965/52878059-11fc2400-315c-11e9-9820-5d7d1a089171.png)![kebab](https://user-images.githubusercontent.com/401965/52878060-1294ba80-315c-11e9-9eda-63c669c73ccf.png)![plant](https://user-images.githubusercontent.com/401965/52878063-132d5100-315c-11e9-9234-fd2e04cb8881.png)![wasteland](https://user-images.githubusercontent.com/401965/52878064-132d5100-315c-11e9-89ce-1d7fe93e173b.png)
![courbet](https://user-images.githubusercontent.com/401965/52878100-293b1180-315c-11e9-917c-e103c8dfc496.png)![creebet](https://user-images.githubusercontent.com/401965/52878101-293b1180-315c-11e9-9add-94c55de92c19.png)![pool](https://user-images.githubusercontent.com/401965/52878102-29d3a800-315c-11e9-8482-4d166a18f0e0.png)![sea](https://user-images.githubusercontent.com/401965/52878104-29d3a800-315c-11e9-81e2-429e4ba11b91.png)![sunset](https://user-images.githubusercontent.com/401965/52878105-29d3a800-315c-11e9-832e-1fcccd01a759.png)
![graham](https://user-images.githubusercontent.com/401965/52878172-4b349400-315c-11e9-805f-02ad20f37906.png)![wanderer](https://user-images.githubusercontent.com/401965/52878178-4c65c100-315c-11e9-9b53-675df098ec52.png)![bust](https://user-images.githubusercontent.com/401965/52878171-4b349400-315c-11e9-812b-2ba3ac46217f.png)![match](https://user-images.githubusercontent.com/401965/52878173-4bcd2a80-315c-11e9-96e8-61e3c5de59cb.png)![skull_and_roses](https://user-images.githubusercontent.com/401965/52878174-4bcd2a80-315c-11e9-8968-af53df908327.png)![stage](https://user-images.githubusercontent.com/401965/52878176-4bcd2a80-315c-11e9-8bc7-d16f881f6600.png)![void](https://user-images.githubusercontent.com/401965/52878177-4c65c100-315c-11e9-9b25-f0ace4ee59d1.png)![wither](https://user-images.githubusercontent.com/401965/52878179-4c65c100-315c-11e9-8e75-ffa1a2aa9661.png)![fighters](https://user-images.githubusercontent.com/401965/52878248-73bc8e00-315c-11e9-81cc-9d2fa9757270.png)
![donkey_kong](https://user-images.githubusercontent.com/401965/52878282-8767f480-315c-11e9-9823-0f4b5bbdb9a4.png)![skeleton](https://user-images.githubusercontent.com/401965/52878283-88008b00-315c-11e9-9684-d18dae0c32d6.png)
![burning_skull](https://user-images.githubusercontent.com/401965/52878306-9189f300-315c-11e9-9b90-19174b213b64.png)![pigscene](https://user-images.githubusercontent.com/401965/52878307-9189f300-315c-11e9-84fe-45dcb71afd80.png)![pointer](https://user-images.githubusercontent.com/401965/52878308-9189f300-315c-11e9-9972-f46fee1b5ce1.png)

**Comment by CuddleWoozle** [comment]
Just make sure it's still OK to use Fools artwork.  They do a lot of pixel
art and such but my worry is that they'll be upset.

There is no longer a way to credit within the art file itself.

**Comment by CuddleWoozle** [comment]
Also the alternative paintings are small focused selections of real fine
art paintings.  I made them using images taken from art museum websites.
Their virtual collections.

I would have to figure out which paintings and artists to properly credit
them.

**Comment by lipki** [comment]
I add a txt file with the credits.
And I found the authors of most of the painting.
thanks to google image.

**Comment by tobyplowy** [comment]
Fool is just so good at pixelart.
I'm jealous.
