### ISSUE TITLE
[1.14] Fox

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#503]
I'm already working on it.

**Comment by tobyplowy** [comment]
My proposal.
Fox
![fox](https://user-images.githubusercontent.com/16853304/52833163-e8031d00-30db-11e9-9bae-63124d595f97.png)
![fox_sleep](https://user-images.githubusercontent.com/16853304/52833164-e9344a00-30db-11e9-950a-3d46fc4970ab.png)
Snow fox
![snow_fox](https://user-images.githubusercontent.com/16853304/52833165-ea657700-30db-11e9-840a-f7974e098938.png)
![snow_fox_sleep](https://user-images.githubusercontent.com/16853304/52833167-eb96a400-30db-11e9-80c8-02d6b5211ea8.png)

**Comment by lipki** [comment]
You're too strong, you have to teach me how to make textures.
;)

**Comment by lipki** [comment]
![capture du 2019-02-15 13-45-20](https://user-images.githubusercontent.com/401965/52857675-16a6e500-3128-11e9-9fee-0b0fba1f3892.png)

**Comment by chengzzi89** [comment]
@tobyplowy nice！👏👏👍

**Comment by tobyplowy** [comment]
Thanks guys =D

**Comment by tobyplowy** [comment]
@lipki can we consider this done?

**Comment by lipki** [comment]
yep
