### ISSUE TITLE
Close snapshot-17w48a branch and open branch for 1.14

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#504]
![image](https://user-images.githubusercontent.com/16853304/53120813-f7a6b980-3552-11e9-87c7-d5ec90154d82.png)

**Comment by lipki** [comment]
let me do my thing.

**Comment by tobyplowy** [comment]
@lipki ok.
So that is a no?

**Comment by lipki** [comment]
For the snapshot, I do not really know what's inside.
The 1.14 remains in the master branch for now, the branch will be created at the time of the release.
