### ISSUE TITLE
[1.14] Brown Mooshroom

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#505]
![brown_mooshroom](https://user-images.githubusercontent.com/401965/53133706-5a5c7d00-3574-11e9-9787-7607e06929c1.png)

**Comment by lipki** [comment]
![brown_mooshroom](https://user-images.githubusercontent.com/401965/53133714-61838b00-3574-11e9-8d8d-0537afa5f1de.png)

**Comment by lipki** [comment]
![capture du 2019-02-21 01-08-54](https://user-images.githubusercontent.com/401965/53134067-ddca9e00-3575-11e9-9a14-2c013d974da5.png)

**Comment by tobyplowy** [comment]
@lipki Nice.
Is this done?

**Comment by lipki** [comment]
yep
