### ISSUE TITLE
[1.14] Separated particles

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#507]
They have also separated the particles.

**Comment by tobyplowy** [comment]
@chengzzi89 Are you interested in doing this one?

**Comment by chengzzi89** [comment]
@tobyplowy OK！

**Comment by chengzzi89** [comment]
https://www.dropbox.com/s/usawvc5ehy3tp0y/particle.zip?dl=0

**Comment by tobyplowy** [comment]
@chengzzi89 Nice :D
Make sure to keep that link working until we merge it :D
