### ISSUE TITLE
[1.14 Villager] GUI

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#508]
![villager](https://user-images.githubusercontent.com/401965/54376759-0aa93700-4684-11e9-8f96-bd0c0f9d0865.png)

19w13b

![villager2](https://user-images.githubusercontent.com/401965/55281271-46095e00-5332-11e9-88bf-1c4c108f06de.png)

**Comment by tobyplowy** [comment]
![54376759-0aa93700-4684-11e9-8f96-bd0c0f9d0865](https://user-images.githubusercontent.com/16853304/54479209-e5026600-481a-11e9-95f0-132c58e2dc8b.png)

**Comment by lipki** [comment]
We must be able to do better.
![Capture du 2019-03-17 14-37-37](https://user-images.githubusercontent.com/401965/54491956-cf487b80-48c2-11e9-845d-42afb199e0d4.png)

**Comment by lipki** [comment]
![Capture du 2019-03-17 14-56-24](https://user-images.githubusercontent.com/401965/54498809-dc3d8d00-490b-11e9-93ae-15244f3e36bf.png)
![villager](https://user-images.githubusercontent.com/401965/54498819-ef505d00-490b-11e9-8a32-61a5d09f51d9.png)

**Comment by tobyplowy** [comment]
Nice improvement :)

**Comment by lipki** [comment]
we change everything ...
19w13b

![villager2](https://user-images.githubusercontent.com/401965/55281271-46095e00-5332-11e9-88bf-1c4c108f06de.png)

**Comment by lipki** [comment]
![villager2](https://user-images.githubusercontent.com/401965/55282445-41e63c00-5344-11e9-8137-f01860655457.png)

![Capture du 2019-03-30 23-33-20](https://user-images.githubusercontent.com/401965/55282452-57f3fc80-5344-11e9-9910-ae6323c9d7d3.png)

**Comment by tobyplowy** [comment]
Looking good :)
