### ISSUE TITLE
Redo chicken and beef item textures

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#509]
They look like the minecraft textures but upscaled in a very lazy way.
Especially the chicken needs a redo.

**Comment by tobyplowy** [comment]
@lipki Ping

**Comment by lipki** [comment]
yes,yes, why not

**Comment by lipki** [comment]
![Capture du 2019-03-17 14-54-48](https://user-images.githubusercontent.com/401965/54492229-0586fa80-48c5-11e9-9c7e-65563f6b3e8c.png)

**Comment by tobyplowy** [comment]
I think the mutton looks good.
The chicken needs to be completely redone.
The rest needs some small improvements.
@lipki you interested in taking this task?

**Comment by lipki** [comment]
![chicken](https://user-images.githubusercontent.com/401965/54538561-c031fe00-4994-11e9-8247-d733959f05d4.png)![cooked_chicken](https://user-images.githubusercontent.com/401965/54538569-c3c58500-4994-11e9-93cf-f7f7dc03bc49.png) ?

**Comment by tobyplowy** [comment]
Yeah that does look a little odd :'D
Also does not look like chicken at all.

**Comment by lipki** [comment]
:D

**Comment by jaygradon** [comment]
I have had a go at some new pork textures

![cooked_porkchop](https://user-images.githubusercontent.com/16079512/63647238-33287780-c772-11e9-9a1f-ceea2ba2b64d.png)
![porkchop](https://user-images.githubusercontent.com/16079512/63647239-33c10e00-c772-11e9-9b7a-869c1b5df691.png)

Here is a take on a chicken drumstick (not sure if they fit well enough)

![chicken](https://user-images.githubusercontent.com/16079512/63647246-48050b00-c772-11e9-9e44-f49452246c38.png)
![cooked_chicken](https://user-images.githubusercontent.com/16079512/63647247-48050b00-c772-11e9-93d7-c2c884be677d.png)

**Comment by lipki** [comment]
I like the chicken

I made changes, and I add the rabbit, what do you think?

![cooked_chicken](https://user-images.githubusercontent.com/401965/71112231-5799db00-21cb-11ea-8b39-0c5571b8d12f.png)![chicken](https://user-images.githubusercontent.com/401965/71112245-5e285280-21cb-11ea-8e21-e54f7f315e71.png)
![cooked_porkchop](https://user-images.githubusercontent.com/401965/71112232-58327180-21cb-11ea-9bac-c0f03ac00508.png)![porkchop](https://user-images.githubusercontent.com/401965/71112264-697b7e00-21cb-11ea-853c-8da2dcbbe95c.png)
![cooked_rabbit](https://user-images.githubusercontent.com/401965/71112233-58327180-21cb-11ea-93eb-8ccdbce87b83.png)![rabbit](https://user-images.githubusercontent.com/401965/71112255-641e3380-21cb-11ea-8346-157fd6615d81.png)

**Comment by tobyplowy** [comment]
@lipki Yeah it's getting there... Just needs a bit more contrast and complexity in the texture I think?
