### ISSUE TITLE
[1.14] accessibility button

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#520]
![accessibility](https://user-images.githubusercontent.com/401965/55281314-cd56d180-5332-11e9-9a31-564e109e13fb.png)

**Comment by lipki** [comment]
![accessibility](https://user-images.githubusercontent.com/401965/55281485-5ff87000-5335-11e9-8ab9-36b52f13991f.png)

**Comment by tobyplowy** [comment]
Nice. Done?
