### ISSUE TITLE
[1.14] hero of the village

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#521]
![hero_of_the_village](https://user-images.githubusercontent.com/401965/55281351-7c93a880-5333-11e9-9e2e-5bdb99a977bf.png)

**Comment by tobyplowy** [comment]
@lipki How's this?
![hero of the village](https://user-images.githubusercontent.com/16853304/56137758-cb794900-5f95-11e9-89f1-557ea0e17b2f.png)

**Comment by lipki** [comment]
We win that when we finish a raid.

**Comment by tobyplowy** [comment]
Yeah...?
So is it good?

**Comment by tobyplowy** [comment]
@lipki Ping want me to make to something different?

**Comment by lipki** [comment]
yep is good.

**Comment by tobyplowy** [comment]
Lt's get this merged.
