### ISSUE TITLE
Acacia button textures have not changed

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#546]
For some reason it is using the standard way of mapping the textures on to the button.
![image](https://user-images.githubusercontent.com/16853304/57978007-62f21180-7a04-11e9-8f41-4f4ca2b384ab.png)

**Comment by tobyplowy** [comment]
@lipki @chengzzi89 In the top image you can see that the left and right buttons are correct.
I have attempted to fix it but I do not understand at all why this is happening.

**Comment by tobyplowy** [comment]
Fixed by https://github.com/SummerFields/SummerFields/pull/548

**Comment by lipki** [comment]
I did not understand why, that's why I left it.
Cool, you have find.

**Comment by tobyplowy** [comment]
Yup. It was hard but I did it =D
Also welcome back, SO happy to see you again.
