### ISSUE TITLE
Lithiumsound's other packs need a home

### ISSUE THREAD

**Issue by lunapanshiel** [SummerFields/SummerFields#547]
Lithiumsound, the creator of summerfields, had two other texture packs they had created and have unfortunately been mostly forgotten, with the closure of the minecraft forum there needs to be a place for them to be preserved and possibly updated

the first and reasonably well-known is greatwood, a 16x texture pack designed to be similar to summerfields, which I have put in a lot of effort to make it work for 1.14 but it's far from complete http://www.mediafire.com/file/itt9kcali93tf9e/Greatwood_Continuation_WIP_for_1.14.zip/file

the second is one that has been completely forgotten is a precious treasure called ToyBoxTales, it is a 32x texture pack and a sister to summerfields, i strongly believe it should be restored as an addon pack to summerfields to give it a different feel, it is unfortunately so old that the forum thread has been deleted. Summerfields uses textures made for ToyBoxTales for the end

http://www.mediafire.com/file/py5fnre1g6kbbqb/ToyBoxTales_v5_%252810-08-12%2529.zip/file

an image of ToyBoxTales old terrain.png so you understand what it looks like, complete with it's striped end stone https://i.imgur.com/BMuRh9K.png

lithiumsound's deviantart still mentions that they created it https://www.deviantart.com/lithium-sound

it would be nice to have a repository for these packs set up so they can be expanded and restored

PS: i'm the person who upgraded potted flowers use different textures from the ones on the ground to fix the issue of plants poking through pots, and you forgot to credit me

Edit: replaced the ToyBoxTales download with a pure, unedited version, the last release lithiumsound made before abandoning it

**Comment by tobyplowy** [comment]
I am interested in this if lipki is.
@lipki Are you interested?

**Comment by lipki** [comment]
I agree to help make a "repo" for GreatWood, I'm curious to see the result in 1.14.
I'm thinking of a separate "repo" because it's different from SummerFields.

I did not know about ToyBoxTales. Make it an addon, why not! The addons are boring to manage, it must be said, they are never updated. But why not.

Sorry for the lack of credit.
When I did the repo, I did a lot of research to understand who did what, when.
I probably did miss a lot.

**Comment by tobyplowy** [comment]
@lipki I want to help with GreatWood =D

**Comment by tobyplowy** [comment]
Bdw GreatWood looks a lot like SummerFields so why not put it in the SummerFields repo?
I'm sure it would be fine =D

**Comment by lipki** [comment]
Because I'm obsessive :)
But it may not be up to me to decide after all.

**Comment by tobyplowy** [comment]
@lipki It is up to you to decide =D
We are a team and I say we do whatever you think is best.
I'm just happy to help as always =D

**Comment by lipki** [comment]
Following this conversation ... is happening here for the GreatWood.
https://github.com/greatwood-minecraft/greatwood
