### ISSUE TITLE
switch texture packs

### ISSUE THREAD

**Issue by angel8808301798** [SummerFields/SummerFields#549]
I hope you can make the summer fields texture packs gor switch!!!! I really like the summer fields texture packs!!!! If it can be real I will buy it!!!

**Comment by tobyplowy** [comment]
First of all hello welcome on our GitHub page =D
Yeah that is not really how it works...
You have to get the approval of Microsoft first. and even if we get it I do not think it's a good idea to put SummerFields on the "minecraft" store. I am also very sure that lipki and CuddleWoozle agree with this. Also we still have the packs license, which explicitly states no commercial use.

So I here by state that this can't happen what you can do however is help us by supporting us.
Thanks for being a fan of the SummerFields pack =D

**Comment by tobyplowy** [comment]
You can support me on patreon if you want. this will help me keep this pack updated becouse right now I'm the only one that is working on it.
https://www.patreon.com/toby109tt
