### ISSUE TITLE
Terrafirmacraft 1.7.x link doesnt work properly

### ISSUE THREAD

**Issue by intrushok** [SummerFields/SummerFields#552]
The link from site:
![1](https://user-images.githubusercontent.com/50256886/64621067-b93cf300-d3ed-11e9-8aea-1e2a317dcded.png)
When GitHub loads:
![3](https://user-images.githubusercontent.com/50256886/64621081-bf32d400-d3ed-11e9-9584-108be25c888f.png)
What I found in google:
![2](https://user-images.githubusercontent.com/50256886/64621103-c78b0f00-d3ed-11e9-805a-71771f3da9ac.png)
Please correct the link error in the site.

**Comment by lipki** [comment]
I just tested, it works well ...
