### ISSUE TITLE
Downloaded the master and it doesn't appear in my resource packs menu

### ISSUE THREAD

**Issue by JohnsanGeezo** [SummerFields/SummerFields#555]
Tried renaming it, tried adding the new flowing lava from another issue to myexisting pack, and it doesn't work. Can someone help?

I can't bring myself to use another resource pack after using this one for 5 years...

**Comment by tobyplowy** [comment]
If you are ruing it on java check inside the zip and see if the files are in the correct structure.
I should be (Name of zip)/assets/minecraft
If it's not like that then you may reed to re pack.

**Comment by JohnsanGeezo** [comment]
> If you are ruing it on java check inside the zip and see if the files are in the correct structure.
> I should be (Name of zip)/assets/minecraft
> If it's not like that then you may need to re pack.

Yeah the file structure looks ok. There's a few other files under (name of zip) with assets - license, pack.mcdata, pack.png and readme. Don't think that matters though.

Still doesn't work. Any other suggestions?

**Comment by tobyplowy** [comment]
Huh...
Perhaps you are running a minecraft version that's too old?
Also make sure that you are running java edition.

**Comment by JohnsanGeezo** [comment]
Definitely Java, and definitely the latest version. 1.14.4.

**Comment by tobyplowy** [comment]
Hmmm, well I'm confused...
Maybe show me a picture of what's in the zip?

**Comment by JohnsanGeezo** [comment]
Ok I've got it working (there was an extra copy of the home folder in there). Thanks for the help, and sorry for being a pain! So glad it's working again.
