### ISSUE TITLE
When is 1.14!!!!

### ISSUE THREAD

**Issue by KaitoAomiOokami** [SummerFields/SummerFields#558]
the 1.15 is coming out !!! where is 1.14!! I really like this texture pack plz make it!!

**Comment by chengzzi89** [comment]
This package is still in production, please don't worry!

**Comment by tobyplowy** [comment]
@KaitoAomiOokami Can you "plz" have some patience.
I am currently working on epic adventures (My other pack)
https://www.planetminecraft.com/texture_pack/epic-adventures-by-toby109tt-x32-wip/
So it may be a while untill I get back to summerfealds.
Please just be patient. Thank you.

**Comment by tobyplowy** [comment]
@KaitoAomiOokami Currently working on the update.
Please have a look at my patreon to support me. https://www.patreon.com/toby109tt
More support means more progress =D
