### ISSUE TITLE
[1.15]bee nest

### ISSUE THREAD

**Issue by chengzzi89** [SummerFields/SummerFields#582]
![bee_nest_front_honey](https://user-images.githubusercontent.com/28303754/71295044-5c21e780-23b5-11ea-81fe-e0f2ebfe1d17.png)
![bee_nest_front](https://user-images.githubusercontent.com/28303754/71295069-6fcd4e00-23b5-11ea-919a-931bef4f0500.png)
![bee_nest_side](https://user-images.githubusercontent.com/28303754/71295084-78be1f80-23b5-11ea-8e9f-8a28b2a47271.png)

**Comment by lipki** [comment]
![bee_nest_bottom](https://user-images.githubusercontent.com/401965/71298263-9c6a7100-2387-11ea-91a6-5659f7068769.png)![bee_nest_front](https://user-images.githubusercontent.com/401965/71298264-9c6a7100-2387-11ea-9a85-cdf42ba472f2.png)![bee_nest_front_honey](https://user-images.githubusercontent.com/401965/71298265-9c6a7100-2387-11ea-9d01-f14ec1d94ea9.png)![bee_nest_side](https://user-images.githubusercontent.com/401965/71298266-9c6a7100-2387-11ea-8ad8-c907848150de.png)![bee_nest_top](https://user-images.githubusercontent.com/401965/71298267-9d030780-2387-11ea-8881-d7432166d80b.png)

**Comment by lipki** [comment]
I find the pictures a little blurry, but I like the design.

**Comment by tobyplowy** [comment]
@chengzzi89 I agree with lipki.
Nice texture but a bit blurry.
Also the holes in the hive look a bit strange. And there is not bottom and top texture.

**Comment by chengzzi89** [comment]
@tobyplowy This is only a manuscript, or was required by you put it modified summerfields style texture!😅😅XD

**Comment by tobyplowy** [comment]
@chengzzi89 Can you update it?

**Comment by chengzzi89** [comment]
@tobyplowy 😅
![bee_nest_top](https://user-images.githubusercontent.com/28303754/71321366-3f8bc980-24f3-11ea-96e9-5abd8b0f07ff.png)![bee_nest_side](https://user-images.githubusercontent.com/28303754/71321506-2421be00-24f5-11ea-915e-ace0d49c4825.png)![bee_nest_front](https://user-images.githubusercontent.com/28303754/71321508-2c79f900-24f5-11ea-8326-a8e98f69768e.png)![bee_nest_front_honey](https://user-images.githubusercontent.com/28303754/71321511-326fda00-24f5-11ea-9b17-1ad0d93e585b.png)![bee_nest_bottom](https://user-images.githubusercontent.com/28303754/71321516-3865bb00-24f5-11ea-9b69-e308d0c40621.png)

**Comment by tobyplowy** [comment]
@chengzzi89 Very nice.
@lipki What do you think?
