### ISSUE TITLE
[1.15] honey_block

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#585]
![honey_block_bottom](https://user-images.githubusercontent.com/401965/71298301-bf952080-2387-11ea-8cab-4d1ae6815554.png)![honey_block_side](https://user-images.githubusercontent.com/401965/71298302-bf952080-2387-11ea-98d4-b550272426f8.png)![honey_block_top](https://user-images.githubusercontent.com/401965/71298303-c02db700-2387-11ea-8a8c-fc48b3938dda.png)
![honey_bottle](https://user-images.githubusercontent.com/401965/71298765-fec47100-2389-11ea-827c-d7aa3949b78d.png)

**Comment by tobyplowy** [comment]
@lipki There are already honey textures in the repo.

**Comment by lipki** [comment]
yes yes

**Comment by tobyplowy** [comment]
=D

**Comment by lipki** [comment]
by @Snykeurs 
![honey_bottle](https://user-images.githubusercontent.com/401965/71300786-78635b80-2398-11ea-9ba7-bf83808c09e6.png)

THIS STUPID HONEY IS GETTING ON NERVES OF @tobyplowy 
![honey_block_bottom](https://user-images.githubusercontent.com/401965/71300798-8dd88580-2398-11ea-84f0-e50e17bec52f.png)![honey_block_side](https://user-images.githubusercontent.com/401965/71300799-8e711c00-2398-11ea-8a81-4f8f3858a8a2.png)![honey_block_top](https://user-images.githubusercontent.com/401965/71300800-8e711c00-2398-11ea-934d-d4b0e5cd778e.png)
;)

**Comment by tobyplowy** [comment]
@lipki "THIS STUPID HONEY IS GETTING ON NERVES OF @tobyplowy"
Hahaaha Nice! That's really funny actually ;)
