### ISSUE TITLE
[1.15] Bee

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#587]
![bee](https://user-images.githubusercontent.com/401965/71298601-2ff07180-2389-11ea-9880-0937f0764986.png)![bee_angry](https://user-images.githubusercontent.com/401965/71298602-2ff07180-2389-11ea-96dd-fbf958d74eb4.png)![bee_angry_nectar](https://user-images.githubusercontent.com/401965/71298603-2ff07180-2389-11ea-97fb-69b948a901b5.png)![bee_nectar](https://user-images.githubusercontent.com/401965/71298604-2ff07180-2389-11ea-988d-f65218e1634b.png)![bee_stinger](https://user-images.githubusercontent.com/401965/71298605-30890800-2389-11ea-9ff0-c793a900c719.png)

**Comment by lipki** [comment]
Basic
![Capture du 2019-12-22 00-07-08](https://user-images.githubusercontent.com/401965/71314789-b7081d00-244f-11ea-82d3-511575eee09d.png)
![bee](https://user-images.githubusercontent.com/401965/71314790-bd969480-244f-11ea-8d21-668c7e6bcf16.png)![bee_angry](https://user-images.githubusercontent.com/401965/71314791-bd969480-244f-11ea-8951-7fe794fa8b8b.png)![bee_angry_nectar](https://user-images.githubusercontent.com/401965/71314792-be2f2b00-244f-11ea-839d-d34c7b1fb582.png)![bee_nectar](https://user-images.githubusercontent.com/401965/71314793-be2f2b00-244f-11ea-80f0-a2759885cecb.png)

**Comment by tobyplowy** [comment]
@lipki Looks good!

**Comment by tobyplowy** [comment]
@lipki Can you add them?

**Comment by lipki** [comment]
done
