### ISSUE TITLE
1.16 Update Preparation.

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#596]
Changes...
https://minecraft.fandom.com/wiki/1.16_-_Nether_Update

**Comment by tobyplowy** [comment]
Let's wait for the update a bit longer.

**Comment by lipki** [comment]
lol, i make the same, just now.

**Comment by tobyplowy** [comment]
Hahahah =D
I guess I beat you to it XD

**Comment by tobyplowy** [comment]
I will close my issue tho.
