### ISSUE TITLE
[1.16.x] Update Preparation

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#597]
![72-2](https://user-images.githubusercontent.com/401965/72852063-c3310580-3cad-11ea-86f7-e7ba8a8a9317.png) Blue Fire #601

![soul_fire_0](https://user-images.githubusercontent.com/401965/73889493-1db29000-4870-11ea-878a-af06d42fc7f8.png)![soul_fire_1](https://user-images.githubusercontent.com/401965/73889495-2014ea00-4870-11ea-94f3-645f5943058d.png)![soul_fire_lantern](https://user-images.githubusercontent.com/401965/73889512-2acf7f00-4870-11ea-8d67-4450bfa6bf18.png)![soul_fire_torch](https://user-images.githubusercontent.com/401965/73889516-302cc980-4870-11ea-8621-ea852a8d5034.png)![soul_fire_lantern](https://user-images.githubusercontent.com/401965/73890097-6fa7e580-4871-11ea-866f-7f73860d6856.png)
![soul_fire_flame](https://user-images.githubusercontent.com/401965/73890172-a4b43800-4871-11ea-8df8-6a0f11d06caf.png)

![72-7](https://user-images.githubusercontent.com/401965/72852007-8e24b300-3cad-11ea-8a79-9e8990dfead9.png) Warped #599

![warped_door_top](https://user-images.githubusercontent.com/401965/73889692-94e82400-4870-11ea-80a0-99f0187ec2e7.png)
![warped_door_bottom](https://user-images.githubusercontent.com/401965/73889691-944f8d80-4870-11ea-97cf-51c27cb2263b.png)![warped_stem_top](https://user-images.githubusercontent.com/401965/73889703-974a7e00-4870-11ea-91e9-bc84506c6449.png)![warped_trapdoor](https://user-images.githubusercontent.com/401965/73889708-987bab00-4870-11ea-8f47-597bb1a1626c.png)![warped_planks](https://user-images.githubusercontent.com/401965/73889699-96195100-4870-11ea-8376-6676c37df7e2.png)![stripped_warped_stem](https://user-images.githubusercontent.com/401965/73889556-45095d00-4870-11ea-8ca4-4b3e3d48ca3b.png)![stripped_warped_stem_top](https://user-images.githubusercontent.com/401965/73889559-45095d00-4870-11ea-883e-188621a4ed70.png)![warped_stripped_log_side](https://user-images.githubusercontent.com/401965/73889706-974a7e00-4870-11ea-8c0a-138af1bbd47b.png)![warped_stripped_log_top](https://user-images.githubusercontent.com/401965/73889707-97e31480-4870-11ea-9990-f34827c02621.png)

![warped_stem](https://user-images.githubusercontent.com/401965/73889701-96b1e780-4870-11ea-98e4-bca6a5d4cb50.png)![warped_wart_block](https://user-images.githubusercontent.com/401965/73889709-987bab00-4870-11ea-931c-052b6d7b187e.png)![warped_nylium](https://user-images.githubusercontent.com/401965/73889696-9580ba80-4870-11ea-93c9-4a38867acf01.png)![warped_nylium_side](https://user-images.githubusercontent.com/401965/73889698-96195100-4870-11ea-82ae-4b7272ed2cac.png)![nether_sprouts](https://user-images.githubusercontent.com/401965/73889443-f8258680-486f-11ea-806b-0cd7d15fbb93.png)![warped_fungi](https://user-images.githubusercontent.com/401965/73889694-9580ba80-4870-11ea-851d-a43311a86c70.png)![warped_roots](https://user-images.githubusercontent.com/401965/73889700-96b1e780-4870-11ea-977f-783c47dde388.png)

![warped](https://user-images.githubusercontent.com/401965/73889835-d7116580-4870-11ea-8eea-0cf89e457852.png)

![warped_door](https://user-images.githubusercontent.com/401965/73890106-78002080-4871-11ea-950b-9fdaea72fa64.png)![warped_sign](https://user-images.githubusercontent.com/401965/73890108-7898b700-4871-11ea-9b8f-0028ef6df41d.png)

Crimson #600

![crimson_door_top](https://user-images.githubusercontent.com/401965/73889320-b72d7200-486f-11ea-99eb-9e2d26dc682d.png)
![crimson_door_bottom](https://user-images.githubusercontent.com/401965/73889318-b694db80-486f-11ea-98bc-ae2b788bbb59.png)![crimson_stem_top](https://user-images.githubusercontent.com/401965/73889329-b8f73580-486f-11ea-9bce-3f0aee1c8ea2.png)![crimson_trapdoor](https://user-images.githubusercontent.com/401965/73889333-b98fcc00-486f-11ea-9ecb-cc4bfbc0c340.png)![crimson_planks](https://user-images.githubusercontent.com/401965/73889325-b85e9f00-486f-11ea-9383-21f6bd97dae1.png)![stripped_crimson_stem](https://user-images.githubusercontent.com/401965/73889544-40dd3f80-4870-11ea-9f6e-7d0f2a806990.png)![stripped_crimson_stem_top](https://user-images.githubusercontent.com/401965/73889545-4175d600-4870-11ea-857e-e313117404a9.png)

![crimson_stem](https://user-images.githubusercontent.com/401965/73889328-b8f73580-486f-11ea-964b-f5609fc10020.png)![crimson_nylium](https://user-images.githubusercontent.com/401965/73889322-b7c60880-486f-11ea-9a07-751d90fa6566.png)![crimson_nylium_side](https://user-images.githubusercontent.com/401965/73889324-b7c60880-486f-11ea-8fb3-2faf00ab294c.png)![crimson_roots](https://user-images.githubusercontent.com/401965/73889327-b85e9f00-486f-11ea-87e3-6cefac2a3857.png)![crimson_fungi](https://user-images.githubusercontent.com/401965/73889321-b72d7200-486f-11ea-9a76-68f0bef25352.png)![weeping_vines](https://user-images.githubusercontent.com/401965/73889762-b2b58900-4870-11ea-855b-f6e0b1b4947f.png)![weeping_vines_plant](https://user-images.githubusercontent.com/401965/73889765-b3e6b600-4870-11ea-9f9f-0ef39e4bf95f.png)

![crimson](https://user-images.githubusercontent.com/401965/73889834-d7116580-4870-11ea-8452-a70d0e3e2538.png)

![crimson_door](https://user-images.githubusercontent.com/401965/73890004-3cfded00-4871-11ea-942c-c237cd98cb2c.png)![crimson_sign](https://user-images.githubusercontent.com/401965/73890006-3d968380-4871-11ea-8822-3e20244aeeaa.png)

![72-9](https://user-images.githubusercontent.com/401965/72852320-7863bd80-3cae-11ea-8625-456415e24711.png) Shroomlight

![shroomlight](https://user-images.githubusercontent.com/401965/73889473-0e334700-4870-11ea-9b1f-fac68a4cf907.png)

![72-10](https://user-images.githubusercontent.com/401965/72852344-903b4180-3cae-11ea-8dfd-a084a60759d8.png) Basalt  #598

![basalt_side](https://user-images.githubusercontent.com/401965/73889247-8a795a80-486f-11ea-857c-a37b2bea3008.png)![basalt_top](https://user-images.githubusercontent.com/401965/73889249-8b11f100-486f-11ea-837f-a566d97398a5.png)

![soul_soil](https://user-images.githubusercontent.com/401965/73889521-3327ba00-4870-11ea-9ad4-63ca09714144.png)

Netherite #602

![ancient_debris_side](https://user-images.githubusercontent.com/401965/73889233-84837980-486f-11ea-9f60-00cea3308d75.png)![ancient_debris_top](https://user-images.githubusercontent.com/401965/73889237-851c1000-486f-11ea-9495-50de92bf5c24.png)

![netherite_block](https://user-images.githubusercontent.com/401965/73889459-02e01b80-4870-11ea-9513-97e41bbd6a88.png)

![netherite_scrap](https://user-images.githubusercontent.com/401965/73890069-6159c980-4871-11ea-9551-62a9d5ec9579.png)![netherite_ingot](https://user-images.githubusercontent.com/401965/73890064-60289c80-4871-11ea-8407-fc95fbc6808f.png)

![netherite_hoe](https://user-images.githubusercontent.com/401965/73890063-60289c80-4871-11ea-9215-3873e9dcb40c.png)![netherite_shovel](https://user-images.githubusercontent.com/401965/73890070-6159c980-4871-11ea-9ff6-a5b5dd55d63d.png)![netherite_axe](https://user-images.githubusercontent.com/401965/73890058-5ef76f80-4871-11ea-9bea-8f38c3b986ac.png)![netherite_pickaxe](https://user-images.githubusercontent.com/401965/73890068-60c13300-4871-11ea-867c-ec464b8f2fda.png)![netherite_sword](https://user-images.githubusercontent.com/401965/73890072-61f26000-4871-11ea-936d-e4cc5a996aa0.png)

![netherite_boots](https://user-images.githubusercontent.com/401965/73890059-5f900600-4871-11ea-9fe7-9911d9262210.png)![netherite_leggings](https://user-images.githubusercontent.com/401965/73890067-60c13300-4871-11ea-95fe-6ac34bedf262.png)![netherite_chestplate](https://user-images.githubusercontent.com/401965/73890060-5f900600-4871-11ea-86bf-1484eb2bfae2.png)![netherite_helmet](https://user-images.githubusercontent.com/401965/73890062-5f900600-4871-11ea-9942-a9e944d505d0.png)

![netherite_layer_1](https://user-images.githubusercontent.com/401965/73890137-8c441d80-4871-11ea-9740-d0fa3d31d188.png)
![netherite_layer_2](https://user-images.githubusercontent.com/401965/73890138-8cdcb400-4871-11ea-9b69-de047885d8d2.png)

Hoglin #603

![hoglin](https://user-images.githubusercontent.com/401965/73889815-c9f47680-4870-11ea-8d78-2d28c0d2bc61.png)

Piglin

![piglin](https://user-images.githubusercontent.com/401965/74569447-b933b700-4f7a-11ea-8c61-b1c783460adf.png)![zombie_piglin](https://user-images.githubusercontent.com/401965/74569450-b9cc4d80-4f7a-11ea-978f-2a25785366de.png)

![chainmail_piglin_helmet](https://user-images.githubusercontent.com/401965/74569425-af11b880-4f7a-11ea-80b4-9845615b6791.png)![diamond_piglin_helmet](https://user-images.githubusercontent.com/401965/74569427-afaa4f00-4f7a-11ea-91de-488fff2e2769.png)![gold_piglin_helmet](https://user-images.githubusercontent.com/401965/74569428-afaa4f00-4f7a-11ea-9f01-3044e5098df8.png)![iron_piglin_helmet](https://user-images.githubusercontent.com/401965/74569429-b042e580-4f7a-11ea-9fb1-07ef895c5bf3.png)![leather_piglin_helmet](https://user-images.githubusercontent.com/401965/74569430-b042e580-4f7a-11ea-9384-6e319eae9294.png)![leather_piglin_helmet_overlay](https://user-images.githubusercontent.com/401965/74569433-b042e580-4f7a-11ea-88f7-7dc5a2aaaf3c.png)![netherite_piglin_helmet](https://user-images.githubusercontent.com/401965/74569434-b0db7c00-4f7a-11ea-961f-c5de45405156.png)

**Comment by tobyplowy** [comment]
This may also be useful.
https://minecraft.fandom.com/wiki/1.16_-_Nether_Update

**Comment by tobyplowy** [comment]
@lipki I will wait for the update a little before doing any textures but feel free to already start =D

**Comment by lipki** [comment]
I want to do some.

Most importantly, I would like to start thinking about it.

**Comment by tobyplowy** [comment]
Ok. You know what... I will do the mushrooms. and the light block.

**Comment by lipki** [comment]
:)

**Comment by tobyplowy** [comment]
@lipki I'm working on the mushrooms now.

**Comment by lipki** [comment]
snapsooooot :)

**Comment by tobyplowy** [comment]
Yes.
=D

**Comment by tobyplowy** [comment]
Time to get to work =D
I will start tomorrow.

**Comment by lipki** [comment]
![2020-02-05_23 12 42](https://user-images.githubusercontent.com/401965/73888229-8ba98800-486d-11ea-832d-6c7983910baa.png)
![2020-02-05_23 13 32](https://user-images.githubusercontent.com/401965/73888266-9bc16780-486d-11ea-8345-4f9795bb45b8.png)
![2020-02-05_23 14 02](https://user-images.githubusercontent.com/401965/73888306-aed43780-486d-11ea-91f1-86f3d5bd191f.png)
