### ISSUE TITLE
[1.16.X] Warped forest.

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#599]
![warped_door_top](https://user-images.githubusercontent.com/401965/73889692-94e82400-4870-11ea-80a0-99f0187ec2e7.png)
![warped_door_bottom](https://user-images.githubusercontent.com/401965/73889691-944f8d80-4870-11ea-97cf-51c27cb2263b.png)![warped_stem_top](https://user-images.githubusercontent.com/401965/73889703-974a7e00-4870-11ea-91e9-bc84506c6449.png)![warped_trapdoor](https://user-images.githubusercontent.com/401965/73889708-987bab00-4870-11ea-8f47-597bb1a1626c.png)![warped_planks](https://user-images.githubusercontent.com/401965/73889699-96195100-4870-11ea-8376-6676c37df7e2.png)![stripped_warped_stem](https://user-images.githubusercontent.com/401965/73889556-45095d00-4870-11ea-8ca4-4b3e3d48ca3b.png)![stripped_warped_stem_top](https://user-images.githubusercontent.com/401965/73889559-45095d00-4870-11ea-883e-188621a4ed70.png)![warped_stripped_log_side](https://user-images.githubusercontent.com/401965/73889706-974a7e00-4870-11ea-8c0a-138af1bbd47b.png)![warped_stripped_log_top](https://user-images.githubusercontent.com/401965/73889707-97e31480-4870-11ea-9990-f34827c02621.png)

![warped_stem](https://user-images.githubusercontent.com/401965/73889701-96b1e780-4870-11ea-98e4-bca6a5d4cb50.png)![warped_wart_block](https://user-images.githubusercontent.com/401965/73889709-987bab00-4870-11ea-931c-052b6d7b187e.png)![warped_nylium](https://user-images.githubusercontent.com/401965/73889696-9580ba80-4870-11ea-93c9-4a38867acf01.png)![warped_nylium_side](https://user-images.githubusercontent.com/401965/73889698-96195100-4870-11ea-82ae-4b7272ed2cac.png)![nether_sprouts](https://user-images.githubusercontent.com/401965/73889443-f8258680-486f-11ea-806b-0cd7d15fbb93.png)![warped_fungi](https://user-images.githubusercontent.com/401965/73889694-9580ba80-4870-11ea-851d-a43311a86c70.png)![warped_roots](https://user-images.githubusercontent.com/401965/73889700-96b1e780-4870-11ea-977f-783c47dde388.png)

![twisting_vines](https://user-images.githubusercontent.com/401965/76473628-5a3a5400-63f9-11ea-8d02-9bf3b41a6d7a.png)![twisting_vines_plant](https://user-images.githubusercontent.com/401965/76473632-5dcddb00-63f9-11ea-8cca-6c53be0e45a2.png)

![warped](https://user-images.githubusercontent.com/401965/73889835-d7116580-4870-11ea-8eea-0cf89e457852.png)

![warped_door](https://user-images.githubusercontent.com/401965/73890106-78002080-4871-11ea-950b-9fdaea72fa64.png)![warped_sign](https://user-images.githubusercontent.com/401965/73890108-7898b700-4871-11ea-9b8f-0028ef6df41d.png)

![shroomlight](https://user-images.githubusercontent.com/401965/73889473-0e334700-4870-11ea-9b1f-fac68a4cf907.png)

**Comment by tobyplowy** [comment]
Blue nether mushroom.
![blua nether mushroom](https://user-images.githubusercontent.com/16853304/73128312-888cdd00-3fcd-11ea-9358-4a997e63ad49.png)

**Comment by lipki** [comment]
eh nice !

**Comment by tobyplowy** [comment]
Are you sure?
the "eh" sounds like you don't like it much.

**Comment by lipki** [comment]
oh nice !
:)

No, it's very good, it's very chemical.

**Comment by tobyplowy** [comment]
@lipki I have been a bit busy but I will get to the other textures soon =D

**Comment by lipki** [comment]
Fungi grow trees.

**Comment by tobyplowy** [comment]
Yeah I know.
The texture still works so that's good =D
Now the other one.

**Comment by lipki** [comment]
![Capture du 2020-02-06 20-20-08](https://user-images.githubusercontent.com/401965/73971298-eb13a080-491e-11ea-9446-925567108fd8.png)

**Comment by tobyplowy** [comment]
Nice :)

**Comment by tobyplowy** [comment]
Now the glowing block.

**Comment by lipki** [comment]
color test
![Capture du 2019-06-03 14-37-26](https://user-images.githubusercontent.com/401965/73985806-70597e00-493c-11ea-8117-2c30ec52a637.png)

**Comment by tobyplowy** [comment]
I like the purple.

**Comment by lipki** [comment]
I put that there, it's not for textures, because I think we can do different.
But that's just to say that I made the model files.

![Capture du 2020-02-09 22-31-28](https://user-images.githubusercontent.com/401965/74110348-01726400-4b8c-11ea-9cfa-36150c0d6902.png)

**Comment by lipki** [comment]
warped_roots_pot ![warped_roots_pot](https://user-images.githubusercontent.com/401965/75805512-44d28380-5d82-11ea-81b9-9aa5ca3510de.png)

**Comment by lipki** [comment]
![Capture du 2020-02-07 00-47-49](https://user-images.githubusercontent.com/401965/75812608-ce884e00-5d8e-11ea-89eb-02d1675e7c35.png)

nylium ![warped_nylium](https://user-images.githubusercontent.com/401965/75812450-9254ed80-5d8e-11ea-81c1-0ea7aca8d64b.png) ![warped_nylium_side](https://user-images.githubusercontent.com/401965/75812451-92ed8400-5d8e-11ea-9096-724449401975.png)
leaves ![warped_wart_block](https://user-images.githubusercontent.com/401965/75812491-a26ccd00-5d8e-11ea-9b94-61330ef056e4.png)

stem 
![warped_stem_top](https://user-images.githubusercontent.com/401965/75812497-a7318100-5d8e-11ea-9178-6f4ac9b72ada.png)
![warped_stem](https://user-images.githubusercontent.com/401965/75812510-aa2c7180-5d8e-11ea-95e0-f0189f80c5bd.png)

**Comment by lipki** [comment]
![Capture du 2020-02-07 00-48-04](https://user-images.githubusercontent.com/401965/75812694-ed86e000-5d8e-11ea-89f0-f9028a90ba7e.png)

stripped stem ![stripped_warped_stem](https://user-images.githubusercontent.com/401965/75812751-0abbae80-5d8f-11ea-9329-ed34ec914dac.png) ![stripped_warped_stem_top](https://user-images.githubusercontent.com/401965/75812806-29ba4080-5d8f-11ea-93b6-6c42e7ac8f8a.png)

**Comment by lipki** [comment]
New magic bean
![twisting_vines](https://user-images.githubusercontent.com/401965/76473628-5a3a5400-63f9-11ea-8d02-9bf3b41a6d7a.png)
![twisting_vines_plant](https://user-images.githubusercontent.com/401965/76473632-5dcddb00-63f9-11ea-8cca-6c53be0e45a2.png)

**Comment by lipki** [comment]
TEST
![Capture du 2020-06-10 01-09-23](https://user-images.githubusercontent.com/401965/84209788-529d5080-aab7-11ea-90b6-690b5dcd2ba6.png)

**Comment by tobyplowy** [comment]
OOoohhhh that's interesting.

**Comment by lipki** [comment]
I hesitate a bit because it's a lot of block in 3d models.
![Capture du 2020-07-23 10-44-23](https://user-images.githubusercontent.com/401965/88274499-19721600-ccdc-11ea-9501-5946be03cba0.png)
