### ISSUE TITLE
[1.16.X] Crimson forest

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#600]
![crimson_door_top](https://user-images.githubusercontent.com/401965/73889320-b72d7200-486f-11ea-99eb-9e2d26dc682d.png)
![crimson_door_bottom](https://user-images.githubusercontent.com/401965/73889318-b694db80-486f-11ea-98bc-ae2b788bbb59.png)![crimson_stem_top](https://user-images.githubusercontent.com/401965/73889329-b8f73580-486f-11ea-9bce-3f0aee1c8ea2.png)![crimson_trapdoor](https://user-images.githubusercontent.com/401965/73889333-b98fcc00-486f-11ea-9ecb-cc4bfbc0c340.png)![crimson_planks](https://user-images.githubusercontent.com/401965/73889325-b85e9f00-486f-11ea-9383-21f6bd97dae1.png)![stripped_crimson_stem](https://user-images.githubusercontent.com/401965/73889544-40dd3f80-4870-11ea-9f6e-7d0f2a806990.png)![stripped_crimson_stem_top](https://user-images.githubusercontent.com/401965/73889545-4175d600-4870-11ea-857e-e313117404a9.png)

![crimson_stem](https://user-images.githubusercontent.com/401965/73889328-b8f73580-486f-11ea-964b-f5609fc10020.png)![crimson_nylium](https://user-images.githubusercontent.com/401965/73889322-b7c60880-486f-11ea-9a07-751d90fa6566.png)![crimson_nylium_side](https://user-images.githubusercontent.com/401965/73889324-b7c60880-486f-11ea-8fb3-2faf00ab294c.png)![crimson_roots](https://user-images.githubusercontent.com/401965/73889327-b85e9f00-486f-11ea-87e3-6cefac2a3857.png)![crimson_fungi](https://user-images.githubusercontent.com/401965/73889321-b72d7200-486f-11ea-9a76-68f0bef25352.png)![weeping_vines](https://user-images.githubusercontent.com/401965/73889762-b2b58900-4870-11ea-855b-f6e0b1b4947f.png)![weeping_vines_plant](https://user-images.githubusercontent.com/401965/73889765-b3e6b600-4870-11ea-9f9f-0ef39e4bf95f.png)

Fungi grow trees.

![crimson](https://user-images.githubusercontent.com/401965/73889834-d7116580-4870-11ea-8452-a70d0e3e2538.png)

![crimson_door](https://user-images.githubusercontent.com/401965/73890004-3cfded00-4871-11ea-942c-c237cd98cb2c.png)![crimson_sign](https://user-images.githubusercontent.com/401965/73890006-3d968380-4871-11ea-8822-3e20244aeeaa.png)

![shroomlight](https://user-images.githubusercontent.com/401965/73889473-0e334700-4870-11ea-9b1f-fac68a4cf907.png)

**Comment by tobyplowy** [comment]
![red nether mushroom](https://user-images.githubusercontent.com/16853304/73963776-34f58a00-4911-11ea-8fd1-9ff04d5b118b.png)

**Comment by lipki** [comment]
eh :D 
It looks like a witch hat.
I really like !

**Comment by lipki** [comment]
crimson_roots_pot ![crimson_roots_pot](https://user-images.githubusercontent.com/401965/75805189-a34b3200-5d81-11ea-9be9-81664ae1e45a.png)

**Comment by lipki** [comment]
![Capture du 2020-02-07 00-47-49](https://user-images.githubusercontent.com/401965/75811905-8d436e80-5d8d-11ea-9b28-568d406befd8.png)

nylium ![crimson_nylium](https://user-images.githubusercontent.com/401965/75811837-70a73680-5d8d-11ea-92c2-9e254f771609.png)![crimson_nylium_side](https://user-images.githubusercontent.com/401965/75811846-7270fa00-5d8d-11ea-98a5-a7cbe91b90e9.png)
stem
![crimson_stem_top](https://user-images.githubusercontent.com/401965/75811725-3e95d480-5d8d-11ea-84fd-85d981ef8e2f.png)
![crimson_stem](https://user-images.githubusercontent.com/401965/75811735-43f31f00-5d8d-11ea-9494-5d3f0ff9a570.png)

**Comment by lipki** [comment]
stripped stem ![stripped_crimson_stem](https://user-images.githubusercontent.com/401965/75812014-c24fc100-5d8d-11ea-83f2-afebae24b1d4.png) ![stripped_crimson_stem_top](https://user-images.githubusercontent.com/401965/75812016-c2e85780-5d8d-11ea-9a57-a1436453c8ab.png)

![Capture du 2020-02-07 00-48-14](https://user-images.githubusercontent.com/401965/75812261-312d1a00-5d8e-11ea-9a07-f99f29dcf0f6.png)

**Comment by lipki** [comment]
I wanted to bring these blocks closer to mushrooms rather than trees.
What do you think about that ?

![Capture du 2020-07-25 19-21-47](https://user-images.githubusercontent.com/401965/88462558-8936fb00-ceac-11ea-9c7d-520934df3c92.png)
