### ISSUE TITLE
[1.16.X] Blue Fire

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#601]
![soul_fire_0](https://user-images.githubusercontent.com/401965/73889493-1db29000-4870-11ea-878a-af06d42fc7f8.png)![soul_fire_1](https://user-images.githubusercontent.com/401965/73889495-2014ea00-4870-11ea-94f3-645f5943058d.png)![soul_fire_lantern](https://user-images.githubusercontent.com/401965/73889512-2acf7f00-4870-11ea-8d67-4450bfa6bf18.png)![soul_fire_torch](https://user-images.githubusercontent.com/401965/73889516-302cc980-4870-11ea-8621-ea852a8d5034.png)![soul_fire_lantern](https://user-images.githubusercontent.com/401965/73890097-6fa7e580-4871-11ea-866f-7f73860d6856.png)
![soul_fire_flame](https://user-images.githubusercontent.com/401965/73890172-a4b43800-4871-11ea-8df8-6a0f11d06caf.png)

**Comment by lipki** [comment]
I take the first dance.

![soul_fire_0](https://user-images.githubusercontent.com/401965/73896241-9cb0c400-4882-11ea-8659-a1c0f2f01b1b.png)![soul_fire_1](https://user-images.githubusercontent.com/401965/73896245-a3d7d200-4882-11ea-961c-fbe3796a19be.png)![soul_fire_lantern](https://user-images.githubusercontent.com/401965/73896262-b18d5780-4882-11ea-846d-f91e43717538.png)![soul_fire_torch](https://user-images.githubusercontent.com/401965/73896266-b3efb180-4882-11ea-8d29-01a0ed266a2e.png)
![soul_fire_flame](https://user-images.githubusercontent.com/401965/73896276-c1a53700-4882-11ea-96d2-7c77f6515591.png)

![Capture du 2020-02-06 01-50-34](https://user-images.githubusercontent.com/401965/73896403-3a0bf800-4883-11ea-9225-d13ebcd34f32.png)

**Comment by tobyplowy** [comment]
Very nice! I was planning on doing these but you best me to it =D

**Comment by lipki** [comment]
Blue Campfire
![soul_campfire_fire](https://user-images.githubusercontent.com/401965/78827345-44fa1a80-79e3-11ea-98be-da10f7ea2b4f.png)
![soul_campfire_log_lit](https://user-images.githubusercontent.com/401965/78827349-4592b100-79e3-11ea-8661-195beca8261f.png)
make model

**Comment by lipki** [comment]
soul_campfire : ![soul_campfire](https://user-images.githubusercontent.com/401965/78830630-8f31ca80-79e8-11ea-9f45-7997ac19abd2.png)

**Comment by lipki** [comment]
![Capture du 2020-04-08 23-16-16](https://user-images.githubusercontent.com/401965/78834633-2dc12a00-79ef-11ea-8ba3-add81a3da31f.png)

![soul_campfire_fire](https://user-images.githubusercontent.com/401965/78834672-3dd90980-79ef-11ea-939e-5ffccebde5c8.png)![soul_campfire_log_lit](https://user-images.githubusercontent.com/401965/78834684-429dbd80-79ef-11ea-98ae-84efd99e4e5d.png)![soul_campfire_log](https://user-images.githubusercontent.com/401965/78834713-47fb0800-79ef-11ea-8fe7-1ab4a509954e.png)

**Comment by tobyplowy** [comment]
Fire looks good but may need a bit more hue shifting.

**Comment by lipki** [comment]
After you :D

**Comment by tobyplowy** [comment]
![73896245-a3d7d200-4882-11ea-961c-fbe3796a19be](https://user-images.githubusercontent.com/16853304/86983646-b2f1e180-c18c-11ea-97f0-21184889829d.png)
The other textures are fine.

**Comment by tobyplowy** [comment]
Makes the fire more colorful and brighter.

**Comment by lipki** [comment]
I left both, it's a bit of a variation.
