### ISSUE TITLE
[1.16.X] Netherite

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#602]
![netherite_block](https://user-images.githubusercontent.com/401965/73889459-02e01b80-4870-11ea-9513-97e41bbd6a88.png)

![netherite_scrap](https://user-images.githubusercontent.com/401965/73890069-6159c980-4871-11ea-9551-62a9d5ec9579.png)![netherite_ingot](https://user-images.githubusercontent.com/401965/73890064-60289c80-4871-11ea-8407-fc95fbc6808f.png)

![netherite_hoe](https://user-images.githubusercontent.com/401965/73890063-60289c80-4871-11ea-9215-3873e9dcb40c.png)![netherite_shovel](https://user-images.githubusercontent.com/401965/73890070-6159c980-4871-11ea-9ff6-a5b5dd55d63d.png)![netherite_axe](https://user-images.githubusercontent.com/401965/73890058-5ef76f80-4871-11ea-9bea-8f38c3b986ac.png)![netherite_pickaxe](https://user-images.githubusercontent.com/401965/73890068-60c13300-4871-11ea-867c-ec464b8f2fda.png)![netherite_sword](https://user-images.githubusercontent.com/401965/73890072-61f26000-4871-11ea-936d-e4cc5a996aa0.png)

![netherite_boots](https://user-images.githubusercontent.com/401965/73890059-5f900600-4871-11ea-9fe7-9911d9262210.png)![netherite_leggings](https://user-images.githubusercontent.com/401965/73890067-60c13300-4871-11ea-95fe-6ac34bedf262.png)![netherite_chestplate](https://user-images.githubusercontent.com/401965/73890060-5f900600-4871-11ea-86bf-1484eb2bfae2.png)![netherite_helmet](https://user-images.githubusercontent.com/401965/73890062-5f900600-4871-11ea-9942-a9e944d505d0.png)

![netherite_layer_1](https://user-images.githubusercontent.com/401965/73890137-8c441d80-4871-11ea-9740-d0fa3d31d188.png)
![netherite_layer_2](https://user-images.githubusercontent.com/401965/73890138-8cdcb400-4871-11ea-9b69-de047885d8d2.png)

It is a modification of diamond tools and armor.
I propose to use the diamond textures and add a netherite touch.

**Comment by lipki** [comment]
That's what I suggest, for the color, I'm not sure ... I'm sure it's not good.

So the diamond armor, with netherite parts.
The advantage being of not having to redo an armor.

![Capture du 2020-02-06 18-24-25](https://user-images.githubusercontent.com/401965/73962132-278ad080-490e-11ea-9517-c53fee739ea8.png)

**Comment by tobyplowy** [comment]
Yeah that looks cool!

**Comment by lipki** [comment]
![Capture du 2020-02-08 00-35-43](https://user-images.githubusercontent.com/401965/74073617-4cb13900-4a0b-11ea-8ce3-aa5075426261.png)

**Comment by tobyplowy** [comment]
:)

**Comment by lunapanshiel** [comment]
I don't approve of simply recoloring diamond armor, that's lazy and defeats much of the uniqueness of having Netherite to begin with. 

Netherite is actually very similar to the material Thulecite in the game don't starve, which is made from the remnants of ancient technology found deep underground https://dontstarve.fandom.com/wiki/Thulecite

It makes the best armor and weapons in the game, but is exceedingly dangerous to get, I think basing the Netherite armor on Thulecite would be a good inspirational source.

https://vignette.wikia.nocookie.net/dont-starve-game/images/b/b4/Thulecite_Crown_Wilson.png/revision/latest?cb=20131106101815

https://vignette.wikia.nocookie.net/dont-starve-game/images/f/f2/Thulecite_Club_In-Game.png/revision/latest?cb=20150611135231

https://vignette.wikia.nocookie.net/dont-starve-game/images/c/cd/PickSlashAxe_In-Game.png/revision/latest?cb=20150607141125

it has a very aztec sort of style, and the Thuleciteblocks even look a lot like the ancient debris, probably because it has the same purpose in the setting

**Comment by lipki** [comment]
I like the reference to "don't starve", it would be great.
And you're right, it fits perfectly.

But, there is a constraints, the armors of Summerfields is magnificent, this new armor must be magnificent.

If someone offers me beautiful armor, on this theme, or on another, I would be delighted.
And maybe I would try to do it.

No color constraint on the other hand, the current proposal is, just a proposal.

**Comment by lipki** [comment]
Following the @lunapanshiel proposal, I propose another version for the tools.
![netherite_axe](https://user-images.githubusercontent.com/401965/76625402-6f1d0180-6537-11ea-8316-fbf742bbecc0.png)![netherite_hoe](https://user-images.githubusercontent.com/401965/76625404-704e2e80-6537-11ea-9c95-41377265d227.png)![netherite_pickaxe](https://user-images.githubusercontent.com/401965/76625406-70e6c500-6537-11ea-9722-1994db89ec6b.png)![netherite_shovel](https://user-images.githubusercontent.com/401965/76625407-70e6c500-6537-11ea-95ef-4bede1f8e4e5.png)![netherite_sword](https://user-images.githubusercontent.com/401965/76625408-717f5b80-6537-11ea-8510-b087e04cf4e8.png)

**Comment by lipki** [comment]
![netherite_layer_1](https://user-images.githubusercontent.com/401965/76660867-36eae280-657a-11ea-994a-e7cb68a9cc73.png)
![netherite_layer_2](https://user-images.githubusercontent.com/401965/76660868-37837900-657a-11ea-951f-9b174ea03472.png)
![netherite_piglin_helmet](https://user-images.githubusercontent.com/401965/76661414-ad3c1480-657b-11ea-9eac-8f92cdb39d1c.png)


![Capture du 2020-03-13 22-27-44](https://user-images.githubusercontent.com/401965/76660850-2cc8e400-657a-11ea-80e8-a5e58fd347dc.png)

**Comment by lipki** [comment]
![netherite_layer_1](https://user-images.githubusercontent.com/401965/76663668-fc854380-6581-11ea-85b7-53b6144cf163.png)![netherite_layer_2](https://user-images.githubusercontent.com/401965/76663670-fd1dda00-6581-11ea-9972-97d7b3b5d281.png)![netherite_piglin_helmet](https://user-images.githubusercontent.com/401965/76663671-fdb67080-6581-11ea-92bf-65349e5fb96a.png)

![netherite_chestplate](https://user-images.githubusercontent.com/401965/76663611-d2338600-6581-11ea-8a2a-b5b9507d67d6.png)![netherite_helmet](https://user-images.githubusercontent.com/401965/76663612-d2338600-6581-11ea-97a9-8ef14072f191.png)![netherite_leggings](https://user-images.githubusercontent.com/401965/76663614-d2cc1c80-6581-11ea-9250-d8375ead371f.png)![netherite_boots](https://user-images.githubusercontent.com/401965/76663610-d19aef80-6581-11ea-88bd-1ccd376ef288.png)

![Capture du 2020-03-13 22-27-44](https://user-images.githubusercontent.com/401965/76663579-ba5c0200-6581-11ea-9018-41ff6d67bbd7.png)
![Capture du 2020-03-13 23-22-54](https://user-images.githubusercontent.com/401965/76663567-b334f400-6581-11ea-9d8c-9239ddb0e2c4.png)

**Comment by lipki** [comment]
I commit, you can test this textures with this link : https://github.com/SummerFields/SummerFields/archive/master.zip

**Comment by tobyplowy** [comment]
OOoooooohhh Very nice!
I like it!

**Comment by lipki** [comment]
What do you think of this mix effect ?
![netherite_ingot](https://user-images.githubusercontent.com/401965/76683228-c0de8e00-6602-11ea-9474-7a4cf91f3097.png)![netherite_block](https://user-images.githubusercontent.com/401965/76683183-5f1e2400-6602-11ea-9841-7b89c177e952.png)

**Comment by lipki** [comment]
![Capture du 2020-03-14 14-55-58](https://user-images.githubusercontent.com/401965/76683393-094a7b80-6604-11ea-88e4-62206e18973a.png)

**Comment by lipki** [comment]
![Capture du 2020-03-14 15-01-07](https://user-images.githubusercontent.com/401965/76683487-b7eebc00-6604-11ea-9898-52512893f5bb.png)

**Comment by tobyplowy** [comment]
OOoooooh that's really cool =D

**Comment by lunapanshiel** [comment]
i like this much, much more than the diamond recolor, i find the green on the armor slightly strange, but overall it's quite interesting and makes the set feel more unique

**Comment by lipki** [comment]
This is what I wanted to refer to.

**Comment by pfccalico** [comment]
Hey, Posting here for your review

![image](https://user-images.githubusercontent.com/8011723/88467656-3885c900-ced1-11ea-8184-8c3e130e3af9.png)

**Comment by pfccalico** [comment]
![image](https://user-images.githubusercontent.com/8011723/88467663-42a7c780-ced1-11ea-9371-83b0739dd281.png)

**Comment by pfccalico** [comment]
![image](https://user-images.githubusercontent.com/8011723/88467667-4d625c80-ced1-11ea-846a-c6f541fb3d7b.png)

**Comment by pfccalico** [comment]
![image](https://user-images.githubusercontent.com/8011723/88467669-53f0d400-ced1-11ea-9e37-81e98bdbbc9a.png)

**Comment by pfccalico** [comment]
i think the legs are a little bland but other than that i am pleased with the result.

**Comment by lipki** [comment]
O K .....

I like it but:

I like the tools too.
I like the bi color style.

So I suggest that !

![Capture d’écran du 2020-08-07 15-54-43](https://user-images.githubusercontent.com/401965/89652852-64884d80-d8c6-11ea-9832-5702d5b8131f.png)

**Comment by tobyplowy** [comment]
The orange shirt or vest or whatever you want to call it looks like a heating element of sorts XD
Very nice. I know it wasn't intentional butt still =D

**Comment by ORN-Fox** [comment]
This latest version of netherite armor is perfect! On the other hand I'm not a fan of the sword I will recolor the sword in diamond ;)
