### ISSUE TITLE
[1.16.X] New wall connection

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#604]
3d model bug

**Comment by tobyplowy** [comment]
Oh boy. How many models are broken?

**Comment by lipki** [comment]
just one i think

**Comment by lipki** [comment]
....
14+14*4+1 = 71 files ....
....

**Comment by lipki** [comment]
![Capture du 2020-02-06 21-39-42](https://user-images.githubusercontent.com/401965/73976761-464a9080-4929-11ea-904b-8f301b482d05.png)
