### ISSUE TITLE
[1.16.X] Piglin

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#610]
![piglin](https://user-images.githubusercontent.com/401965/74569621-20516b80-4f7b-11ea-91c2-d9590e25b796.png)![zombie_piglin](https://user-images.githubusercontent.com/401965/74569624-20ea0200-4f7b-11ea-94b2-aa974b002aa0.png)

![chainmail_piglin_helmet](https://user-images.githubusercontent.com/401965/74569658-32cba500-4f7b-11ea-935d-bcac4ca6da9e.png)![diamond_piglin_helmet](https://user-images.githubusercontent.com/401965/74569660-33643b80-4f7b-11ea-910b-c8f7162f887b.png)![gold_piglin_helmet](https://user-images.githubusercontent.com/401965/74569661-33fcd200-4f7b-11ea-806e-981a2061adf8.png)![iron_piglin_helmet](https://user-images.githubusercontent.com/401965/74569662-33fcd200-4f7b-11ea-9fe4-81634c805895.png)![leather_piglin_helmet](https://user-images.githubusercontent.com/401965/74569663-34956880-4f7b-11ea-92c2-85881f4a3280.png)![leather_piglin_helmet_overlay](https://user-images.githubusercontent.com/401965/74569664-34956880-4f7b-11ea-8b46-1a3f511c8d38.png)![netherite_piglin_helmet](https://user-images.githubusercontent.com/401965/74569665-34956880-4f7b-11ea-89e1-63ca01fc7569.png)

**Comment by lipki** [comment]
![chainmail_piglin_helmet](https://user-images.githubusercontent.com/401965/74569684-4840cf00-4f7b-11ea-82b3-360683d8e467.png)![diamond_piglin_helmet](https://user-images.githubusercontent.com/401965/74569686-48d96580-4f7b-11ea-9066-743329568bfa.png)![gold_piglin_helmet](https://user-images.githubusercontent.com/401965/74569687-4971fc00-4f7b-11ea-8e3e-ad72593244a0.png)![iron_piglin_helmet](https://user-images.githubusercontent.com/401965/74569689-4971fc00-4f7b-11ea-9b31-620b50cc2767.png)![leather_piglin_helmet](https://user-images.githubusercontent.com/401965/74569690-4a0a9280-4f7b-11ea-83d8-1d7878008392.png)![leather_piglin_helmet_overlay](https://user-images.githubusercontent.com/401965/74569692-4a0a9280-4f7b-11ea-9114-e60c6e48c6b6.png)![netherite_piglin_helmet](https://user-images.githubusercontent.com/401965/74569693-4aa32900-4f7b-11ea-9950-9af6ca451769.png)

![Capture du 2020-02-14 22-45-00](https://user-images.githubusercontent.com/401965/74569899-c7360780-4f7b-11ea-91ac-66d3138188a4.png)

**Comment by lipki** [comment]
Our pigman are not zombies ... it will be necessary if to put.

**Comment by lipki** [comment]
![piglin](https://user-images.githubusercontent.com/401965/74574723-d8cfdd00-4f84-11ea-81a1-3e39f080792e.png)

![Capture du 2020-02-14 23-52-10](https://user-images.githubusercontent.com/401965/74574805-20566900-4f85-11ea-8578-8a02f7ffcfe2.png)

**Comment by lipki** [comment]
![piglin_leather_layer_1](https://user-images.githubusercontent.com/401965/75806849-b90e2680-5d84-11ea-8b60-f767ea02f8db.png)
![piglin_leather_layer_1_overlay](https://user-images.githubusercontent.com/401965/75806851-b9a6bd00-5d84-11ea-8355-d0d232588b59.png)
I don't understand the interest of this ...

**Comment by lipki** [comment]
![zombified_piglin](https://user-images.githubusercontent.com/401965/75811458-c0393280-5d8c-11ea-8815-0e642ebfb2cb.png)
![Capture du 2020-03-03 20-15-54](https://user-images.githubusercontent.com/401965/75811470-c5967d00-5d8c-11ea-8a4d-0cec0bde52ed.png)

**Comment by tobyplowy** [comment]
@lipki Looks good =D

**Comment by chengzzi89** [comment]
nice!👍

**Comment by lipki** [comment]
new texture 
![piglin](https://user-images.githubusercontent.com/401965/78458181-920e8180-76af-11ea-9d32-edda2d7f4f43.png) ![zombified_piglin](https://user-images.githubusercontent.com/401965/78458183-92a71800-76af-11ea-9848-e894bdd07c1a.png)

**Comment by lipki** [comment]
![piglin](https://user-images.githubusercontent.com/401965/78565888-c9e80700-781e-11ea-84d4-0da08468b5e1.png)![zombified_piglin](https://user-images.githubusercontent.com/401965/78565893-cb193400-781e-11ea-8e4d-a28a25584c3a.png)

**Comment by lipki** [comment]
new banner : ![piglin](https://user-images.githubusercontent.com/401965/78828853-a622ed80-79e5-11ea-9d28-95a2a3388d9b.png)

**Comment by lipki** [comment]
piglin_banner_pattern : ![piglin_banner_pattern](https://user-images.githubusercontent.com/401965/78830397-29454300-79e8-11ea-92f3-6356d548db26.png)

**Comment by lipki** [comment]
![Capture du 2020-04-09 17-25-01](https://user-images.githubusercontent.com/401965/78911834-2b121380-7a87-11ea-94dc-eb25b6d548e8.png)
![piglin_banner_pattern](https://user-images.githubusercontent.com/401965/78913495-631a5600-7a89-11ea-8b3a-878a15617fdd.png)![piglin](https://user-images.githubusercontent.com/401965/78911865-3402e500-7a87-11ea-8a4d-d51413cf005b.png)![piglin](https://user-images.githubusercontent.com/401965/78911851-306f5e00-7a87-11ea-968b-61a491eebee1.png)
