### ISSUE TITLE
[1.16.X] Crying Obsidian

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#611]
![crying_obsidian](https://user-images.githubusercontent.com/401965/75802219-aabc0c80-5d7c-11ea-804d-eb9ad0ca9ada.png)

**Comment by chengzzi89** [comment]
![obsidian](https://user-images.githubusercontent.com/28303754/76530937-6680e880-64af-11ea-8348-d7e2911ca131.png)

**Comment by lipki** [comment]
It's good, it lacks image, but it looks good.
Too bad the particles are purple.
