### ISSUE TITLE
[1.16.X] Target block

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#612]
![target_side](https://user-images.githubusercontent.com/401965/75805359-f9b87080-5d81-11ea-92ca-2ec68d9d593b.png)
![target_top](https://user-images.githubusercontent.com/401965/75805360-fa510700-5d81-11ea-8c52-419c29947c98.png)

**Comment by lipki** [comment]
hay bale + redstone

**Comment by tobyplowy** [comment]
I will try and do this one =D

**Comment by tobyplowy** [comment]
How is this?
![image](https://user-images.githubusercontent.com/16853304/75813761-d8ab4c00-5d90-11ea-9cec-826634dd320e.png)

I also have a version with damage.
![image](https://user-images.githubusercontent.com/16853304/75813957-33dd3e80-5d91-11ea-9c7f-01115832d227.png)

**Comment by lipki** [comment]
we're going to randomize them.
