### ISSUE TITLE
Rewrite all models

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#629]
There are changes that build up.

**Comment by lipki** [comment]
FYI, I'm working on it, it's super long :D

**Comment by lipki** [comment]
The pleasure of checking all personal models.
![Capture d’écran du 2020-11-19 21-34-18](https://user-images.githubusercontent.com/401965/99721502-a0c76e80-2aaf-11eb-8058-f5f1bc26dbf7.png)

**Comment by lipki** [comment]
(s)potted !
![Capture d’écran du 2020-11-19 21-32-55](https://user-images.githubusercontent.com/401965/99721880-1df2e380-2ab0-11eb-969b-0d07d8600015.png)

**Comment by lipki** [comment]
nouveau bambou
![Capture d’écran du 2020-11-19 21-44-51](https://user-images.githubusercontent.com/401965/99722321-ca34ca00-2ab0-11eb-8f67-e9a3a4b8badf.png)

**Comment by chengzzi89** [comment]
> 新竹
> ![2020年19月19日捕获德克兰城21-44-51](https://user-images.githubusercontent.com/401965/99722321-ca34ca00-2ab0-11eb-8f67-e9a3a4b8badf.png)

nice！❤️

**Comment by ORN-Fox** [comment]
I love this !

**Comment by lipki** [comment]
![Capture d’écran du 2024-12-15 19-20-41](https://github.com/user-attachments/assets/487964b1-0b39-427a-8eda-466276f94336)
![Capture d’écran du 2024-12-15 19-20-54](https://github.com/user-attachments/assets/ae81792c-8c23-4d7a-a031-4b9f04eba97a)

**Comment by lipki** [comment]
I finally finished ahah!
