### ISSUE TITLE
[1.16.X] jigsaw block change

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#633]
![Capture du 2020-04-04 19-55-25](https://user-images.githubusercontent.com/401965/78457994-971f0100-76ae-11ea-8146-f55c38293e9c.png)
![jigsaw_lock](https://user-images.githubusercontent.com/401965/78458017-c2a1eb80-76ae-11ea-9712-b71519e99f1f.png)

**Comment by chengzzi89** [comment]
![jigsaw](https://user-images.githubusercontent.com/28303754/78984952-28342300-7b5a-11ea-95e3-99b02d936919.png)

**Comment by lipki** [comment]
Nice :)

**Comment by lipki** [comment]
it's added
