### ISSUE TITLE
[1.16.X] Strider

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#635]
![strider](https://user-images.githubusercontent.com/401965/78458199-bf5b2f80-76af-11ea-8e6a-f62c8deef9fa.png) ![strider_saddle](https://user-images.githubusercontent.com/401965/78458200-bf5b2f80-76af-11ea-8d4a-8dfd51c5b840.png)
![warped_fungus_on_a_stick](https://user-images.githubusercontent.com/401965/78458248-32fd3c80-76b0-11ea-8e7d-9a80d58aa43b.png)

**Comment by lipki** [comment]
I would love to find a pop culture monster that looks like the strider.

**Comment by lipki** [comment]
![strider_cold](https://user-images.githubusercontent.com/401965/78829952-84c30100-79e7-11ea-8869-4f1a8b378204.png)

**Comment by chengzzi89** [comment]
![warped_fungus_on_a_stick](https://user-images.githubusercontent.com/28303754/78984601-40577280-7b59-11ea-8f30-4590d3bb993b.png)

**Comment by lipki** [comment]
![strider](https://user-images.githubusercontent.com/401965/79048230-e8357480-7c1b-11ea-8dc8-f066333e86ce.png)![strider_cold](https://user-images.githubusercontent.com/401965/79048232-e8357480-7c1b-11ea-8458-0ea52ec813c0.png)![strider_saddle](https://user-images.githubusercontent.com/401965/79048233-e8ce0b00-7c1b-11ea-8921-c7831eaefad8.png)

![Capture du 2020-04-11 17-31-01](https://user-images.githubusercontent.com/401965/79048210-bfad7a80-7c1b-11ea-93e3-c7bd289da09a.png)

**Comment by tobyplowy** [comment]
Very cute.
