### ISSUE TITLE
[1.16.X] Basalt Deltas

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#637]
![Capture du 2020-04-08 21-33-21](https://user-images.githubusercontent.com/401965/78826349-a7eab200-79e1-11ea-86f8-2f2f65c514da.png)

![Capture du 2020-04-08 21-27-17](https://user-images.githubusercontent.com/401965/78826402-b933be80-79e1-11ea-8590-a8683999c5a0.png)

blackstone : ![blackstone](https://user-images.githubusercontent.com/401965/78828079-6e677600-79e4-11ea-84c5-5def35ad27ad.png)
blackstone_top : ![blackstone_top](https://user-images.githubusercontent.com/401965/78828193-9951ca00-79e4-11ea-9318-7afb9707fb14.png)
chiseled_polished_blackstone : ![chiseled_polished_blackstone](https://user-images.githubusercontent.com/401965/78828462-0d8c6d80-79e5-11ea-977f-aa811b2933a9.png)
cracked_polished_blackstone_bricks : ![cracked_polished_blackstone_bricks](https://user-images.githubusercontent.com/401965/78828582-3280e080-79e5-11ea-8323-105df7636824.png)
gilded_blackstone : ![gilded_blackstone](https://user-images.githubusercontent.com/401965/78828597-39a7ee80-79e5-11ea-9f6e-ae33e170f958.png)
polished_blackstone : ![polished_blackstone](https://user-images.githubusercontent.com/401965/78828609-41679300-79e5-11ea-8e84-b891363b683a.png)
polished_blackstone_bricks : ![polished_blackstone_bricks](https://user-images.githubusercontent.com/401965/78828636-4c222800-79e5-11ea-9cda-598c9bbc613e.png)

**Comment by lipki** [comment]
![blackstone](https://user-images.githubusercontent.com/401965/78931290-feb9bf80-7aa5-11ea-9455-beed95c3b493.png) ![blackstone_top](https://user-images.githubusercontent.com/401965/78931293-ff525600-7aa5-11ea-9df6-0ab471142785.png)

![polished_blackstone_bricks](https://user-images.githubusercontent.com/401965/78932227-6e7c7a00-7aa7-11ea-97de-32dd1a72b78c.png) ![chiseled_polished_blackstone](https://user-images.githubusercontent.com/401965/78935159-7be83300-7aac-11ea-83b5-9605d41cb4bc.png) ![cracked_polished_blackstone_bricks](https://user-images.githubusercontent.com/401965/78935161-7be83300-7aac-11ea-963d-54c9c32f0bd0.png)
![Capture du 2020-04-09 21-51-47](https://user-images.githubusercontent.com/401965/78935108-6410af00-7aac-11ea-8a97-83807e02e816.png)

![polished_blackstone](https://user-images.githubusercontent.com/401965/78936328-aaffa400-7aae-11ea-8d52-7dfb66d2e8ec.png) ![polished_blackstone_3](https://user-images.githubusercontent.com/401965/78936373-b8b52980-7aae-11ea-9229-c6d610b5417e.png) ![polished_blackstone_4](https://user-images.githubusercontent.com/401965/78936375-b94dc000-7aae-11ea-8f81-56af796f15f6.png) ![polished_blackstone_1](https://user-images.githubusercontent.com/401965/78936364-b6eb6600-7aae-11ea-8161-cd5d628ab0cb.png) ![polished_blackstone_2](https://user-images.githubusercontent.com/401965/78936366-b783fc80-7aae-11ea-90b8-ca77d66333f0.png)
![Capture du 2020-04-09 22-07-55](https://user-images.githubusercontent.com/401965/78936410-cd91bd00-7aae-11ea-8aac-970940f3e9a1.png)

**Comment by lipki** [comment]
![Capture du 2020-04-09 23-59-21](https://user-images.githubusercontent.com/401965/78944440-36ccfc80-7abe-11ea-8815-ec0c0ec39ba4.png)

**Comment by lipki** [comment]
![Capture du 2020-04-16 14-40-42](https://user-images.githubusercontent.com/401965/79459949-62873f80-7ff4-11ea-911e-973681eb5f78.png)

**Comment by tobyplowy** [comment]
I like it.
