### ISSUE TITLE
[1.16.X] nether brick

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#638]
chiseled_nether_bricks : ![chiseled_nether_bricks](https://user-images.githubusercontent.com/401965/78828374-e6ce3700-79e4-11ea-85fa-2fba3c17c72a.png)
cracked_nether_bricks : ![cracked_nether_bricks](https://user-images.githubusercontent.com/401965/78828376-e766cd80-79e4-11ea-84a3-10cdd7e5ab09.png)

**Comment by lipki** [comment]
![Capture du 2020-04-09 19-09-01](https://user-images.githubusercontent.com/401965/78922179-6a942c00-7a96-11ea-8da5-21f5f9b22b2f.png)
![chiseled_nether_bricks](https://user-images.githubusercontent.com/401965/78922213-77b11b00-7a96-11ea-82bb-6825fa67b14c.png)![cracked_nether_bricks](https://user-images.githubusercontent.com/401965/78922216-7849b180-7a96-11ea-9443-73d038bfe24f.png)

**Comment by tobyplowy** [comment]
Hahaha that face is so cute :3
