### ISSUE TITLE
banner and loom pattern results in black-background banners?

### ISSUE THREAD

**Issue by poirotmc** [SummerFields/SummerFields#642]
downloaded the latest master-branch summerfileds resource pack 2020-04-08, new installed minecraft 1.15.2 vanilla, testet on two windows-maschines

simple add a dye and a loom pattern to a red/white/whatever banner, it always results in an black background banner? do i miss something?

![defaultminecraft](https://user-images.githubusercontent.com/63399874/78886440-7e23a080-7a5e-11ea-8fce-f861632200a1.png)

![summerfields](https://user-images.githubusercontent.com/63399874/78886456-85e34500-7a5e-11ea-90ca-51ffc08a973e.png)

**Comment by lipki** [comment]
Ok thank you, I will try to understand and fix it.

**Comment by lipki** [comment]
ok, there was a change in 1.15, which I had not seen.
I'm correcting this.

**Comment by poirotmc** [comment]
wow, great! thanks a lot!

**Comment by lipki** [comment]
The modification is published, you can test.

**Comment by poirotmc** [comment]
work's fine! a thousand thanks!

**Comment by lipki** [comment]
my pleasure :)
