### ISSUE TITLE
[1.16.X] chain

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#651]
![chain](https://user-images.githubusercontent.com/401965/79436241-ea5b5280-7fd0-11ea-8cd1-96477f7ce4ae.png)

**Comment by lipki** [comment]
![chain](https://user-images.githubusercontent.com/401965/79441969-2fcf4e00-7fd8-11ea-99cc-c40324df3099.png)
![Capture du 2020-04-16 11-46-55](https://user-images.githubusercontent.com/401965/79441923-247c2280-7fd8-11ea-831d-5c26108af119.png)

**Comment by lipki** [comment]
![chain](https://user-images.githubusercontent.com/401965/80768074-b2641b80-8b49-11ea-9a38-0a5009153efe.png)

**Comment by tobyplowy** [comment]
Yup all good.
