### ISSUE TITLE
[1.16.X] new disc

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#652]
![music_disc_pigstep](https://user-images.githubusercontent.com/401965/79442807-4f1aab00-7fd9-11ea-9a75-2c702937de2a.png)

**Comment by lipki** [comment]
![music_disc_pigstep](https://user-images.githubusercontent.com/401965/79443320-f8fa3780-7fd9-11ea-8d28-a8a9612bb28d.png)

**Comment by tobyplowy** [comment]
Looks good.
