### ISSUE TITLE
nether portal

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#656]
The nether portal has never been personalized on the SummerFields.
I suggest something.

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/401965/79464620-96fdfa00-7ffa-11ea-8849-262a6b575237.gif)

I take this opportunity to look for techniques to create animated textures.

**Comment by tobyplowy** [comment]
Looks like gross red goo.
I like that.

**Comment by tobyplowy** [comment]
The color also matches the obsidian =D
