### ISSUE TITLE
[1.16.X]soul particle

### ISSUE THREAD

**Issue by chengzzi89** [SummerFields/SummerFields#659]
![soul_0](https://user-images.githubusercontent.com/28303754/79524013-0bd04300-8092-11ea-8f24-b86cf04e4b1c.png)![soul_1](https://user-images.githubusercontent.com/28303754/79524073-2aced500-8092-11ea-8189-70fa3a57ee2f.png)![soul_2](https://user-images.githubusercontent.com/28303754/79524089-30c4b600-8092-11ea-9a9d-42169e272e02.png)![soul_3](https://user-images.githubusercontent.com/28303754/79524098-37532d80-8092-11ea-82fd-0021dee72148.png)![soul_4](https://user-images.githubusercontent.com/28303754/79524106-3d490e80-8092-11ea-9450-7d49ce82111f.png)![soul_5](https://user-images.githubusercontent.com/28303754/79524128-4639e000-8092-11ea-8d5e-7ef504c29de0.png)![soul_6](https://user-images.githubusercontent.com/28303754/79524137-4cc85780-8092-11ea-887a-9b8140150acc.png)![soul_7](https://user-images.githubusercontent.com/28303754/79524144-53ef6580-8092-11ea-97b1-7894bfb78402.png)![soul_8](https://user-images.githubusercontent.com/28303754/79524156-59e54680-8092-11ea-85b7-edf488f47177.png)![soul_9](https://user-images.githubusercontent.com/28303754/79524171-610c5480-8092-11ea-9c1b-fd64468febc3.png)![soul_10](https://user-images.githubusercontent.com/28303754/79524276-ac266780-8092-11ea-8326-fe883ebf4d93.png)

**Comment by lipki** [comment]
#598
