### ISSUE TITLE
I received this email.

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#667]
I received this email.
```
Dear sir,
       I'm an editor of Minecraft Chinese Market place.
       In the github of Summerfields project, I found a contributor named Xxxxxxx is in charge of the 
       MCPE summerfields. And Xxxxxxx publish this texture pack in chinese market place for 
       Commercial purpose, and make thousands of dollars profit. So In china we can not download 
       this pack for free. 
       As I know, according to the LICENSE.md, the Section 1 - i clause is NonCommercial. I wanna 
       make sure if he has this Commercial permission.
        Sorry for bothering you.

Yours sincerely
Troye sharo
```

This person does not teach me anything, I am already aware.

The Summerfields has a clear and legal license.
Everyone is free to distribute all versions of the Summerfields resource pack for free.
There is nothing we can do to prevent someone from selling it.
Only to offer a free version alongside.

There are one or more versions of the Summerfields pack in MCPE version.
And thank you very much to everyone who takes care of it.
And I don't care if you take advantage of it to make money. (It doesn't matter how much money is involved elsewhere.)

But it's against the license.

Could you share here on GitHub the version you are selling, to allow me to propose it for free.
You can send it to this address contact@summerfields.info

We do not make a controversy !

**Comment by tobyplowy** [comment]
I hope they at least gave credit.

**Comment by chengzzi89** [comment]
@lipki 
A free bedrock version is released on the PMC platform!  And it is compatible with version 1.14！😧

**Comment by lipki** [comment]
OK, thanks.
I'm going to get it and put it on the site.

**Comment by chengzzi89** [comment]
@lipki https://www.dropbox.com/s/e1vls5w4as3zlgi/SummerFields-bedrock.mcpack?dl=0😅Give you this link!
