### ISSUE TITLE
New 3d items for armor.

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#676]
Since the creation of the armors, the items are drawn versions of the armor and on 32 pixels it was not great.
![Capture d’écran du 2020-08-07 16-08-40](https://raw.githubusercontent.com/SummerFields/SummerFields/master/assets/minecraft/textures/item/diamond_helmet.png)
I said to myself several times ... maybe more pixel.
![netherite_helmet](https://user-images.githubusercontent.com/401965/89654772-79b2ab80-d8c9-11ea-925c-e910f0223ea6.png)
yes ... but it is no longer 32x32 ... sacrilege!
And then, if you have so many pixels, you might as well do it in 3d ... go and let's go.
![Capture d’écran du 2020-08-07 16-08-02](https://user-images.githubusercontent.com/401965/89655059-d615cb00-d8c9-11ea-9f23-30f0e725b010.png)
![Capture d’écran du 2020-08-07 16-08-40](https://user-images.githubusercontent.com/401965/89655065-d8782500-d8c9-11ea-9bc2-bf4065f3046c.png)
![Capture d’écran du 2020-08-07 17-25-35](https://user-images.githubusercontent.com/401965/89661545-1e85b680-d8d3-11ea-98f7-9ed2b069cc0e.png)

**Comment by tobyplowy** [comment]
OOOohhh very nice.
