### ISSUE TITLE
Leather armor recolor

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#677]
Another thing that was never quite finished.

When the coloring of the leather armor arrived, it hurt my heart to ruin our beautiful hunter outfit.
But hey, we have to make it consistent.

The texture is brightened and desaturated, to highlight the color.
![leather_layer_1](https://user-images.githubusercontent.com/401965/89662828-f39c6200-d8d4-11ea-82d6-62a9c317bc69.png)![leather_layer_1_overlay](https://user-images.githubusercontent.com/401965/89662830-f434f880-d8d4-11ea-940a-71b135bef587.png)![leather_layer_2](https://user-images.githubusercontent.com/401965/89662832-f434f880-d8d4-11ea-81fb-ef61c1b27e9e.png)![leather_layer_2_overlay](https://user-images.githubusercontent.com/401965/89662835-f4cd8f00-d8d4-11ea-8246-67148ed58d5e.png)

![Capture d’écran du 2020-08-07 17-36-59](https://user-images.githubusercontent.com/401965/89662732-cc459500-d8d4-11ea-8b93-6f3b457011bf.png)

**Comment by tobyplowy** [comment]
Yes those colors are really nice =D

**Comment by tobyplowy** [comment]
Good job!
