### ISSUE TITLE
[1.16.2] piglin brute

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#681]
![piglin_brute](https://user-images.githubusercontent.com/401965/91081536-92e88580-e647-11ea-8742-c5386cdcd541.png)

**Comment by lipki** [comment]
![piglin_brute](https://user-images.githubusercontent.com/401965/91717249-6c6ba280-eb91-11ea-9fcf-cc2ff3677e05.png)
![Capture d’écran du 2020-08-30 10-28-40](https://user-images.githubusercontent.com/401965/91717281-80170900-eb91-11ea-81d5-de6e22994d84.png)

**Comment by tobyplowy** [comment]
I like the ear ring. Very cool.
