### ISSUE TITLE
[nazara] Foliage 3d

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#693]
Texture resulting from the work with the Nazara server.

![acacia_leaves](https://user-images.githubusercontent.com/401965/97177657-c4d8ae00-1796-11eb-8119-447ccf368981.png)![birch_leaves](https://user-images.githubusercontent.com/401965/97177658-c5714480-1796-11eb-9ee0-0cd07745eaaf.png)![dark_oak_leaves](https://user-images.githubusercontent.com/401965/97177661-c5714480-1796-11eb-8383-0650481a5cf2.png)![jungle_leaves](https://user-images.githubusercontent.com/401965/97177662-c609db00-1796-11eb-84a8-da2078dbc8a1.png)![oak_leaves](https://user-images.githubusercontent.com/401965/97177663-c609db00-1796-11eb-935d-7d371957f8f0.png)![spruce_leaves](https://user-images.githubusercontent.com/401965/97177664-c6a27180-1796-11eb-963c-a639398d007e.png)

![Capture d’écran du 2020-10-26 14-24-55](https://user-images.githubusercontent.com/401965/97177902-1719cf00-1797-11eb-89ba-4de652e88c54.png)

![Capture d’écran du 2020-10-26 14-21-30](https://user-images.githubusercontent.com/401965/97177696-d0c47000-1796-11eb-8ac8-c35dc1d8d9b1.png)

**Comment by ORN-Fox** [comment]
It's nice but I find that it doesn't work for some trees or specific situation.
