### ISSUE TITLE
[1.17] Goat

### ISSUE THREAD

**Issue by chengzzi89** [SummerFields/SummerFields#694]
![goat](https://user-images.githubusercontent.com/28303754/97761149-e7284e00-1b3f-11eb-92bc-cdde04959e48.png)

**Comment by chengzzi89** [comment]
goat_horn
![goat_horn](https://user-images.githubusercontent.com/28303754/97761238-2191eb00-1b40-11eb-8746-c6248b2760a7.png)

**Comment by lipki** [comment]
#738
