### ISSUE TITLE
[1.17] Powder snow

### ISSUE THREAD

**Issue by chengzzi89** [SummerFields/SummerFields#695]
Powder snow in cauldron
Powder snow #695
\>![powder_snow](https://user-images.githubusercontent.com/401965/98854189-87dd0e80-245a-11eb-854b-6b3108b0717a.png)<
Powder snow in bucket
![powder_snow_bucket](https://user-images.githubusercontent.com/401965/98855501-63823180-245c-11eb-889b-d6be3dabe919.png)
new frozen heart
![icons](https://user-images.githubusercontent.com/401965/101011111-c8fca600-3562-11eb-9820-d17f0c3ca078.png)

**Comment by chengzzi89** [comment]
frozen_effect
![frozen_effect](https://user-images.githubusercontent.com/28303754/97761334-67e74a00-1b40-11eb-9c57-2bc299d00132.png)
promo_corner_left/promo_corner_right
![promo_corner_left](https://user-images.githubusercontent.com/28303754/97761351-759ccf80-1b40-11eb-8ed6-9c1ece3a8a14.png)
![promo_corner_right](https://user-images.githubusercontent.com/28303754/97761386-8f3e1700-1b40-11eb-978d-314f19de6128.png)

**Comment by lipki** [comment]
Je propose d'utiliser la même texture que la neige normale.

**Comment by Physignatily** [comment]
![powder_snow_bucket](https://user-images.githubusercontent.com/74598365/100162221-55e49700-2eb3-11eb-90f7-c104a55580b3.png)

**Comment by Physignatily** [comment]
![powder_snow](https://user-images.githubusercontent.com/74598365/100163811-cb9e3200-2eb6-11eb-89d7-c7e0e7641b4d.png)
![2020-11-25_00 39 23](https://user-images.githubusercontent.com/74598365/100163879-ef617800-2eb6-11eb-88f2-a831313c6066.png)

**Comment by lipki** [comment]
Yes yes, it works very well ...

I also buy the 3d models of the amethysts :)
Calcite and tuff too.
To take away !
I will eat it at home :)

The interface is homemade?

And that block back there ... what kind of sponge is it?

**Comment by lipki** [comment]
![powder_snow_bucket](https://user-images.githubusercontent.com/401965/100281203-c0f0a500-2f69-11eb-9e61-81f3fd7dcacb.png)![snowball](https://user-images.githubusercontent.com/401965/100280908-39a33180-2f69-11eb-8f66-7f2da13d9b4d.png)
Small color adjustment to make it match with the snowballs.

**Comment by Physignatily** [comment]
the sponge is wet_sponge
![wet_sponge1](https://user-images.githubusercontent.com/74598365/100397378-a4c43500-3049-11eb-9ec4-4e8e84d3b2d4.png)

and to be honest... I thought the interface was original-summerfields from 2011 or so (don't know anymore)
![widgets](https://user-images.githubusercontent.com/74598365/100397487-39c72e00-304a-11eb-805b-56643c3d24d6.png)

**Comment by lipki** [comment]
I've never seen this interface before ...
I don't know where she came from.

**Comment by Physignatily** [comment]
![icons](https://user-images.githubusercontent.com/74598365/100526253-5e94e000-31c7-11eb-82d3-bc84f1f699f5.png)
![frozen hearts](https://user-images.githubusercontent.com/74598365/100526276-8e43e800-31c7-11eb-86fa-95841999f48a.PNG)
frozen hearts

**Comment by lipki** [comment]
Perfect

**Comment by lipki** [comment]
![powder_snow](https://user-images.githubusercontent.com/401965/113481577-9b852200-949a-11eb-9962-4917d6f42438.png)
![powder_snow_bucket](https://user-images.githubusercontent.com/401965/113481581-a475f380-949a-11eb-8b45-78b53b9b93bc.png)

**Comment by lipki** [comment]
![powder_snow_outline](https://user-images.githubusercontent.com/401965/121417710-7c0ee780-c96a-11eb-9841-c25d52ea2792.png)
![Capture d’écran du 2021-06-09 21-34-54](https://user-images.githubusercontent.com/401965/121417903-b37d9400-c96a-11eb-8a34-96c917d74d36.png)
