### ISSUE TITLE
[1.17] [GUI]  icon chat

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#701]
new icone in gui/toasts.png
![toasts](https://user-images.githubusercontent.com/401965/98184516-dd6d6480-1f0a-11eb-8387-228054a4bece.png)

**Comment by chengzzi89** [comment]
![toasts](https://user-images.githubusercontent.com/28303754/100034216-ac5fc000-2e36-11eb-993a-a9281979c17f.png)
It doesn't feel very Summerfields☹️☹️

**Comment by lipki** [comment]
No, it's not bad !

If anyone does better, we'll see.
