### ISSUE TITLE
[1.17] Amethyst

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#702]
Amethyst
![amethyst_block](https://user-images.githubusercontent.com/401965/98184618-1c9bb580-1f0b-11eb-85d3-0551f6113fbf.png)![budding_amethyst](https://user-images.githubusercontent.com/401965/98185078-2f62ba00-1f0c-11eb-9751-a7719043dfe2.png)![amethyst_cluster](https://user-images.githubusercontent.com/401965/98184620-1dcce280-1f0b-11eb-9a98-2efa5eba9021.png)![medium_amethyst_bud](https://user-images.githubusercontent.com/401965/98184820-9895fd80-1f0b-11eb-8d0f-10ad91cfd0a6.png)![small_amethyst_bud](https://user-images.githubusercontent.com/401965/98185093-3e496c80-1f0c-11eb-8f6a-4c9f9e727644.png)
![amethyst_shard](https://user-images.githubusercontent.com/401965/98185597-36d69300-1f0d-11eb-9ac3-44fee0de6ace.png)

**Comment by lipki** [comment]
_Originally posted by @chengzzi89 in https://github.com/SummerFields/SummerFields/issues/699#issuecomment-723553706_

![gghh](https://user-images.githubusercontent.com/28303754/98461864-ad63e100-21ea-11eb-8204-2081be3b48c2.png)
![Screenshot_20201108_174802](https://user-images.githubusercontent.com/28303754/98461866-b5238580-21ea-11eb-85cd-4553f49462cc.jpg)

**Comment by lipki** [comment]
It is very pretty, is well done.
Maybe we'll change the color, we'll see.
I find that there is not enough difference between the last two steps.
We could confuse them in game.

**Comment by Physignatily** [comment]
@lipki I'm sorry to let you down, but the 3D-models aren't mine.
I found the here
https://www.planetminecraft.com/texture-pack/3d-amethyst/
but I scaled the texture up to make it less... blocky
![cluster](https://user-images.githubusercontent.com/74598365/100397049-156a5200-3048-11eb-9548-5fdc5baa23fc.png)
![2020-11-27_00 37 29](https://user-images.githubusercontent.com/74598365/100397213-c670ec80-3048-11eb-90d2-d6e51b491914.png)

**Comment by lipki** [comment]
Ok, well we'll do a version ourselves.
But it will probably look a lot like this.

**Comment by lipki** [comment]
I would like to point out that there will be both versions.
With and without 3d model.

**Comment by lipki** [comment]
![ezgif com-gif-maker(47)](https://user-images.githubusercontent.com/401965/114178938-a9c1bb00-993e-11eb-9916-d383d41515f9.gif) ![ezgif com-gif-maker(48)](https://user-images.githubusercontent.com/401965/114179311-1937aa80-993f-11eb-99fa-0e9259f7661c.gif) ![small_amethyst_bud](https://user-images.githubusercontent.com/401965/114179367-29e82080-993f-11eb-8fbb-02786ded770a.png)![medium_amethyst_bud](https://user-images.githubusercontent.com/401965/114179374-2c4a7a80-993f-11eb-9258-61d66d1fc46f.png)![large_amethyst_bud](https://user-images.githubusercontent.com/401965/114179381-2d7ba780-993f-11eb-9a44-0d71ca7b3183.png)![amethyst_cluster](https://user-images.githubusercontent.com/401965/114179383-2f456b00-993f-11eb-9936-94007b32c7b2.png)




![Capture d’écran du 2021-04-09 14-02-23](https://user-images.githubusercontent.com/401965/114178496-17b9b280-993e-11eb-8645-4929a49ae71f.png)

**Comment by chengzzi89** [comment]
ohhh cool！！！
