### ISSUE TITLE
[1.17] Candles

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#704]
candle
![candle](https://user-images.githubusercontent.com/401965/98184756-7308f400-1f0b-11eb-834b-dab161a49b6d.png)![black_candle](https://user-images.githubusercontent.com/401965/98184927-e0b52000-1f0b-11eb-9a0c-7fd56ead5235.png)![blue_candle](https://user-images.githubusercontent.com/401965/98184945-e7439780-1f0b-11eb-8bf9-0963a9fb4546.png)![brown_candle](https://user-images.githubusercontent.com/401965/98184956-ead71e80-1f0b-11eb-93fa-ac266753648a.png)![cyan_candle](https://user-images.githubusercontent.com/401965/98184778-7ef4b600-1f0b-11eb-889a-f89f159dbdb5.png)![gray_candle](https://user-images.githubusercontent.com/401965/98184787-84520080-1f0b-11eb-8f70-0ab653ac2682.png)![green_candle](https://user-images.githubusercontent.com/401965/98184791-86b45a80-1f0b-11eb-9392-d65e3896247f.png)![light_blue_candle](https://user-images.githubusercontent.com/401965/98184797-8caa3b80-1f0b-11eb-860d-ff9ea87a0eb4.png)![light_gray_candle](https://user-images.githubusercontent.com/401965/98184801-8f0c9580-1f0b-11eb-8f80-ece2b9e507e4.png)![lime_candle](https://user-images.githubusercontent.com/401965/98184810-92078600-1f0b-11eb-9fa2-e32ecdeb6418.png)![magenta_candle](https://user-images.githubusercontent.com/401965/98184813-93d14980-1f0b-11eb-9607-6e68d7656565.png)![orange_candle](https://user-images.githubusercontent.com/401965/98184829-9f247500-1f0b-11eb-8e10-97e6cda1ac47.png)![pink_candle](https://user-images.githubusercontent.com/401965/98184834-a186cf00-1f0b-11eb-84cc-35f642aab48f.png)![purple_candle](https://user-images.githubusercontent.com/401965/98184841-a3e92900-1f0b-11eb-9684-215f275efba7.png)![red_candle](https://user-images.githubusercontent.com/401965/98184859-b2cfdb80-1f0b-11eb-86a6-f9f58ab9e3e9.png)![white_candle](https://user-images.githubusercontent.com/401965/98184877-bcf1da00-1f0b-11eb-9229-1c3af0da0acc.png)![yellow_candle](https://user-images.githubusercontent.com/401965/98184881-bebb9d80-1f0b-11eb-9878-cd2d22cdd2ce.png)

![black_candle_lit](https://user-images.githubusercontent.com/401965/119886535-5f6abc80-bf33-11eb-90f7-0bd38d19d7a5.png)![blue_candle_lit](https://user-images.githubusercontent.com/401965/119886546-61348000-bf33-11eb-9ef7-4bd486f33867.png)![brown_candle_lit](https://user-images.githubusercontent.com/401965/119886549-61348000-bf33-11eb-8d09-b5cba86cee31.png)![candle_lit](https://user-images.githubusercontent.com/401965/119886550-61cd1680-bf33-11eb-9821-0e0fecba678c.png)![cyan_candle_lit](https://user-images.githubusercontent.com/401965/119886554-6265ad00-bf33-11eb-89fd-55f832814d27.png)![gray_candle_lit](https://user-images.githubusercontent.com/401965/119886556-62fe4380-bf33-11eb-8c3a-f48f2b001f53.png)![green_candle_lit](https://user-images.githubusercontent.com/401965/119886558-62fe4380-bf33-11eb-9120-af48d8354bfb.png)![light_blue_candle_lit](https://user-images.githubusercontent.com/401965/119886560-6396da00-bf33-11eb-9b7d-7cc549751779.png)![light_gray_candle_lit](https://user-images.githubusercontent.com/401965/119886562-6396da00-bf33-11eb-8ca6-c30f27ce0a2a.png)![lime_candle_lit](https://user-images.githubusercontent.com/401965/119886564-642f7080-bf33-11eb-988c-71059c0d4960.png)![magenta_candle_lit](https://user-images.githubusercontent.com/401965/119886566-64c80700-bf33-11eb-8010-dae57c58a763.png)![orange_candle_lit](https://user-images.githubusercontent.com/401965/119886567-64c80700-bf33-11eb-8c62-ec5fedf1358a.png)![pink_candle_lit](https://user-images.githubusercontent.com/401965/119886569-65609d80-bf33-11eb-90a5-ef630ee7fda3.png)![purple_candle_lit](https://user-images.githubusercontent.com/401965/119886573-65f93400-bf33-11eb-88b6-b0a053dfcb3d.png)![red_candle_lit](https://user-images.githubusercontent.com/401965/119886575-65f93400-bf33-11eb-9c42-526eb5e5651b.png)![white_candle_lit](https://user-images.githubusercontent.com/401965/119886576-6691ca80-bf33-11eb-8118-eb227e215d73.png)![yellow_candle_lit](https://user-images.githubusercontent.com/401965/119886579-6691ca80-bf33-11eb-85d5-536d484ad1f6.png)

![black_candle](https://user-images.githubusercontent.com/401965/100276273-9569bc80-2f61-11eb-800f-14d054c85b3d.png)![blue_candle](https://user-images.githubusercontent.com/401965/100276276-96025300-2f61-11eb-8f24-2955b2346f6d.png)![brown_candle](https://user-images.githubusercontent.com/401965/100276277-96025300-2f61-11eb-9372-a7845322a113.png)![candle](https://user-images.githubusercontent.com/401965/100276278-969ae980-2f61-11eb-9091-7625e26fff35.png)![cyan_candle](https://user-images.githubusercontent.com/401965/100276280-97338000-2f61-11eb-8158-0e8638b1d345.png)![gray_candle](https://user-images.githubusercontent.com/401965/100276283-97cc1680-2f61-11eb-9b46-ca3561e10ff1.png)![green_candle](https://user-images.githubusercontent.com/401965/100276285-9864ad00-2f61-11eb-9dad-0f16d202eab5.png)![light_gray_candle](https://user-images.githubusercontent.com/401965/100276287-9864ad00-2f61-11eb-867b-01502e38c1b7.png)![lime_candle](https://user-images.githubusercontent.com/401965/100276288-98fd4380-2f61-11eb-8480-453148e4eda0.png)![magenta_candle](https://user-images.githubusercontent.com/401965/100276289-9995da00-2f61-11eb-88d6-4be56ac8ccd2.png)![orange_candle](https://user-images.githubusercontent.com/401965/100276291-9995da00-2f61-11eb-81df-23407c2624b3.png)![pink_candle](https://user-images.githubusercontent.com/401965/100276297-9a2e7080-2f61-11eb-81b4-906594bc8a61.png)![purple_candle](https://user-images.githubusercontent.com/401965/100276299-9a2e7080-2f61-11eb-9370-b1e94e0e31c1.png)![red_candle](https://user-images.githubusercontent.com/401965/100276300-9ac70700-2f61-11eb-91b3-109f2623d20f.png)![white_candle](https://user-images.githubusercontent.com/401965/100276301-9b5f9d80-2f61-11eb-8dc4-b3b480e4bd29.png)![yellow_candle](https://user-images.githubusercontent.com/401965/100276303-9b5f9d80-2f61-11eb-8ead-3111b3b79eb3.png)

**Comment by chengzzi89** [comment]
![Untitled 11-28-2020 03-03-36](https://user-images.githubusercontent.com/28303754/100479317-ce07c280-3128-11eb-8dfb-499812b8e275.png)
Candle sample chart🧐

**Comment by lipki** [comment]
![black_candle](https://user-images.githubusercontent.com/401965/119901668-81216f00-bf46-11eb-929c-34d7b0723db0.png)![black_candle_lit](https://user-images.githubusercontent.com/401965/119901670-81ba0580-bf46-11eb-8af5-83c2759667f7.png)![blue_candle](https://user-images.githubusercontent.com/401965/119901673-81ba0580-bf46-11eb-80f5-3447699b38c3.png)![blue_candle_lit](https://user-images.githubusercontent.com/401965/119901675-82529c00-bf46-11eb-9ae8-13b702557fc1.png)![brown_candle](https://user-images.githubusercontent.com/401965/119901677-82eb3280-bf46-11eb-94be-772a37acafdb.png)![brown_candle_lit](https://user-images.githubusercontent.com/401965/119901680-82eb3280-bf46-11eb-9341-f19fbf34d166.png)![candle](https://user-images.githubusercontent.com/401965/119901681-8383c900-bf46-11eb-817f-e52e995196f3.png)![candle_lit](https://user-images.githubusercontent.com/401965/119901683-8383c900-bf46-11eb-850d-171130bf7f67.png)![cyan_candle](https://user-images.githubusercontent.com/401965/119901685-841c5f80-bf46-11eb-8d56-853c0b321fa8.png)![cyan_candle_lit](https://user-images.githubusercontent.com/401965/119901687-84b4f600-bf46-11eb-8c32-2261c85e866c.png)![gray_candle](https://user-images.githubusercontent.com/401965/119901688-84b4f600-bf46-11eb-85a1-4365c5569dae.png)![gray_candle_lit](https://user-images.githubusercontent.com/401965/119901691-854d8c80-bf46-11eb-8c49-9f1b91aa7e4f.png)![green_candle](https://user-images.githubusercontent.com/401965/119901693-85e62300-bf46-11eb-929b-3fe22a4fbb1f.png)![green_candle_lit](https://user-images.githubusercontent.com/401965/119901695-867eb980-bf46-11eb-9f44-95cba1896e9c.png)![light_blue_candle](https://user-images.githubusercontent.com/401965/119901696-87175000-bf46-11eb-96bc-63a3486550cd.png)![light_blue_candle_lit](https://user-images.githubusercontent.com/401965/119901699-87175000-bf46-11eb-9aec-673a625504f2.png)![light_gray_candle](https://user-images.githubusercontent.com/401965/119901700-87afe680-bf46-11eb-8b4e-b5940db45721.png)![light_gray_candle_lit](https://user-images.githubusercontent.com/401965/119901704-88487d00-bf46-11eb-94db-22f33cd3fc36.png)
![lime_candle](https://user-images.githubusercontent.com/401965/119901705-88487d00-bf46-11eb-8810-8e53cd79cacb.png)![lime_candle_lit](https://user-images.githubusercontent.com/401965/119901707-88e11380-bf46-11eb-8fe8-4ecdff5e75fd.png)![magenta_candle](https://user-images.githubusercontent.com/401965/119901708-8979aa00-bf46-11eb-8ec1-21c7b95c6586.png)![magenta_candle_lit](https://user-images.githubusercontent.com/401965/119901711-8979aa00-bf46-11eb-85ee-6938e118fe7c.png)![orange_candle](https://user-images.githubusercontent.com/401965/119901713-8a124080-bf46-11eb-8e17-d9818f9767d2.png)![orange_candle_lit](https://user-images.githubusercontent.com/401965/119901716-8aaad700-bf46-11eb-9aee-cc5dafd02cb0.png)![pink_candle](https://user-images.githubusercontent.com/401965/119901717-8aaad700-bf46-11eb-83d4-d2cb4096a38b.png)![pink_candle_lit](https://user-images.githubusercontent.com/401965/119901721-8b436d80-bf46-11eb-8741-f86e9e9a981e.png)![purple_candle](https://user-images.githubusercontent.com/401965/119901723-8bdc0400-bf46-11eb-910e-57985c4c3e35.png)![purple_candle_lit](https://user-images.githubusercontent.com/401965/119901726-8bdc0400-bf46-11eb-8d9a-ffaedae9765f.png)![red_candle](https://user-images.githubusercontent.com/401965/119901727-8c749a80-bf46-11eb-83ba-db891538989a.png)![red_candle_lit](https://user-images.githubusercontent.com/401965/119901728-8d0d3100-bf46-11eb-9ca7-365e277d7df0.png)![white_candle](https://user-images.githubusercontent.com/401965/119901729-8da5c780-bf46-11eb-8022-5ed21e8b133c.png)![white_candle_lit](https://user-images.githubusercontent.com/401965/119901730-8da5c780-bf46-11eb-8fcf-5eace0463153.png)![yellow_candle](https://user-images.githubusercontent.com/401965/119901735-8e3e5e00-bf46-11eb-8ac7-3c0f16205352.png)![yellow_candle_lit](https://user-images.githubusercontent.com/401965/119901738-8e3e5e00-bf46-11eb-98fa-634add195795.png)
![black_candle](https://user-images.githubusercontent.com/401965/119902072-09a00f80-bf47-11eb-8d7d-ed90ad87f35b.png)![blue_candle](https://user-images.githubusercontent.com/401965/119902074-0a38a600-bf47-11eb-8698-af83c5f20e3a.png)![brown_candle](https://user-images.githubusercontent.com/401965/119902078-0a38a600-bf47-11eb-9c48-10b577ca3c29.png)![candle](https://user-images.githubusercontent.com/401965/119902080-0ad13c80-bf47-11eb-86f2-f4623e80aef4.png)![cyan_candle](https://user-images.githubusercontent.com/401965/119902081-0ad13c80-bf47-11eb-9f2c-0c7cc56e411b.png)![gray_candle](https://user-images.githubusercontent.com/401965/119902082-0b69d300-bf47-11eb-9015-ae6f0fd5f5fe.png)![green_candle](https://user-images.githubusercontent.com/401965/119902083-0c026980-bf47-11eb-9796-105ab7928eaa.png)![light_blue_candle](https://user-images.githubusercontent.com/401965/119902087-0c026980-bf47-11eb-9464-4e95dbc773ce.png)![light_gray_candle](https://user-images.githubusercontent.com/401965/119902088-0c9b0000-bf47-11eb-80ff-ad3b89a1ac2b.png)![lime_candle](https://user-images.githubusercontent.com/401965/119902090-0c9b0000-bf47-11eb-9edf-cf3c478b170f.png)![magenta_candle](https://user-images.githubusercontent.com/401965/119902092-0d339680-bf47-11eb-9f25-1805f6eaaa3e.png)![orange_candle](https://user-images.githubusercontent.com/401965/119902095-0dcc2d00-bf47-11eb-8e0f-df3d0fb2ee50.png)![pink_candle](https://user-images.githubusercontent.com/401965/119902096-0dcc2d00-bf47-11eb-87fa-69c1c0455169.png)![purple_candle](https://user-images.githubusercontent.com/401965/119902098-0e64c380-bf47-11eb-8bd4-cb97b1a1a9f9.png)![red_candle](https://user-images.githubusercontent.com/401965/119902104-0efd5a00-bf47-11eb-88fe-1c806f22ea48.png)![white_candle](https://user-images.githubusercontent.com/401965/119902108-0efd5a00-bf47-11eb-9992-a08388f2704d.png)![yellow_candle](https://user-images.githubusercontent.com/401965/119902110-0f95f080-bf47-11eb-8ece-bf3bddc884af.png)

![Capture d’écran du 2021-05-27 23-59-19](https://user-images.githubusercontent.com/401965/119902554-ac588e00-bf47-11eb-9115-242c1ba5d9f2.png)
