### ISSUE TITLE
[1.17] Calcite

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#705]
Calcite
![calcite](https://user-images.githubusercontent.com/401965/98185247-85cff880-1f0c-11eb-8a58-7233739bcd34.png)

**Comment by lipki** [comment]
![](https://www.aromasud.fr/boutique/images_produits/calcite_opti_bloc-100-z.jpg)

**Comment by Physignatily** [comment]
this is the unused "wax_block"-texture someone made for the 1.15 update
![wax_block](https://user-images.githubusercontent.com/74598365/100396833-fb7c3f80-3046-11eb-8fcc-a5666b881b59.png)
not quite like the vanilla texture, but could work

**Comment by lipki** [comment]
![Capture d’écran du 2020-11-27 12-46-36](https://user-images.githubusercontent.com/401965/100446291-cf94a480-30ae-11eb-95ed-247856dbc39a.png)
I don't know this texture either.
Do you know who made it?

Me, I did that, for now ....
Not great.
![calcite](https://user-images.githubusercontent.com/401965/100446378-fbb02580-30ae-11eb-8741-095d77da73a0.png)
![Capture d’écran du 2020-11-27 12-45-51](https://user-images.githubusercontent.com/401965/100446283-cc011d80-30ae-11eb-807d-6679b2a2bb41.png)

**Comment by lipki** [comment]
waiting for better 
![calcite](https://user-images.githubusercontent.com/401965/109292358-87f6f380-782a-11eb-9537-34f5fada38c8.png)

**Comment by Physignatily** [comment]
![calcite](https://user-images.githubusercontent.com/74598365/118377305-b9cb5b00-b5cc-11eb-8b32-42d3e4c6a2cc.png)
![grafik](https://user-images.githubusercontent.com/74598365/118377286-9ef8e680-b5cc-11eb-8f0a-c1bceb75779d.png)

**Comment by lipki** [comment]
mmmm I know this texture.
The stone of the enigma pack.

**Comment by Physignatily** [comment]
yea, I think it is marble
can we use them? or rather not to prevent duplication?
