### ISSUE TITLE
[1.17] Tuff

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#706]
Tuff
![tuff](https://user-images.githubusercontent.com/401965/98185471-f8d96f00-1f0c-11eb-8a07-a6eacce6d6cb.png)

**Comment by lipki** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/b/bd/Ettringer_Tuff.jpg)

**Comment by Physignatily** [comment]
maybe a bit too dark?
![tuff](https://user-images.githubusercontent.com/74598365/100396783-bfe17580-3046-11eb-933e-f58876c46849.png)

**Comment by lipki** [comment]
I like it.
![Capture d’écran du 2020-11-27 14-18-24](https://user-images.githubusercontent.com/401965/100453601-839c2c80-30bb-11eb-9c64-934fdd4d1100.png)

**Comment by lipki** [comment]
waiting for better 
![tuff](https://user-images.githubusercontent.com/401965/109292178-45351b80-782a-11eb-9ff3-249c92d6903a.png)
