### ISSUE TITLE
[1.17] Tinted glass

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#708]
tinted glass (stop light)
![tinted_glass](https://user-images.githubusercontent.com/401965/98185445-ef500700-1f0c-11eb-808d-d4905a1d615e.png)

**Comment by lipki** [comment]
Metal edging ?

![tinted_glass](https://user-images.githubusercontent.com/401965/98859027-d641db80-2461-11eb-8483-0658c0465fb3.png)

![Capture d’écran du 2020-11-11 21-04-48](https://user-images.githubusercontent.com/401965/98858874-9975e480-2461-11eb-89fa-115691dad993.png)

**Comment by ORN-Fox** [comment]
Maybe it's cool !
