### ISSUE TITLE
[1.17] Bundle

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#709]
Bundle
![bundle](https://user-images.githubusercontent.com/401965/98185760-946adf80-1f0d-11eb-9fa2-039b2cae2deb.png)![bundle_filled](https://user-images.githubusercontent.com/401965/98185763-95037600-1f0d-11eb-861c-32bfb7272dc7.png)
![bundle](https://user-images.githubusercontent.com/401965/102405805-f6793300-3fe9-11eb-9fa3-c6c9afad0099.png)

**Comment by Physignatily** [comment]
as backpack?
![bundle](https://user-images.githubusercontent.com/74598365/99719096-28ab7980-2aac-11eb-96ff-3968a0a49db6.png)
![bundle_filled](https://user-images.githubusercontent.com/74598365/99719099-29dca680-2aac-11eb-817c-8e9ee672fcfe.png)

**Comment by lipki** [comment]
It's a super nice texture.
It's hard to understand that the empty bundle ... is empty.
Maybe leave it open?

![Capture d’écran du 2020-11-19 23-22-58](https://user-images.githubusercontent.com/401965/99731510-47b30700-2abe-11eb-9cb7-dd5f88182690.png)

**Comment by Physignatily** [comment]
do you mean something like this?
![bundle](https://user-images.githubusercontent.com/74598365/100162108-1918a000-2eb3-11eb-8c0e-2a7de97da3d1.png)

**Comment by lipki** [comment]
yes, but maybe darker.
![Sans titre](https://user-images.githubusercontent.com/401965/100277168-0067c300-2f63-11eb-9fcc-14a704311692.png)

Also, the edges must be sharp, not blurry.
Otherwise the rendering is ugly.
![Capture d’écran du 2020-11-25 21-09-52](https://user-images.githubusercontent.com/401965/100277679-d95dc100-2f63-11eb-9c6f-98c3c66d58f4.png)
![Capture d’écran du 2020-11-25 21-16-36](https://user-images.githubusercontent.com/401965/100277966-59842680-2f64-11eb-8c82-8802e831040e.png)

**Comment by lipki** [comment]
**20w51a**
![bundle](https://user-images.githubusercontent.com/401965/102405805-f6793300-3fe9-11eb-9fa3-c6c9afad0099.png)

**Comment by Physignatily** [comment]
![bundle](https://user-images.githubusercontent.com/74598365/102424424-61873180-400b-11eb-8df6-09ee4c29874c.png)
 I used the X of the creative inventory to match it with something
![bundle](https://user-images.githubusercontent.com/74598365/102424530-9c896500-400b-11eb-9cf8-30994b69e659.png)

**Comment by lipki** [comment]
![bundle](https://github.com/user-attachments/assets/4f7d64ca-31ef-4481-8c6b-d19b63a9855c)![bundle_open_back](https://github.com/user-attachments/assets/39212502-8936-4f40-826b-aa01097c4fae)![bundle_open_front](https://github.com/user-attachments/assets/eef7da9b-3212-4a60-811f-def50146705c)


![Capture d’écran du 2024-08-16 20-02-27](https://github.com/user-attachments/assets/a5dced33-f25b-4ae7-8bfe-e1c2bf98c6da)

**Comment by Physignatily** [comment]
I like the texture, but the color could be a bit lighter. 
Rabit skin is pretty pale.

**Comment by lipki** [comment]
I don't like the color either, but now the bundle is crafted with cowhide.

**Comment by lipki** [comment]
#934, #937, #939, #938
