### ISSUE TITLE
[1.17] Spyglass

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#710]
Spyglass
![spyglass](https://user-images.githubusercontent.com/401965/98185828-b8c6bc00-1f0d-11eb-9171-937f547f5530.png)

![spyglass_model](https://user-images.githubusercontent.com/401965/110682974-d669a200-81db-11eb-966b-4b73103f2b64.png)
![white](https://user-images.githubusercontent.com/401965/110683031-e5e8eb00-81db-11eb-8fba-e6f5a726999c.png)

misc/spyglass_scope
![spyglass_scope](https://user-images.githubusercontent.com/401965/98855690-b2c86200-245c-11eb-8578-2c53425d8b1f.png)

**Comment by lipki** [comment]
21w10a update

**Comment by chengzzi89** [comment]
![src=http%3A%2F%2Fimg5 artron net%2Fauction%2F2012%2Fart502145%2Fd%2Fart5021450117 jpg refer=http%3A%2F%2Fimg5 artron](https://user-images.githubusercontent.com/28303754/115741884-b9bbaf00-a3c2-11eb-951b-786ab58800b9.jpg)

**Comment by lipki** [comment]
I had thought of that.
![hop](https://static.wikia.nocookie.net/zelda/images/f/f5/Longue_vue.png/revision/latest/scale-to-width-down/150?cb=20120625195618&path-prefix=fr)
https://zelda.fandom.com/fr/wiki/Longue-Vue

**Comment by lipki** [comment]
![spyglass](https://user-images.githubusercontent.com/401965/121266520-ecf6c680-c8ba-11eb-8633-8490e5aea14a.png)
![spyglass_model](https://user-images.githubusercontent.com/401965/121266525-ee27f380-c8ba-11eb-94f2-44df5caa724c.png)
![spyglass_scope](https://user-images.githubusercontent.com/401965/121266541-f3853e00-c8ba-11eb-870c-0dc8e5ef4bbe.png)
![Capture d’écran du 2021-06-08 22-44-16](https://user-images.githubusercontent.com/401965/121266926-a81f5f80-c8bb-11eb-8812-15876bd2abf4.png)
![Capture d’écran du 2021-06-09 00-38-21](https://user-images.githubusercontent.com/401965/121266930-a9508c80-c8bb-11eb-9ba4-7bea0724c017.png)
