### ISSUE TITLE
gamemode_switcher

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#711]
![gamemode_switcher](https://user-images.githubusercontent.com/401965/98853958-33399380-245a-11eb-9e59-79558eb1435d.png)

**Comment by lipki** [comment]
![gamemode_switcher](https://user-images.githubusercontent.com/401965/98857814-e2c53480-245f-11eb-848a-961e8d01e4f4.png)
![Capture d’écran du 2020-11-11 20-54-08](https://user-images.githubusercontent.com/401965/98857986-228c1c00-2460-11eb-8852-cb595893f71d.png)

**Comment by chengzzi89** [comment]
Sorry, which button is used in the game to use this window?😅😅

**Comment by lipki** [comment]
F3+F4
I don't know if it exists on bedrock.

**Comment by ORN-Fox** [comment]
Nice !

**Comment by ORN-Fox** [comment]
I need this for enigma ;) it's possible ?

**Comment by ORN-Fox** [comment]
@lipki The texture is really great, but you have a few pixels difference between the game mode boxes. At least when I tried the texture it was ;)

**Comment by lipki** [comment]
I will watch.
