### ISSUE TITLE
[1.17] Dripstone

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#715]
![dripstone_block](https://user-images.githubusercontent.com/401965/100274576-f47a0200-2f5e-11eb-924e-257b8aa5c945.png)![pointed_dripstone_down_base](https://user-images.githubusercontent.com/401965/100274644-17a4b180-2f5f-11eb-9439-52a935e9ad41.png)![pointed_dripstone_down_frustum](https://user-images.githubusercontent.com/401965/100274645-183d4800-2f5f-11eb-981f-e07deefc863e.png)![pointed_dripstone_down_middle](https://user-images.githubusercontent.com/401965/100274647-18d5de80-2f5f-11eb-856d-6484b263c267.png)![pointed_dripstone_down_tip](https://user-images.githubusercontent.com/401965/100274649-18d5de80-2f5f-11eb-8ba9-3d30adf28094.png)![pointed_dripstone_down_tip_merge](https://user-images.githubusercontent.com/401965/100274651-196e7500-2f5f-11eb-8445-eab5be301e94.png)![pointed_dripstone_up_base](https://user-images.githubusercontent.com/401965/100274652-196e7500-2f5f-11eb-97f6-b0fc7dc41c18.png)![pointed_dripstone_up_frustum](https://user-images.githubusercontent.com/401965/100274655-1a070b80-2f5f-11eb-89d1-3c8b10679ba8.png)![pointed_dripstone_up_middle](https://user-images.githubusercontent.com/401965/100274656-1a9fa200-2f5f-11eb-94fc-ee5c37cd53c7.png)![pointed_dripstone_up_tip](https://user-images.githubusercontent.com/401965/100274657-1a9fa200-2f5f-11eb-9f25-2e27a759ef16.png)![pointed_dripstone_up_tip_merge](https://user-images.githubusercontent.com/401965/100274658-1b383880-2f5f-11eb-97c6-e8eea0c4bea3.png)

![pointed_dripstone](https://user-images.githubusercontent.com/401965/100274931-841fb080-2f5f-11eb-95d2-4228b26f7c19.png)

**Comment by Physignatily** [comment]
![dripstone_block](https://user-images.githubusercontent.com/74598365/103449875-ad460600-4cae-11eb-92fa-6527e1b0faa7.png)
this is my first time doing 3d models, so they're maybe a bit "chunky"
![2021-01-01_02 59 20](https://user-images.githubusercontent.com/74598365/103449904-13cb2400-4caf-11eb-9637-2b435a2578fc.png)
[Dripstones.zip](https://github.com/SummerFields/SummerFields/files/5759706/Dripstones.zip)

**Comment by lipki** [comment]
It's not bad for a first try.
What's bothering you @chengzzi89 ?

**Comment by chengzzi89** [comment]
Nothing, I was just thinking about how to change to bedrock version! @lipki

**Comment by lipki** [comment]
![dripstone_block](https://user-images.githubusercontent.com/401965/110951338-3f205e00-8345-11eb-842c-048f3f7d8b70.png)

![Capture d’écran du 2021-03-12 15-10-02](https://user-images.githubusercontent.com/401965/110951280-2fa11500-8345-11eb-9225-df9636571cd1.png)

**Comment by lipki** [comment]
![pointed_dripstone_down_base](https://user-images.githubusercontent.com/401965/110962320-25851380-8351-11eb-997c-88334e470919.png)![pointed_dripstone_up_tip](https://user-images.githubusercontent.com/401965/110962337-28800400-8351-11eb-9c99-663755ed54a7.png)![pointed_dripstone_down_tip_merge](https://user-images.githubusercontent.com/401965/110962329-274ed700-8351-11eb-820f-c7e0d525d8a5.png)
![pointed_dripstone_down_middle](https://user-images.githubusercontent.com/401965/110962325-261daa00-8351-11eb-90a7-0e9b2ff86916.png)![pointed_dripstone_up_frustum](https://user-images.githubusercontent.com/401965/110962332-27e76d80-8351-11eb-9aae-e459518e5ee7.png)![pointed_dripstone_up_tip_merge](https://user-images.githubusercontent.com/401965/110962338-29189a80-8351-11eb-8f21-8d29e8e12cd7.png)
![pointed_dripstone_down_frustum](https://user-images.githubusercontent.com/401965/110962323-261daa00-8351-11eb-8339-1fb0a42c5631.png)![pointed_dripstone_up_middle](https://user-images.githubusercontent.com/401965/110962336-27e76d80-8351-11eb-8095-26a5823abdf6.png)
![pointed_dripstone_down_tip](https://user-images.githubusercontent.com/401965/110962327-26b64080-8351-11eb-9194-9c32bc526884.png)![pointed_dripstone_up_base](https://user-images.githubusercontent.com/401965/110962330-274ed700-8351-11eb-8fb0-4c3fb8d41a71.png)












![Capture d’écran du 2021-03-12 16-35-12](https://user-images.githubusercontent.com/401965/110962239-0a1a0880-8351-11eb-9df7-da6225e43956.png)

**Comment by lunapanshiel** [comment]
looks way too similar in pattern to the normal stone it comes from, it needs to be more "striped" or "veiny" rather than having those square chunks. 

![merlin_155318763_ce4ade53-a0fc-46ea-bbbd-f1a6b390ca7c-superJumbo](https://user-images.githubusercontent.com/27765468/110975177-61a67d00-832d-11eb-8ac4-7430ec6f6b60.jpg)

**Comment by lipki** [comment]
I tried, but I did not succeed.
The advantage of keeping the same pattern is that it allows the stones to match.

**Comment by lunapanshiel** [comment]
not all stone needs to match, that is the point of having it different, as it is it doesn't look like stalactites with those square segments on the texture, it just looks like you took regular stone and broke it

could you give this a try? all i did was smooth out the square-ish chunks that were bothering me, i'm not in a good position to test it myself 
![stalactite test](https://user-images.githubusercontent.com/27765468/111197480-e6470480-8594-11eb-8c89-5b3f6b8210f3.png)

**Comment by lipki** [comment]
Yes we can completely change the pointed dripstones. 
It gives that.

![Capture d’écran du 2021-03-15 20-35-02](https://user-images.githubusercontent.com/401965/111210822-fe874580-85cd-11eb-89f7-dd0f50be9614.png)
![Capture d’écran du 2021-03-15 20-32-23](https://user-images.githubusercontent.com/401965/111210619-be27c780-85cd-11eb-8e78-fb55be2662bf.png)

**Comment by lunapanshiel** [comment]
oh yeah that's definitely an improvement, i'd need to work on it a bit more to remove that "square" pattern from the pointed dripstone, that's what was bothering me, it made it look too much like the rock it was coming from

**Comment by lunapanshiel** [comment]
![stalactite test 2](https://user-images.githubusercontent.com/27765468/111213808-8dcd3280-85a7-11eb-90d4-a69cb7943994.png)
![stalactite test 3](https://user-images.githubusercontent.com/27765468/111213824-91f95000-85a7-11eb-9dce-f4cee02568f6.png)

i made an attempt to straighten out the lines and make it look more like it was shaped by water. also a version with higher contrast because i think the texture is a bit too "pale"
