### ISSUE TITLE
Texture for the debug stick

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#717]
![wrench_item](https://user-images.githubusercontent.com/401965/101212848-b1fca780-3679-11eb-9114-161f851b85b3.png)
![Capture d’écran du 2020-12-04 21-41-27](https://user-images.githubusercontent.com/401965/101212833-add08a00-3679-11eb-865c-f9396ed71fec.png)
The texture comes from an old buildcraft mod support.
I don't know who made it.

**Comment by ORN-Fox** [comment]
It's verry cool !
