### ISSUE TITLE
[1.17] glow item frame

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#721]
glow item frame :
![glow_item_frame](https://user-images.githubusercontent.com/401965/105214079-d2ac8e00-5b4f-11eb-9a0e-178d8701e1fb.png)
![glow_item_frame](https://user-images.githubusercontent.com/401965/105214387-3931ac00-5b50-11eb-9dfe-ddaf692526f9.png)

**Comment by chengzzi89** [comment]
![1611290111501](https://user-images.githubusercontent.com/28303754/105447033-54b2c900-5cae-11eb-8495-fccc644c817f.png)
![1611290111619](https://user-images.githubusercontent.com/28303754/105447038-58465000-5cae-11eb-920d-0d58f4c9e554.png)

**Comment by lipki** [comment]
I find that we do not recognize him easily enough.
![glow_item_frame](https://user-images.githubusercontent.com/401965/114191185-6ff7b100-994c-11eb-8823-5129aa6e0ca5.png)
It's better this way ?
