### ISSUE TITLE
Difficulty with the versionning of the pack in the repository !

### ISSUE THREAD

**Issue by ORN-Fox** [SummerFields/SummerFields#724]
Hi guys! You're doing a great job, but I'm having trouble understanding the versions of the pack. Why not use the tags?

**Comment by lipki** [comment]
It's me who struggles with the creation of releases, there's no real explanation.

**Comment by lipki** [comment]
One of the things that pisses me off is that the package automatically provided by GitHub must be unzipped to be used with Minecraft.
So I have to pack my own package for each releases.
That I put on the site.
And suddenly I don't feel the need to release on GitHub.

**Comment by ORN-Fox** [comment]
I understand why you don't feel this need, but I think using the tags on the commits and not the release system will help keep the meaning of the pack versionning.

It would help to know where you are, because if you want to make a modification to the 1.16 package for example and not the 1.17 one. Well personally I don't know from some base to leave! And it's a little embarrassing!

We could have tags on commits like 1.16 v1.2.0, 1.17 0.0.1. Tell me if it makes sense, so that we can all find our way to help in the best way !

**Comment by lipki** [comment]
In fact the versions are separated in different repos.
https://github.com/SummerFields/SummerFields-Format-pack-4__1.13-1.14
https://github.com/SummerFields/SummerFields-Format-pack-3__1.11-1.12

**Comment by ORN-Fox** [comment]
Ah well it works too ;) I didn't pay attention to that!
