### ISSUE TITLE
Opening the sounds/portal/ folder crashes the windows 10 file explorer?

### ISSUE THREAD

**Issue by ORN-Fox** [SummerFields/SummerFields#725]
Hi :D I wanted to know if you have any idea why opening the sounds/portal/ folder crashes the windows 10 file explorer? Am I the only one in this case?

**Comment by lunapanshiel** [comment]
> 
> 
> Hi :D I wanted to know if you have any idea why opening the sounds/portal/ folder crashes the windows 10 file explorer? Am I the only one in this case?

my guess that the file in there has exif data that windows is trying to display in explorer but it can't properly read. it shouldn't actually be an issue, but depending on what you have installed on your system that could be intefering

**Comment by ORN-Fox** [comment]
Thanks for the feedback, you put me on the track with the EXIF data. And actually it's because of the .ogg files and this "Web Media Extensions" extension installed on the pc made Windows Explorer crash. 

The :
- Remove the "Web Media Extensions" extension from the pc to fix the problem. 

I found this by searching on the net and finding this message on Reddit : https://www.reddit.com/r/Windows10/comments/f4ehjm/crash_ogg_files_keep_hangingcrashing_my_windows/

**Comment by lipki** [comment]
windows 10 ... What the hell is that ?
