### ISSUE TITLE
[1.17] moss block

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#732]
![moss_block](https://user-images.githubusercontent.com/401965/106809220-b0e0fa00-666b-11eb-92b8-9c879b89696e.png)

**Comment by Physignatily** [comment]
![moss_block](https://user-images.githubusercontent.com/74598365/108625337-b0f23f80-744a-11eb-8af3-d30ad5c2c0a5.png)
![strgse](https://user-images.githubusercontent.com/74598365/108625351-c5ced300-744a-11eb-85c5-23cb5f86e272.PNG)

**Comment by lipki** [comment]
Here are all the possible colors of grass.
![Capture d’écran du 2021-04-09 16-33-03](https://user-images.githubusercontent.com/401965/114204334-5c067c00-9959-11eb-8003-8eaed1f69537.png)
Here is the average color of all biomes.
![Capture d’écran du 2021-04-09 16-33-03](https://user-images.githubusercontent.com/401965/114205097-3cbc1e80-995a-11eb-8242-1f941005019a.png)

Example :

![moss_block](https://user-images.githubusercontent.com/401965/114207340-90c80280-995c-11eb-885c-4d058885e27b.png)
![Capture d’écran du 2021-04-09 17-52-20](https://user-images.githubusercontent.com/401965/114207840-19df3980-995d-11eb-98a8-b5c3b42bff82.png)

![moss_block](https://user-images.githubusercontent.com/401965/114207991-46935100-995d-11eb-8330-d87a0f0d0af7.png)
![Capture d’écran du 2021-04-09 18-00-42](https://user-images.githubusercontent.com/401965/114208634-fb2d7280-995d-11eb-9702-8ceece154d1c.png)
