### ISSUE TITLE
[1.17] spore blossom

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#734]
![spore_blossom](https://user-images.githubusercontent.com/401965/106809715-4c726a80-666c-11eb-9b93-e9d6a4ddc585.png)![spore_blossom_base](https://user-images.githubusercontent.com/401965/106809720-4d0b0100-666c-11eb-92af-4f78aa465748.png)

**Comment by Physignatily** [comment]
![spore_blossom](https://user-images.githubusercontent.com/74598365/108611473-13adf180-73df-11eb-82a5-0709aab6b351.png) ![spore_blossom_base](https://user-images.githubusercontent.com/74598365/108611481-1f99b380-73df-11eb-9384-f0009358f414.png)
![image](https://user-images.githubusercontent.com/74598365/108611505-71dad480-73df-11eb-94b5-76553a27c29e.png)
