### ISSUE TITLE
[redesign] firework star

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#754]
![firework_rocket](https://raw.githubusercontent.com/SummerFields/SummerFields/a1fff16fdb7c3b2fe057e71d4d1562b7a9c907ae/assets/minecraft/textures/item/firework_rocket.png)
old : ![firework_star](https://raw.githubusercontent.com/SummerFields/SummerFields/a1fff16fdb7c3b2fe057e71d4d1562b7a9c907ae/assets/minecraft/textures/item/firework_star.png) ![firework_star_overlay](https://raw.githubusercontent.com/SummerFields/SummerFields/a1fff16fdb7c3b2fe057e71d4d1562b7a9c907ae/assets/minecraft/textures/item/firework_star_overlay.png)

new : ![firework_star](https://user-images.githubusercontent.com/401965/142766832-9bd1421b-c267-4dd6-8023-d7dcda107263.png) ![firework_star_overlay](https://user-images.githubusercontent.com/401965/142766839-4cd66e4a-6950-4838-95d2-5a95d48695c8.png)

**Comment by ORN-Fox** [comment]
The new texture is more homogeneous with the rest of the pack. That's great !
