### ISSUE TITLE
[1.17 - 1.18] Azalea (textures)

### ISSUE THREAD

**Issue by ORN-Fox** [SummerFields/SummerFields#756]
Hi, I textured the azalea foliage because it was missing, and then we use it on Buildmyworld. So I'm contributing to the Summerfield while keeping our Enigma version of our board up to date.

![2021-12-03_12 50 09](https://user-images.githubusercontent.com/49326517/144649872-2f33ff67-ea63-45a5-a4fb-f3f24bbfc4f3.jpg)

When do you think ? I opened a PR if you want to test https://github.com/SummerFields/SummerFields/pull/757

**Comment by lipki** [comment]
It's weird, yet I made them.
I don't know if I prefer yours or mine ... 
#729

**Comment by ORN-Fox** [comment]
Honestly, I don't like the summerfield version. I even thought it was the XD vanilla texture

**Comment by lipki** [comment]
C'est bon ta gagner :)
