### ISSUE TITLE
[1.19] Warden

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#767]
Warden
_![warden](https://user-images.githubusercontent.com/401965/154591165-11bad2ea-c502-4cc1-b593-bad3e0c24bc1.png) _![warden_bioluminescent_layer](https://user-images.githubusercontent.com/401965/154591168-b6142eb3-1f01-4cc5-92dc-be4471d97479.png) _![warden_ears](https://user-images.githubusercontent.com/401965/154591170-d1bec659-54a7-42fd-b011-4b2b9dcc9820.png) _![warden_heart](https://user-images.githubusercontent.com/401965/154591173-be5e45ca-4352-4f17-800b-277d5669bee4.png) _![warden_pulsating_spots_1](https://user-images.githubusercontent.com/401965/154591175-8d10e96b-c57f-443d-ba58-d9dd135fa7a2.png) _![warden_pulsating_spots_2](https://user-images.githubusercontent.com/401965/154591178-afd2bc58-0362-4d7f-93c2-2d371469d375.png) _

**Comment by lipki** [comment]
It could be related with the phantom.
![Capture d’écran du 2022-02-18 01-37-37](https://user-images.githubusercontent.com/401965/154596294-e3c1982d-b02e-4f7f-a8dc-69cf0ded98b0.png)

**Comment by lipki** [comment]
So...for this mob, I think we can let loose, and do something really different.

![Capture d’écran du 2022-03-29 15-48-59](https://user-images.githubusercontent.com/401965/160628931-57a076fc-3355-47f2-9ee1-d4856bc16dea.png)

I love horns.
I like the general shape without the head. 
For the drawing, the colors... I don't know.

**Comment by lipki** [comment]
Well, in the absence of a better proposal, I take this one.

![warden](https://user-images.githubusercontent.com/401965/173144018-178a6842-bfd6-4214-b931-7870cda68a41.png)![warden_bioluminescent_layer](https://user-images.githubusercontent.com/401965/173144022-f20345e4-725a-4c56-86f8-fb3ef14a9102.png)![warden_heart](https://user-images.githubusercontent.com/401965/173144025-42106bc6-29b4-4072-8a81-fd8252d595b9.png)![warden_pulsating_spots_1](https://user-images.githubusercontent.com/401965/173144028-94a3dc7c-26fd-47b8-a683-2beb199ed4cf.png)![warden_pulsating_spots_2](https://user-images.githubusercontent.com/401965/173144032-858399ee-3ced-4978-9c61-a9d4f44bcd17.png)

![Capture d’écran du 2022-06-10 22-13-35](https://user-images.githubusercontent.com/401965/173143998-3fe6b43a-8899-4b0d-b8b1-71da0f6aedc3.png)

**Comment by ORN-Fox** [comment]
Hi Lipki, this warden have no head ? It's very strange.

**Comment by lipki** [comment]
@ORN-Fox 
Well, in the absence of a better proposal, I take this one.
Yes, that's the idea :)
The head is in the body
And that makes it possible to have very large horns.
It's an aesthetic choice, and for the moment I have no other idea.

**Comment by lipki** [comment]
Give me one.

**Comment by ORN-Fox** [comment]
Alright, I'll work on it!

**Comment by ORN-Fox** [comment]
I'm trying this, to add the head of the warden. Maybe to rework to have a different mouth from the body, but here's the idea

![2022-06-12_11 41 16](https://user-images.githubusercontent.com/49326517/173241349-b1626524-5941-4bcb-b064-bb354edb83cd.png)
![warden](https://user-images.githubusercontent.com/49326517/173241248-e276b480-0936-4264-a6e8-0ece4d4e1c16.png)

**Comment by ORN-Fox** [comment]
@lipki What do you think about it ?
