### ISSUE TITLE
[1.19.x] Allay

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#776]
![allay](https://user-images.githubusercontent.com/401965/161154815-519a8c3e-cf0e-46ed-9ca2-5b75387e70ea.png)

**Comment by lipki** [comment]
ref :
![vex](https://user-images.githubusercontent.com/401965/161155365-eb6d6188-4f9f-419e-8b85-f9a0b17c4467.png) ![vex_charging](https://user-images.githubusercontent.com/401965/161155373-417c9317-740e-4797-8dae-f74ea508ba48.png)

![Capture d’écran du 2022-03-31 23-55-27](https://user-images.githubusercontent.com/401965/161155992-62e1f2f9-326c-4510-8004-2f93545cebbc.png)

**Comment by lipki** [comment]
Tinker Bell  :joy:
![allay](https://user-images.githubusercontent.com/401965/161164201-876e8cbe-e457-4c25-8a3b-fa6aa161c07c.png)
![Capture d’écran du 2022-04-01 01-09-26](https://user-images.githubusercontent.com/401965/161164317-65b841df-49e4-4605-879e-d372ecea298f.png)

**Comment by Physignatily** [comment]
wow, you work fast. I like the idea of pixies/fairies (but maybe not one that screams Tinkerbell™)

i also thougt of ghosts, as in flying rags, without wings? 
but i guess ghosts don't really fit the purpose of collecting items for you

**Comment by lipki** [comment]
Tinker Bell it's a joke. eh.

Yes, maybe a ghost.
Either way, it has to be cute.

**Comment by Physignatily** [comment]
![allay](https://user-images.githubusercontent.com/74598365/161360061-286df37b-9e2e-4ebd-92ab-cc0b3fb94fdb.png)
![grafik](https://user-images.githubusercontent.com/74598365/161360086-5a50a6e9-caf6-4de4-b5f4-04f2dcdcdd28.png)

**Comment by lipki** [comment]
ha! not bad...
I really like.
