### ISSUE TITLE
[1.19.x] echo shard

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#777]
![echo_shard](https://user-images.githubusercontent.com/401965/162189393-be803f00-567c-4169-909e-b25e1b263de2.png)

**Comment by lipki** [comment]
![echo_shard](https://user-images.githubusercontent.com/401965/162329423-d41857a7-5de8-4ed8-a6db-9fac92778d9e.png)

**Comment by Physignatily** [comment]
![echo_shard](https://user-images.githubusercontent.com/74598365/162334180-fbb4582b-adc5-41ab-81b7-d520bac8875d.png) ![echo_shard](https://user-images.githubusercontent.com/74598365/162334333-4f1d3b8e-0923-4145-86c9-ed8781881c0b.png)

**Comment by lipki** [comment]
Yeah I like it, it's more shard.

**Comment by ORN-Fox** [comment]
Either way, I like them both!

**Comment by lipki** [comment]
![echo_shard](https://user-images.githubusercontent.com/401965/167627717-d9125b68-be9a-4117-81d6-931ef10c45bf.png) ![echo_shard](https://user-images.githubusercontent.com/401965/167627916-7dbc404e-6c1e-4af1-9d43-2fc0fa748aff.png)
small color tweak to match other sculk textures.
