### ISSUE TITLE
[1.19.x] recovery compass

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#778]
![recovery_compass_00](https://user-images.githubusercontent.com/401965/162189765-7bf76cd4-625a-489d-9ecc-c228c1e86670.png)![recovery_compass_01](https://user-images.githubusercontent.com/401965/162189793-87f01dc4-dc27-4e0c-9e5a-737fcba15188.png)![recovery_compass_02](https://user-images.githubusercontent.com/401965/162189795-cd2c58fe-a90e-4f20-b211-6f306c5c2523.png)![recovery_compass_03](https://user-images.githubusercontent.com/401965/162189799-0cc37cae-318c-43ff-8b82-80ce94fbfa11.png)![recovery_compass_04](https://user-images.githubusercontent.com/401965/162189804-15548516-558f-4aeb-9380-d531e7eb4582.png)![recovery_compass_05](https://user-images.githubusercontent.com/401965/162189806-bd55ff22-32ad-4bd2-8403-bd3498060a14.png)![recovery_compass_06](https://user-images.githubusercontent.com/401965/162189809-dc334a7a-dff4-49ea-8d37-f19c5a8d43a7.png)![recovery_compass_07](https://user-images.githubusercontent.com/401965/162189811-1f4871a7-4c84-42c5-9aae-aa370456b525.png)![recovery_compass_08](https://user-images.githubusercontent.com/401965/162189813-4bafb66e-97f8-487f-84cb-208aeae287f7.png)![recovery_compass_09](https://user-images.githubusercontent.com/401965/162189819-a474bad5-9e9d-46bb-bb8b-2644592dc31d.png)![recovery_compass_10](https://user-images.githubusercontent.com/401965/162189822-7b57c6f7-7f15-4fb1-a455-93f11ea3d64f.png)![recovery_compass_11](https://user-images.githubusercontent.com/401965/162189824-90575117-fb2b-4419-8595-0306b566ec2f.png)![recovery_compass_12](https://user-images.githubusercontent.com/401965/162189826-0c622a20-19a4-4cc7-999e-60b348f25b6e.png)![recovery_compass_13](https://user-images.githubusercontent.com/401965/162189829-8ce973f3-64f7-49eb-9b09-5f858b2b2bdd.png)![recovery_compass_14](https://user-images.githubusercontent.com/401965/162189831-f15ed5ba-a8ea-4f5b-a886-d356c490f814.png)![recovery_compass_15](https://user-images.githubusercontent.com/401965/162189835-54255371-b816-4b51-988e-9d425cd1567e.png)![recovery_compass_16](https://user-images.githubusercontent.com/401965/162189837-327871de-ba04-41fc-89bd-5df20f4d0089.png)![recovery_compass_17](https://user-images.githubusercontent.com/401965/162189843-3824952f-b205-462f-bac7-53490e7ffdc3.png)![recovery_compass_18](https://user-images.githubusercontent.com/401965/162189845-e7c105ea-4704-4043-98f8-3418ec966ed8.png)![recovery_compass_19](https://user-images.githubusercontent.com/401965/162189846-955fe4f7-3878-4d14-ac66-58d91b48421d.png)![recovery_compass_20](https://user-images.githubusercontent.com/401965/162189848-62187f6d-0d54-41b3-8fbb-b93d324adeb9.png)![recovery_compass_21](https://user-images.githubusercontent.com/401965/162189849-15750eec-4414-4548-b46c-034257138f7c.png)![recovery_compass_22](https://user-images.githubusercontent.com/401965/162189851-9b54ecd8-712b-48d1-bd27-d6ca0288ad2b.png)![recovery_compass_23](https://user-images.githubusercontent.com/401965/162189853-f3494af7-76b0-4f66-9521-15e9b7f9ba14.png)![recovery_compass_24](https://user-images.githubusercontent.com/401965/162189855-aff1ba3f-4aad-4af1-b613-4c9b1d6bc983.png)![recovery_compass_25](https://user-images.githubusercontent.com/401965/162189858-732332b4-04e4-40f5-809a-51c27537512e.png)![recovery_compass_26](https://user-images.githubusercontent.com/401965/162189859-3e4f36d6-cf86-4f3d-afe5-84795ca7f8ba.png)![recovery_compass_27](https://user-images.githubusercontent.com/401965/162189864-46642673-c056-45b3-9106-41f3f8e4facc.png)![recovery_compass_28](https://user-images.githubusercontent.com/401965/162189866-b0bb67ac-eab8-45fa-8956-418c42cf269f.png)![recovery_compass_29](https://user-images.githubusercontent.com/401965/162189868-5237f6b9-8c18-4536-bbd9-5a4619166f27.png)![recovery_compass_30](https://user-images.githubusercontent.com/401965/162189871-d9fd3ce3-9b65-4043-a390-4ed1e6c79a6e.png)![recovery_compass_31](https://user-images.githubusercontent.com/401965/162189874-7e27478b-971f-4778-8b06-c756b5fc92e0.png)
If you have an idea, but you don't want to do all 32 textures, let me know.

**Comment by lipki** [comment]
You can take the opportunity to modify the normal compass too if you want.

**Comment by lipki** [comment]
Well I wanted to wait, but finally I'm not waiting :D
As always, this is just a suggestion.
![recovery_compass_00](https://user-images.githubusercontent.com/401965/162282153-005102b4-75bd-4e91-a288-ce93d93cce87.png)![recovery_compass_01](https://user-images.githubusercontent.com/401965/162282156-e33582d9-932f-419a-a5d7-b6c4c0ebc84c.png)![recovery_compass_02](https://user-images.githubusercontent.com/401965/162282159-a1962569-c9cb-4756-affe-ea6e656c62d2.png)![recovery_compass_03](https://user-images.githubusercontent.com/401965/162282163-f52e3248-ddeb-43b8-b5d1-bef45d619642.png)![recovery_compass_04](https://user-images.githubusercontent.com/401965/162282166-a114b52b-9437-4f92-a8a6-00c0dba5283b.png)![recovery_compass_05](https://user-images.githubusercontent.com/401965/162282170-b481bff3-ceb0-47b9-a308-a65f25e59560.png)![recovery_compass_06](https://user-images.githubusercontent.com/401965/162282172-b4b63fc5-e8fe-489f-bf19-32461920b906.png)![recovery_compass_07](https://user-images.githubusercontent.com/401965/162282174-bbf12572-8acc-427c-96ae-16b5b5a2da47.png)![recovery_compass_08](https://user-images.githubusercontent.com/401965/162282179-68a5702f-4c2a-4640-9901-53f50707216e.png)![recovery_compass_09](https://user-images.githubusercontent.com/401965/162282181-0b0c8d25-a655-4b16-bcb0-1b8fcc8bf5b2.png)![recovery_compass_10](https://user-images.githubusercontent.com/401965/162282183-ccc9e4cb-531e-431f-9ff4-e284f4f5d26a.png)![recovery_compass_11](https://user-images.githubusercontent.com/401965/162282189-d4aac778-4e3b-4551-abfd-fc62bcff361b.png)![recovery_compass_12](https://user-images.githubusercontent.com/401965/162282192-af4ac0a8-0ec1-4afa-b7a7-fbb122666dfa.png)![recovery_compass_13](https://user-images.githubusercontent.com/401965/162282194-46c67569-19c0-4ef3-baf7-f1f1e409fd65.png)![recovery_compass_14](https://user-images.githubusercontent.com/401965/162282197-4487a23b-ed03-4a99-a9a4-c008a3152d7e.png)![recovery_compass_15](https://user-images.githubusercontent.com/401965/162282202-f47cde6f-586b-4b21-8509-8f3c245867d6.png)![recovery_compass_16](https://user-images.githubusercontent.com/401965/162282203-719b5609-1a0b-4c5b-94f2-ef2e4a497622.png)![recovery_compass_17](https://user-images.githubusercontent.com/401965/162282207-cf68beb4-1231-4f96-bb17-a43074481412.png)![recovery_compass_18](https://user-images.githubusercontent.com/401965/162282209-5c104ec8-6f3b-4966-b2b8-1630772d1062.png)![recovery_compass_19](https://user-images.githubusercontent.com/401965/162282213-9aa705c0-07ee-4991-b550-94d840b9766c.png)![recovery_compass_20](https://user-images.githubusercontent.com/401965/162282216-0e0ad50c-f91c-4362-a482-f5dcb3b656e2.png)![recovery_compass_21](https://user-images.githubusercontent.com/401965/162282217-acd6b3a9-97ef-471b-8f87-e38cb5612ffa.png)![recovery_compass_22](https://user-images.githubusercontent.com/401965/162282219-35f76165-e056-4779-8d69-e7b6cff9d809.png)![recovery_compass_23](https://user-images.githubusercontent.com/401965/162282220-ff413059-017c-46e9-8acf-0e780731543a.png)![recovery_compass_24](https://user-images.githubusercontent.com/401965/162282221-b7a727e6-c1bf-4184-b9fb-af3d3d6c3c94.png)![recovery_compass_25](https://user-images.githubusercontent.com/401965/162282226-9069d408-7cb6-46a7-bd93-9508c1382d7d.png)![recovery_compass_26](https://user-images.githubusercontent.com/401965/162282229-e85c9571-c474-405e-af37-e8bcc57de5fe.png)![recovery_compass_27](https://user-images.githubusercontent.com/401965/162282230-9225553e-eaaf-43a9-8024-ea75322ed5f4.png)![recovery_compass_28](https://user-images.githubusercontent.com/401965/162282234-44355cfc-ffdd-4aef-ac79-eaa9ac76bcf0.png)![recovery_compass_29](https://user-images.githubusercontent.com/401965/162282235-b092beab-a64d-47d0-a48d-c35a634dd917.png)![recovery_compass_30](https://user-images.githubusercontent.com/401965/162282242-c79afbc8-28b5-421d-b77d-d2bfdef56780.png)![recovery_compass_31](https://user-images.githubusercontent.com/401965/162282244-e3fe8df3-cc9a-44c6-908a-fd0deac9bf30.png)

**Comment by Physignatily** [comment]
i did a model for the regular compass, but i don't know if it fits :/
![grafik](https://user-images.githubusercontent.com/74598365/162324547-4b1426f0-8bd9-4733-a6fa-7e64ff69eb1b.png)

for the recovery compass maybe an other shape? (clock is square, compass is round and recovery compass is an octagon or sth?)

**Comment by lipki** [comment]
Why not ! Go suggest something.

**Comment by ORN-Fox** [comment]
The model has a strange rendering then the round shape is not something common in the pack. So I prefer Lipki's proposal.
