### ISSUE TITLE
[1.19.x] Disc 5

### ISSUE THREAD

**Issue by Physignatily** [SummerFields/SummerFields#782]
Disc:
![music_disc_5](https://user-images.githubusercontent.com/74598365/164348033-2ed94c7b-d880-477b-aba0-3214cbd9539c.png) 
Fragment:
![disc_fragment_5](https://user-images.githubusercontent.com/74598365/164348066-74d78bb2-04c0-4b5b-ba2f-4f507ca7bf7a.png)

**Comment by Physignatily** [comment]
![music_disc_5](https://user-images.githubusercontent.com/74598365/164348361-dfe8bc0b-1cf5-42c2-9a28-3d1ddd46ec3c.png) ![disc_fragment_5](https://user-images.githubusercontent.com/74598365/164348366-67413143-8e23-4df6-9cea-88f91704fdd0.png)
![disc](https://user-images.githubusercontent.com/74598365/164348453-96466562-73dd-4d7c-adb0-0486fc810b45.gif)

**Comment by lipki** [comment]
We won't do better :D
Perfect !

**Comment by lipki** [comment]
{
  "animation": {
    "interpolate": true,
    "frametime": 6
  }
}

?

**Comment by Physignatily** [comment]
I used frametime:10
