### ISSUE TITLE
[1.19] Mangroove trapdoor model bug

### ISSUE THREAD

**Issue by ORN-Fox** [SummerFields/SummerFields#786]
Hi, I saw this while trying the pack being updated for 1.19. The textures are super cool, great work.

Model seen from below, we do not see the texture of the top.

![2022-06-10_23 14 03](https://user-images.githubusercontent.com/49326517/173241499-32b86d5f-9cb6-4a38-bdbc-0a6a090d0dce.png)

Model seen from above, we see the texture of the top.

![2022-06-10_23 14 07](https://user-images.githubusercontent.com/49326517/173241501-b45157ef-8dd0-44d1-a76e-6379d3f66f62.png)

**Comment by lipki** [comment]
ok merci.

**Comment by lipki** [comment]
I can not reproduce, at home I have the textures on both sides.

**Comment by ORN-Fox** [comment]
Strange, I'll try again on my side :thinking:

**Comment by lipki** [comment]
It's good I found it.

**Comment by ORN-Fox** [comment]
You have fixed this problem ?

**Comment by lipki** [comment]
yes i am
