### ISSUE TITLE
[1.20] Bambou

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#790]
- Bambou #790
![bamboo_door_bottom](https://user-images.githubusercontent.com/401965/196739424-c1862f24-6107-4849-92f2-7b7c976afafa.png) ![bamboo_door_top](https://user-images.githubusercontent.com/401965/196739429-051d5f8b-39c7-41a9-9e30-ad2821550670.png) ![bamboo_fence](https://user-images.githubusercontent.com/401965/196739432-39b2c4d1-b5ca-4cd1-9994-5fec2375ea66.png) ![bamboo_fence_gate](https://user-images.githubusercontent.com/401965/196739433-58fe13ca-5d03-43c2-bcd2-095a5f78b2fb.png) ![bamboo_fence_gate_particle](https://user-images.githubusercontent.com/401965/196739436-64a8d3a6-e7f9-41d1-a3e2-0cd50ed7455b.png) ![bamboo_fence_particle](https://user-images.githubusercontent.com/401965/196739445-1b0b667b-dc0c-485b-8b94-8bbf7a1192e2.png) ![bamboo_mosaic](https://user-images.githubusercontent.com/401965/196739449-cd0ca6a7-d7fb-4c07-a856-90dd6c727cdf.png) ![bamboo_planks](https://user-images.githubusercontent.com/401965/202474102-9407cfb5-2706-4cde-b4ca-aed83f3fabef.png) ![bamboo_trapdoor](https://user-images.githubusercontent.com/401965/196739455-aaf21af5-067d-4af7-be7e-e6da7961cebc.png)
![bamboo_block](https://user-images.githubusercontent.com/401965/202474191-f363c6cc-6165-461a-8a12-06c1ef35dcf0.png) ![bamboo_block_top](https://user-images.githubusercontent.com/401965/202474198-832a6cf8-56c7-467e-bb5f-27cb670b6fac.png) ![stripped_bamboo_block](https://user-images.githubusercontent.com/401965/202474327-036bc908-7657-478f-8dcd-c5554f47dd5e.png) ![stripped_bamboo_block_top](https://user-images.githubusercontent.com/401965/202474330-8d073aab-575a-4641-b7b9-4fd7dec37e42.png)
![bamboo](https://user-images.githubusercontent.com/401965/196740314-85ff75de-c1c6-4ae3-9937-69d022e29b8e.png)
![bamboo](https://user-images.githubusercontent.com/401965/196740672-e8d5b7b3-fdb5-4cee-84a9-a6af310646ed.png)
![bamboo_chest_raft](https://user-images.githubusercontent.com/401965/196743158-693df161-1afc-4a7e-ab8a-04c94370ec79.png) ![bamboo_door](https://user-images.githubusercontent.com/401965/196743162-bed762d4-5927-48bf-980a-3ef52c8c6e8c.png) ![bamboo_hanging_sign](https://user-images.githubusercontent.com/401965/196743167-e9adbf25-ba35-4869-9707-1601ced231bb.png) ![bamboo_raft](https://user-images.githubusercontent.com/401965/196743171-2e7daa49-6573-49d9-b87b-9cf060db88eb.png) ![bamboo_sign](https://user-images.githubusercontent.com/401965/196743173-43329c5a-ee6c-472d-b4c7-7b75ba05f792.png)

**Comment by lipki** [comment]
![bamboo_door_bottom](https://user-images.githubusercontent.com/401965/197274720-634cee63-9762-4739-a8ec-f58a5b16ece2.png) ![bamboo_door_top](https://user-images.githubusercontent.com/401965/197274722-3b5cd37d-54f9-40e4-a786-989ced4ede0d.png) ![bamboo_fence](https://user-images.githubusercontent.com/401965/197274726-ce04737c-1ab6-492c-97c0-1e2b07c637e3.png) ![bamboo_fence_gate](https://user-images.githubusercontent.com/401965/197274729-626a455d-f4a1-4727-a131-761e01f13778.png) ![bamboo_fence_gate_particle](https://user-images.githubusercontent.com/401965/197274731-8f04ae78-ef78-4da4-8fc3-2437d242b1a6.png) ![bamboo_fence_particle](https://user-images.githubusercontent.com/401965/197274733-94080106-99d2-4c09-9b49-4afc341c723f.png) ![bamboo_mosaic](https://user-images.githubusercontent.com/401965/197274734-e19ee851-1cb2-49c8-9c9e-5a0f0fa74ce7.png) ![bamboo_planks](https://user-images.githubusercontent.com/401965/197274740-e30ffd78-e5b0-4560-b9af-aa416135914b.png) ![bamboo_trapdoor](https://user-images.githubusercontent.com/401965/197274741-ea5053d4-57ff-4ea7-9293-e162a79a0dd4.png)

![bamboo](https://user-images.githubusercontent.com/401965/197274854-324632aa-5cc9-437a-8b54-29e5a8d7eb06.png) ![bamboo](https://user-images.githubusercontent.com/401965/197274899-427836fd-a316-4195-b147-16e280fc5ad8.png)

![bamboo_chest_raft](https://user-images.githubusercontent.com/401965/197274975-213ae638-0624-4192-bfbb-118a1a883b62.png) ![bamboo_door](https://user-images.githubusercontent.com/401965/197274980-65c511e9-fd5d-4fe4-8161-f4aeff10f949.png) ![bamboo_hanging_sign](https://user-images.githubusercontent.com/401965/197274983-67c35a52-b75b-4090-b8c6-50393570c85a.png) ![bamboo_raft](https://user-images.githubusercontent.com/401965/197274989-e4c2f577-e952-4897-9ea6-0d31d60c702f.png) ![bamboo_sign](https://user-images.githubusercontent.com/401965/197274990-98a3bfaa-54e2-422f-bca3-8ff48fbe63bb.png)

![Capture d’écran du 2022-10-21 21-35-52](https://user-images.githubusercontent.com/401965/197275813-d91ebf63-d3fe-43c2-a478-68daeb92d220.png)
![Capture d’écran du 2022-10-21 21-34-07](https://user-images.githubusercontent.com/401965/197275583-2c4180be-330c-4e37-87be-be97813a0868.png)

**Comment by Physignatily** [comment]
Wow, as fast as ever

**Comment by lipki** [comment]
You tell me if it sucks huh!
![bamboo_block](https://user-images.githubusercontent.com/401965/201102691-2bd11a54-9c26-4896-bcd0-6eba8441ad77.png) ![bamboo_block_top](https://user-images.githubusercontent.com/401965/201102696-055b7783-9b80-42b8-924b-834505a4c978.png) ![stripped_bamboo_block](https://user-images.githubusercontent.com/401965/201102744-60277dc5-9202-403d-b8e1-e597ae433888.png) ![stripped_bamboo_block_top](https://user-images.githubusercontent.com/401965/201102745-83ac20b3-b265-4a7c-ba27-dfa405d137ce.png)
![Capture d’écran du 2022-11-10 14-20-37](https://user-images.githubusercontent.com/401965/201102645-d7604cad-8590-4b0d-9166-c79725b9e2d1.png)

**Comment by lipki** [comment]
22w46a
![bamboo_planks](https://user-images.githubusercontent.com/401965/202474102-9407cfb5-2706-4cde-b4ca-aed83f3fabef.png)
![bamboo_block](https://user-images.githubusercontent.com/401965/202474191-f363c6cc-6165-461a-8a12-06c1ef35dcf0.png) ![bamboo_block_top](https://user-images.githubusercontent.com/401965/202474198-832a6cf8-56c7-467e-bb5f-27cb670b6fac.png) ![stripped_bamboo_block](https://user-images.githubusercontent.com/401965/202474327-036bc908-7657-478f-8dcd-c5554f47dd5e.png) ![stripped_bamboo_block_top](https://user-images.githubusercontent.com/401965/202474330-8d073aab-575a-4641-b7b9-4fd7dec37e42.png)

**Comment by Physignatily** [comment]
> You tell me if it sucks huh! ![bamboo_block](https://user-images.githubusercontent.com/401965/201102691-2bd11a54-9c26-4896-bcd0-6eba8441ad77.png) ![bamboo_block_top](https://user-images.githubusercontent.com/401965/201102696-055b7783-9b80-42b8-924b-834505a4c978.png) ![stripped_bamboo_block](https://user-images.githubusercontent.com/401965/201102744-60277dc5-9202-403d-b8e1-e597ae433888.png) ![stripped_bamboo_block_top](https://user-images.githubusercontent.com/401965/201102745-83ac20b3-b265-4a7c-ba27-dfa405d137ce.png) ![Capture d’écran du 2022-11-10 14-20-37](https://user-images.githubusercontent.com/401965/201102645-d7604cad-8590-4b0d-9166-c79725b9e2d1.png)

I really like it in general... except the black spots on the top side.
In my opinion the contrast is to harsh on these holes.

**Comment by chengzzi89** [comment]
![20230618223452](https://github.com/SummerFields/SummerFields/assets/28303754/20f35825-ef75-4420-9d7d-b53f918ee9ac)
[bamboo_block.zip](https://github.com/SummerFields/SummerFields/files/11781784/bamboo_block.zip)
Perfect your bamboo blocks

**Comment by chengzzi89** [comment]
![20230618225300](https://github.com/SummerFields/SummerFields/assets/28303754/e073cb53-a1a4-4989-b56e-7299adcfb7d9)
？？

**Comment by lipki** [comment]
@Physignatily  ![stripped_bamboo_block_top](https://github.com/SummerFields/SummerFields/assets/401965/5a27018b-0d83-4a67-aca4-969fee83fb61) ![bamboo_block_top](https://github.com/SummerFields/SummerFields/assets/401965/9437bd60-12dd-462f-8495-8a42e1e0354e) ?

**Comment by Physignatily** [comment]
> @Physignatily  ![stripped_bamboo_block_top](https://github.com/SummerFields/SummerFields/assets/401965/5a27018b-0d83-4a67-aca4-969fee83fb61) ![bamboo_block_top](https://github.com/SummerFields/SummerFields/assets/401965/9437bd60-12dd-462f-8495-8a42e1e0354e) ?
> 
> 

I used this texture for quite some time now and I think i came to like it 😁
