### ISSUE TITLE
Orientation bug for the chorus flowers 3D model

### ISSUE THREAD

**Issue by ORN-Fox** [SummerFields/SummerFields#797]
Hi, a member of my team during an event reported a problem I know about chorus flowers.

It is a problem of orientation of the 3D models, which exists as much on the summerfield as on the enigma.

I don't know much about working on 3D models, otherwise it would be with pleasure that I would have tried to correct this to contribute.

I put two images to show you the problem. Tell me if you need more information.

![2022-10-29_19 16 54](https://user-images.githubusercontent.com/49326517/198911483-43c1104a-72fe-4cc3-b9d0-eca9b44ecfb4.png)
![2022-10-29_19 18 04](https://user-images.githubusercontent.com/49326517/198911486-47915af5-c5ac-46d4-89b9-24ecc27309b4.png)

Thanks, have a good day !

**Comment by lipki** [comment]
The original block is a solid block, so there is no connection problem.
But I wanted to make small seeds.
It's an unsolvable problem, which I chose to ignore :)

Is it really annoying for you ?

**Comment by ORN-Fox** [comment]
It's really not a problem, just a detail.

This is a block that is rarely used only during construction events. So in real life, we can live with it ;)

It was mainly to give feedback.

**Comment by lipki** [comment]
It's still a concern, I keep it open for a while.
![Capture d’écran du 2022-11-01 16-53-25](https://user-images.githubusercontent.com/401965/199278589-06a078ca-5efe-41b9-b8e8-a0083fc390ce.png)

**Comment by lipki** [comment]
![Capture d’écran du 2023-09-17 16-17-28](https://github.com/SummerFields/SummerFields/assets/401965/8ddac9ba-2194-49c6-9248-36db5be4292b)
![Capture d’écran du 2023-09-17 16-17-39](https://github.com/SummerFields/SummerFields/assets/401965/f4ea66ac-18e0-408e-a9ab-d41466c8fa82)
