### ISSUE TITLE
[1.19.4] new creative tabs

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#800]
![tabs](https://user-images.githubusercontent.com/401965/200974888-aca58fc7-86a9-4982-9121-95990ea8b496.png)

**Comment by lipki** [comment]
![tabs](https://user-images.githubusercontent.com/401965/201104007-e8dac2e9-ab6b-414f-8628-fe1a7ab5b2a6.png)

**Comment by lipki** [comment]
![tabs](https://user-images.githubusercontent.com/401965/202589734-58a7d73b-4a9c-46bd-ae75-613483469b40.png)

**Comment by ORN-Fox** [comment]
My team and I prefer the current version using in wood mode which is more homogeneous with the rest of the GUIs.

**Comment by lipki** [comment]
I agree that it is less homogeneous. But the current version uses slots, like buttons.
And that is not consistent.

So maybe we should add a wooden interface button design.

**Comment by lipki** [comment]
![tabs](https://user-images.githubusercontent.com/401965/203152576-f952ded0-5c6b-445e-a6e4-02f19c1b730d.png)![Capture d’écran du 2022-11-21 21-22-50](https://user-images.githubusercontent.com/401965/203152848-522b4a3a-efec-487f-b3b8-9c147ee78cc5.png)

Mouais bof

**Comment by ORN-Fox** [comment]
I stay on the basic wood version which is currently in place.
