### ISSUE TITLE
[1.20] smithing template

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#806]
![netherite_upgrade_smithing_template](https://user-images.githubusercontent.com/401965/227574518-7b6a45c8-acf1-4d06-85f2-f3ebf3c3a99d.png)
![coast_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573973-cb6147f6-1017-4389-b574-5dfa60fb3541.png) ![dune_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573979-49deb665-2b4e-4b13-9fc8-428ab1f05bb9.png) ![eye_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573984-5a6676c6-88d9-49f8-881a-457ef04b3504.png) ![host_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573987-366b4858-e9b5-4cee-98cc-e3aa2c92fb26.png) ![raiser_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573991-08eaa758-f869-42b8-84b3-bbc961cdfa9c.png) ![rib_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573996-ea56cb50-ce09-4975-9ea2-57896d946336.png) ![sentry_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573998-b9bfc2ba-d526-4b2b-8a14-6ee61d21dbdc.png) ![shaper_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574000-4a1ac6e3-5443-4e20-9387-8420e43ef7b8.png) ![silence_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574002-deb98e2a-cc18-45c9-ae9f-f54b07169b96.png) ![snout_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574006-3d168f6e-eaa2-4e53-8ffe-3e7bf3ea73cf.png) ![spire_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574009-f09590f9-de48-4435-9854-2890ef16c152.png) ![tide_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574014-1b326c72-caa6-406a-a539-a825809ba55d.png) ![vex_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574017-265fe5a2-d41b-4a26-b986-9ac8fe5dfc80.png) ![ward_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574018-0bc978f1-55c3-4533-9509-3dd63c621cbc.png) ![wayfinder_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574021-3bd44d10-2a99-4c5c-ad84-16d09fd00f7d.png) ![wild_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574023-a43458ee-3a21-4644-82c9-c562e2d0fa0f.png)

**Comment by lipki** [comment]
@Physignatily Have fun :D

**Comment by Physignatily** [comment]
![netherite_upgrade_smithing_template](https://user-images.githubusercontent.com/74598365/218284132-f34b27f7-2a60-4c95-b133-645131359545.png)
![coast_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284142-e32ee78e-43f1-4e65-90e0-90550dcd4e6b.png)![dune_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284144-f25865a2-a556-4e38-b8f4-bf98775dee2f.png)![eye_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284146-5de34d1e-4a05-49ab-8b07-56f196569890.png)![rib_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284147-a2cb11db-a623-4743-8098-a346bf4f52da.png)![sentry_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284148-05c152b4-e76f-4c5a-b55b-b45bc42175c4.png)![snout_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284150-692cac5d-199f-4354-83dc-cd1ee012bc44.png)![spire_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284151-d0ce7e5b-0d96-48a0-a86e-2bdfdd79ed60.png)![tide_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284152-4438b9b9-dd9c-44f9-8da5-b95750c08f17.png)![vex_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284153-9a38b955-9f8c-46b0-9c31-12e3e1058b86.png)![ward_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284154-f411a3a7-c5e8-4153-8435-6a3c66ed9cea.png)![wild_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284155-f41ff14f-07e6-4e5c-a528-d2f0d108ecd8.png)

**Comment by lipki** [comment]
Not bad, it looks good.
Maybe the coast could be prismarine.
And for the wild, we feel less volume.

**Comment by Physignatily** [comment]
![wild_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218287284-be0ee322-96be-4cee-9ae5-bbf69fce7279.png)
I tried an other base with this one.

**Comment by lipki** [comment]
For coast, I'm bad, you right.
Yes, wild is better.

**Comment by lipki** [comment]
![coast_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573973-cb6147f6-1017-4389-b574-5dfa60fb3541.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![dune_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573979-49deb665-2b4e-4b13-9fc8-428ab1f05bb9.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![eye_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573984-5a6676c6-88d9-49f8-881a-457ef04b3504.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![host_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573987-366b4858-e9b5-4cee-98cc-e3aa2c92fb26.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![raiser_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573991-08eaa758-f869-42b8-84b3-bbc961cdfa9c.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![rib_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573996-ea56cb50-ce09-4975-9ea2-57896d946336.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![sentry_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227573998-b9bfc2ba-d526-4b2b-8a14-6ee61d21dbdc.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![shaper_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574000-4a1ac6e3-5443-4e20-9387-8420e43ef7b8.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![silence_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574002-deb98e2a-cc18-45c9-ae9f-f54b07169b96.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![snout_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574006-3d168f6e-eaa2-4e53-8ffe-3e7bf3ea73cf.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![spire_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574009-f09590f9-de48-4435-9854-2890ef16c152.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![tide_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574014-1b326c72-caa6-406a-a539-a825809ba55d.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![vex_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574017-265fe5a2-d41b-4a26-b986-9ac8fe5dfc80.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![ward_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574018-0bc978f1-55c3-4533-9509-3dd63c621cbc.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![wayfinder_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574021-3bd44d10-2a99-4c5c-ad84-16d09fd00f7d.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![wild_armor_trim_smithing_template](https://user-images.githubusercontent.com/401965/227574023-a43458ee-3a21-4644-82c9-c562e2d0fa0f.png)

![cobblestone](https://user-images.githubusercontent.com/401965/227718210-645caf14-8e14-452f-ac32-132e36ec20a7.png)![sandstone_bottom](https://user-images.githubusercontent.com/401965/227719188-5609c005-a313-44e9-b2ff-c48d244ffa49.png)![end_stone](https://user-images.githubusercontent.com/401965/227719061-4b8fe4b7-fd70-43e7-b9f8-0c2c8b315147.png)![terracotta](https://user-images.githubusercontent.com/401965/227718252-044d4f3c-add1-46a2-aecc-35aaa4f20342.png)![terracotta](https://user-images.githubusercontent.com/401965/227718252-044d4f3c-add1-46a2-aecc-35aaa4f20342.png)![netherrack](https://user-images.githubusercontent.com/401965/227718203-f4d192bd-95e1-4f59-93ca-05d6898969ae.png)![cobblestone](https://user-images.githubusercontent.com/401965/227718210-645caf14-8e14-452f-ac32-132e36ec20a7.png)![terracotta](https://user-images.githubusercontent.com/401965/227718252-044d4f3c-add1-46a2-aecc-35aaa4f20342.png)![cobbled_deepslate](https://user-images.githubusercontent.com/401965/227718263-e4a1b399-2c3a-43dd-ac2b-d6ce173234d0.png)![blackstone](https://user-images.githubusercontent.com/401965/227718275-95f79a2e-9714-458f-b417-f4e83736fddf.png)![purpur_block](https://user-images.githubusercontent.com/401965/227718283-0df8909f-e4fd-443d-b7ce-dbc936cbf631.png)![prismarine](https://user-images.githubusercontent.com/401965/227718345-0008f66f-ad5c-4152-b130-90213c64e7fd.png)![cobblestone](https://user-images.githubusercontent.com/401965/227718210-645caf14-8e14-452f-ac32-132e36ec20a7.png)![cobbled_deepslate](https://user-images.githubusercontent.com/401965/227718263-e4a1b399-2c3a-43dd-ac2b-d6ce173234d0.png)![terracotta](https://user-images.githubusercontent.com/401965/227718252-044d4f3c-add1-46a2-aecc-35aaa4f20342.png)![mossy_cobblestone](https://user-images.githubusercontent.com/401965/227718358-f3e5f293-7baa-4eb1-8234-9b5645a49191.png)

![coast_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284142-e32ee78e-43f1-4e65-90e0-90550dcd4e6b.png)![dune_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284144-f25865a2-a556-4e38-b8f4-bf98775dee2f.png)![eye_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284146-5de34d1e-4a05-49ab-8b07-56f196569890.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![rib_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284147-a2cb11db-a623-4743-8098-a346bf4f52da.png)![sentry_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284148-05c152b4-e76f-4c5a-b55b-b45bc42175c4.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![snout_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284150-692cac5d-199f-4354-83dc-cd1ee012bc44.png)![spire_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284151-d0ce7e5b-0d96-48a0-a86e-2bdfdd79ed60.png)![tide_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284152-4438b9b9-dd9c-44f9-8da5-b95750c08f17.png)![vex_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284153-9a38b955-9f8c-46b0-9c31-12e3e1058b86.png)![ward_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284154-f411a3a7-c5e8-4153-8435-6a3c66ed9cea.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![prismarine](https://user-images.githubusercontent.com/401965/227718757-84bc8064-c7f0-4f85-a79e-7f2d9a6c4854.png)![wild_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/218284155-f41ff14f-07e6-4e5c-a528-d2f0d108ecd8.png)

@Physignatily

**Comment by Physignatily** [comment]
![host_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/229364794-a53eb2ba-6297-4254-bd63-47c333dcdb62.png)![raiser_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/229364802-62c1ee61-0f73-4ad2-855a-32f9e2e05d4e.png)![shaper_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/229364810-644f95f2-c17d-4ef0-b0d5-9922d84147da.png)![wayfinder_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/229364814-beebae61-bcfe-47cb-8006-fb4ac16dd3ad.png)
![silence_armor_trim_smithing_template](https://user-images.githubusercontent.com/74598365/229364818-e526047c-22fa-4412-80c7-8acf5ad71c93.png)
