### ISSUE TITLE
[1.20] trims

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#808]
color_palettes :
![amethyst](https://user-images.githubusercontent.com/401965/227719313-e0a590c7-b29e-4525-8da0-104bfc688a62.png)![copper](https://user-images.githubusercontent.com/401965/227719315-b292e9b4-51e6-4140-a1a5-9589f4ed9127.png)![diamond](https://user-images.githubusercontent.com/401965/227719316-d8469efe-664b-4def-85d3-a7c616c78fec.png)![diamond_darker](https://user-images.githubusercontent.com/401965/227719318-b9da7368-df20-40cd-b380-26e3e7ab7b3b.png)![emerald](https://user-images.githubusercontent.com/401965/227719319-30ab4cad-32d6-42c7-9047-023d833d9e1f.png)![gold](https://user-images.githubusercontent.com/401965/227719320-f1eeb033-8772-4460-ba79-b11dfaf38cf1.png)![gold_darker](https://user-images.githubusercontent.com/401965/227719322-81993f1d-049a-4963-8e83-35d22912138a.png)![iron](https://user-images.githubusercontent.com/401965/227719324-a113d25f-2389-4f27-b8f0-ced926edb80e.png)![iron_darker](https://user-images.githubusercontent.com/401965/227719325-4b9bf2a4-9843-4bbc-9690-59c8aa95507a.png)![lapis](https://user-images.githubusercontent.com/401965/227719326-9926d065-ebc1-4cc0-947f-6314cd9c9c32.png)![netherite](https://user-images.githubusercontent.com/401965/227719327-43d3b5f4-54b9-4849-8b43-a0b131fe743b.png)![netherite_darker](https://user-images.githubusercontent.com/401965/227719328-d6252102-8ba3-4677-9580-983bf6f2c0e7.png)![quartz](https://user-images.githubusercontent.com/401965/227719329-e7386f7c-6e0d-4345-b10e-479ff4cc23eb.png)![redstone](https://user-images.githubusercontent.com/401965/227719331-00f7faf7-d5b5-4fa5-8c71-5cdf1ea23713.png)![trim_palette](https://user-images.githubusercontent.com/401965/227719332-2f741986-4aa9-4f53-b44d-5e4fa4f007df.png)

items :
![boots_trim](https://user-images.githubusercontent.com/401965/214563772-a9daa526-06f1-4175-896f-1273b440dfe3.png)![chestplate_trim](https://user-images.githubusercontent.com/401965/214563773-ec489769-3722-4e54-80fd-12926edb06b2.png)![helmet_trim](https://user-images.githubusercontent.com/401965/214563777-1fac31bd-b2e5-4230-86c4-baec3282a63a.png)![leggings_trim](https://user-images.githubusercontent.com/401965/214563780-8d8a4638-aa21-4990-9dad-d57b0f28f6d4.png)

armor :
![coast](https://user-images.githubusercontent.com/401965/227719585-e6e06c3d-9cc4-4191-8fb6-aac19b22245b.png)![coast_leggings](https://user-images.githubusercontent.com/401965/227719586-7d3689af-ec4f-4881-811c-3dedf1dc2c9b.png)![dune](https://user-images.githubusercontent.com/401965/227719587-89b12b88-af80-4b92-8b7c-70e8c8258b7d.png)![dune_leggings](https://user-images.githubusercontent.com/401965/227719591-8d7df907-6fc9-4860-b555-815e062e85ac.png)![eye](https://user-images.githubusercontent.com/401965/227719594-da9e83a4-7c8b-4a33-b6bd-4b0e6430bc75.png)![eye_leggings](https://user-images.githubusercontent.com/401965/227719597-b32464e8-c25a-4595-a8a1-1e7851ce0874.png)![host](https://user-images.githubusercontent.com/401965/227719602-ccb0e39c-ca72-43ac-924c-978b735c0458.png)![host_leggings](https://user-images.githubusercontent.com/401965/227719605-f6dd6dd4-30bc-4725-9f4c-59c70e4d196c.png)![raiser](https://user-images.githubusercontent.com/401965/227719607-8262f8c1-4fa4-476d-9e76-20c70d204529.png)![raiser_leggings](https://user-images.githubusercontent.com/401965/227719609-008d128e-284e-4ed8-ab04-ab97fa768f08.png)![rib](https://user-images.githubusercontent.com/401965/227719612-0789ea31-3ffa-4325-bb6b-97bd621c6976.png)![rib_leggings](https://user-images.githubusercontent.com/401965/227719613-afd20634-c699-46d9-9b4c-2079277c32d2.png)![sentry](https://user-images.githubusercontent.com/401965/227719616-42142825-48f5-45a8-95cc-165ca8a8d4ee.png)![sentry_leggings](https://user-images.githubusercontent.com/401965/227719617-30cd8c6c-cd28-41b8-9b1b-6ab79807c5ba.png)![shaper](https://user-images.githubusercontent.com/401965/227719618-fec6cea3-9fe8-48eb-a86e-39f82b04dfdb.png)![shaper_leggings](https://user-images.githubusercontent.com/401965/227719620-ce2e3067-e82b-411e-8b05-ac848fc657f2.png)![silence](https://user-images.githubusercontent.com/401965/227719621-ec341f32-f286-427a-9e67-aaa23ff27342.png)![silence_leggings](https://user-images.githubusercontent.com/401965/227719623-1fa61677-4a18-47e5-9e09-fb099fbc381d.png)![snout](https://user-images.githubusercontent.com/401965/227719624-ce972832-32aa-48e2-b1bc-baa9221222aa.png)![snout_leggings](https://user-images.githubusercontent.com/401965/227719625-8b4ace3c-7541-473c-95fa-9c845bffc246.png)![spire](https://user-images.githubusercontent.com/401965/227719628-32f4f803-a618-41cc-91eb-dba366e10df6.png)![spire_leggings](https://user-images.githubusercontent.com/401965/227719630-9a2235c5-2b32-48d7-8949-9a34c3ead577.png)![tide](https://user-images.githubusercontent.com/401965/227719631-0303c093-3e44-4b67-964e-13e8d21ed9b4.png)![tide_leggings](https://user-images.githubusercontent.com/401965/227719633-6b5fbab4-8ef6-40be-a4b3-ae37e258ea06.png)![vex](https://user-images.githubusercontent.com/401965/227719634-212bba54-8864-4865-8bd1-149e22e4e925.png)![vex_leggings](https://user-images.githubusercontent.com/401965/227719636-b77c09c1-2887-4a77-b482-253c8f15174a.png)![ward](https://user-images.githubusercontent.com/401965/227719638-cca55655-dd1b-4c95-ae55-ec0bfe2402a2.png)![ward_leggings](https://user-images.githubusercontent.com/401965/227719641-98e8afc8-06a6-44bd-aad4-c1a0d2c51f31.png)![wayfinder](https://user-images.githubusercontent.com/401965/227719642-4a284de4-ebc3-47e8-aa9e-958359c44f7b.png)![wayfinder_leggings](https://user-images.githubusercontent.com/401965/227719643-7e698f80-0b22-4fdb-b65c-b5ac9dd612af.png)![wild](https://user-images.githubusercontent.com/401965/227719646-9adcb64f-23a0-423e-90d9-02beaaeddc01.png)![wild_leggings](https://user-images.githubusercontent.com/401965/227719647-18e5cea7-4fc5-4a57-a72c-78d889b4f91d.png)

**Comment by lipki** [comment]
Well, there's a lot to say.

First, I like the color palette system.
I wonder if they will reuse the system, to see what they do with it.

Then we see that they only made a variant of the trims for the items.
We see if it is relevant, it will in any case be easier.

Then the trims and there, it's boring.
All our armors are different and rich in details.

However, the same trim applies to all armours.

Alright, we'll see.
Please make suggestions.

**Comment by lipki** [comment]
I can't find a solution. :(

**Comment by lipki** [comment]
We will never be able to find patterns that fit all armors.
![Capture d’écran du 2023-01-25 16-45-03](https://user-images.githubusercontent.com/401965/214608715-ba0c164c-4b20-4fb1-8361-4e9f47aa6da0.png)

**Comment by lipki** [comment]
It's okay, I have a good lead.
![Capture d’écran du 2023-01-26 00-23-54](https://user-images.githubusercontent.com/401965/214715984-368f02b5-5479-4ac2-8e2b-7e23f17666d6.png)
![Capture d’écran du 2023-01-26 00-19-42](https://user-images.githubusercontent.com/401965/214716313-c6f21bf3-f583-4b2b-b729-d53ef0d6b571.png)

**Comment by lipki** [comment]
zoom zoom zoom
![2023-01-26_20 45 03](https://user-images.githubusercontent.com/401965/214935383-c1628644-76cf-4c79-9f04-78bc1695b5a0.png)

**Comment by lipki** [comment]
As usual, this is a first draft.
I don't share textures, because it's complicated, I'll commit directly.
![Capture d’écran du 2023-01-27 00-49-02](https://user-images.githubusercontent.com/401965/214976935-0d4c351f-51ee-4019-96bb-7c7f2c66b9fe.png)
![Capture d’écran du 2023-01-27 00-49-25](https://user-images.githubusercontent.com/401965/214976942-931708e7-4247-44cb-8f47-782c4a2dce84.png)
![Capture d’écran du 2023-01-27 00-50-17](https://user-images.githubusercontent.com/401965/214976954-4ba76042-79ef-498b-afcc-5e8a253e983f.png)
![Capture d’écran du 2023-01-27 00-50-31](https://user-images.githubusercontent.com/401965/214976969-dd4e5852-680b-4753-adac-75fc4b45f3b6.png)
![Capture d’écran du 2023-01-27 00-50-53](https://user-images.githubusercontent.com/401965/214976981-8b16b398-34a8-40e3-9876-1ec3cece3efe.png)
![Capture d’écran du 2023-01-27 00-51-52](https://user-images.githubusercontent.com/401965/214977004-46fe651b-7b85-4161-be89-3c93ea076c7b.png)

**Comment by lipki** [comment]
![amethyst](https://user-images.githubusercontent.com/401965/214977416-37b53a5a-b06f-46b4-a7b8-5cc4813c7b71.png)![copper](https://user-images.githubusercontent.com/401965/214977417-96fbb536-82df-46cf-916d-3f5117b0fa87.png)![diamond](https://user-images.githubusercontent.com/401965/214977418-ae099335-c071-4dd4-9a99-1d316eb95c23.png)![emerald](https://user-images.githubusercontent.com/401965/214977420-648cde4a-f5c9-4cb2-b3fc-f9cb2d3f790d.png)![gold](https://user-images.githubusercontent.com/401965/214977422-d0c652fe-42a8-49a6-96ef-f524bf007445.png)![iron](https://user-images.githubusercontent.com/401965/214977424-168fee1e-cb00-44e4-a2ba-6623dc0f8676.png)![lapis](https://user-images.githubusercontent.com/401965/214977427-5f6335bf-73d7-456c-8afb-35653f55d5b1.png)![netherite](https://user-images.githubusercontent.com/401965/214977429-cf48eb34-7333-4922-bd12-83740459a989.png)![quartz](https://user-images.githubusercontent.com/401965/214977431-8d883195-3080-4bbe-a206-df3817ecbd74.png)![redstone](https://user-images.githubusercontent.com/401965/214977432-9d0975d2-34b3-4e6b-ac67-fb224e66b35d.png)![trim_palette](https://user-images.githubusercontent.com/401965/214977434-434962f8-a97a-4e0a-a9d8-71b0f6c462c7.png)

![Capture d’écran du 2023-01-26 00-19-42](https://user-images.githubusercontent.com/401965/214977910-e2eb74a2-8652-44f3-9281-2860e0295236.png)

![boots_trim](https://user-images.githubusercontent.com/401965/214977939-7c7012e1-9cb7-4387-8721-639f1db6c412.png)![chestplate_trim](https://user-images.githubusercontent.com/401965/214977942-1c1dfb5e-e4c8-49be-b6db-2f80e0d56f99.png)![helmet_trim](https://user-images.githubusercontent.com/401965/214977944-d76decd7-d9b6-43d8-9aea-94f32ede710b.png)![leggings_trim](https://user-images.githubusercontent.com/401965/214977951-c26ea793-44e2-4dba-911a-046b085e5bae.png)

![coast](https://user-images.githubusercontent.com/401965/214978007-2e50cd9b-5628-46b9-babd-b5b874b511b2.png)![coast_leggings](https://user-images.githubusercontent.com/401965/214978013-9939dc5f-9025-4842-af5b-7dc76af9d587.png)![eye](https://user-images.githubusercontent.com/401965/214978015-d307c984-f3e6-4980-9c42-d34051fe95b8.png)![eye_leggings](https://user-images.githubusercontent.com/401965/214978018-07c17df7-d2d2-49d7-9725-86ebc193a27f.png)![rib](https://user-images.githubusercontent.com/401965/214978021-2b290b03-d1a5-4766-b588-b81facc69bd6.png)![rib_leggings](https://user-images.githubusercontent.com/401965/214978023-1da6027e-23ed-4dcc-a09d-ef3a7d1d5a1f.png)![tide](https://user-images.githubusercontent.com/401965/214978024-174cf92f-aae5-46f7-9478-c14dfebd96e6.png)![tide_leggings](https://user-images.githubusercontent.com/401965/214978026-ba5e6834-b6e5-4447-8249-54afb63e6a5c.png)![vex](https://user-images.githubusercontent.com/401965/214978029-1f906f16-6b2e-4238-9f5b-f0e8af974c16.png)![vex_leggings](https://user-images.githubusercontent.com/401965/214978031-9a51d80f-1ff7-4e32-9b8b-bd8c7de7c742.png)![ward](https://user-images.githubusercontent.com/401965/214978034-19e7c870-583d-4439-b49d-5dd0d3826bbf.png)![ward_leggings](https://user-images.githubusercontent.com/401965/214978037-8c6967fc-69e0-4ae3-99ed-e46c7983335e.png)

**Comment by lipki** [comment]
Add 23w12a : 

![diamond_darker](https://user-images.githubusercontent.com/401965/227719318-b9da7368-df20-40cd-b380-26e3e7ab7b3b.png)![gold_darker](https://user-images.githubusercontent.com/401965/227719322-81993f1d-049a-4963-8e83-35d22912138a.png)![iron_darker](https://user-images.githubusercontent.com/401965/227719325-4b9bf2a4-9843-4bbc-9690-59c8aa95507a.png)![netherite_darker](https://user-images.githubusercontent.com/401965/227719328-d6252102-8ba3-4677-9580-983bf6f2c0e7.png)

![host](https://user-images.githubusercontent.com/401965/227719602-ccb0e39c-ca72-43ac-924c-978b735c0458.png)![host_leggings](https://user-images.githubusercontent.com/401965/227719605-f6dd6dd4-30bc-4725-9f4c-59c70e4d196c.png)![raiser](https://user-images.githubusercontent.com/401965/227719607-8262f8c1-4fa4-476d-9e76-20c70d204529.png)![raiser_leggings](https://user-images.githubusercontent.com/401965/227719609-008d128e-284e-4ed8-ab04-ab97fa768f08.png)![shaper](https://user-images.githubusercontent.com/401965/227719618-fec6cea3-9fe8-48eb-a86e-39f82b04dfdb.png)![shaper_leggings](https://user-images.githubusercontent.com/401965/227719620-ce2e3067-e82b-411e-8b05-ac848fc657f2.png)![silence](https://user-images.githubusercontent.com/401965/227719621-ec341f32-f286-427a-9e67-aaa23ff27342.png)![silence_leggings](https://user-images.githubusercontent.com/401965/227719623-1fa61677-4a18-47e5-9e09-fb099fbc381d.png)![wayfinder](https://user-images.githubusercontent.com/401965/227719642-4a284de4-ebc3-47e8-aa9e-958359c44f7b.png)![wayfinder_leggings](https://user-images.githubusercontent.com/401965/227719643-7e698f80-0b22-4fdb-b65c-b5ac9dd612af.png)

**Comment by lipki** [comment]
Coast : Shipwreck
Dune : Desert temple
Eye : Stronghold
Rib :  Nether fortress
Sentry : Pillager Outpost
Silence : Ancient City
Snout : Bastion remnant
Spire : End city
Vex : Woodland mansion
Ward : Ancient City
Wild : Jungle temple
Wayfinder : Trail ruins
Shaper : Trail ruins
Host : Trail ruins
Raiser : Trail ruins
Tide : Trail ruins

**Comment by lipki** [comment]
![Capture d’écran du 2023-03-26 01-49-42](https://user-images.githubusercontent.com/401965/227790498-7f71c0bb-5b25-4160-bd88-42724735d87c.png)
![Capture d’écran du 2023-03-26 01-51-50](https://user-images.githubusercontent.com/401965/227790512-fdf5a61f-c191-41bf-862f-2ff82c27fccc.png)
![Capture d’écran du 2023-03-26 18-18-16](https://user-images.githubusercontent.com/401965/227790525-06746f06-63cc-4955-9d52-261a1ce645e7.png)

**Comment by lipki** [comment]
![Capture d’écran du 2023-03-27 13-55-32](https://user-images.githubusercontent.com/401965/227934766-10b267b0-fc6c-4b89-912e-89e0341f3eac.png)

**Comment by lipki** [comment]
```
spire      End city           Diamond
silence    Ancient City       Wool
ward       Ancient City       Sculk
snout      Bastion remnant    Netherite
rib        Nether fortress    Whiter
eye        Stronghold         Eye
tide       Ocean Monument     Trident
sentry     Pillager Outpost   Gold
vex        Woodland mansion   Kilt
dune       Desert temple      Jacket
wild       Jungle temple      Leather
coast      Shipwreck          Algue
shaper     Trail ruins        1 bands
wayfinder  Trail ruins        2 bandes
raiser     Trail ruins        Adidas
host       Trail ruins        Rib
```

**Comment by lipki** [comment]
![z-spire](https://user-images.githubusercontent.com/401965/228390712-ff195c5c-4693-496a-9ed1-d0aa450b3111.png)
![z-silence](https://user-images.githubusercontent.com/401965/228390682-435c55e6-b8cb-473c-ae71-9068674b3eae.png)
![z-ward](https://user-images.githubusercontent.com/401965/228390764-e76cc9cd-a390-4924-879e-0237c4658488.png)
![z-snout](https://user-images.githubusercontent.com/401965/228390696-b85a742f-ca47-4c2b-9383-ba1824d6e477.png)
![z-rib](https://user-images.githubusercontent.com/401965/228390618-5efb94d5-ad80-4a8c-bb8c-43f3fe05eee2.png)
![z-eye](https://user-images.githubusercontent.com/401965/228390526-756c4fcf-5725-4a66-8782-7cbc056cdc68.png)
![z-tide](https://user-images.githubusercontent.com/401965/228390731-60090937-9bd1-4b61-869b-6de60858801b.png)
![z-sentry](https://user-images.githubusercontent.com/401965/228390640-25f1222a-2fcb-4391-b763-b29b3dfa255d.png)
![z-vex](https://user-images.githubusercontent.com/401965/228390744-c5dc0301-4480-4d73-8999-af597fd5872a.png)
![z-dune](https://user-images.githubusercontent.com/401965/228390496-3f59b675-8fa3-46f7-a564-630b0d51ac78.png)
![z-wild](https://user-images.githubusercontent.com/401965/228390814-b78173cd-1b1f-456f-9a4b-053efc7dda53.png)
![z-coast](https://user-images.githubusercontent.com/401965/228390478-d54aa478-45d5-47e0-99e8-98263610a483.png)
![z-shaper](https://user-images.githubusercontent.com/401965/228390657-569a37df-a68d-43cd-91bd-70f7bbb9a29d.png)
![z-wayfinder](https://user-images.githubusercontent.com/401965/228390788-e47f6238-4f60-4262-92b0-b4855d3e4a58.png)
![z-raiser](https://user-images.githubusercontent.com/401965/228390576-53f4dc78-062d-48f1-b1b4-85cae08b6532.png)
![z-host](https://user-images.githubusercontent.com/401965/228390551-3734d74f-d4cf-4f0b-8db5-c4551f92fbdf.png)

**Comment by ORN-Fox** [comment]
WOW !!!

**Comment by ORN-Fox** [comment]
@lipki Holy work! The finish is super clean!

**Comment by ORN-Fox** [comment]
I try the armor patterns in 1.20.1 and I see that the 3d models in the inventory are displayed badly (see the image) on the other hand in game the rendering is spot on!
![image](https://github.com/SummerFields/SummerFields/assets/49326517/78a4c820-20c3-4ec3-829d-1e2eb7fc4f84)
