### ISSUE TITLE
[1.20] Archeologies

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#812]
![suspicious_sand_0](https://user-images.githubusercontent.com/401965/219157819-60b2d599-b76e-4e65-a95f-189454a60880.png) ![suspicious_sand_1](https://user-images.githubusercontent.com/401965/219157829-0ac6a29f-d9b5-4c01-8219-6c566231c709.png) ![suspicious_sand_2](https://user-images.githubusercontent.com/401965/219157834-5ddf1161-4954-41e4-882c-c511b7badc58.png) ![suspicious_sand_3](https://user-images.githubusercontent.com/401965/219157837-62fbc67b-8154-4bcb-9086-a193e2d625e2.png)

![suspicious_gravel_0](https://user-images.githubusercontent.com/401965/227566307-a1a5dfd0-d222-4266-b5a2-bc66d1f9eb5f.png) ![suspicious_gravel_1](https://user-images.githubusercontent.com/401965/227566315-1573ab5e-4618-45d3-b114-c2295885e9bc.png) ![suspicious_gravel_2](https://user-images.githubusercontent.com/401965/227566326-12165797-eed0-4bcc-9e96-58b221a5b8da.png) ![suspicious_gravel_3](https://user-images.githubusercontent.com/401965/227566346-53296149-96e4-44e9-8447-7d1bb752a459.png)

![decorated_pot_base](https://user-images.githubusercontent.com/401965/219159312-f9819c39-3b9c-4dad-92f6-3cf0c82e1ad5.png)![decorated_pot_side](https://user-images.githubusercontent.com/401965/219159320-a5e7073f-4845-4b27-8027-7b7c88603e2a.png)

![angler_pottery_pattern](https://user-images.githubusercontent.com/401965/227567317-ce46c121-f706-4bbd-a12c-908d393b3e39.png) ![archer_pottery_pattern](https://user-images.githubusercontent.com/401965/227567320-148451a7-5fe7-4587-912e-01d6326424d2.png) ![arms_up_pottery_pattern](https://user-images.githubusercontent.com/401965/227567324-387bab6e-5950-4a38-a158-6242342862b9.png) ![blade_pottery_pattern](https://user-images.githubusercontent.com/401965/227567328-44b2db7e-724a-4365-8826-8003f8fd99e1.png) ![brewer_pottery_pattern](https://user-images.githubusercontent.com/401965/227567334-d082a30c-9564-4041-88b1-48e1fee80b84.png) ![burn_pottery_pattern](https://user-images.githubusercontent.com/401965/227567336-4239f7e1-c2d5-495c-ab53-d0814d57b532.png) ![danger_pottery_pattern](https://user-images.githubusercontent.com/401965/227567338-fd89d4de-0405-4812-8736-ff60d6706e66.png) ![explorer_pottery_pattern](https://user-images.githubusercontent.com/401965/227567340-1fd659e4-42ef-477d-977e-6818bd2664b2.png) ![friend_pottery_pattern](https://user-images.githubusercontent.com/401965/227567345-006d94e4-a31e-49fa-a653-98d1cbd16d62.png) ![heartbreak_pottery_pattern](https://user-images.githubusercontent.com/401965/227567350-f3450702-f0b6-46d2-83a2-15120518818b.png) ![heart_pottery_pattern](https://user-images.githubusercontent.com/401965/227567352-a2c9b114-980b-47ba-aa79-869ee7968509.png) ![howl_pottery_pattern](https://user-images.githubusercontent.com/401965/227567353-4cf4d2a5-2098-4a5a-8ec1-acc2671abe28.png) ![miner_pottery_pattern](https://user-images.githubusercontent.com/401965/227567355-a9df4734-f416-4417-a342-618cb826e8d9.png) ![mourner_pottery_pattern](https://user-images.githubusercontent.com/401965/227567357-a3cb2d20-6492-493c-91fb-e36f37579a22.png) ![plenty_pottery_pattern](https://user-images.githubusercontent.com/401965/227567359-36790843-86d9-49ff-a7f9-0408d225257d.png) ![prize_pottery_pattern](https://user-images.githubusercontent.com/401965/227567361-ce742962-44ef-4367-90bb-5b53cf520541.png) ![sheaf_pottery_pattern](https://user-images.githubusercontent.com/401965/227567362-6542318b-5efa-40e2-9512-0314bf6ecd8d.png) ![shelter_pottery_pattern](https://user-images.githubusercontent.com/401965/227567366-dec38eef-b63f-4a77-81ae-fc17ad202128.png) ![skull_pottery_pattern](https://user-images.githubusercontent.com/401965/227567367-af1bc51f-2d55-478d-b69a-220202befc7e.png) ![snort_pottery_pattern](https://user-images.githubusercontent.com/401965/227567369-f4fc30d4-e279-408d-a803-5403bbf2a3f7.png)

![brush](https://user-images.githubusercontent.com/401965/219161616-0568fcd4-18ac-4343-b656-10ba73edf53c.png)

![angler_pottery_shard](https://user-images.githubusercontent.com/401965/227567910-4e425c96-07c1-4b83-aafd-9abcb11531f1.png) ![archer_pottery_shard](https://user-images.githubusercontent.com/401965/227567914-1c4780c2-3e35-45f6-8592-6f1ffd9d11e7.png) ![arms_up_pottery_shard](https://user-images.githubusercontent.com/401965/227567919-24a0324d-7860-4981-bdfb-ecb5b748dc44.png) ![blade_pottery_shard](https://user-images.githubusercontent.com/401965/227567921-44ecfcc1-f572-4b82-a7a3-a3d987e282d8.png) ![brewer_pottery_shard](https://user-images.githubusercontent.com/401965/227567923-4ffd3dd3-a24b-401d-8161-8089febdcd84.png) ![burn_pottery_shard](https://user-images.githubusercontent.com/401965/227567927-1cd79cfe-8fd0-4086-af64-822bd175f831.png) ![danger_pottery_shard](https://user-images.githubusercontent.com/401965/227567929-87798e80-631a-4d1f-b7e1-62bdedc9340d.png) ![explorer_pottery_shard](https://user-images.githubusercontent.com/401965/227567933-b5929366-1831-4263-9656-01e5e0b909b7.png) ![friend_pottery_shard](https://user-images.githubusercontent.com/401965/227567934-e255935a-8cad-41e0-bb15-aa61c7e64dcb.png) ![heartbreak_pottery_shard](https://user-images.githubusercontent.com/401965/227567936-2ca72555-16ca-49cd-a434-704c07e17ab3.png) ![heart_pottery_shard](https://user-images.githubusercontent.com/401965/227567939-70b9fb36-7a50-46e2-8ce3-c407e017f040.png) ![howl_pottery_shard](https://user-images.githubusercontent.com/401965/227567944-0b70833a-3abf-4acf-97f6-94613441fbe2.png) ![miner_pottery_shard](https://user-images.githubusercontent.com/401965/227567945-083a3129-1abe-456f-b7f8-0be58399489a.png) ![mourner_pottery_shard](https://user-images.githubusercontent.com/401965/227567949-a3d1b154-1210-4fb4-9c0f-3d2d89bdcea4.png) ![plenty_pottery_shard](https://user-images.githubusercontent.com/401965/227567954-455dbb5a-2cc0-4b8c-9ad1-2011878df719.png) ![prize_pottery_shard](https://user-images.githubusercontent.com/401965/227567958-a6e22604-9210-4d2e-bd83-59ace9e9d3b8.png) ![sheaf_pottery_shard](https://user-images.githubusercontent.com/401965/227568222-b512408f-d3cb-496a-a260-1cee6a42d0aa.png) ![shelter_pottery_shard](https://user-images.githubusercontent.com/401965/227568228-dad05332-bafa-4b3f-9436-ae129b792791.png) ![skull_pottery_shard](https://user-images.githubusercontent.com/401965/227568230-e01f45dc-5c0f-4728-acf3-399567fb84de.png) ![snort_pottery_shard](https://user-images.githubusercontent.com/401965/227568232-cd71d84a-9c14-4cac-b617-c1528018c309.png)

**Comment by lipki** [comment]
If you have any design ideas for the pot, I'm interested.

**Comment by Physignatily** [comment]
![brush](https://user-images.githubusercontent.com/74598365/219185771-0fb41d99-7260-46b2-9df5-5aba0b85dfe4.png)

**Comment by lipki** [comment]
Faster than your shadow :smile:

**Comment by lipki** [comment]
Merci, it's great !

**Comment by lipki** [comment]
![decorated_pot_base](https://user-images.githubusercontent.com/401965/219784277-a367f4ee-c2ab-4ac1-b36a-b9ca7dbd6f13.png)![decorated_pot_side](https://user-images.githubusercontent.com/401965/219784141-1aad7ea9-347b-4d4b-b5ad-afec3b23fe74.png)
![Capture d’écran du 2023-02-17 21-10-58](https://user-images.githubusercontent.com/401965/219784036-fe47bcfd-4cfb-410e-8462-c4003495c9cf.png)

**Comment by lipki** [comment]
![pottery_pattern_archer](https://user-images.githubusercontent.com/401965/219785200-f6085aaf-e004-4afb-8216-e0ad9c6d8b84.png)![pottery_pattern_arms_up](https://user-images.githubusercontent.com/401965/219785207-96ba3ab6-b0ab-48b5-b174-6ee79c3f6df4.png)![pottery_pattern_prize](https://user-images.githubusercontent.com/401965/219785208-5fb07e49-61ff-4e8f-944c-7469f13c67aa.png)![pottery_pattern_skull](https://user-images.githubusercontent.com/401965/219785211-f9586e28-0d11-4476-875d-4cd775e711d4.png)

Go pattern contest, All together, we can do better.

**Comment by lipki** [comment]
![Capture d’écran du 2023-02-17 21-30-06](https://user-images.githubusercontent.com/401965/219787048-bb06b23a-f1c0-4de1-94f0-ed4b1b11dc30.png)

**Comment by Physignatily** [comment]
I like the suspicious sand. It is reather hard to differentiate from normal sand, so you have to look very carefully in the dungeons.

To the pots: Generally i like the style, except the top part. The bright orange of the top has to reoccur on the rest of the pot to work. 

To the patterns: The skull looks really nice. The other three don't strike me that much :/

**Comment by lipki** [comment]
I don't like any patterns :)

![Capture d’écran du 2023-02-18 19-57-28](https://user-images.githubusercontent.com/401965/219883403-f1e4bae2-00cc-4cc7-8558-c023ff33cc71.png)

**Comment by lipki** [comment]
![suspicious_gravel_0](https://user-images.githubusercontent.com/401965/227601184-ad600100-1545-4e0e-9e4d-63517f646d6d.png)![suspicious_gravel_1](https://user-images.githubusercontent.com/401965/227601190-a7eece07-bf0a-4103-ab22-9a3b97c1876b.png)![suspicious_gravel_2](https://user-images.githubusercontent.com/401965/227601193-381c8111-7fe7-4194-80b1-5d4fb9ed02d8.png)![suspicious_gravel_3](https://user-images.githubusercontent.com/401965/227601196-880675bd-32bc-4861-a0ad-58b9b8321a89.png)

![Capture d’écran du 2023-03-24 18-47-12](https://user-images.githubusercontent.com/401965/227601831-d1a0e1c6-58fc-4b84-90f5-1f0518f6d956.png)

**Comment by Physignatily** [comment]
![angler_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/74598365/b1f64122-bf6c-4953-9101-fb8da5ddef96)![brewer_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/74598365/c8320acd-42a9-4918-947a-b841e973800c)![burn_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/74598365/1770a2ac-ef35-44f3-87dc-29ef8e996aee)![friend_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/74598365/580d9053-f894-4e98-82c2-2a8ec61ad6c4)![heart_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/74598365/9c572f8f-06dc-43b4-976d-a639639839db)![heartbreak_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/74598365/48eb44ab-258f-4f27-bc22-68db45c1d20d)![miner_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/74598365/3f0cac50-989c-4a65-8ffb-88a9d0860b2c)![prize_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/74598365/eee3ad23-399f-4677-a3e5-7c3db4c4a0fc)
angler, brewer,burn, friend, heart, heartbreak, miner, prize v2
![grafik](https://github.com/SummerFields/SummerFields/assets/74598365/5b1a9567-2aac-459e-94e9-2b0797f5d3da)

**Comment by ORN-Fox** [comment]
I just tried the texture of the decorate pot, here is the strange rendering I have?!
![2023-07-24_13 23 50](https://github.com/SummerFields/SummerFields/assets/49326517/bffc524e-bfd1-48ee-935d-e6cfa249b2f3)

**Comment by Physignatily** [comment]
![music_disc_relic](https://github.com/SummerFields/SummerFields/assets/74598365/c4c4c606-10a5-4da0-bae7-93359982e4c2)
music disc relic

**Comment by lipki** [comment]
> ![angler_pottery_pattern](https://user-images.githubusercontent.com/74598365/248594624-b1f64122-bf6c-4953-9101-fb8da5ddef96.png)![brewer_pottery_pattern](https://user-images.githubusercontent.com/74598365/248594626-c8320acd-42a9-4918-947a-b841e973800c.png)![burn_pottery_pattern](https://user-images.githubusercontent.com/74598365/248594627-1770a2ac-ef35-44f3-87dc-29ef8e996aee.png)![friend_pottery_pattern](https://user-images.githubusercontent.com/74598365/248594628-580d9053-f894-4e98-82c2-2a8ec61ad6c4.png)![heart_pottery_pattern](https://user-images.githubusercontent.com/74598365/248594629-9c572f8f-06dc-43b4-976d-a639639839db.png)!

I hadn't seen it, it's really good!!

**Comment by lipki** [comment]
![danger_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/ce50755c-d33a-4476-bb9e-bc1496336fb5)![explorer_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/12cf4c37-f40e-4f7a-822d-a83655b4020c)![friend_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/4e8aa886-a783-453a-bf41-d546c730829a)

![arms_up_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/77fdb6bd-633c-4111-a84e-993d383df73b)![howl_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/81ba416d-5619-49cf-8aea-dba95ecb1a18)![mourner_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/7d83e1a9-6d99-4172-ad24-ac5e0b3a33c0)![plenty_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/60f94ac7-2aaa-4a39-b061-0c6b29c781e6)![sheaf_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/7778d418-3eca-4b4b-88ba-2357b018b925)![shelter_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/2ab64a7d-e837-4810-8c89-854bec7b5fba)

**Comment by lipki** [comment]
![decorated_pot_base](https://github.com/SummerFields/SummerFields/assets/401965/e151cb62-8738-4a6b-8ede-5730544f80e1)

**Comment by lipki** [comment]
![suspicious_gravel_0](https://github.com/SummerFields/SummerFields/assets/401965/86be0217-1447-4c3b-94fa-08d8d2299980)![suspicious_gravel_1](https://github.com/SummerFields/SummerFields/assets/401965/5d262be2-cc86-4402-9c13-c17677b11de9)![suspicious_gravel_2](https://github.com/SummerFields/SummerFields/assets/401965/8e3f8271-9dc3-4d18-b9d6-43480075b08b)![suspicious_gravel_3](https://github.com/SummerFields/SummerFields/assets/401965/6fdc5073-08e4-489f-9807-ddf38be32be8)

![suspicious_sand_0](https://github.com/SummerFields/SummerFields/assets/401965/286d4f0d-249a-4944-87aa-6d04bc8e2774)![suspicious_sand_1](https://github.com/SummerFields/SummerFields/assets/401965/01d48f8d-a227-437f-a0ce-06555b54d955)![suspicious_sand_2](https://github.com/SummerFields/SummerFields/assets/401965/0d4e4226-3af7-4c52-be40-a4e4d2ec3acf)![suspicious_sand_3](https://github.com/SummerFields/SummerFields/assets/401965/19e32957-999f-44b6-a3c2-fe9e54f4232d)


![Capture d’écran du 2023-09-15 12-49-54](https://github.com/SummerFields/SummerFields/assets/401965/17090f18-6fdb-44e1-b1ae-bcb92110f39c)
![Capture d’écran du 2023-09-15 12-50-01](https://github.com/SummerFields/SummerFields/assets/401965/6258bc59-d9b6-4567-bfca-134c3e40321e)

![Capture d’écran du 2023-09-15 14-38-55](https://github.com/SummerFields/SummerFields/assets/401965/edcc45ad-9d63-4178-812b-43c027a2d46e)
![Capture d’écran du 2023-09-15 14-38-49](https://github.com/SummerFields/SummerFields/assets/401965/4c7bf0ee-e3e3-459b-a9d9-8931bcce51d1)

**Comment by ORN-Fox** [comment]
> ![decorated_pot_base](https://user-images.githubusercontent.com/401965/267683137-e151cb62-8738-4a6b-8ede-5730544f80e1.png)

Decorated pot is fixed in 1.20.1, great !

**Comment by lipki** [comment]
![angler_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/da023567-651c-4a9a-8a78-195dbd81f268)![archer_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/1de8f520-d795-41ea-9b80-c40769f25705)![arms_up_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/3470959d-e038-4561-8e8e-03aab36aec0c)![blade_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/37b2cf77-4ce3-4682-ab3d-4e517ee9f4be)![brewer_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/0cd4a1ff-818c-4c44-a992-1866be4f2fd1)![burn_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/94ca27da-55c8-41a4-8b5b-1251ecacbc52)![danger_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/a29d82ed-f901-41ec-abc5-a21bf4ca0ea3)![explorer_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/ac4ae1de-477f-4932-9871-d3f999c01513)![friend_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/c88fa595-f8ef-4051-acd1-f6696ad76d9c)![heartbreak_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/b5bf26c8-ca1a-4554-a6fc-e42cec5c0baa)![heart_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/6a667603-afff-4d89-b44b-7155327d69c1)![howl_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/476f096b-4bf3-4a2b-ad88-f93471d0f2b9)![miner_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/d89d8fab-30e0-4c1b-b1cb-b2c59005b64f)![mourner_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/b0a79f58-ccfb-41bd-8ede-f423c08445d9)![plenty_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/33686bcb-b70a-4e54-9262-cd2a2fde995b)![prize_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/e1a63a9e-1671-47ce-8817-2eeebae1ce83)![sheaf_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/7f55bd4b-7ac7-4c8a-9859-26793cd9984b)![shelter_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/29691a25-3258-4965-9392-8b12883be1c6)![skull_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/36bf3d21-0f52-4aeb-b2c7-6540d1320ebe)![snort_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/d4a04bb9-473d-4000-85b5-3aa372fd0b8f)

![angler_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/86a5be6c-13d7-48a9-a727-2142150643e5)![archer_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/3d169cbb-1e25-47af-be08-0e824a13611d)![arms_up_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/c7cf6db0-6916-4264-9cfd-66f3a881cd7e)![blade_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/82b44335-7057-4b3f-a0d8-8aa8fb5f0ef6)![brewer_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/78c97a1b-1d78-41a1-ae9b-15aec3287a8f)![burn_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/f053b390-f2ba-462e-b616-82cda7686d02)![danger_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/f7212992-dbb4-4aab-a078-05562cfbe848)![explorer_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/2332e0d0-c73b-44bd-a12f-7c08ebf3efde)![friend_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/9c674f41-a3ba-4e35-8e6d-f66df6f96b7c)![heartbreak_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/fd963203-ad8b-478c-a8a4-2d2cf3810fd3)![heart_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/9ea5d2e4-6e53-43de-b1b3-63edc3adced2)![howl_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/8b9c0fa9-b9ee-4535-a44e-ffdc9812bf9e)![miner_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/96d4e4cc-8114-446f-a4c6-cf35134402e2)![mourner_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/2d9352b1-a466-47f4-abba-79a5b9ea910a)![plenty_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/b397dbff-369a-4eab-951d-908e56afca1c)![prize_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/599deee2-f9a3-478b-a19b-87a6e4018a39)![sheaf_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/c0d96fc0-f273-4c14-baab-635732b26844)![shelter_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/68d44ff8-7654-4162-9e91-40e18737b764)![skull_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/afc37825-9e69-4fd7-9502-52c44150e371)![snort_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/7b59c96a-9c3f-44ce-9f4b-cd5394981312)
