### ISSUE TITLE
[1.20] Cherry wood

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#813]
![cherry_door_top](https://user-images.githubusercontent.com/401965/219157126-b2d7d142-e9ed-4538-a31a-36497e10b59c.png)![cherry_log](https://user-images.githubusercontent.com/401965/219157132-68dd7671-13c8-46a6-a81f-f8336f5fc8e4.png)![cherry_log_top](https://user-images.githubusercontent.com/401965/219157138-21050d51-511b-433b-9e58-febf908093f6.png)![cherry_planks](https://user-images.githubusercontent.com/401965/219157143-acacd605-fba0-4a9b-a2e9-6a0b1b8205d9.png)![cherry_trapdoor](https://user-images.githubusercontent.com/401965/219157148-c138b059-0795-4334-af07-3579f263529e.png)![stripped_cherry_log](https://user-images.githubusercontent.com/401965/219157157-0b5a0096-3858-455b-81a7-10768f290ed9.png)![stripped_cherry_log_top](https://user-images.githubusercontent.com/401965/219157167-7c16b74f-6c7b-4d7b-8b28-0a6c25a06aa8.png)
![cherry_door_bottom](https://user-images.githubusercontent.com/401965/219157112-abf4b8b5-58c5-4f81-bcb9-a72eecea1784.png)

![cherry](https://user-images.githubusercontent.com/401965/219158756-67a7c007-2a73-4044-a5e1-b585ac5d645a.png)![cherry](https://user-images.githubusercontent.com/401965/219158853-9c99318b-7795-46e0-9056-3ecddab65da3.png)

![cherry](https://user-images.githubusercontent.com/401965/219159917-272ea6d0-6daa-4119-986e-b38e335fa6e2.png)![cherry](https://user-images.githubusercontent.com/401965/219159951-bf02c3ab-c380-48a5-b756-6384be888c26.png)![cherry](https://user-images.githubusercontent.com/401965/219161156-a95a956d-a30d-439d-a09a-5c2cedc59473.png)

![cherry_boat](https://user-images.githubusercontent.com/401965/219161958-41806ac0-ea16-4b99-82ac-30579a783bb5.png)![cherry_chest_boat](https://user-images.githubusercontent.com/401965/219161970-3240d98a-b2ee-46de-a5d4-847dfd93df52.png)![cherry_door](https://user-images.githubusercontent.com/401965/219161978-35ab97b1-e44b-4208-a14d-1caf938089e3.png)![cherry_hanging_sign](https://user-images.githubusercontent.com/401965/219161984-14e6cc44-5255-4101-8b89-4aade18eb8af.png)![cherry_sign](https://user-images.githubusercontent.com/401965/219161993-21ed3116-8674-49a1-b24c-b089303bef2a.png)

particle :

![cherry_0](https://user-images.githubusercontent.com/401965/227575631-09244c52-2ad2-42b1-a3fd-c822d1b0a1c7.png) ![cherry_1](https://user-images.githubusercontent.com/401965/227575637-2ca8a8a9-4b57-4ee7-b912-8d724ece05e0.png) ![cherry_2](https://user-images.githubusercontent.com/401965/227575639-40375a83-b93b-46fd-a1f7-136f240f428f.png) ![cherry_3](https://user-images.githubusercontent.com/401965/227575644-5babd3f2-df96-4228-84e2-d8e15f1f5c3b.png) ![cherry_4](https://user-images.githubusercontent.com/401965/227575645-76b24fcd-3958-40bc-a50d-014b9422ee81.png) ![cherry_5](https://user-images.githubusercontent.com/401965/227575650-ec80f446-d3f0-43a5-88df-94401564efc6.png) ![cherry_6](https://user-images.githubusercontent.com/401965/227575652-ab320ec3-8985-465e-bf90-f3fd489be76f.png) ![cherry_7](https://user-images.githubusercontent.com/401965/227575657-067f50d7-4587-4095-a1b9-5ef279884de9.png) ![cherry_8](https://user-images.githubusercontent.com/401965/227575662-681d454c-38c8-42bc-a344-c96f7eac5c71.png) ![cherry_9](https://user-images.githubusercontent.com/401965/227575666-39b152a4-50e2-497e-983a-c88d12b7830e.png)

**Comment by lipki** [comment]
![cherry_log](https://user-images.githubusercontent.com/401965/219448374-baeed93d-9051-4209-8b1c-8c97e7c8d30a.png)![cherry_log_top](https://user-images.githubusercontent.com/401965/219448377-52a6327d-1cef-4d7c-9f07-01f9ef649f0b.png) I'm too proud.
![Capture d’écran du 2023-02-16 18-53-57](https://user-images.githubusercontent.com/401965/219448271-012d287b-b259-463d-87f9-97afadb61ac7.png)

**Comment by lipki** [comment]
![cherry_door_top](https://user-images.githubusercontent.com/401965/219519196-cbf8fe5f-af47-4a5d-a1c4-edf86c22e418.png)![cherry_log](https://user-images.githubusercontent.com/401965/219519197-8da844f5-299c-40af-97bc-b3b64e9fe544.png)![cherry_log_top](https://user-images.githubusercontent.com/401965/219519199-2a5336d8-f56c-472f-8dec-2b494a28a782.png)![cherry_planks](https://user-images.githubusercontent.com/401965/219519201-ab1042b6-9779-42e4-9600-531311aaa1c4.png)![cherry_trapdoor](https://user-images.githubusercontent.com/401965/219519202-613abe4f-4da5-4838-bd76-90a3cecd960b.png)![stripped_cherry_log](https://user-images.githubusercontent.com/401965/219519323-85a0ad53-790d-485b-aadb-bffe98b475d0.png)![stripped_cherry_log_top](https://user-images.githubusercontent.com/401965/219519324-5b55db74-a310-4d32-b4ac-7c7233fa1ba2.png)
![cherry_door_bottom](https://user-images.githubusercontent.com/401965/219519187-daedc290-baee-49c2-83ca-993f3b1ea032.png)
![Capture d’écran du 2023-02-17 01-30-33](https://user-images.githubusercontent.com/401965/219519056-d1032143-4ccc-45d5-9e8b-18c569af8c18.png)
![cherry](https://user-images.githubusercontent.com/401965/219519427-420aea4c-4af9-4aad-ac0d-d942b509fcd9.png)![cherry](https://user-images.githubusercontent.com/401965/219519450-859261b7-4b72-4e76-8341-0430cfaf23cc.png)
![cherry](https://user-images.githubusercontent.com/401965/219519538-d432a589-ceeb-4888-8016-c34ca3deaa25.png)![cherry](https://user-images.githubusercontent.com/401965/219519555-682741d2-5eac-40fd-96bc-94546248d279.png)![cherry](https://user-images.githubusercontent.com/401965/219519801-2acca228-1afe-4f8b-9494-de7ace1f422c.png)
![cherry_boat](https://user-images.githubusercontent.com/401965/219520645-4c47e06e-7764-4cbd-89f5-b038b9af7815.png)![cherry_chest_boat](https://user-images.githubusercontent.com/401965/219520646-5c5b1bbb-2010-4d19-888c-429c2fc502b4.png)![cherry_door](https://user-images.githubusercontent.com/401965/219520650-b078a887-0c5a-47c3-883b-dd248efe3414.png)![cherry_hanging_sign](https://user-images.githubusercontent.com/401965/219520652-81e36312-228e-4edf-8b76-752f38116380.png)![cherry_sign](https://user-images.githubusercontent.com/401965/219520656-4ddd050c-45ca-4738-ab47-ea4080fcdb33.png)

**Comment by Physignatily** [comment]
don't know if it's just me, but I had some black pixels in the door. 
![cherry_door](https://user-images.githubusercontent.com/74598365/219905683-3953eb0e-8095-417d-af1e-2a4a1f440c1d.png)
(i cleaned them up)

**Comment by lipki** [comment]
![cherry_0](https://user-images.githubusercontent.com/401965/227624867-22691332-f09b-4089-aefa-d0a61748fa7e.png) ![cherry_1](https://user-images.githubusercontent.com/401965/227624872-3675c1e3-da61-42a0-98ad-bae7c2323429.png) ![cherry_2](https://user-images.githubusercontent.com/401965/227624873-6d0e3105-1ae1-4355-97a2-45a1cd0ebadb.png) ![cherry_3](https://user-images.githubusercontent.com/401965/227624876-7e79b8ca-6ecd-4211-9256-22323970b2c4.png) ![cherry_4](https://user-images.githubusercontent.com/401965/227624879-8b77959d-a9d8-4d1e-9e85-ab17339a689e.png) ![cherry_5](https://user-images.githubusercontent.com/401965/227624881-fe599a03-1338-4b25-a360-91ea89108625.png) ![cherry_6](https://user-images.githubusercontent.com/401965/227624882-9f66baf5-100b-451a-8d08-04409a025a79.png) ![cherry_7](https://user-images.githubusercontent.com/401965/227624884-1c1eb42b-0b45-40ff-8a85-0e54ad179b64.png) ![cherry_8](https://user-images.githubusercontent.com/401965/227624886-201d878a-a85a-4c14-920c-13f720654571.png) ![cherry_9](https://user-images.githubusercontent.com/401965/227624887-51faee61-b6ae-4ca2-9215-21671360e107.png) ![cherry_10](https://user-images.githubusercontent.com/401965/227624890-ce7aa9b8-d6f5-4e66-80b4-970a18084635.png) ![cherry_11](https://user-images.githubusercontent.com/401965/227624891-7c9a1b32-162b-4086-9377-8b2cbc51c436.png)

**Comment by lipki** [comment]
![pink_petals](https://user-images.githubusercontent.com/401965/227629559-a33f80b1-611e-4cbc-b0bd-5b4467217cc9.png)
![cherry_leaves](https://user-images.githubusercontent.com/401965/227629608-f55210d5-f6a9-48ca-b63b-49f8b0ab1948.png)
![cherry_leaves](https://user-images.githubusercontent.com/401965/227630453-d72ea8fc-0a12-4f17-a9e9-5b2ade3b8d7c.png)
