### ISSUE TITLE
font update

### ISSUE THREAD

**Issue by Physignatily** [SummerFields/SummerFields#816]
![ascii](https://user-images.githubusercontent.com/74598365/221969357-c0d60892-96e9-4817-b877-2e094c99c7aa.png)
![2023-02-28_21 23 29](https://user-images.githubusercontent.com/74598365/221969978-df5a566d-e97a-4533-8b6a-854e3e76eeeb.png)
That'd be my proposal.
Feel free to critisize. :)

**Comment by Physignatily** [comment]
![accented](https://github.com/SummerFields/SummerFields/assets/74598365/28116ac3-28fe-46aa-88f8-078ab5d493c4)
![2023-05-18_00 10 28](https://github.com/SummerFields/SummerFields/assets/74598365/4f37db18-5d56-4262-8203-866394ecccc7)
  The accented.png actually has alot more space for different letters (but I never used any of them, so I don't know how they should look like)

**Comment by lipki** [comment]
Is this just your work, or should we credit someone else ?
