### ISSUE TITLE
[1.20] Pitcher

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#819]
![pitcher_crop_side](https://user-images.githubusercontent.com/401965/227565107-be2190b5-83b1-4318-886d-eefa11992a3f.png) ![pitcher_crop_top](https://user-images.githubusercontent.com/401965/227565113-d3f37dc6-0e8c-4a95-8885-f766d3d0bae1.png) ![pitcher_crop_top_stage_3](https://user-images.githubusercontent.com/401965/227565134-d99f4a74-0bb7-492e-a2f2-08249ed8450c.png) ![pitcher_crop_top_stage_4](https://user-images.githubusercontent.com/401965/227565147-5fa9c66f-32bf-4b64-8f45-d92241f2811b.png) ![pitcher_plant](https://user-images.githubusercontent.com/401965/227565164-873ee40c-3a7e-4338-99fb-909b6418ede5.png) ![pitcher_pod](https://user-images.githubusercontent.com/401965/227565188-01dfdc6e-0ffd-450e-bc7a-8d4d92d4ba05.png)
![pitcher_crop_bottom](https://user-images.githubusercontent.com/401965/227564975-9529dae1-9c32-4ed8-a8e7-4ed4cedb0644.png) ![pitcher_crop_bottom_stage_1](https://user-images.githubusercontent.com/401965/227565004-d97a28b7-dfe6-4cdf-8193-1ecef0a1f372.png) ![pitcher_crop_bottom_stage_2](https://user-images.githubusercontent.com/401965/227565029-15e926a0-eeb1-465b-b98a-9990f01473e3.png) ![pitcher_crop_bottom_stage_3](https://user-images.githubusercontent.com/401965/227565053-9f9e68e9-3101-4dc7-b1ec-5ad3b2c80f25.png) ![pitcher_crop_bottom_stage_4](https://user-images.githubusercontent.com/401965/227565073-32141125-3374-4832-a305-872c284dbabc.png)

**Comment by ORN-Fox** [comment]
Textures are missing for this plant :)

**Comment by lipki** [comment]
I know I know :/

**Comment by Physignatily** [comment]
![pitcher_pod](https://github.com/SummerFields/SummerFields/assets/74598365/696788f4-3e07-41da-9036-783c250d61dc) 
![pitcher_crop_side](https://github.com/SummerFields/SummerFields/assets/74598365/3057fd8a-89be-46e9-a3f7-1a52c05ed140)![pitcher_crop_bottom](https://github.com/SummerFields/SummerFields/assets/74598365/dc0d6410-dd60-486c-8eb7-8c0e8d541670)![pitcher_crop_top](https://github.com/SummerFields/SummerFields/assets/74598365/fdfa0822-12d9-4ec7-a1fe-07652d030ede)
![pitcher_crop_bottom_stage_1](https://github.com/SummerFields/SummerFields/assets/74598365/b7be1d8b-9458-49b0-8329-d064a3b86d01)![pitcher_crop_bottom_stage_2](https://github.com/SummerFields/SummerFields/assets/74598365/d44a8d83-9316-41ae-ab51-8483077bcff1)![pitcher_crop_bottom_stage_3](https://github.com/SummerFields/SummerFields/assets/74598365/e6469a83-715e-4233-81de-6a17e4d0bf25)![pitcher_crop_bottom_stage_4](https://github.com/SummerFields/SummerFields/assets/74598365/65de7734-fa52-449e-910e-9d6ab3d67ff2)![pitcher_crop_top_stage_3](https://github.com/SummerFields/SummerFields/assets/74598365/5d447e15-c6f1-4048-830d-f0c3c5e03411)![pitcher_crop_top_stage_4](https://github.com/SummerFields/SummerFields/assets/74598365/f7f357b9-a681-42d5-ad27-d53651d9bd9f)

![grafik](https://github.com/SummerFields/SummerFields/assets/74598365/a6ef194f-7869-4d46-bccd-c9a4ae27e98c)

According to Mojang the pitcher plant is a fictional piece of foliage, but I tried to kind of resemble the real pitcher plant in my design... or something like that. 

To the pitcher pod... I don't really like this texture myself. :P

**Comment by ORN-Fox** [comment]
Honestly, it's pretty close to the real plant and it looks really good in game.
