### ISSUE TITLE
[1.20] Sniffer egg

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#820]
![sniffer_egg](https://user-images.githubusercontent.com/401965/227565899-e9b1d071-8a6c-4ffe-a876-452f7c5a0ee7.png)
![sniffer_egg_not_cracked](https://user-images.githubusercontent.com/401965/227565913-779bdc2a-69d5-4a2d-a80a-800a7fc49a70.png) ![sniffer_egg_slightly_cracked](https://user-images.githubusercontent.com/401965/227565920-69d2fb7d-419b-41ce-b467-9c5752828afe.png) ![sniffer_egg_very_cracked](https://user-images.githubusercontent.com/401965/227565930-ff018aa7-3aa1-470d-a877-54395757b039.png)

**Comment by lipki** [comment]
![sniffer_egg](https://github.com/SummerFields/SummerFields/assets/401965/b2e949dd-4828-4fb7-bb16-db2af0e6986e)
![sniffer_egg_not_cracked_bottom](https://github.com/SummerFields/SummerFields/assets/401965/cf1f5a1f-cc07-45c8-a96f-4cabeb0c8508)![sniffer_egg_not_cracked_east](https://github.com/SummerFields/SummerFields/assets/401965/d2efd880-caac-45c7-98c2-d862397c1d8f)![sniffer_egg_not_cracked_north](https://github.com/SummerFields/SummerFields/assets/401965/3c8298cc-e144-495f-8c45-7ebfda5ec56b)![sniffer_egg_not_cracked_south](https://github.com/SummerFields/SummerFields/assets/401965/f78838cd-6de9-46a2-8157-0bd9980f878d)![sniffer_egg_not_cracked_top](https://github.com/SummerFields/SummerFields/assets/401965/415a88ec-3985-4dc8-977e-c4bc5cd272dc)![sniffer_egg_not_cracked_west](https://github.com/SummerFields/SummerFields/assets/401965/db9bbff7-75ac-4a56-9ddb-a0ce650d17ff)
![sniffer_egg_slightly_bottom](https://github.com/SummerFields/SummerFields/assets/401965/87bf7f3f-7aa6-410c-a756-77dd670c385b)![sniffer_egg_slightly_cracked_east](https://github.com/SummerFields/SummerFields/assets/401965/7e6167d2-0e59-40eb-a9e7-8e84697a009a)![sniffer_egg_slightly_cracked_north](https://github.com/SummerFields/SummerFields/assets/401965/54efc892-3571-4c40-85c5-e6f6bb22ed28)![sniffer_egg_slightly_cracked_south](https://github.com/SummerFields/SummerFields/assets/401965/e32416a6-ddde-48de-8b3d-8b70fdef619b)![sniffer_egg_slightly_cracked_top](https://github.com/SummerFields/SummerFields/assets/401965/6668d07d-6e1d-4a60-830e-977658ef9440)![sniffer_egg_slightly_cracked_west](https://github.com/SummerFields/SummerFields/assets/401965/d9161292-f80d-4c72-bf12-c131d921bc5d)
![sniffer_egg_very_cracked_bottom](https://github.com/SummerFields/SummerFields/assets/401965/b9fa3701-0f59-49e9-a3f3-cac58a5605fa)![sniffer_egg_very_cracked_east](https://github.com/SummerFields/SummerFields/assets/401965/39460744-f1b4-4c43-baac-de16c5841e19)![sniffer_egg_very_cracked_north](https://github.com/SummerFields/SummerFields/assets/401965/4d88946f-fb38-4e35-941f-fbf6bb68c991)![sniffer_egg_very_cracked_south](https://github.com/SummerFields/SummerFields/assets/401965/e61567c6-4147-4b8b-bede-fe6432e0d8bc)![sniffer_egg_very_cracked_top](https://github.com/SummerFields/SummerFields/assets/401965/3b04bba2-f2fe-4841-a18d-c701353e5ca9)![sniffer_egg_very_cracked_west](https://github.com/SummerFields/SummerFields/assets/401965/2b7117f9-4239-4ed7-bb35-f381e2a4cf3f)

![Capture d’écran du 2023-09-18 17-00-02](https://github.com/SummerFields/SummerFields/assets/401965/bacb5802-2dc7-4bf4-862b-695b387224ee)

Well, I'm in doubt.
Already, I find that the sniffer I made is too similar to the original.
And what's more, the egg looks too much like the sniffer. :D
But I like the idea of the egg developing in successive layers.
So this is it.

**Comment by ORN-Fox** [comment]
I like him like that! Superb idea that it takes its foliage gradually!
