### ISSUE TITLE
[1.20.x] New title "minecraft"

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#821]
![realms](https://github.com/SummerFields/SummerFields/assets/401965/8a7882c3-f291-457e-bd42-8b3ef9fe3e73)
![edition](https://github.com/SummerFields/SummerFields/assets/401965/3b7beec6-b6ab-4e6c-8993-bdd4535d2d75)
![minceraft](https://github.com/SummerFields/SummerFields/assets/401965/3cd02965-e642-4bb5-b31d-cf0f7f9080b0)
![minecraft](https://github.com/SummerFields/SummerFields/assets/401965/9284bedb-94aa-4a6b-9b51-6fa16704580c)

**Comment by lipki** [comment]
We could refresh this logo, it is a bit outdated.

**Comment by lipki** [comment]
Propal !?

![new_logo_summerfields_1](https://github.com/SummerFields/SummerFields/assets/401965/7d87398c-f0ad-42cc-ab47-bd4f4b76c922)
![new_logo_summerfields_2](https://github.com/SummerFields/SummerFields/assets/401965/df178e4a-089e-4fa4-859f-35451cad1a2f)

**Comment by lipki** [comment]
![new_logo_summerfields_3](https://github.com/SummerFields/SummerFields/assets/401965/9a264a5d-9658-4244-85ec-f99e3d32d39a)

**Comment by lipki** [comment]
![Capture d’écran du 2023-06-15 20-04-42](https://github.com/SummerFields/SummerFields/assets/401965/9740cbfb-9046-49cc-9b01-29e38904ce74)
![Capture d’écran du 2023-06-15 20-05-56](https://github.com/SummerFields/SummerFields/assets/401965/80ac2340-f147-47f7-9476-dd74b356ef00)
![Capture d’écran du 2023-06-15 20-13-38](https://github.com/SummerFields/SummerFields/assets/401965/ead87026-0018-4848-9aad-d7227d54ce17)

**Comment by chengzzi89** [comment]
![20230618223056](https://github.com/SummerFields/SummerFields/assets/28303754/eebcdde3-3894-4570-84f5-24511ebe8bcc)
!!!!

**Comment by lipki** [comment]
This is due to the method used to make the borders in 3d.
It's both a choice and an "it'll be good like that!".

**Comment by lipki** [comment]
@chengzzi89 But that is a detail! What do you think of the whole.

**Comment by ORN-Fox** [comment]
@lipki A good update! It's clean ! How do you do them? I'm looking to update the Enigma pack!?
