### ISSUE TITLE
[23w43a] New Bat style

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#841]
![bat](https://github.com/SummerFields/SummerFields/assets/401965/7b5939a6-6344-40c6-929b-e3e0f6db3aaa)

**Comment by lipki** [comment]
![bat](https://github.com/SummerFields/SummerFields/assets/401965/ea310df3-bb79-4f46-bd5f-3cede50644a4)
![Capture d’écran du 2023-10-25 20-49-33](https://github.com/SummerFields/SummerFields/assets/401965/3a82b76a-9432-4550-8e72-4248f2a482a9)

**Comment by ORN-Fox** [comment]
I like this bat version a lot more!
