### ISSUE TITLE
[23w45a] Breeze

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#850]
![breeze](https://github.com/SummerFields/SummerFields/assets/401965/b47531da-6c28-411d-bbec-3d5f009fcaba)
![breeze_eyes](https://github.com/SummerFields/SummerFields/assets/401965/239404de-95b7-42d7-bdeb-c8b9bfcac93e)
![breeze_wind](https://github.com/SummerFields/SummerFields/assets/401965/df7b6c08-f289-48fb-8a90-fbe2bac9d334)
![wind_charge](https://github.com/SummerFields/SummerFields/assets/401965/bc26683f-3b7c-4a3c-8912-3e20cf6fa421)

**Comment by lipki** [comment]
ref :
![breeze](https://github.com/SummerFields/SummerFields/assets/401965/f44ea7b5-2910-44f5-809d-54ddb94b51c3)
![breeze_wind](https://github.com/SummerFields/SummerFields/assets/401965/bb32b60a-d480-46ba-a5c0-32df0b7e3109)


![Capture d’écran du 2023-11-08 23-04-09](https://github.com/SummerFields/SummerFields/assets/401965/12781449-9fe2-4b91-a6e1-73189d57527d)

**Comment by lipki** [comment]
![blaze](https://github.com/SummerFields/SummerFields/assets/401965/ba51e5df-e532-49ef-8f3e-fa511bbd4b95)

**Comment by lipki** [comment]
![breeze](https://github.com/SummerFields/SummerFields/assets/401965/68832c69-984c-4b75-82c8-a89d7208b59b)
![breeze_wind](https://github.com/SummerFields/SummerFields/assets/401965/446b2524-f5c5-4342-8f90-15306b20fd88)


![Capture d’écran du 2023-11-10 22-08-26](https://github.com/SummerFields/SummerFields/assets/401965/151c18fc-4014-47cb-922e-4f408a6ea92d)

**Comment by lipki** [comment]
![breeze](https://github.com/SummerFields/SummerFields/assets/401965/03c2dd15-650e-470a-ad9e-1670f9fe9cdb)

![Capture d’écran du 2023-11-10 22-12-06](https://github.com/SummerFields/SummerFields/assets/401965/1d6040e2-115c-4fc9-89d1-d369fbe7aa6c)

**Comment by lipki** [comment]
Gray or blue?
I like gray.

**Comment by lipki** [comment]
![Capture d’écran du 2023-11-10 22-36-55](https://github.com/SummerFields/SummerFields/assets/401965/5ec518ac-2bfb-4e3b-8d80-01ceb460b5a0)

**Comment by ORN-Fox** [comment]
The choice is difficult, maybe blue for me

**Comment by lipki** [comment]
In use, the gray is too dark.
It's hard to see him in the trials chambers.

**Comment by lipki** [comment]
Il s'est fait un regard de breeze :D (French Word-games.)

There are two versions above, with sunglasses and with eyebrow cloud.
Which one do you like?
