### ISSUE TITLE
[23w45a] Trial Spawner

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#851]
![trial_spawner_bottom](https://github.com/SummerFields/SummerFields/assets/401965/c0d7a623-f2bb-43ff-b83d-71dcea4f3b91)![trial_spawner_side_active](https://github.com/SummerFields/SummerFields/assets/401965/109e118c-1381-4cab-bc72-b5773e936cc3)![trial_spawner_side_inactive](https://github.com/SummerFields/SummerFields/assets/401965/91d7a35f-6564-4d6c-8466-514228c1d23d)![trial_spawner_top_active](https://github.com/SummerFields/SummerFields/assets/401965/44a26dee-dbe4-4a91-9572-64291fed34d0)![trial_spawner_top_ejecting_reward](https://github.com/SummerFields/SummerFields/assets/401965/6f6ce440-b13e-4000-b0cd-fcdd02fbc7f5)![trial_spawner_top_inactive](https://github.com/SummerFields/SummerFields/assets/401965/8b3b4504-df88-4ae7-8077-f6cf2170e786)

**Comment by lipki** [comment]
ref :
Actual Mob spawner : ![spawner](https://github.com/SummerFields/SummerFields/assets/401965/97448358-ea69-49a6-854b-b34c1893a337)
Old Mob Spawner : ![original mob spawner](https://github.com/SummerFields/SummerFields/assets/401965/15335e7d-9f6c-4ff3-b4fe-cc3048c4a7d1)

It is entirely possible to redo the classic mob spawner.

**Comment by lipki** [comment]
![trial_spawner_bottom](https://github.com/SummerFields/SummerFields/assets/401965/5be22aa6-1a2f-4a91-ad22-a11e86a5beaa) ![trial_spawner_side_active](https://github.com/SummerFields/SummerFields/assets/401965/a70c0518-0ba5-4381-9f52-4890a64717f6) ![trial_spawner_side_inactive](https://github.com/SummerFields/SummerFields/assets/401965/bc1e55c8-e6fa-4717-b37f-9f278237a968) ![trial_spawner_top_active](https://github.com/SummerFields/SummerFields/assets/401965/0e0d4965-e7be-4d0d-81ae-993e72b73e25) ![trial_spawner_top_ejecting_reward](https://github.com/SummerFields/SummerFields/assets/401965/f33aa534-2577-4ac7-b48e-3d93c2d39a88) ![trial_spawner_top_inactive](https://github.com/SummerFields/SummerFields/assets/401965/8d58e48e-4289-4495-8f52-c8ccb59e76f4)

![Capture d’écran du 2023-12-08 22-50-59](https://github.com/SummerFields/SummerFields/assets/401965/8b1556f3-c0fa-4b4a-b1a3-4d1bc34861e8)

**Comment by lipki** [comment]
![spawner_bottom](https://github.com/SummerFields/SummerFields/assets/401965/d9798004-95cb-46e5-8343-478faf8c3df8) ![spawner_side](https://github.com/SummerFields/SummerFields/assets/401965/e888e588-6812-40ee-b853-862ae0ff195a) ![spawner](https://github.com/SummerFields/SummerFields/assets/401965/20529dd5-e140-47a5-b9b1-34c85f2bcdd7)

![Capture d’écran du 2023-12-08 22-49-29](https://github.com/SummerFields/SummerFields/assets/401965/d6010ab3-0a83-4a75-a7bb-b45df55f4f73)

**Comment by ORN-Fox** [comment]
This new look is so cool ! I prefer it to old
