### ISSUE TITLE
[24w11a] New Banner

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#877]
![flow](https://github.com/SummerFields/SummerFields/assets/401965/7c2de680-a0e2-4ec6-a21a-e9bbad23a3ef) ![guster](https://github.com/SummerFields/SummerFields/assets/401965/e75d9d43-8501-440b-bf13-f753bd7d52be)
![flow_banner_pattern](https://github.com/SummerFields/SummerFields/assets/401965/12b569b1-3e24-40bd-8003-84f7038efda9) ![guster_banner_pattern](https://github.com/SummerFields/SummerFields/assets/401965/1190e5ca-e8a6-471b-9f4a-70ec2f0789af)

**Comment by lipki** [comment]
![flow](https://github.com/SummerFields/SummerFields/assets/401965/e3515e5a-5d74-4d8c-bc55-31c5ed91e2b8) ![guster](https://github.com/SummerFields/SummerFields/assets/401965/702dc285-21b2-47f2-bf27-efd7ba21a7e3)
![flow_banner_pattern](https://github.com/SummerFields/SummerFields/assets/401965/49794745-dd15-42e5-aa34-d9865b1bb831) ![guster_banner_pattern](https://github.com/SummerFields/SummerFields/assets/401965/761ddff8-b682-4b0d-ab91-5c8bbbf5fdfa)

**Comment by lipki** [comment]
![Capture d’écran du 2024-03-17 21-12-57](https://github.com/SummerFields/SummerFields/assets/401965/91092b6f-681a-4b10-b3bb-96f2c326213f)

**Comment by ORN-Fox** [comment]
On the left banner, I don't really like the fact that the spiral ends on the side. Can you try making it finish down more like vanilla?
Right banner is so cool !

**Comment by lipki** [comment]
I try to be original and this is how I am received ! 😡

.

.

😜

**Comment by lipki** [comment]
![flow2](https://github.com/SummerFields/SummerFields/assets/401965/dcf16a95-d639-4d15-95e8-2420123b9b98)

**Comment by Physignatily** [comment]
Maybe I'm a bit late,... but how about a fade-out at the end of the spiral?

**Comment by ORN-Fox** [comment]
Why not yes, we can try?

**Comment by lipki** [comment]
You are never late ! Besides, don't you have one or two ideas for the trims?
