### ISSUE TITLE
[24w11a] new pottery pattern

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#878]
![flow_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/f26f64e7-730e-4a68-944d-fea13fece8f8) ![guster_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/02531d9d-e87c-412d-9055-440d0b544132) ![scrape_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/d2f39b47-22aa-4853-ad9a-a3985a36d211)
![flow_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/ecccda5c-9aa8-4d1b-93be-1f6b5a6fe08f) ![guster_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/6da7dd61-b357-4f62-912d-eb816521dd14) ![scrape_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/4188316b-1205-40d3-b170-be2a363f1e6c)

**Comment by lipki** [comment]
![flow_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/63461125-e9b0-4a96-88cc-31d08f30caa3) ![guster_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/e532e0b6-f287-4393-932c-6dd3a08e6bab) ![scrape_pottery_pattern](https://github.com/SummerFields/SummerFields/assets/401965/51a91394-8446-4c70-9250-8a2924bdd596)
![flow_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/7fecbac2-c4bc-4c6b-b152-36ad03f10b8a) ![guster_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/7b861e99-9635-4b1c-90ff-6d09755cf1a2) ![scrape_pottery_sherd](https://github.com/SummerFields/SummerFields/assets/401965/ab9d5139-204c-4b32-ada8-709b465c68ca)

![Capture d’écran du 2024-03-17 22-03-09](https://github.com/SummerFields/SummerFields/assets/401965/94babd84-4803-4162-b8b3-eaa5fcd2ac95)

**Comment by Physignatily** [comment]
Why are the texures of the gust and flow sherds swapped?

**Comment by lipki** [comment]
Because I made a mistake.
