### ISSUE TITLE
[24w12a] split map decorations

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#883]
![black_banner](https://github.com/SummerFields/SummerFields/assets/401965/68844234-6c54-450b-9b30-f6efbd0cff00)![blue_banner](https://github.com/SummerFields/SummerFields/assets/401965/b14ddd33-773e-4245-95da-eccef18cba5e)![brown_banner](https://github.com/SummerFields/SummerFields/assets/401965/af64bc43-0045-47af-a10c-91ba837fea31)![cyan_banner](https://github.com/SummerFields/SummerFields/assets/401965/f892277a-a681-4e08-868b-491e1c739845)![gray_banner](https://github.com/SummerFields/SummerFields/assets/401965/a52da2e2-5803-499c-8f50-201d5884db06)![green_banner](https://github.com/SummerFields/SummerFields/assets/401965/7bb0167f-c76e-45a8-91f8-9a4857359d73)![light_blue_banner](https://github.com/SummerFields/SummerFields/assets/401965/ebe45607-7ec5-4556-a561-d9f0f3057201)![light_gray_banner](https://github.com/SummerFields/SummerFields/assets/401965/a36c7c0a-2a0a-4c41-845f-38259661e257)![lime_banner](https://github.com/SummerFields/SummerFields/assets/401965/7f27a3be-b755-482a-938a-f28ecce4d136)![magenta_banner](https://github.com/SummerFields/SummerFields/assets/401965/6133e564-b5bc-4076-b904-cac84b1912d1)![orange_banner](https://github.com/SummerFields/SummerFields/assets/401965/bba61968-2a0c-4f8c-a299-98f360d9978a)![pink_banner](https://github.com/SummerFields/SummerFields/assets/401965/31e3bc56-e990-4b2d-aaec-329fce185ead)![purple_banner](https://github.com/SummerFields/SummerFields/assets/401965/1fe65247-b0f1-4973-83df-f0a9945303bf)![red_banner](https://github.com/SummerFields/SummerFields/assets/401965/ab4b949f-9380-48b6-9951-4ac6b244369d)![white_banner](https://github.com/SummerFields/SummerFields/assets/401965/bfde0445-8a01-48c1-89eb-c9e1de9d05a4)![yellow_banner](https://github.com/SummerFields/SummerFields/assets/401965/1510bf39-4638-43ae-8141-ccbc67e20484)

![desert_village](https://github.com/SummerFields/SummerFields/assets/401965/1b8f5409-d3ce-4577-8ef6-053f0c80217c)![plains_village](https://github.com/SummerFields/SummerFields/assets/401965/9a844f35-22f9-488b-889a-72e4f77609d9)![savanna_village](https://github.com/SummerFields/SummerFields/assets/401965/cd676527-fcdd-47d9-8315-cbbc9e2e6a24)![snowy_village](https://github.com/SummerFields/SummerFields/assets/401965/5549fd65-8736-49fe-885c-22bde8e40af6)![taiga_village](https://github.com/SummerFields/SummerFields/assets/401965/ade281ea-dfad-4b80-99e1-8d34b33fd754)

![swamp_hut](https://github.com/SummerFields/SummerFields/assets/401965/9e95c573-6e39-4a61-b84c-b7a80326c540)![jungle_temple](https://github.com/SummerFields/SummerFields/assets/401965/17e4c71b-aec1-4749-9a43-2bd08e20db6e)![ocean_monument](https://github.com/SummerFields/SummerFields/assets/401965/479994d7-4061-48f2-9738-52075d30251e)![woodland_mansion](https://github.com/SummerFields/SummerFields/assets/401965/6b8683ab-a12e-4ed8-84b5-4c1ac2151cfa)![trial_chambers](https://github.com/SummerFields/SummerFields/assets/401965/76ce4648-6dd1-479f-bb74-3e3e72412f15)

![target_x](https://github.com/SummerFields/SummerFields/assets/401965/da1a9d30-df68-4c29-a662-f021452a634e)![target_point](https://github.com/SummerFields/SummerFields/assets/401965/b5135e81-259d-40e6-827e-d7ddcccfceba)![red_x](https://github.com/SummerFields/SummerFields/assets/401965/d34ef861-770e-4a12-83fd-cf62b0aef440)

![frame](https://github.com/SummerFields/SummerFields/assets/401965/82e1068b-38f0-4fd1-8e22-5331c3d89f31)![blue_marker](https://github.com/SummerFields/SummerFields/assets/401965/9e5d38f9-7a2b-4055-a87a-829a65cbe37e)![red_marker](https://github.com/SummerFields/SummerFields/assets/401965/1970bd71-038e-4628-b861-5e305b867d39)![player](https://github.com/SummerFields/SummerFields/assets/401965/5292ebb1-59db-48a7-8300-a8a80f1dcfc9)![player_off_limits](https://github.com/SummerFields/SummerFields/assets/401965/b4b99557-4bdd-4201-8a7f-8f738870610a)![player_off_map](https://github.com/SummerFields/SummerFields/assets/401965/5bdc4098-f7dd-45b0-9656-3297d1a54434)

**Comment by lipki** [comment]
ref : 
![map_icons](https://github.com/SummerFields/SummerFields/assets/401965/d1cdbfaf-aec2-4b42-82f0-eab9a35287ca)

**Comment by lipki** [comment]
![black_banner](https://github.com/SummerFields/SummerFields/assets/401965/88132c11-2e03-40a9-b1d4-dd6083cfaa50) ![blue_banner](https://github.com/SummerFields/SummerFields/assets/401965/8df30957-a8db-41a0-bd64-712021b7473b) ![brown_banner](https://github.com/SummerFields/SummerFields/assets/401965/b508cfe6-3582-4ebb-92f4-a829aa4c492e) ![cyan_banner](https://github.com/SummerFields/SummerFields/assets/401965/f651a615-57c8-4b35-ab96-8ba3b6b16402) ![gray_banner](https://github.com/SummerFields/SummerFields/assets/401965/87b1a810-b3dd-4e10-ad5a-f8103d919e60) ![green_banner](https://github.com/SummerFields/SummerFields/assets/401965/d6425fa7-c12b-4bdf-8f57-006778a4a83e) ![light_blue_banner](https://github.com/SummerFields/SummerFields/assets/401965/38c01a82-14fb-48ef-bdf9-a029cd5bf96e) ![light_gray_banner](https://github.com/SummerFields/SummerFields/assets/401965/c764aa5b-4111-4d55-bb3b-66483d24860a) ![lime_banner](https://github.com/SummerFields/SummerFields/assets/401965/8da89496-7352-44c8-9218-07a2cdbef0f8) ![magenta_banner](https://github.com/SummerFields/SummerFields/assets/401965/e603c4cf-baa5-45c0-856c-353f92958dbd) ![orange_banner](https://github.com/SummerFields/SummerFields/assets/401965/661ebeb6-b066-49e5-be2b-d92fde57ffac) ![pink_banner](https://github.com/SummerFields/SummerFields/assets/401965/73da091d-314a-4fae-b1d5-7213148c3607) ![purple_banner](https://github.com/SummerFields/SummerFields/assets/401965/b301356f-f6a8-47c8-ab28-93cbc1340ded) ![red_banner](https://github.com/SummerFields/SummerFields/assets/401965/03990db6-2313-4358-807f-c109ed8b53d9) ![white_banner](https://github.com/SummerFields/SummerFields/assets/401965/6df55122-db1b-4469-ace2-cfc237278ee6) ![yellow_banner](https://github.com/SummerFields/SummerFields/assets/401965/a0d2fb85-e245-4896-8f5d-31fed8f853ef)


![desert_village](https://github.com/SummerFields/SummerFields/assets/401965/33ade738-276f-4d3c-8825-60472cbded6d) ![plains_village](https://github.com/SummerFields/SummerFields/assets/401965/6cafdb2a-2545-4156-8a74-d6105d9933cd) ![savanna_village](https://github.com/SummerFields/SummerFields/assets/401965/9b40fc08-4b30-4f83-ae89-c57b32ae6f70) ![snowy_village](https://github.com/SummerFields/SummerFields/assets/401965/1929c5d3-c925-416b-961c-892bd410fbf5) ![taiga_village](https://github.com/SummerFields/SummerFields/assets/401965/182d80c6-0a4e-4b36-9a39-cd81c0c311bc)

![swamp_hut](https://github.com/SummerFields/SummerFields/assets/401965/79a93502-a18b-43b3-9ad7-b2be6ea65385) ![jungle_temple](https://github.com/SummerFields/SummerFields/assets/401965/581a77ce-51bd-4224-b60e-dbb603223633) ![ocean_monument](https://github.com/SummerFields/SummerFields/assets/401965/9365f276-e228-433a-9d6c-568a6a81737d) ![woodland_mansion](https://github.com/SummerFields/SummerFields/assets/401965/4dac9ffe-cb9b-494b-bc16-d58284386778) ![trial_chambers](https://github.com/SummerFields/SummerFields/assets/401965/d6404ece-5967-4832-bbe8-2b1222104abd)

![map_icons6](https://github.com/SummerFields/SummerFields/assets/401965/beb2c8c6-6e00-41c3-a12a-c3e348b7c685) ![red_x](https://github.com/SummerFields/SummerFields/assets/401965/fc102d32-1153-4fc1-9637-1eb80f77d420) ![target_x](https://github.com/SummerFields/SummerFields/assets/401965/76399389-215f-42ec-aa01-2205fd0baba6)

![blue_marker](https://github.com/SummerFields/SummerFields/assets/401965/d30da0d4-3665-4027-8101-9dcc95c82798) ![frame](https://github.com/SummerFields/SummerFields/assets/401965/eaff6fb0-359d-4fed-9b05-d9f63012357d) ![red_marker](https://github.com/SummerFields/SummerFields/assets/401965/bc7d37f9-7382-4d6e-a07c-33266a491b41) ![player](https://github.com/SummerFields/SummerFields/assets/401965/a0db78ba-7b8f-4d10-baf4-939c180bf8b3) ![player_off_limits](https://github.com/SummerFields/SummerFields/assets/401965/c495813d-597f-4a3a-93e2-f4bab610bcab) ![player_off_map](https://github.com/SummerFields/SummerFields/assets/401965/d0c155cd-f43a-4273-a4b6-d388ce86e4f9)



![Capture d’écran du 2024-03-26 22-46-49](https://github.com/SummerFields/SummerFields/assets/401965/2586977d-467d-43c8-98db-c6ba03a598c6)

**Comment by lipki** [comment]
![trial_chambers](https://github.com/SummerFields/SummerFields/assets/401965/9d37e8a7-e683-4cd1-bc51-b1a2ae8a64ac)

**Comment by lipki** [comment]
![Capture d’écran du 2024-03-27 00-29-42](https://github.com/SummerFields/SummerFields/assets/401965/81dc2b18-6630-4252-93f1-9c7692ad3c55)

**Comment by ORN-Fox** [comment]
A great addition for maps !
