### ISSUE TITLE
[Model bug] Texture bug in the hat of the savanna villagers

### ISSUE THREAD

**Issue by ORN-Fox** [SummerFields/SummerFields#913]
Hi, 

during a build on Buildmyworld we used savanna villagers (cleric example in the image below). We see that textures are missing for the villager's hat or that the 3D model is poorly finished.

![2024-04-28_11 56 27](https://github.com/SummerFields/SummerFields/assets/49326517/2c4658fd-95b8-4b28-a4ac-289fc52c045d)

**Comment by lipki** [comment]
It's intentional, but...

I wanted a pointed hat, and I didn't find better solutions to achieve this effect.
Since nobody has complained so far, I thought everyone had understood the intention :)

There's a way to revisit it to do better.
Maybe.

**Comment by lipki** [comment]
Thanks to your team for taking the time to look for errors in the pack. Even though I say it's intentional, it's not necessarily right, and maybe we can do better, I'm open to change.

**Comment by lipki** [comment]
![Capture d’écran du 2024-06-02 23-22-04](https://github.com/SummerFields/SummerFields/assets/401965/2ba582a1-ba33-48c7-bfbe-e1f1d1fa7805)

**Comment by ORN-Fox** [comment]
It's much better ! No texture flies without logic.
