### ISSUE TITLE
A SummerFields datapack ?

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#918]
Do you think it is useful, interesting, necessary to create a Summerfields datapack?

**Comment by ORN-Fox** [comment]
To do what ? Do you already have an idea in mind?

**Comment by lipki** [comment]
Right away, I'm thinking of adding a few paintings.
But that is not enough.

**Comment by ORN-Fox** [comment]
If you have extra tables, yes, make a datapack, please! :smiley:
