### ISSUE TITLE
Compatibility with Painting selector

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#925]
https://www.planetminecraft.com/data-pack/painting-selector/

![alban](https://github.com/SummerFields/SummerFields/assets/401965/4b3ff8fb-400b-4d1c-8801-dc1b724507f4)![aztec](https://github.com/SummerFields/SummerFields/assets/401965/2fa4d74f-7f33-437a-b9b0-e791c1849531)![aztec2](https://github.com/SummerFields/SummerFields/assets/401965/c50ceb64-b65c-49f8-8abd-4738f7bdb5c3)![backyard](https://github.com/SummerFields/SummerFields/assets/401965/c559f2df-d1b2-4106-9f9e-7aa519952f32)![baroque](https://github.com/SummerFields/SummerFields/assets/401965/19779d71-5a95-488d-bdf8-3ed0bfbc94a8)![bomb](https://github.com/SummerFields/SummerFields/assets/401965/5b566cb8-ade7-4afc-b2e0-b909702a7b9b)![bouquet](https://github.com/SummerFields/SummerFields/assets/401965/b816a826-c975-4afa-9ae5-2555c51f71b3)![burning_skull](https://github.com/SummerFields/SummerFields/assets/401965/68488c30-04c7-492a-9527-d39540857003)![bust](https://github.com/SummerFields/SummerFields/assets/401965/dfbba41d-3074-41c2-8263-6b9f2d6a02ab)![cavebird](https://github.com/SummerFields/SummerFields/assets/401965/077d07d3-d0cb-4eb3-974f-011807fa5312)![changing](https://github.com/SummerFields/SummerFields/assets/401965/54e0d819-2c9e-4978-8c3d-55584bdf35bd)![cotan](https://github.com/SummerFields/SummerFields/assets/401965/66ab652b-d44b-438d-8971-29d43c797b9c)![courbet](https://github.com/SummerFields/SummerFields/assets/401965/5c1cb385-8c59-4b61-b8bc-cfa065b4a0c3)![creebet](https://github.com/SummerFields/SummerFields/assets/401965/58367610-bfcf-4924-9dad-146519ff3fb5)![donkey_kong](https://github.com/SummerFields/SummerFields/assets/401965/a49477dc-d67d-4d2a-93b7-2b2e4ffb21df)![earth](https://github.com/SummerFields/SummerFields/assets/401965/f81bcb16-bddd-4fbf-b998-0e281948feed)![endboss](https://github.com/SummerFields/SummerFields/assets/401965/66666d1f-1989-4cfc-b78d-dad97f0def13)![fern](https://github.com/SummerFields/SummerFields/assets/401965/e3eb379b-c9f2-44e9-9f6e-9fdff3c5e826)![fighters](https://github.com/SummerFields/SummerFields/assets/401965/5da21a48-ec08-4e88-98e2-9698a01aaf6e)![finding](https://github.com/SummerFields/SummerFields/assets/401965/95dc4801-6498-48f2-93a7-45b8b81d22fd)![fire](https://github.com/SummerFields/SummerFields/assets/401965/0e4ff685-27b7-4de4-88a4-a8bebaa11026)![graham](https://github.com/SummerFields/SummerFields/assets/401965/6abb6043-3584-4ad9-afc5-4ffbf815b85e)![humble](https://github.com/SummerFields/SummerFields/assets/401965/e5529b01-b38d-4c7a-baa3-afd330c91229)![kebab](https://github.com/SummerFields/SummerFields/assets/401965/75c74e17-817d-4cb4-b0e8-444015adce18)![lowmist](https://github.com/SummerFields/SummerFields/assets/401965/1a267d21-75e4-45a3-9d1a-d36132cd8547)![match](https://github.com/SummerFields/SummerFields/assets/401965/005c1c0e-f671-4792-b075-0cebb7c0f0ef)![meditative](https://github.com/SummerFields/SummerFields/assets/401965/3b90255f-60a7-4fba-8955-b1a97e729614)![orb](https://github.com/SummerFields/SummerFields/assets/401965/b0fd8f35-a579-428f-977d-f3974429d50c)![owlemons](https://github.com/SummerFields/SummerFields/assets/401965/486a8e95-640d-47b6-bb67-38b6b18f6e2e)![passage](https://github.com/SummerFields/SummerFields/assets/401965/e01ac67d-4931-4323-b434-de8ca7da1b3c)![pigscene](https://github.com/SummerFields/SummerFields/assets/401965/daca0b63-7a11-4642-bec4-3e684981d767)![plant](https://github.com/SummerFields/SummerFields/assets/401965/896f6d44-1370-40bb-9848-094d9aa90547)![pointer](https://github.com/SummerFields/SummerFields/assets/401965/1ac74ba5-9bde-48c2-a9e3-baa13db10b50)![pond](https://github.com/SummerFields/SummerFields/assets/401965/3b7ed196-ad14-4d47-a4ee-304a6fe59d62)![pool](https://github.com/SummerFields/SummerFields/assets/401965/d6d0e970-3f07-4273-b9f5-d2d63f49f106)![prairie_ride](https://github.com/SummerFields/SummerFields/assets/401965/6c7b01c9-61fc-44f1-9b29-17b1badc0fa0)![sea](https://github.com/SummerFields/SummerFields/assets/401965/69a600f0-3649-4b6f-8b57-0a3d3533e4cb)![skeleton](https://github.com/SummerFields/SummerFields/assets/401965/a8dd698a-86e5-4893-8eda-10e1251611f3)![skull_and_roses](https://github.com/SummerFields/SummerFields/assets/401965/cb9b8809-4b70-4952-abeb-df27511520b6)![stage](https://github.com/SummerFields/SummerFields/assets/401965/09d7a572-0a16-4ebb-94e7-acfc21b16579)![sunflowers](https://github.com/SummerFields/SummerFields/assets/401965/b8e9592b-7c03-4eb4-8121-011405138230)![sunset](https://github.com/SummerFields/SummerFields/assets/401965/4e2eff88-b48d-4a1e-9ebc-6323a547b098)![tides](https://github.com/SummerFields/SummerFields/assets/401965/47ee767c-27fb-4c23-a366-85792bc72905)![unpacked](https://github.com/SummerFields/SummerFields/assets/401965/91df1e18-254e-46fb-b737-b8586d75e8be)![void](https://github.com/SummerFields/SummerFields/assets/401965/0a145df8-a764-484a-94e3-690238e86f3f)![wanderer](https://github.com/SummerFields/SummerFields/assets/401965/05cdb5ee-b287-414c-adf9-f292b4ac2e43)![wasteland](https://github.com/SummerFields/SummerFields/assets/401965/df4638bb-89b1-4af7-974d-cfff8ce570fc)![water](https://github.com/SummerFields/SummerFields/assets/401965/9bdbd442-c56d-4fd4-9971-b2bd93a71342)![wind](https://github.com/SummerFields/SummerFields/assets/401965/43198ec6-6fbf-41d5-b23c-40fce3262981)![wither](https://github.com/SummerFields/SummerFields/assets/401965/71a6668d-46e8-4785-879a-3222aafb51f3)

![Capture d’écran du 2024-06-04 03-55-46](https://github.com/SummerFields/SummerFields/assets/401965/cb6ffae2-2973-4646-ae65-93f27ed7ecd0)

**Comment by ORN-Fox** [comment]
It's incredible !

**Comment by lipki** [comment]
So I made a version with the custom names.
You rename the painting to give it the right texture. That's it.

![Image](https://github.com/user-attachments/assets/2a3df216-a4f8-49be-bf7e-a8b728ba285e)
![Image](https://github.com/user-attachments/assets/50a7a5c0-1db6-44fa-831c-9d4dc2173abd)

And here is the list of names that works.

alban
aztec
aztec2
backyard
baroque
bomb
bouquet
burning_skull
bust
cavebird
changing
cotan
courbet
creebet
donkey_kong
earth
endboss
fern
fighters
finding
fire
graham
humble
kebab
lowmist
match
meditative
orb
owlemons
passage
pigscene
plant
pointer
pond
pool
prairie_ride
sea
skeleton
skull_and_roses
stage
sunflowers
sunset
tides
unpacked
void
wanderer
wasteland
water
wind
wither
