### ISSUE TITLE
[24w33] new model for Redstone torch

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#933]
![Capture d’écran du 2024-09-22 15-44-51](https://github.com/user-attachments/assets/f3708cc1-e4e3-4543-8cc3-4b95bdd041aa)

**Comment by lipki** [comment]
Well, it's ugly.
You'll have to step on me to change the texture of the torches.
(And if you step on me, I won't be able to do it anymore AHAHAH!)

**Comment by ORN-Fox** [comment]
Out of curiosity, did the texture change after Mojand's work or the model?

I like the current redstone torches, the new ones are ok...meh...

**Comment by lipki** [comment]
Both.
Well, the advantage is that it is thanks to this torch that we have the emissive light layer.
And that is good.
