### ISSUE TITLE
[24w36] Armor System Overhaul

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#936]
New Armors can now be created with custom textures.

![Capture d’écran du 2024-09-22 22-19-05](https://github.com/user-attachments/assets/91a9b36c-3199-4454-8acf-5d5a4ce545f4)

**Comment by lipki** [comment]
Allows us to add both types of elytra.
To be studied.

**Comment by lipki** [comment]
Also allows putting trims on all the armors above.
If someone is motivated. :)

**Comment by lipki** [comment]
Command for elytra ange.

/give @s minecraft:feather[minecraft:equippable={model:"minecraft:elytra_ange", slot:"chest"},minecraft:glider={}]

![Capture d’écran du 2024-09-27 20-29-18](https://github.com/user-attachments/assets/b29f640b-10ab-4415-8881-e6fef8fed62a)
![Capture d’écran du 2024-09-27 20-30-26](https://github.com/user-attachments/assets/493037e9-10d2-4587-ba54-a0ab90c0e2eb)

**Comment by ORN-Fox** [comment]
Modifying Mojang at this level allows what? I didn't understand ??

**Comment by lipki** [comment]
This allows you to create armors with the same model, but a different texture.
And then obtain this armor via a command or a data pack.

For example, you can create a copper armor recipe, which gives you a custom iron armor item, but representing a copper armor.
Which if equipped appears as a copper armor.
You can even change the stats, I think.

**Comment by lipki** [comment]
Which makes the Summerfields datapack more and more interesting.

**Comment by lipki** [comment]
D'ailleurs : https://github.com/SummerFields/datapack
There you go, we have a base.
