### ISSUE TITLE
[24w36] new tooltip texture

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#937]
![background](https://github.com/user-attachments/assets/15233332-cbbc-4874-b378-a5d2ea1ea6fa)
![frame](https://github.com/user-attachments/assets/fdffdef7-bec9-43dd-be99-3ea94724a242)

**Comment by lipki** [comment]
![Capture d’écran du 2024-09-25 13-38-08](https://github.com/user-attachments/assets/fee76456-559a-4fd4-b8b5-c79bb3af4b9a)
Need your opinion.

**Comment by ORN-Fox** [comment]
I find the writing hard to read on a white background!

I did some tests on my side. I like the first one but not the second one :D

![Image](https://github.com/user-attachments/assets/c98dec0d-f879-4d0b-b87e-839a61ec715a)
![Image](https://github.com/user-attachments/assets/b5364c4a-6a42-4d37-b6ba-d0993e8d5cbc)

You'll tell me if this inspires you!
