### ISSUE TITLE
[24w40] New tree - Pale oak

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#963]
![Capture d’écran du 2024-10-02 22-32-27](https://github.com/user-attachments/assets/e89cd89a-3a69-4e25-ba16-1d5257bb9992)
![pale_oak_door_top](https://github.com/user-attachments/assets/c1805f9d-53bb-49a2-b5c4-ce2b4822310b) ![pale_oak_log_top](https://github.com/user-attachments/assets/2b2ef4d0-b698-4aa3-a084-03d1a3aea3b9) ![stripped_pale_oak_log_top](https://github.com/user-attachments/assets/a86469e0-adfd-4f21-9e57-064b8f844ea2) ![pale_oak_trapdoor](https://github.com/user-attachments/assets/5ee245ff-9af4-46b5-9e47-e1d7287b8ed9)
![pale_oak_door_bottom](https://github.com/user-attachments/assets/9d8c8535-4357-4448-9355-4ae29c8948a5) ![pale_oak_log](https://github.com/user-attachments/assets/4d0b3850-a6bb-45d3-8c7f-b2d8696af87d) ![stripped_pale_oak_log](https://github.com/user-attachments/assets/70ef97f6-141e-4b8f-bc25-cc3c89afe0d5) ![pale_oak_planks](https://github.com/user-attachments/assets/b215829f-0761-46b8-836a-5b6b0f13b67b)
![pale_oak_leaves](https://github.com/user-attachments/assets/b15550e9-7e8c-4ce4-a00d-2a21978b34f1) ![pale_oak_sapling](https://github.com/user-attachments/assets/d7526440-0249-4247-90b7-6bf9e98cd1be)

![pale_oak_door](https://github.com/user-attachments/assets/d067388e-75fe-4adf-8e5f-c81c3180685b)

![pale_oak_boat](https://github.com/user-attachments/assets/daebe110-2350-4f95-9ad7-0b32c0d0da7a) ![pale_oak_chest_boat](https://github.com/user-attachments/assets/33bb8a30-bba2-44ee-81c8-d2cd69ad110f)

![pale_oak](https://github.com/user-attachments/assets/b0f3a1a4-3349-4ff9-a37f-0c45ccdb7108) ![pale_oak](https://github.com/user-attachments/assets/60275d9e-2190-48ee-a558-66d781896003)

![pale_oak_hanging_sign](https://github.com/user-attachments/assets/086f5758-51c0-4fe4-afad-79eee95f2b46)

![pale_oak](https://github.com/user-attachments/assets/359e31ed-1bab-4cde-9b9f-3a9beb1d4753) ![pale_oak](https://github.com/user-attachments/assets/18d55c6d-a245-48a0-aa07-051fbf408d88)

![pale_oak_sign](https://github.com/user-attachments/assets/3c6b82cf-0a04-41b2-8bae-8706df72ef84)

![pale_oak](https://github.com/user-attachments/assets/77bffd92-6e80-46a7-9db7-8bc1517a4013)

**Comment by Physignatily** [comment]
![2024-10-03_21 55 54](https://github.com/user-attachments/assets/cc05760b-a2fb-421d-9d09-5be6d27ffeb6)

![pale_oak_door_top](https://github.com/user-attachments/assets/d2fd43ee-9324-43c6-b6d4-398410d718e5)![pale_oak_log_top](https://github.com/user-attachments/assets/fb8dddb7-0a26-4379-b1d9-c62133e1c80d)![stripped_pale_oak_log_top](https://github.com/user-attachments/assets/d92665cf-c564-4d60-b741-335d4e88cf4a)![pale_oak_trapdoor](https://github.com/user-attachments/assets/aa7cc103-227b-4616-8f1f-64ca509054c7)
![pale_oak_door_bottom](https://github.com/user-attachments/assets/7cfacd86-1fb2-4beb-942f-5e824b59f15c)![pale_oak_log](https://github.com/user-attachments/assets/2bfa2694-8e40-48bf-b36d-e9995c9a4a14)![stripped_pale_oak_log](https://github.com/user-attachments/assets/9de17c5e-87b9-4e36-b879-f7cf4015c2d8)![pale_oak_planks](https://github.com/user-attachments/assets/52ac2acf-de69-49b2-9b40-cbd6ee57a8a8)



![pale_oaks](https://github.com/user-attachments/assets/74ccde6f-fbf3-4c4d-b1a8-62f5af6f1632)
![pale_oak](https://github.com/user-attachments/assets/fb178335-24e9-4b6e-8e17-5ee69d957e00)

**Comment by lipki** [comment]
It's not bad at your place, but it lacks a bit of color :)

**Comment by lipki** [comment]
Actually, it's not that white.
I made this version of the boat.
What do you think of this color ?

![pale_oak](https://github.com/user-attachments/assets/987ef998-abf9-4b71-8b74-f13d5b8c973e)
![Capture d’écran du 2024-10-04 14-11-55](https://github.com/user-attachments/assets/ce0bdc92-124c-40e7-aed0-312a0489a619)
Your wood, my boat.

**Comment by Physignatily** [comment]
I also like your color variant.
My "vision" of the wood was a dead tree, completly void of life.

But the vanilla version is a bit purple, which wuld mess with our grayscale even more...

**Comment by lipki** [comment]
The difficult balance between the atmosphere of the dead tree forest, and the building block.

As you can see, mine is leaning towards yellow.

We can see it like this :
- The tree is dead and gloomy.
- But the boards are white and bright.

I'll ask the builder of "Buildmyworld" what he thinks.

If you have made leaves or hanging moss, do not hesitate to propose them.
