### ISSUE TITLE
[24w40] New moss - pale moss

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#964]
![Capture d’écran du 2024-10-02 22-45-37](https://github.com/user-attachments/assets/35ff7379-a412-401a-b579-ef0335b6d9b8)![Capture d’écran du 2024-10-02 22-47-41](https://github.com/user-attachments/assets/6bcf4400-7055-4fcd-b1b0-3ca563ca38b6)

![pale_moss_block](https://github.com/user-attachments/assets/0f102cfb-782d-4918-b78d-a7bb0cbefe00) ![pale_moss_carpet_side_small](https://github.com/user-attachments/assets/a41f70b6-c52e-49bf-9b4b-726bc3e4182b) ![pale_hanging_moss](https://github.com/user-attachments/assets/74a33d2b-1f37-4033-b5bb-74fc9f2f04dd)
![pale_moss_carpet](https://github.com/user-attachments/assets/ea6b1ad2-3ef7-408f-bfbc-f77363d54d1a) ![pale_moss_carpet_side_tall](https://github.com/user-attachments/assets/0b0d652e-52fd-47f2-9e1b-8dc6190f8f28) ![pale_hanging_moss_tip](https://github.com/user-attachments/assets/cfa46649-eb43-4071-8ae3-f2b7022941b8)

**Comment by Physignatily** [comment]
![pale moss](https://github.com/user-attachments/assets/a072aa18-bc74-4944-99f0-d9ea77255540)
![pale_moss_block](https://github.com/user-attachments/assets/888dac6b-bb27-47ba-8a9b-aa4bd4282098)

**Comment by lipki** [comment]
frametime ?

**Comment by Physignatily** [comment]
{"animation": {"interpolate":true, "frametime":18}}
